'use strict';
function html(nonce,assets){return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${assets.source} https: data:; style-src ${assets.source} 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${assets.css}"></head><body>
<header><select id="sessions" aria-label="Conversation history"></select><button id="rename" title="Rename conversation" aria-label="Rename conversation" hidden disabled><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m16 3 5 5-12 12H4v-5Z M14 5l5 5"/></svg></button><button id="new" title="New conversation" aria-label="New conversation">＋</button><button id="refresh" title="Refresh history" aria-label="Refresh history">↻</button><button id="settings" title="Settings" aria-label="Settings">⚙</button></header><div id="status" role="status">Connecting to xMind…</div>
<div id="run-picker" class="run-picker" hidden><label for="runs">Run details</label><select id="runs" aria-label="Inspect a recorded run"></select></div>
<main id="scroll"><div id="empty"><strong>Work with xMind</strong>Start a conversation with your project.<br>History and execution stay on your backend.</div><div id="history" aria-live="polite"></div><div id="live" aria-live="polite"></div><section id="run-failure" class="message" hidden role="alert" aria-label="Selected run failure"></section><section id="graph-view" hidden aria-label="Graph workflow"></section><div id="process-streams" aria-live="polite"></div><div id="operations"></div><details><summary>Selected run activity</summary><pre id="events"></pre></details></main>
<footer><div class="workflow-picker" id="workflow-picker" hidden><label for="workflow">Run mode</label><select id="workflow" aria-label="Agent workflow" title="Agent chooses its next tool step dynamically. Workflows run registered connected steps."><option value="">Agent (default)</option></select></div><div class="composer"><textarea id="prompt" aria-label="Message xMind" placeholder="Ask xMind to work on your project…"></textarea><div class="composer-bar"><select id="model" aria-label="Model" disabled><option>No model configured</option></select><span class="spacer"></span><button id="cancel" hidden>Stop</button><button id="send" class="primary" title="Send · Enter" disabled>Send ↑</button></div></div><p class="hint">Enter to send · Shift+Enter for a new line <span id="provider-mode" hidden></span></p></footer>
<dialog id="rename-dialog" aria-labelledby="rename-title"><form id="rename-form"><div class="settings-heading"><h2 id="rename-title">Rename conversation</h2><button id="rename-close" type="button" aria-label="Close rename dialog">×</button></div><label for="conversation-title">Title</label><input id="conversation-title" type="text" maxlength="4096" required autocomplete="off"><p id="rename-status" role="status"></p><div class="rename-actions"><button id="rename-cancel" type="button">Cancel</button><button id="rename-save" class="primary" type="submit">Save</button></div></form></dialog>
<dialog id="provider-settings" aria-labelledby="settings-title"><form id="provider-form"><div class="settings-heading"><h2 id="settings-title">Settings</h2><button id="settings-close" type="button" aria-label="Close settings">×</button></div><label for="provider-name">Provider</label><select id="provider-name" disabled><option>OpenAI</option></select><label for="provider-key">API key</label><input id="provider-key" type="password" autocomplete="off" spellcheck="false" maxlength="32768" placeholder="Enter a key, or leave blank to use the saved key"><p id="settings-info">The key is encrypted on your xMind Server after you choose a model. It is never included in conversations.</p><p id="settings-status" role="status"></p><button id="settings-save" class="primary" type="submit">Fetch models</button><p class="hint">Choose a model in the sidebar below after fetching.</p></form></dialog>
<script nonce="${nonce}" src="${assets.marked}"></script><script nonce="${nonce}" src="${assets.purify}"></script><script nonce="${nonce}" src="${assets.script}"></script><script nonce="${nonce}">/* Renderer loads only extension-owned scripts; no backend credentials. */</script></body></html>`;}
module.exports={html};
