'use strict';
// Synthetic public DTOs for thin view contracts; no execution claims.
function planFixture({root='plan-root',session='plan-session',answer=false}={}){
 const read={id:'read',type:'agent',objective:'Read actual project bytes',preset:'workspace.inspect',depends_on:[],backend_node_id:'node-read',definition_revision:1,state:'settled',protected:true,effect_state:'none',preset_revision:1,claim_revision:1,claim_id:'claim-read',child_run_id:'leaf-read',child_state:'completed',outcome_json:'{"content":"Synthetic observed bytes"}',settled_event_seq:10};
 const gate={id:'gate',type:'human',question:'Review <script>fixtureAttack()</script> before coding',depends_on:[{task:'read',require:'success'}],backend_node_id:'node-gate',definition_revision:2,state:answer?'settled':'waiting_human',protected:true,effect_state:'none',claim_revision:2,claim_id:'question-gate',human_request_id:'question-gate',...(answer?{outcome_json:'{"human_state":"answered","input_json":"{\\"answer\\":true}"}',settled_event_seq:24}:{})};
 const definitions=nodes=>nodes.map(node=>Object.fromEntries(Object.entries(node).filter(([key])=>['id','type','objective','preset','question','depends_on'].includes(key))));
 const calls=[{id:'call-first',plan_id:'plan-owned',root_run_id:root,provider_tool_call_id:'provider-first',origin_attempt_id:'attempt-first',name:'plan_tasks',state:'turn_committed',accepted_revision:1,accepted_event_seq:3,result_event_seq:11,conversation_commit_seq:12,continuation_attempt_id:'attempt-second',pending:false},{id:'call-second',plan_id:'plan-owned',root_run_id:root,provider_tool_call_id:'provider-second',origin_attempt_id:'attempt-second',name:'revise_plan',state:'accepted',accepted_revision:2,accepted_event_seq:15,result_event_seq:null,conversation_commit_seq:null,continuation_attempt_id:'',pending:true,response:{model:'synthetic-held-model',usage:{input_tokens:7,output_tokens:3},elapsed_ms:1100,first_token_ms:100}}];
 return {run:{id:root,session_id:session,state:'paused',parent_id:'',node_id:'',graph_root:false},enabled:true,plan:{id:'plan-owned',root_run_id:root,revision:2,state_sequence:answer?18:17,state:'waiting_human',ready:[],blocked:[],claimed:[],waiting_human:answer?[]:['gate'],finished:answer,report_ready:answer,halted:false,retired_labels:[],planned_children_reserved:0,planned_humans_reserved:0,humans_published:1,nodes:[read,gate]},questions:[{id:'question-gate',plan_id:'plan-owned',root_run_id:root,label:'gate',backend_node_id:'node-gate',question:gate.question,state:answer?'answered':'waiting',definition_revision:2,published_event_seq:16,expires_unix_ms:Date.now()+600000,input_json:answer?'{"answer":true}':'',input_event_seq:answer?23:null}],calls,revisions:[{plan_id:'plan-owned',revision:1,accepted_event_seq:3,call_id:'call-first',spec:{nodes:definitions([read])}},{plan_id:'plan-owned',revision:2,accepted_event_seq:15,call_id:'call-second',spec:{nodes:definitions([read,gate])}}],policy:{revision:1,catalogue_finalized:true,limits:{max_nodes:32,max_revisions:16,max_humans:8,change_bytes:262144,human_expiry_ms:900000,max_parent_turns:16},presets:[{id:'workspace.inspect',revision:1,readonly:true,turn_limit:4},{id:'workspace.coding',revision:1,readonly:false,turn_limit:4}]},budget:{policy_id:'native.dynamic-plan',policy_revision:1,revision:4,max_children:8,max_parallel:2,max_model_calls:32,wall_limit_ms:600000,children_admitted:1,planned_children_reserved:0,model_calls_reserved:3,parent_calls_held:1,parent_model_calls_reserved:2}};
}
function inputMessage(record,input_json='{"answer":true}') {const question=record.questions[0];return {type:'plan-input',root:record.run.id,plan_id:record.plan.id,request:question.id,backend_node_id:question.backend_node_id,definition_revision:question.definition_revision,published_event_seq:question.published_event_seq,input_json,expected_revision:record.plan.revision,expected_state_sequence:record.plan.state_sequence};}
module.exports={planFixture,inputMessage};
