---
# xMind Config
XlangStartDebuger: true 
XlangStartPythonDebuger: false 
 
Log:
 OutputLevel: 79999
 MBSize: 10

WebServer:
  Port: 9901
  ServiceEntry: ../Service/main.x

RootAgents:
   - name: simple
     file: ../Examples/Simple/simple.yml
   - name: QAJudge
     file: ../Examples/Simple/two_simples.yml
