// Actual native graph execution/storage and A2A task controls. No model peer,
// synthetic model replies, manual lifecycle writes or CPython execution.
import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,dirname,basename} from 'node:path';
import {randomBytes} from 'node:crypto';
const [server,modules,stdlib]=process.argv.slice(2),root=await mkdtemp(join(tmpdir(),'xmind-a2a-control-'));
const workspace=join(root,'work'),token=randomBytes(32).toString('hex');let child,port;
async function http(path,body,headers={}){const response=await fetch(`http://127.0.0.1:${port}${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(10000)});return {status:response.status,data:response.status===204?undefined:await response.json()};}
async function rpc(method,params,id='control-client'){const result=await http('/a2a',{jsonrpc:'2.0',id,method,params});assert.equal(result.status,200);assert.equal(result.data.jsonrpc,'2.0');assert.equal(result.data.id,id);assert.equal('result' in result.data,'error' in result.data?false:true);return result.data;}
async function until(id,wanted){const end=Date.now()+10000;for(;;){const result=await http('/v1/graph-runs/'+id);assert.equal(result.status,200);if(result.data.run.state===wanted)return result.data;if(Date.now()>=end)throw new Error('Actual graph state deadline: '+wanted);await new Promise(resolve=>setTimeout(resolve,5));}}
async function admit(session,graph){const result=await http('/v1/graph-runs',{session_id:session,graph_id:graph,graph_revision:1,prompt:'Read actual A2A task output'});assert.equal(result.status,202);return result.data.id;}
try{
 await mkdir(workspace);await writeFile(join(workspace,'observed.txt'),'First actual workspace bytes');await writeFile(join(root,'graphs.json'),JSON.stringify({graphs:[{id:'read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'observed.txt'}}]}},{id:'wait',spec:{nodes:[{id:'answer',type:'human',prompt:'Wait for data'}]}}]}));
 child=spawn(server,['--db',join(root,'state.sqlite'),'--modules',modules,'--stdlib',stdlib,'--port','0','--workspace',workspace,'--model-tools','supported','--graphs-config',join(root,'graphs.json')],{env:{...process.env,XMIND_AUTH_TOKEN:token,XMIND_API_KEY:''},windowsHide:true});let errors='';child.stderr.on('data',bytes=>errors+=bytes);
 port=await new Promise((yes,no)=>{let text='';const timer=setTimeout(()=>no(new Error('Native A2A readiness deadline')),10000);child.once('error',error=>{clearTimeout(timer);no(error);});child.once('exit',code=>{clearTimeout(timer);no(new Error(`Native server exited ${code}: ${errors}`));});child.stdout.on('data',bytes=>{text+=bytes;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(text);if(match){clearTimeout(timer);yes(Number(match[1]));}});});
 assert.equal((await http('/a2a',{jsonrpc:'2.0',id:1,method:'tasks/get',params:{id:'missing'}},{Authorization:''})).status,401);
 assert.equal((await http('/a2a','{}',{Origin:'https://outside.invalid'})).status,403);assert.equal((await http('/a2a','{}',{'Content-Type':'text/plain'})).status,415);assert.equal((await http('/a2a?actor=spoof','{}')).status,400);
 for(const [body,code] of [['not JSON',-32700],['',-32700],['[]',-32600],['{"jsonrpc":"2.0","id":1,"id":2,"method":"tasks/get"}',-32600],[{jsonrpc:'1.0',id:1,method:'tasks/get'},-32600],[{jsonrpc:'2.0',id:true,method:'tasks/get'},-32600],[{jsonrpc:'2.0',id:9007199254740992,method:'tasks/get'},-32600]]){const result=await http('/a2a',body);assert.equal(result.status,200);assert.equal(result.data.error.code,code);assert.equal(result.data.id,null);assert.ok(!('result' in result.data));}
 assert.equal((await rpc('tasks/get',{id:'missing'},-7)).error.code,-32001);assert.equal((await rpc('tasks/get',{id:'missing',actor:'spoof'})).error.code,-32602);assert.equal((await rpc('tasks/get',{id:'missing',historyLength:-1})).error.code,-32602);
 for(const method of ['message/stream','tasks/resubscribe','agent/getAuthenticatedExtendedCard'])assert.equal((await rpc(method,{})).error.code,-32004);
 assert.equal((await rpc('message/send',{})).error.code,-32602);
 assert.equal((await rpc('tasks/pushNotificationConfig/set',{})).error.code,-32003);assert.equal((await rpc('unknown/method',{})).error.code,-32601);
 await http('/v1/sessions',{id:'context',title:'Actual shared task control'});const first=await admit('context','read');await until(first,'completed');
 let task=(await rpc('tasks/get',{id:first},'unicode-请求')).result;assert.equal(task.kind,'task');assert.equal(task.id,first);assert.equal(task.contextId,'context');assert.equal(task.status.state,'completed');assert.ok(!('history' in task));assert.equal(task.artifacts[0].parts[0].kind,'text');assert.ok(task.artifacts[0].parts[0].text.includes('First actual workspace bytes'));assert.equal(task.artifacts[0].parts[0].text,(await http('/v1/sessions/context/history')).data.at(-1).data.content);
 await writeFile(join(workspace,'observed.txt'),'Second actual workspace bytes');const second=await admit('context','read');await until(second,'completed');task=(await rpc('tasks/get',{id:first,historyLength:0},null)).result;assert.ok(task.artifacts[0].parts[0].text.includes('First actual workspace bytes'));assert.ok(!task.artifacts[0].parts[0].text.includes('Second actual workspace bytes'),'Artifact must come from this task, never the latest shared-session reply');assert.ok((await rpc('tasks/get',{id:second},1.5)).result.artifacts[0].parts[0].text.includes('Second actual workspace bytes'));
 const taskHistory=(await rpc('tasks/get',{id:first,historyLength:1})).result.history;assert.equal(taskHistory.length,1);assert.ok(taskHistory[0].parts[0].text.includes('First actual workspace bytes'));assert.ok(!taskHistory[0].parts[0].text.includes('Second actual workspace bytes'));assert.equal((await rpc('tasks/cancel',{id:first})).error.code,-32002);
 const children=(await http('/v1/graph-runs/'+first+'/children')).data;assert.equal((await rpc('tasks/get',{id:children[0].id})).error.code,-32001);assert.equal((await rpc('tasks/cancel',{id:children[0].id})).error.code,-32001);
 const waiting=await admit('context','wait');await until(waiting,'paused');assert.equal((await rpc('tasks/get',{id:waiting})).result.status.state,'input-required');const cancelled=await rpc('tasks/cancel',{id:waiting});assert.ok(['input-required','working','canceled'].includes(cancelled.result.status.state),'Cancellation response reports only observed state');await until(waiting,'cancelled');assert.equal((await rpc('tasks/get',{id:waiting})).result.status.state,'canceled');
 assert.equal((await http('/a2a',{jsonrpc:'2.0',method:'tasks/get',params:{id:first}})).status,204);assert.equal((await http('/a2a',{jsonrpc:'2.0',method:'unknown/method',params:{}})).status,204);
 assert.equal((await http('/a2a',{jsonrpc:'2.0',id:1,method:'tasks/get',params:{id:first,metadata:{private:'DO_NOT_ECHO_'+ 'x'.repeat(66000)}}})).data.error.code,-32600);
 for(let attempt=0;attempt<16;++attempt){const id=await admit('context','read'),result=await rpc('tasks/cancel',{id});if(result.error)assert.equal(result.error.code,-32002,'A finishing task must never be reported as absent');const end=Date.now()+10000;for(;;){const observed=(await rpc('tasks/get',{id})).result.status.state;if(['completed','canceled'].includes(observed))break;if(Date.now()>=end)throw new Error('Cancellation retirement race deadline');await new Promise(resolve=>setTimeout(resolve,5));}}
 console.log('Native A2A task controls passed authenticated JSON-RPC boundaries, exact IDs, native graph artifacts isolated by run, real paused-root cancellation, repeated finish/cancel scheduling and unsupported admission/stream/history rejection. Full A2A compliance is not established.');
}finally{if(child&&child.exitCode===null){const ended=new Promise(resolve=>child.once('exit',resolve));child.kill();await ended;}assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-a2a-control-'));await rm(root,{recursive:true,force:true});}
