// Native A2A 1.0 wire, shared C++ executor and embedded-xlang3 SQLite.
// The official SDK is an independent test client; provider replies are synthetic.
import assert from 'node:assert/strict';import {createServer} from 'node:http';import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname,basename,resolve} from 'node:path';
import {randomBytes} from 'node:crypto';import {setTimeout as delay} from 'node:timers/promises';
import {ClientFactory,DefaultAgentCardResolver,JsonRpcTransportFactory} from './sdk/node_modules/@a2a-js/sdk/dist/client/index.js';
import {Role,TaskState} from './sdk/node_modules/@a2a-js/sdk/dist/index.js';
const [server,modules,stdlib]=process.argv.slice(2),root=await mkdtemp(join(tmpdir(),'xmind-a2a-v1-'));
const token=randomBytes(32).toString('hex'),env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
let child,port,peerError;const held=new Map(),requests=[],wire=[],streams=[];
const delta=text=>`data: ${JSON.stringify({choices:[{index:0,delta:{content:text},finish_reason:null}]})}\n\n`;
const finish=`data: ${JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})}\n\ndata: [DONE]\n\n`;
const peer=createServer((request,response)=>{let raw='';request.on('data',bytes=>raw+=bytes);request.on('end',()=>{try{
 const data=JSON.parse(raw),text=data.messages.findLast(message=>message.role==='user').content;assert.equal(data.model,'synthetic-native-v1-model');requests.push(data);
 if(text==='fail'){response.writeHead(503);response.end('DO_NOT_ECHO_PROVIDER_BODY');return;}
 response.writeHead(200,{'Content-Type':'text/event-stream'});
 if(['block','legacy-block','stream','cancel','disconnect'].includes(text)){response.write(delta('Synthetic prefix 🌍 '));held.set(text,response);}
 else response.end(delta('Synthetic reply '+text)+finish);
 }catch(error){peerError=error;response.writeHead(500);response.end('Synthetic peer failure');}});});
async function start(model=true){const args=['--db',join(root,'state.sqlite'),'--modules',modules,'--stdlib',stdlib,'--port','0'];if(model)args.push('--model','synthetic-native-v1-model','--model-endpoint',`http://127.0.0.1:${peer.address().port}/chat`);child=spawn(server,args,{env,windowsHide:true});let errors='';child.stderr.on('data',bytes=>errors+=bytes);port=await new Promise((yes,no)=>{let output='';const timer=setTimeout(()=>no(new Error('Native readiness: '+errors)),15000);child.once('error',error=>{clearTimeout(timer);no(error);});child.once('exit',code=>{clearTimeout(timer);no(new Error('Native exited '+code+': '+errors));});child.stdout.on('data',bytes=>{output+=bytes;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(output);if(match){clearTimeout(timer);yes(Number(match[1]));}});});}
async function stop(){if(child&&child.exitCode===null){const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;}child=null;}
async function http(path,body,headers={},signal=AbortSignal.timeout(10000)){return fetch(`http://127.0.0.1:${port}${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body),signal});}
async function api(path,body){const response=await http(path,body);assert.ok(response.ok,await response.clone().text());return response.json();}
async function rpc(method,params,version='1.0',id='raw-client',signal){const response=await http('/a2a',{jsonrpc:'2.0',id,method,params},{'A2A-Version':version},signal);assert.equal(response.status,200);const value=await response.json();assert.equal(value.id,id);return value;}
function input(id,text){return {message:{messageId:id,role:'ROLE_USER',parts:[{text}]},configuration:{returnImmediately:true,historyLength:8}};}
function legacy(id,text){return {message:{kind:'message',messageId:id,role:'user',parts:[{kind:'text',text}]},configuration:{blocking:true,historyLength:8}};}
function sdkInput(id,text,immediate){return {message:{messageId:id,role:Role.ROLE_USER,parts:[{content:{$case:'text',value:text}}]},...(immediate===undefined?{}:{configuration:{returnImmediately:immediate,historyLength:8}})};}
async function until(read,predicate){const deadline=Date.now()+10000;while(Date.now()<deadline){if(peerError)throw peerError;const value=await read();if(predicate(value))return value;await delay(10);}throw new Error('Native v1 observation deadline');}
function client(){const origin=`http://127.0.0.1:${port}`;const authenticatedFetch=(url,init={})=>{assert.equal(new URL(url).origin,origin);const headers=new Headers(init.headers);headers.set('Authorization','Bearer '+token);if(init.body){const body=JSON.parse(init.body);wire.push({method:body.method,version:headers.get('A2A-Version'),params:body.params});}return fetch(url,{...init,headers,redirect:'error',signal:init.signal?AbortSignal.any([init.signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)});};return new ClientFactory({cardResolver:new DefaultAgentCardResolver({fetchImpl:authenticatedFetch}),transports:[new JsonRpcTransportFactory({fetchImpl:authenticatedFetch})]}).createFromUrl(origin);}
function list(sdk,params={}){return sdk.listTasks({tenant:'',contextId:'',status:TaskState.TASK_STATE_UNSPECIFIED,pageToken:'',...params});}
function consume(generator){const stream={records:[],done:false,error:null};streams.push(stream);stream.pump=(async()=>{try{for await(const event of generator)stream.records.push(event);}catch(error){stream.error=error;}finally{stream.done=true;}})();return stream;}
async function streamTask(stream){await until(()=>{if(stream.error)throw stream.error;return stream.records;},records=>records.length>0);assert.equal(stream.records[0].payload.$case,'task');return stream.records[0].payload.value;}
async function streamFinal(stream,state){await until(()=>stream.done,value=>value);if(stream.error)throw stream.error;assert.equal(stream.records.at(-1).payload.$case,'statusUpdate');assert.equal(stream.records.at(-1).payload.value.status.state,state);}
try{
 const earliest=Date.now();
 await new Promise(resolve=>peer.listen(0,'127.0.0.1',resolve));await start();
 const cardResponse=await http('/.well-known/agent-card.json',undefined,{'A2A-Version':'1.0'}),card=await cardResponse.json();assert.equal(cardResponse.headers.get('A2A-Version'),'1.0');assert.deepEqual(card.supportedInterfaces.map(item=>item.protocolVersion),['1.0','0.3']);assert.equal(card.securitySchemes.ownerToken.httpAuthSecurityScheme.scheme,'Bearer');assert.ok(!('protocolVersion' in card));assert.ok(!JSON.stringify(card).includes(token));
 const legacyCard=await api('/.well-known/agent-card.json');assert.equal(legacyCard.protocolVersion,'0.3.0');
 for(const version of ['2.0','1.0.1','0.3.0'])assert.equal((await rpc('SendMessage',input('bad-version','unused'),version)).error.code,-32009);
 const badCard=await http('/.well-known/agent-card.json',undefined,{'A2A-Version':'2.0'});assert.equal(badCard.status,400);assert.equal((await badCard.json()).error.code,-32009);
 assert.equal((await rpc('SendMessage',input('wrong-binding','unused'),'')).error.code,-32601);assert.equal((await rpc('message/send',legacy('wrong-binding','unused'))).error.code,-32601);
 for(const [params,code] of [[{...input('role','unused'),message:{...input('role','unused').message,role:'user'}},-32602],[{...input('kind','unused'),message:{...input('kind','unused').message,kind:'message'}},-32602],[{...input('part','unused'),message:{...input('part','unused').message,parts:[{text:'x',data:{}}]}},-32005],[{...input('tenant','unused'),tenant:'unconfigured'},-32004],[{...input('push','unused'),configuration:{taskPushNotificationConfig:{}}},-32003]])assert.equal((await rpc('SendMessage',params)).error.code,code);
 assert.equal((await rpc('GetExtendedAgentCard',{})).error.code,-32007);assert.equal((await rpc('GetTask',{id:'absent'})).error.code,-32001);assert.deepEqual(await api('/v1/sessions'),[],'Rejected wire/version requests cannot admit work');
 const sdk=await client();let blockResult,blockError,legacyResult,legacyError;
 const empty=await list(sdk,{});assert.equal(empty.totalSize,0);assert.equal(empty.nextPageToken,'');assert.equal(empty.pageSize,50);
 const blocking=sdk.sendMessage(sdkInput('blocking-message','block')).then(value=>{blockResult=value;},error=>{blockError=error;});await until(()=>held.has('block'),value=>value);
 const legacyBlocking=rpc('message/send',legacy('legacy-block-message','legacy-block'),'0.3').then(value=>{legacyResult=value;},error=>{legacyError=error;});await until(()=>held.has('legacy-block'),value=>value);
 assert.equal(blockResult,undefined);assert.equal(blockError,undefined);assert.equal(legacyResult,undefined);assert.equal(legacyError,undefined);
 const sessions=await api('/v1/sessions');assert.equal(sessions.length,2);const run=(await api('/v1/sessions/'+sessions[0].id+'/runs'))[0];assert.equal((await sdk.getTask({id:run.id})).status.state,TaskState.TASK_STATE_WORKING);
 assert.equal((await rpc('SendMessage',{message:input('capacity','unused').message})).error.code,-32004);assert.equal((await api('/v1/sessions')).length,2);assert.equal((await api('/v1/health')).agent_execution,true);
 held.get('block').end(delta('suffix')+finish);held.get('legacy-block').end(delta('suffix')+finish);await blocking;await legacyBlocking;if(blockError)throw blockError;if(legacyError)throw legacyError;
 assert.equal(blockResult.status.state,TaskState.TASK_STATE_COMPLETED);assert.equal(blockResult.artifacts[0].parts[0].content.value,'Synthetic prefix 🌍 suffix');assert.equal(legacyResult.result.kind,'task');assert.equal(legacyResult.result.status.state,'completed');
 assert.equal((await sdk.getTask({id:blockResult.id,historyLength:8})).history[0].role,Role.ROLE_USER);assert.equal((await rpc('SubscribeToTask',{id:blockResult.id})).error.code,-32004);assert.equal((await rpc('CancelTask',{id:blockResult.id})).error.code,-32002);
 const stream=consume(sdk.sendMessageStream(sdkInput('stream-message','stream',true))),task=await streamTask(stream);await until(()=>stream.records,records=>records.some(item=>item.payload?.$case==='artifactUpdate'));
 const subscription=consume(sdk.resubscribeTask({id:task.id}));assert.equal((await streamTask(subscription)).id,task.id);held.get('stream').end(delta('suffix')+finish);await streamFinal(stream,TaskState.TASK_STATE_COMPLETED);await streamFinal(subscription,TaskState.TASK_STATE_COMPLETED);
 const cancelStream=consume(sdk.sendMessageStream(sdkInput('cancel-message','cancel',true))),cancelTask=await streamTask(cancelStream);await until(()=>held.has('cancel'),value=>value);await sdk.cancelTask({id:cancelTask.id});await streamFinal(cancelStream,TaskState.TASK_STATE_CANCELED);
 const failed=await sdk.sendMessage(sdkInput('failure-message','fail'));assert.equal(failed.status.state,TaskState.TASK_STATE_FAILED);assert.ok(!JSON.stringify(failed).includes('DO_NOT_ECHO_PROVIDER_BODY'));
 const controller=new AbortController();let disconnected=false;const pending=rpc('SendMessage',{message:input('disconnected-message','disconnect').message},'1.0','disconnected',controller.signal).catch(error=>{assert.equal(error.name,'AbortError');disconnected=true;});await until(()=>held.has('disconnect'),value=>value);controller.abort();await pending;assert.equal(disconnected,true);
 let disconnectedRun;for(const session of await api('/v1/sessions')){const history=await api('/v1/sessions/'+session.id+'/history');if(history.some(item=>item.data?.a2a_message_id==='disconnected-message'))disconnectedRun=(await api('/v1/sessions/'+session.id+'/runs'))[0];}
 assert.ok(disconnectedRun);assert.equal((await sdk.getTask({id:disconnectedRun.id})).status.state,TaskState.TASK_STATE_WORKING);held.get('disconnect').end(delta('suffix')+finish);await until(()=>sdk.getTask({id:disconnectedRun.id}),value=>value.status.state===TaskState.TASK_STATE_COMPLETED);
 const firstPage=await list(sdk,{pageSize:1}),seen=new Set();assert.equal(firstPage.totalSize,6);assert.equal(firstPage.tasks.length,1);assert.ok(firstPage.nextPageToken);let page=firstPage,prior=Infinity;
 for(;;){for(const task of page.tasks){assert.ok(!seen.has(task.id),'Cursor pages cannot repeat task IDs');seen.add(task.id);const time=Date.parse(task.status.timestamp);assert.ok(Number.isFinite(time)&&time>=earliest&&time<=Date.now());assert.ok(time<=prior,'Task pages must follow actual status update time');prior=time;}if(!page.nextPageToken)break;page=await list(sdk,{pageSize:1,pageToken:page.nextPageToken});}assert.equal(seen.size,6);
 const rawList=(await rpc('ListTasks',{pageSize:100})).result;assert.equal(rawList.totalSize,6);assert.ok(rawList.tasks.every(task=>!('artifacts' in task)),'Default listing must omit artifacts rather than return placeholders');
 const scoped=await list(sdk,{contextId:blockResult.contextId,includeArtifacts:true,historyLength:8});assert.equal(scoped.tasks.length,1);assert.equal(scoped.tasks[0].id,blockResult.id);assert.equal(scoped.tasks[0].artifacts[0].parts[0].content.value,'Synthetic prefix 🌍 suffix');
 const completed=await list(sdk,{status:TaskState.TASK_STATE_COMPLETED});assert.equal(completed.totalSize,4);assert.ok(completed.tasks.every(task=>task.status.state===TaskState.TASK_STATE_COMPLETED));
 assert.equal((await list(sdk,{statusTimestampAfter:new Date(Date.now()+60000).toISOString()})).totalSize,0);assert.equal((await list(sdk,{statusTimestampAfter:'1970-01-01T01:00:00+01:00'})).totalSize,6);
 for(const params of [{pageSize:0},{pageSize:101},{pageToken:'invalid-token'},{includeArtifacts:'yes'},{statusTimestampAfter:'2026-02-30T00:00:00Z'},{status:'UNKNOWN'},{pageToken:firstPage.nextPageToken,status:'TASK_STATE_COMPLETED'}])assert.equal((await rpc('ListTasks',params)).error.code,-32602);
 const forged=JSON.parse(Buffer.from(firstPage.nextPageToken,'hex').toString('utf8'));forged.bound+=100000;assert.equal((await rpc('ListTasks',{pageToken:Buffer.from(JSON.stringify(forged)).toString('hex')})).error.code,-32602);
 assert.ok(wire.length>5);assert.ok(wire.every(item=>item.version==='1.0'&&!item.method.includes('/')),'Official SDK must use native v1 headers/methods without a compatibility layer');assert.ok(wire.some(item=>item.method==='SendStreamingMessage'&&item.params.message.parts[0].text==='stream'));
 const count=requests.length;await stop();await start(false);const restarted=await client();assert.equal((await restarted.getTask({id:blockResult.id})).artifacts[0].parts[0].content.value,'Synthetic prefix 🌍 suffix');
 assert.equal((await list(restarted,{pageSize:1,pageToken:firstPage.nextPageToken})).totalSize,6,'Cursor/filter data must remain usable after restart');
 assert.equal((await rpc('message/send',legacy('blocking-message','block'),'0.3')).result.id,blockResult.id,'Cross-version replay must reuse the same persisted task');assert.equal((await restarted.sendMessage(sdkInput('blocking-message','block'))).id,blockResult.id);assert.equal(requests.length,count);
 console.log('Native A2A 1.0 passed official SDK discovery/send/get/list/cancel/stream/subscribe without compatibility translation, default and legacy blocking, version/shape rejection, control capacity, disconnect isolation, actual status times and scoped cursor pagination, cross-version durable retries and restart. Provider replies are synthetic. Continuation, files/push/delegation/team scope and full compliance remain incomplete.');
}finally{for(const response of held.values())response.destroy();await stop();for(const stream of streams)await stream.pump;await new Promise(resolve=>peer.close(resolve));assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-a2a-v1-'));await rm(root,{recursive:true,force:true});}
