// Synthetic provider frames; real compiled agent/CLI, owned files, approvals,
// scope delivery and embedded xlang3 SQLite. No live provider or UI claim.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
const [serverExe,cliExe,modules,stdlib]=process.argv.slice(2);
const owned=await mkdtemp(join(tmpdir(),'xmind-agent-patch-')),workspace=join(owned,'workspace');
const token=randomBytes(32).toString('hex'),env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
let child,port,stderr='',peerError;const calls=new Map(),reports=new Map();
const mixed='*** Begin Patch\n*** Add File: created/first.txt\n+first\n*** Update File: update.txt\n@@\n-before\n+after\n*** Update File: src/source.txt\n*** Move to: dest/moved.txt\n@@\n-before move\n+after move\n*** Delete File: delete.txt\n*** End Patch\n';
const ownGuide='*** Begin Patch\n*** Add File: own/AGENTS.md\n+Synthetic approved own scope instructions.\n*** Add File: own/code.txt\n+code\n*** End Patch\n';
const finalCode='*** Begin Patch\n*** Add File: own/code.txt\n+code\n*** End Patch\n';
const denied='*** Begin Patch\n*** Add File: deny-first.txt\n+first\n*** Add File: deny-second.txt\n+second\n*** End Patch\n';
const peer=createServer((request,response)=>{let body='';request.on('data',bytes=>body+=bytes);request.on('end',async()=>{try{
 const value=JSON.parse(body),prompt=value.messages.find(message=>message.role==='user')?.content;assert.ok(['mixed','own-guide','denied','readonly'].includes(prompt));
 const count=(calls.get(prompt)||0)+1;calls.set(prompt,count);const names=value.tools.map(tool=>tool.function.name);
 assert.equal(names.includes('apply_patch'),prompt!=='readonly','Read-only authority must not advertise patch effects');
 const definition=value.tools.find(tool=>tool.function.name==='apply_patch');if(definition)assert.equal(definition.function.parameters.additionalProperties,false);
 const last=value.messages.filter(message=>message.role==='tool').at(-1);let patch;
 if(prompt==='mixed'){
  if(count===1)patch=mixed;
  else if(count===2){assert.equal(JSON.parse(last.content).error.code,'repository_instructions_required');const supplied=value.messages.filter(message=>message.role==='system').map(message=>message.content).join('\n');assert.ok(supplied.includes('Synthetic source scope instructions.')&&supplied.includes('Synthetic destination scope instructions.'));const [run]=await api('/v1/sessions/mixed/runs');assert.deepEqual(await api('/v1/runs/'+run.id+'/operations'),[],'Guidance-only model turn must create no approval/effect');patch=mixed;}
  else{assert.equal(count,3);const result=JSON.parse(last.content);assert.equal(result.state,'succeeded');assert.equal(result.atomic,false);assert.equal(result.succeeded_files,4);assert.deepEqual(result.outcomes.map(outcome=>outcome.action),['add','update','move','delete']);reports.set(prompt,result);}
 }else if(prompt==='own-guide'){
  if(count===1)patch=ownGuide;
  else if(count===2){const result=JSON.parse(last.content);assert.equal(result.state,'partial');assert.equal(result.succeeded_files,1);assert.equal(result.stop_reason,'guidance_changed');assert.equal(result.not_requested.length,1);assert.equal(await readFile(join(workspace,'own/AGENTS.md'),'utf8'),'Synthetic approved own scope instructions.\n');await assert.rejects(readFile(join(workspace,'own/code.txt')),{code:'ENOENT'});assert.ok(value.messages.filter(message=>message.role==='system').some(message=>message.content.includes('Synthetic approved own scope instructions.')));reports.set('own-guide-partial',result);patch=finalCode;}
  else{assert.equal(count,3);const result=JSON.parse(last.content);assert.equal(result.state,'succeeded');assert.equal(result.succeeded_files,1);reports.set(prompt,result);}
 }else if(prompt==='denied'){
  if(count===1)patch=denied;else{assert.equal(count,2);const result=JSON.parse(last.content);assert.equal(result.state,'partial');assert.equal(result.succeeded_files,1);assert.equal(result.stop_reason,'permission_denied');assert.deepEqual(result.outcomes.map(outcome=>outcome.state),['succeeded','denied']);reports.set(prompt,result);}
 }else assert.equal(count,1);
 const delta=patch?{tool_calls:[{index:0,id:'synthetic-patch-'+prompt+'-'+count,type:'function',function:{name:'apply_patch',arguments:JSON.stringify({patch_text:patch,create_parents:true})}}]}:{content:prompt==='denied'?'Observed one actual creation and one denial.':'Observed actual native patch result: '+prompt};
 response.writeHead(200,{'Content-Type':'text/event-stream'});response.end(`data: ${JSON.stringify({choices:[{index:0,delta,finish_reason:null}]})}\n\ndata: ${JSON.stringify({choices:[{index:0,delta:{},finish_reason:patch?'tool_calls':'stop'}]})}\n\ndata: ${JSON.stringify({choices:[],usage:{prompt_tokens:12,completion_tokens:6,total_tokens:18}})}\n\ndata: [DONE]\n\n`);
 }catch(error){peerError=error;response.writeHead(500);response.end('Synthetic patch provider fixture failed');}});});
async function api(path,body){const response=await fetch(`http://127.0.0.1:${port}${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(5000)});assert.ok(response.ok,await response.clone().text());return response.json();}
function cli(...args){const result=spawnSync(cliExe,[String(port),...args],{env,windowsHide:true,encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout);}
async function start(edits=true){stderr='';const args=['--db',join(owned,'state.sqlite'),'--modules',modules,'--stdlib',stdlib,'--port','0','--model','synthetic-native-patch','--model-stream-usage','supported','--model-endpoint','http://127.0.0.1:'+peer.address().port+'/chat','--model-tools','supported','--workspace',workspace];if(edits)args.push('--workspace-edits','approved');child=spawn(serverExe,args,{env,windowsHide:true});child.stderr.on('data',bytes=>stderr+=bytes);port=await new Promise((yes,no)=>{let output='';const timer=setTimeout(()=>no(Error('Native readiness deadline: '+stderr)),10000);child.once('error',no);child.once('exit',code=>{clearTimeout(timer);no(Error('Native exited '+code+': '+stderr));});child.stdout.on('data',bytes=>{output+=bytes;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(output);if(match){clearTimeout(timer);yes(Number(match[1]));}});});}
async function stop(){if(child&&child.exitCode===null){const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;}}
async function completed(id){const deadline=Date.now()+8000;while(Date.now()<deadline){if(peerError)throw peerError;const run=await api('/v1/runs/'+id);if(['completed','failed','cancelled'].includes(run.state)){assert.equal(run.state,'completed',JSON.stringify(await api('/v1/runs/'+id+'/events')));return run;}await delay(10);}throw Error('Native patch run deadline');}
async function consolePatch(prompt){const process=spawn(cliExe,[String(port),'chat',prompt],{env,windowsHide:true}),records=[],reviewed=[];let buffer='',errorText='',failure;
 process.stderr.on('data',bytes=>errorText+=bytes);process.stdout.on('data',bytes=>{buffer+=bytes;let newline;while((newline=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,newline);buffer=buffer.slice(newline+1);try{const record=JSON.parse(line);records.push(record);if(record.type==='operation_review'){const operation=record.operation,plan=JSON.parse(operation.arguments_json);assert.equal(operation.tool,'patch_file');assert.equal(operation.state,'awaiting_approval');assert.ok(Array.isArray(plan.patch_files)&&plan.patch_files.length===plan.patch_file_count);if(plan.action==='add')assert.equal(plan.before_exists,false);if(plan.action==='delete')assert.equal(plan.after_exists,false);if(plan.action==='move')assert.deepEqual(plan.repository_guidance.scope_directories,['src','dest']);reviewed.push(operation.id);process.stdin.write('/'+(prompt==='denied'&&reviewed.length===2?'deny':'allow')+' '+operation.id+'\n');}if(record.type==='turn_finished')process.stdin.end('/exit\n');}catch(error){failure=error;process.kill();}}});
 const timer=setTimeout(()=>process.kill(),15000);const exited=await new Promise((yes,no)=>{process.once('error',no);process.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal});});process.stdin.write(prompt+'\n');});if(failure)throw failure;if(peerError)throw peerError;assert.equal(exited.signal,null);assert.equal(exited.code,0,errorText);assert.ok(records.some(record=>record.kind==='run.completed'));return {records,reviewed};}
try{
 await mkdir(workspace);await mkdir(join(workspace,'src'));await mkdir(join(workspace,'dest'));await writeFile(join(workspace,'AGENTS.md'),'Synthetic root instructions.\n');await writeFile(join(workspace,'src/AGENTS.md'),'Synthetic source scope instructions.\n');await writeFile(join(workspace,'dest/AGENTS.md'),'Synthetic destination scope instructions.\n');await writeFile(join(workspace,'src/source.txt'),'before move\n');await writeFile(join(workspace,'update.txt'),'before\n');await writeFile(join(workspace,'delete.txt'),'delete these bytes\n');await new Promise(resolve=>peer.listen(0,'127.0.0.1',resolve));await start();
 const observed={};for(const prompt of ['mixed','own-guide','denied']){await api('/v1/sessions',{id:prompt,title:'Synthetic native patch '+prompt});observed[prompt]=await consolePatch(prompt);assert.equal(observed[prompt].reviewed.length,prompt==='mixed'?4:2);}
 assert.equal(await readFile(join(workspace,'created/first.txt'),'utf8'),'first\n');assert.equal(await readFile(join(workspace,'update.txt'),'utf8'),'after\n');assert.equal(await readFile(join(workspace,'dest/moved.txt'),'utf8'),'after move\n');await assert.rejects(readFile(join(workspace,'src/source.txt')),{code:'ENOENT'});await assert.rejects(readFile(join(workspace,'delete.txt')),{code:'ENOENT'});assert.equal(await readFile(join(workspace,'own/code.txt'),'utf8'),'code\n');assert.equal(await readFile(join(workspace,'deny-first.txt'),'utf8'),'first\n');await assert.rejects(readFile(join(workspace,'deny-second.txt')),{code:'ENOENT'});
 for(const outcome of reports.get('mixed').outcomes){const actual=await api('/v1/operations/'+outcome.operation_id);assert.equal(actual.state,'succeeded');const receipt=JSON.parse(actual.result_json);if(receipt.after_exists){const bytes=await readFile(join(workspace,receipt.path));assert.equal(createHash('sha256').update(bytes).digest('hex'),receipt.after_sha256);}else assert.equal(receipt.removed_size,Buffer.byteLength('delete these bytes\n'));}
 const sessions=await api('/v1/sessions'),histories=new Map();for(const session of sessions){const history=await api('/v1/sessions/'+session.id+'/history');histories.set(session.id,history);assert.ok(history.some(message=>message.role==='assistant'&&message.data.usage?.total_tokens===18),'Actual persisted response must retain exactly supplied synthetic counters');}
 await stop();await start(false);for(const [id,history]of histories)assert.deepEqual(await api('/v1/sessions/'+id+'/history'),history,'Restart must preserve exact provider/tool history without replay');const before=calls.size;await api('/v1/sessions',{id:'readonly',title:'Synthetic read-only patch catalogue'});const run=cli('run','readonly','readonly');await completed(run.id);assert.equal((await api('/v1/runs/'+run.id+'/operations')).length,0);assert.equal(calls.size,before+1);if(peerError)throw peerError;
 console.log('Native patch agent/CLI contract passed real approvals, mixed effects and hash receipts, source/destination guidance delivery, own-guide partial outcome and fresh model turn, denial, read-only catalogue and exact xlang3 SQLite history restart. Inference/usage are synthetic; no live provider or rendered client acceptance.');
}finally{await stop();peer.closeAllConnections();await new Promise(resolve=>peer.close(resolve));assert.equal(dirname(resolve(owned)),resolve(tmpdir()));assert.ok(owned.includes('xmind-agent-patch-'));await rm(owned,{recursive:true,force:true});}
