// Synthetic wire data validates a real native decoder; no model or network.
#include "agentflow/anthropic_stream.hpp"
#include "nlohmann/json.hpp"
#include <algorithm>
#include <iostream>
using namespace agentflow;using Json=nlohmann::json;
namespace {
void require(bool value,const char* reason){if(!value)throw std::runtime_error(reason);}
std::string event(const Json& value){return "event: "+value.at("type").get<std::string>()+"\ndata: "+value.dump()+"\n\n";}
Json start(){return {{"type","message_start"},{"message",{{"id","msg_fixture"},{"type","message"},{"role","assistant"},{"model","fixture-model"},{"content",Json::array()},{"stop_reason",nullptr},{"stop_sequence",nullptr},{"usage",{{"input_tokens",12},{"output_tokens",0},{"cache_read_input_tokens",7}}}}}};}
Json update(const std::string& reason="end_turn",int tokens=8){return {{"type","message_delta"},{"delta",{{"stop_reason",reason},{"stop_sequence",nullptr}}},{"usage",{{"output_tokens",tokens}}}};}
std::string stop(){return event({{"type","message_stop"}});}
std::string text(){return event({{"type","content_block_start"},{"index",0},{"content_block",{{"type","text"},{"text",""}}}})+event({{"type","content_block_delta"},{"index",0},{"delta",{{"type","text_delta"},{"text","Exact text 🌍"}}}})+event({{"type","content_block_stop"},{"index",0}});}
std::string tool(int index,const std::string& id){return event({{"type","content_block_start"},{"index",index},{"content_block",{{"type","tool_use"},{"id",id},{"name","read_file"},{"input",Json::object()}}}})+event({{"type","content_block_delta"},{"index",index},{"delta",{{"type","input_json_delta"},{"partial_json","{\"path\":"}}}})+event({{"type","content_block_delta"},{"index",index},{"delta",{{"type","input_json_delta"},{"partial_json","\"README.md\"}"}}}})+event({{"type","content_block_stop"},{"index",index}});}
std::string begin(int index,const Json& content){return event({{"type","content_block_start"},{"index",index},{"content_block",content}});}
std::string change(int index,const std::string& kind,const std::string& field,const std::string& value){return event({{"type","content_block_delta"},{"index",index},{"delta",{{"type",kind},{field,value}}}});}
std::string end(int index){return event({{"type","content_block_stop"},{"index",index}});}
std::string signed_thinking(int index,const std::string& hidden,const std::string& signature){return begin(index,{{"type","thinking"},{"thinking",""},{"signature",""}})+change(index,"thinking_delta","thinking",hidden)+change(index,"signature_delta","signature",signature.substr(0,signature.size()/2))+change(index,"signature_delta","signature",signature.substr(signature.size()/2))+end(index);}
std::string initial_tool(int index,const std::string& id,const std::string& input){
    // The member name and argument keys are independently Unicode-escaped in
    // this original wire string; Json.dump would normalize both and the numbers.
    return "event: content_block_start\ndata: {\"type\":\"content_block_start\",\"index\":"+std::to_string(index)+",\"content_block\":{\"type\":\"tool_use\",\"id\":"+Json(id).dump()+",\"name\":\"read_file\",\"\\u0069nput\":"+input+"}}\n\n"+end(index);
}
std::string fragmented_tool(int index,const std::string& id,const std::string& input){return begin(index,{{"type","tool_use"},{"id",id},{"name","read_file"},{"input",Json::object()}})+change(index,"input_json_delta","partial_json",input.substr(0,input.size()/2))+change(index,"input_json_delta","partial_json",input.substr(input.size()/2))+end(index);}
Json receipt(const ModelCompletion& result){const auto items=Json::parse(result.provider_items_json);require(items.is_array()&&items.size()==1&&items[0].size()==4&&items[0].at("type")=="anthropic_content"&&items[0].at("content_json").is_string(),"Claude ordered receipt must keep original content JSON inside a string");return items[0];}
void rejects(const std::string& wire){bool failed=false;std::size_t acknowledgements=0;AnthropicStream decoder([&](const ModelEvent& value){if(value.kind=="model.done")++acknowledgements;});try{decoder.feed(wire);decoder.finish();}catch(const ModelProtocolError&){failed=true;}require(failed&&acknowledgements==0,"Invalid Claude stream cannot acknowledge completion");}
}
int main(){try{
    const auto wire=event(start())+event({{"type","ping"}})+text()+event(update())+stop();
    for(const std::size_t width:{1,2,7,37,4096}){
        std::vector<ModelEvent> events;AnthropicStream decoder([&](const ModelEvent& value){events.push_back(value);});for(std::size_t offset=0;offset<wire.size();offset+=width)decoder.feed(std::string_view(wire).substr(offset,width));require(std::none_of(events.begin(),events.end(),[](const auto& value){return value.kind=="model.done";}),"Terminal acknowledgement waits for validated EOF");const auto result=decoder.finish();require(result.content=="Exact text 🌍"&&result.finish_reason=="stop"&&result.tool_calls.empty(),"Chunking must preserve observed content and terminal state");require(Json::parse(result.usage_json)==Json{{"input_tokens",12},{"output_tokens",8},{"cache_read_input_tokens",7}},"Reported token counters remain exact without invented totals");const auto saved=receipt(result);require(saved.at("finish_reason")=="stop"&&saved.at("provider_finish_reason")=="end_turn"&&Json::parse(saved.at("content_json").get<std::string>())==Json::array({{{"type","text"},{"text","Exact text 🌍"}}}),"Ordinary Claude text must receive an ordered replay receipt");decoder.finish();require(std::count_if(events.begin(),events.end(),[](const auto& value){return value.kind=="model.done";})==1,"Repeated finish cannot duplicate completion acknowledgement");
    }
    const auto calls=event(start())+tool(0,"call-left")+tool(1,"call-right")+event(update("tool_use"))+stop();AnthropicStream decoder([](const auto&){});decoder.feed(calls);const auto result=decoder.finish();require(result.tool_calls.size()==2&&result.tool_calls[0].id=="call-left"&&result.tool_calls[1].id=="call-right"&&result.tool_calls[0].name=="read_file"&&Json::parse(result.tool_calls[0].arguments_json)==Json{{"path","README.md"}},"Parallel tool deltas retain real call IDs and parsed object arguments");
    AnthropicStream truncated([](const auto&){});truncated.feed(event(start())+tool(0,"fragment")+event(update("max_tokens"))+stop());require(truncated.finish().finish_reason=="length"&&truncated.finish().tool_calls.empty()&&truncated.finish().provider_items_json=="[]","Truncated tool turns cannot expose executable calls or replayable mismatched receipts");
    const std::string raw_initial=R"({ "\u0070ath" : "README.md", "big":18446744073709551616, "precise":1.234567890123456789e-42 })",raw_fragmented=R"({"\u0070ath":"second.txt","negative":-9223372036854775809,"precise":0.1234567890123456789012345678901234})";
    auto zero=start();zero["message"]["usage"]={{"input_tokens",0},{"output_tokens",0},{"cache_creation_input_tokens",0},{"cache_read_input_tokens",0}};
    const std::string hidden="Synthetic private thinking 🌍",signature="synthetic-signature-fragments",redacted="synthetic-opaque-redacted-data";
    const auto interleaved=event(zero)+signed_thinking(0,hidden,signature)+begin(1,{{"type","text"},{"text","Before "}})+end(1)+initial_tool(2,"raw-initial",raw_initial)+begin(3,{{"type","redacted_thinking"},{"data",redacted}})+end(3)+begin(4,{{"type","text"},{"text",""}})+change(4,"text_delta","text","After 🌍")+end(4)+fragmented_tool(5,"raw-fragments",raw_fragmented)+event(update("tool_use",0))+stop();
    for(const std::size_t width:{1,2,7,37,4096}){
        std::vector<ModelEvent> events;AnthropicStream stream([&](const auto& value){events.push_back(value);});for(std::size_t offset=0;offset<interleaved.size();offset+=width)stream.feed(std::string_view(interleaved).substr(offset,width));const auto result=stream.finish();
        require(result.content=="Before After 🌍"&&result.finish_reason=="tool_calls"&&result.tool_calls.size()==2,"Only visible text and validated executable calls belong in the common completion");require(result.tool_calls[0].id=="raw-initial"&&result.tool_calls[0].arguments_json==raw_initial&&result.tool_calls[1].id=="raw-fragments"&&result.tool_calls[1].arguments_json==raw_fragmented,"Initial and fragmented arguments must retain original escaped keys, whitespace and precise numeric tokens");
        const auto saved=receipt(result);const auto source=saved.at("content_json").get<std::string>();const auto content=Json::parse(source);require(saved.at("finish_reason")=="tool_calls"&&saved.at("provider_finish_reason")=="tool_use"&&content.size()==6,"Claude receipt must preserve the complete ordered block sequence");
        const std::vector<std::string> types={"thinking","text","tool_use","redacted_thinking","text","tool_use"};for(std::size_t index=0;index<types.size();++index)require(content[index].at("type")==types[index],"Text, tool and private metadata interleaving must survive the receipt");
        require(content[0].at("thinking")==hidden&&content[0].at("signature")==signature&&content[3].at("data")==redacted,"Opaque signed and redacted blocks must be retained exactly without fabricated signature verification");require(source.find(raw_initial)!=std::string::npos&&source.find(raw_fragmented)!=std::string::npos,"Receipt content must retain exact original tool input JSON rather than dumped floating-point values");
        std::string visible;for(const auto& value:events){require(value.json.find(hidden)==std::string::npos&&value.json.find(signature)==std::string::npos&&value.json.find(redacted)==std::string::npos,"Hidden thinking, signatures and redacted data cannot leak through public model events");if(value.kind=="model.text")visible+=Json::parse(value.json).at("text").get<std::string>();if(value.kind=="model.usage")require(Json::parse(value.json)==zero["message"]["usage"],"Raw token decoder must retain supplied zero counters without normalized aliases or reasoning estimates");}
        require(visible==result.content&&Json::parse(result.usage_json)==zero["message"]["usage"],"Visible text events and raw actual zero usage must agree with completion");
    }
    AnthropicStream signed_length([](const auto&){});signed_length.feed(event(zero)+signed_thinking(0,hidden,signature)+begin(1,{{"type","text"},{"text","Limited visible text"}})+end(1)+event(update("max_tokens",0))+stop());const auto limited=signed_length.finish();require(limited.content=="Limited visible text"&&limited.tool_calls.empty()&&receipt(limited).at("provider_finish_reason")=="max_tokens","A signed text-only length stop may retain its matching nonexecutable receipt");
    std::vector<ModelEvent> private_events;AnthropicStream private_only([&](const auto& value){private_events.push_back(value);});private_only.feed(event(zero)+begin(0,{{"type","thinking"},{"thinking",hidden},{"signature",signature}})+end(0)+begin(1,{{"type","redacted_thinking"},{"data",redacted}})+end(1)+event(update("end_turn",0))+stop());const auto private_result=private_only.finish();require(private_result.content.empty()&&private_result.tool_calls.empty()&&Json::parse(receipt(private_result).at("content_json").get<std::string>()).size()==2&&std::none_of(private_events.begin(),private_events.end(),[](const auto& value){return value.kind=="model.text";}),"Nonempty signed/redacted-only receipt must not fabricate visible text");
    AnthropicStream empty([](const auto&){});empty.feed(event(zero)+event(update("end_turn",0))+stop());require(receipt(empty.finish()).at("content_json")=="[]","An empty valid natural stop must preserve its checked empty content array");
    auto incremental=update();incremental["delta"]["stop_reason"]=nullptr;incremental["usage"]["output_tokens"]=3;AnthropicStream cumulative([](const auto&){});cumulative.feed(event(start())+event(incremental)+text()+event(update())+stop());require(Json::parse(cumulative.finish().usage_json)["output_tokens"]==8,"Usage-only updates retain the eventual terminal count");
    for(std::size_t length=0;length<wire.size();++length)rejects(wire.substr(0,length));
    rejects(event(start())+text()+stop());rejects(event(start())+event(start()));rejects(event(start())+tool(0,"same")+tool(1,"same")+event(update("tool_use"))+stop());rejects(event(start())+tool(1,"wrong-index"));
    rejects(event(start())+event({{"type","content_block_stop"},{"index",0}}));rejects(event(start())+event({{"type","content_block_start"},{"index",0},{"content_block",{{"type","thinking"},{"thinking","private"}}}}));
    rejects(event(start())+text()+event(update("unsupported"))+stop());rejects(wire+event({{"type","ping"}}));rejects("event: ping\ndata: {\"type\":\"message_stop\"}\n\n");rejects("event: ping\ndata: {\"type\":\"ping\",\"type\":\"ping\"}\n\n");
    rejects(event(start())+event({{"type","error"},{"error",{{"message","private-provider-error"}}}}));auto decreasing=update();decreasing["usage"]["input_tokens"]=1;rejects(event(start())+text()+event(decreasing)+stop());
    const auto bad=event(start())+event({{"type","content_block_start"},{"index",0},{"content_block",{{"type","tool_use"},{"id","bad-json"},{"name","read_file"},{"input",Json::object()}}}})+event({{"type","content_block_delta"},{"index",0},{"delta",{{"type","input_json_delta"},{"partial_json","{\"path\":1,\"path\":2}"}}}})+event({{"type","content_block_stop"},{"index",0}});rejects(bad);
    const auto thinking=begin(0,{{"type","thinking"},{"thinking",""}}),thinking_delta=change(0,"thinking_delta","thinking",hidden),signature_delta=change(0,"signature_delta","signature",signature);
    rejects(event(start())+thinking+thinking_delta+end(0));rejects(event(start())+thinking+thinking_delta+change(0,"signature_delta","signature","")+end(0));rejects(event(start())+thinking+signature_delta+thinking_delta);
    rejects(event(start())+thinking+change(0,"signature_delta","signature","")+thinking_delta);rejects(event(start())+begin(0,{{"type","thinking"},{"signature",signature}}));
    rejects(event(start())+begin(0,{{"type","thinking"},{"thinking","initial"},{"signature",signature}})+thinking_delta);rejects(event(start())+thinking+change(0,"text_delta","text","private"));rejects(event(start())+begin(0,{{"type","text"},{"text",""}})+signature_delta);
    rejects(event(start())+begin(0,{{"type","thinking"},{"thinking",0},{"signature",signature}}));rejects(event(start())+begin(0,{{"type","thinking"},{"thinking",""},{"signature",0}}));rejects(event(start())+thinking+change(0,"signature_delta","signature",std::string(65537,'s')));
    rejects(event(start())+thinking+change(0,"signature_delta","signature",std::string("bad\0signature",13)));rejects(event(start())+thinking+signature_delta+end(0)+end(0));
    rejects(event(start())+begin(0,{{"type","redacted_thinking"},{"data",""}}));rejects(event(start())+begin(0,{{"type","redacted_thinking"},{"data",0}}));rejects(event(start())+begin(0,{{"type","redacted_thinking"},{"data",redacted}})+change(0,"thinking_delta","thinking",hidden));rejects(event(start())+begin(0,{{"type","redacted_thinking"},{"data",redacted},{"signature",signature}}));
    rejects(event(start())+"event: content_block_start\ndata: {\"type\":\"content_block_start\",\"index\":0,\"content_block\":{\"type\":\"thinking\",\"thinking\":\"a\",\"\\u0074hinking\":\"b\"}}\n\n");
    rejects(event(start())+fragmented_tool(0,"duplicate-escaped",R"({"path":1,"\u0070ath":2})"));rejects(event(start())+fragmented_tool(0,"array-input","[]"));rejects(event(start())+fragmented_tool(0,"empty-fragment",""));rejects(event(start())+fragmented_tool(0,"malformed-input","{\"path\":}"));
    rejects(event(start())+begin(0,{{"type","tool_use"},{"id","conflicting-input"},{"name","read_file"},{"input",{{"path","initial"}}}})+change(0,"input_json_delta","partial_json","{}"));
    std::string deep="{}";for(int index=0;index<18;++index)deep="{\"nested\":"+deep+'}';rejects(event(start())+initial_tool(0,"deep-input",deep));
    rejects(event(start())+text()+event(update())+event(update())+stop());rejects(event(start())+begin(0,{{"type","unknown"},{"text","unsupported"}}));
    std::string oversized=event(start())+thinking;for(int index=0;index<6;++index)oversized+=change(0,"thinking_delta","thinking",std::string(768*1024,'t'));rejects(oversized);
    std::cout<<"Native Claude SSE component passed fragmented Unicode text and ordered text/tool/signed-thinking/redacted receipts, exact initial/delta tool JSON precision and escaped keys, hidden-content exclusion, supplied raw zero/cumulative counters, signature ordering/bounds, truncated-call/receipt exclusion and malformed/duplicate/incomplete/late-event rejection without completion acknowledgement. Wire fixtures are synthetic; no network, cryptographic signature verification, enrollment or live inference occurred.\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
