// Actual production server entry point, two physically distinct qualified
// directories, HTTP commands and embedded-xlang3 SQLite. Package provenance,
// unused executables and license notice are fixtures. No model/provider calls,
// accepted release package, installed editor or file-writing acceptance.
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {setTimeout as delay} from 'node:timers/promises';
const [server,dll,modules,stdlib]=process.argv.slice(2);if(!stdlib)throw Error('Actual xmind executable and allowed SDK sources required');
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-handoff-')),workspace=path.join(base,'workspace-写-😀'),other=path.join(base,'other-workspace'),database=path.join(base,'state.sqlite'),token='t'.repeat(64),children=new Set();await fs.mkdir(workspace);await fs.mkdir(other);const sha=b=>crypto.createHash('sha256').update(b).digest('hex');let passed=false;
async function generation(name,revision){const root=path.join(base,name);await fs.mkdir(root);const content={'xmind.exe':await fs.readFile(server),'xlang3_runtime.dll':await fs.readFile(dll),'xlang3.exe':Buffer.from('unused synthetic integrity fixture'),'licenses/NOTICE.txt':Buffer.from('Synthetic handoff contract; not release provenance.')};for(const name of ['xlang_json.x3pkg.dll','xlang_sqlite3.x3pkg.dll'])content['modules/'+name]=await fs.readFile(path.join(modules,name));for(const name of ['os.py','json/__init__.py','encodings/__init__.py','importlib/__init__.py'])content['stdlib/'+name]=await fs.readFile(path.join(stdlib,...name.split('/')));for(const [name,bytes]of Object.entries(content)){await fs.mkdir(path.dirname(path.join(root,...name.split('/'))),{recursive:true});await fs.writeFile(path.join(root,...name.split('/')),bytes,{flag:'wx'});}const raw=Buffer.from(JSON.stringify({schemaVersion:1,platform:'win32',arch:'x64',bridgeEnabled:false,nativeRevision:revision.repeat(40),sdkRevision:'c'.repeat(40),sourceManifestSha256:'d'.repeat(64),files:Object.fromEntries(Object.entries(content).map(([n,b])=>[n,sha(b)]))}));await fs.writeFile(path.join(root,'native-runtime-manifest.json'),raw);return {root,digest:sha(raw),programName:'xmind.exe'};}
async function observedExit(closed){let timer;try{return await Promise.race([closed,new Promise((_,no)=>{timer=setTimeout(()=>no(Error('Native process exit observation timed out')),10000);})]);}finally{clearTimeout(timer);}}
async function start(gen,{receipt,edits=false,auth=token,ws=workspace,reject=false,digest=gen.digest,errorPattern=/Replacement receipt, target or database binding changed/}={}){
 const args=['--db',database,'--modules',path.join(gen.root,'modules'),'--stdlib',path.join(gen.root,'stdlib'),'--workspace',ws,'--port','0','--runtime-manifest-sha256',digest];if(receipt)args.push('--owner-receipt',`${receipt.generation}:${receipt.revision}:${receipt.receipt_id}`);if(edits)args.push('--workspace-edits','approved');const env={...process.env,XMIND_AUTH_TOKEN:auth};delete env.XMIND_API_KEY;
 const child=cp.spawn(path.join(gen.root,gen.programName),['serve',...args],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});children.add(child);let stdout='',stderr='',origin;const closed=new Promise((yes,no)=>{child.once('error',no);child.once('close',(code,signal)=>{children.delete(child);yes({code,signal});});});child.stdout.on('data',b=>{stdout+=b;origin=/listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(stdout)?.[1];});child.stderr.on('data',b=>stderr+=b);
 const deadline=Date.now()+15000;while(Date.now()<deadline&&!origin&&child.exitCode===null)await delay(10);
 if(reject){assert.equal(origin,undefined,'Rejected bootstrap cannot bind a listener');assert.deepEqual(await observedExit(closed),{code:1,signal:null},stderr);assert.match(stderr,errorPattern,'A module-loading failure cannot count as a receipt/target rejection');return;}
 assert.ok(origin,stderr);return {child,closed,origin};
}
async function request(owner,route,body,authorization='Bearer '+token){return fetch(owner.origin+route,{method:body===undefined?'GET':'POST',headers:{Authorization:authorization,...(authorization.startsWith('View ')?{'X-XMind-View-Origin':'http://127.0.0.1:60405'}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(5000)});}
async function read(owner,route){const r=await request(owner,route);assert.equal(r.status,200);return r.json();}
function expected(state,ws){return {expected_generation:state.generation,expected_revision:state.revision,receipt_id:state.receipt_id,expected_workspace_id:ws.workspace_id,expected_workspace_authority_id:ws.authority_id};}

try{
 const old=await generation('old-generation','a'),next=await generation('next-generation-新-😀','b');const owner=await start(old);const ws=await read(owner,'/v1/workspace');let state=await read(owner,'/v1/backend/owner');assert.equal(state.process_id,owner.child.pid);assert.match(state.process_birth,/^\d+$/);assert.equal(state.retirement_supported,true);assert.equal((await read(owner,'/v1/health')).file_edit_proposals,false);assert.equal((await request(owner,'/v1/sessions',{id:'saved',title:'Actual native handoff fixture'})).status,201);const sessions=await read(owner,'/v1/sessions'),history=await read(owner,'/v1/sessions/saved/history'),profiles=await read(owner,'/v1/provider/profiles');
 const view=await(await request(owner,'/v1/view-sessions',{origin:'http://127.0.0.1:60405'})).json();assert.equal((await request(owner,'/v1/backend/owner/retire',{...expected(state,ws),target_runtime_root:next.root,target_manifest_sha256:next.digest,approved_edits:true},'View '+view.credential)).status,401);
 const q=await request(owner,'/v1/backend/owner/quiesce',{expected_generation:state.generation,expected_revision:state.revision,expected_workspace_id:ws.workspace_id,expected_workspace_authority_id:ws.authority_id});assert.equal(q.status,200);state=await q.json();const receipt={generation:state.generation,revision:state.revision,receipt_id:state.receipt_id};assert.equal((await request(owner,'/v1/backend/owner/retire',{...expected(state,ws),target_runtime_root:next.root,target_manifest_sha256:'f'.repeat(64),approved_edits:true})).status,409);assert.equal((await read(owner,'/v1/backend/owner')).retirement_requested,false);
 const retired=await request(owner,'/v1/backend/owner/retire',{...expected(state,ws),target_runtime_root:next.root,target_manifest_sha256:next.digest,approved_edits:true});assert.equal(retired.status,200);assert.deepEqual((await retired.json()).bootstrap_receipt,receipt);assert.deepEqual(await owner.closed,{code:0,signal:null},'Retirement must actually stop the production server');
 for(const options of [{auth:'w'.repeat(64)},{ws:other},{edits:false},{digest:'f'.repeat(64),errorPattern:/Native runtime generation verification failed/}])await start(next,{receipt,edits:true,...options,reject:true});await start(old,{receipt,edits:true,reject:true});
 const replacement=await start(next,{receipt,edits:true});const actual=await read(replacement,'/v1/workspace');const prepared=await read(replacement,'/v1/backend/owner');assert.equal(prepared.replacement_prepared,true);assert.equal(prepared.quiesced,true);assert.notEqual(prepared.generation,state.generation);assert.equal(actual.workspace_id,ws.workspace_id);assert.notEqual(actual.authority_id,ws.authority_id);assert.deepEqual(await read(replacement,'/v1/sessions'),sessions);assert.deepEqual(await read(replacement,'/v1/sessions/saved/history'),history);assert.deepEqual(await read(replacement,'/v1/provider/profiles'),profiles);assert.equal((await request(replacement,'/v1/sessions',{id:'blocked',title:'must not exist'})).status,503);assert.equal((await request(replacement,'/a2a',{jsonrpc:'2.0',id:1,method:'message/send',params:{}})).status,503);assert.equal((await request(replacement,'/v1/backend/owner/resume',expected(prepared,actual))).status,409);
 const activation=await request(replacement,'/v1/backend/owner/activate',expected(prepared,actual));assert.equal(activation.status,200);assert.equal((await activation.json()).quiesced,false);assert.equal((await request(replacement,'/v1/backend/owner/activate',expected(prepared,actual))).status,409);assert.equal((await read(replacement,'/v1/health')).file_edit_proposals,true);assert.equal((await request(replacement,'/v1/sessions',{id:'after',title:'Actual new-generation admission'})).status,201);assert.ok((await read(replacement,'/v1/sessions')).some(s=>s.id==='saved'));replacement.child.kill();await replacement.closed;await start(next,{receipt,edits:true,reject:true});
 passed=true;console.log(JSON.stringify({actualProductionServerEntryPoint:true,actualQualifiedImageAndWorkspace:true,unicodeWorkspaceAndPackage:true,targetBoundRetirementAndObservedExit:true,wrongAuthWorkspacePolicyManifestAndPackageRejected:true,preparedAdmissionClosed:true,nativeActivationAndNewAdmission:true,savedSessionAndEmptyHistoryAndProviderListRetained:true,providerRequests:0,liveProvider:false,releasePackage:false,installedLegacyMigration:false,installed:false,fileWrite:false}));
}finally{for(const child of children)child.kill();const deadline=Date.now()+10000;while(children.size&&Date.now()<deadline)await delay(10);assert.equal(children.size,0,'Owned fixture processes must exit before directory cleanup');assert.equal(await fs.realpath(base),base);assert.equal(path.dirname(base),parent);assert.ok(path.basename(base).startsWith('xmind-handoff-'));assert.ok(!(await fs.lstat(base)).isSymbolicLink());if(passed)await fs.rm(base,{recursive:true,force:true});else console.error(JSON.stringify({failedFixtureRetained:base}));}
