// Actual unified console, native HTTP, tool graph and xlang3 SQLite. The small
// proxy changes public metadata only to test connection pinning and admission
// races; it never simulates an agent, model, tool effect or provider usage.
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import http from 'node:http';import {randomBytes} from 'node:crypto';
const [program,modules,stdlib]=process.argv.slice(2);assert.ok(stdlib);
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-console-workspace-')),workspace=path.join(base,'workspace 雪'),other=path.join(base,'other'),catalog=path.join(base,'graphs.json'),token=randomBytes(32).toString('hex'),env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
await fs.mkdir(workspace);await fs.mkdir(other);await fs.writeFile(path.join(workspace,'note.txt'),'Native pinned workspace\n');await fs.writeFile(catalog,JSON.stringify({graphs:[{id:'pinned.read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'note.txt'}}]}}]}));
const child=cp.spawn(program,['serve','--db',path.join(base,'state.sqlite'),'--modules',modules,'--stdlib',stdlib,'--workspace',workspace,'--graphs-config',catalog,'--port','0'],{env,windowsHide:true});let origin,errors='',passed=false;const proxies=new Set();const closed=new Promise((yes,no)=>{child.once('error',no);child.once('close',(code,signal)=>yes({code,signal}));});child.stderr.on('data',b=>errors+=b);
async function invoke(port,args,options={}){return new Promise((yes,no)=>{const client=cp.spawn(program,['--port',String(port),...args],{env,windowsHide:true});let stdout='',stderr='';client.stdout.on('data',b=>stdout+=b);client.stderr.on('data',b=>stderr+=b);client.once('error',no);const timer=setTimeout(()=>client.kill(),20000);client.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal,stdout,stderr});});client.stdin.end(options.input??'');});}
async function command(...args){const value=await invoke(new URL(origin).port,args);assert.equal(value.code,0,value.stderr);assert.equal(value.signal,null);return JSON.parse(value.stdout);}
async function proxy(mode){let observations=0;const posts=[];const server=http.createServer(async(req,res)=>{try{const parts=[];for await(const chunk of req)parts.push(chunk);const body=Buffer.concat(parts);if(req.method==='POST')posts.push({route:req.url,body:JSON.parse(body.toString('utf8'))});const up=await fetch(origin+req.url,{method:req.method,headers:{Authorization:'Bearer '+token,...(req.method==='POST'?{'Content-Type':'application/json'}:{})},body:req.method==='POST'?body:undefined});if(req.method==='POST')posts.at(-1).status=up.status;let value=await up.text();if(req.url==='/v1/workspace'){observations++;const meta=JSON.parse(value);if(mode==='changed'&&observations>=2||mode==='race')value=JSON.stringify({...meta,authority_id:'f'.repeat(32)});if(mode==='duplicate')value=value.slice(0,-1)+',"authority_id":"'+meta.authority_id+'"}';}res.writeHead(up.status,{'Content-Type':'application/json'});res.end(value);}catch{res.writeHead(502);res.end('{}');}});await new Promise(yes=>server.listen(0,'127.0.0.1',yes));proxies.add(server);return {port:server.address().port,posts,get observations(){return observations;}};}
try{
 origin=await new Promise((yes,no)=>{const timer=setTimeout(()=>no(Error('Native startup: '+errors)),15000);child.once('exit',()=>{clearTimeout(timer);no(Error('Native stopped: '+errors));});let text='';child.stdout.on('data',b=>{text+=b;const match=/listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(text);if(match){clearTimeout(timer);yes(match[1]);}});});
 assert.equal((await command('--workspace',workspace,'health')).status,'ok');
 const wrong=await invoke(new URL(origin).port,['--workspace',other,'create-session','must not exist']);assert.equal(wrong.code,1);assert.match(wrong.stderr,/workspace differs/);assert.deepEqual(await command('sessions'),[]);
 for(const args of [['--workspace'],['--workspace',''],['--workspace',workspace,'--workspace',workspace],['--port','4']]){const value=await invoke(new URL(origin).port,args);assert.equal(value.code,2);}
 const composed=await invoke(new URL(origin).port,['--workspace',workspace,'chat'],{input:'/compose pinned.read\nRead this workspace\n/send\n/exit\n'});assert.equal(composed.code,0,composed.stderr);const rows=composed.stdout.trim().split(/\r?\n/).map(s=>JSON.parse(s)),run=rows.find(r=>r.type==='run').run;assert.equal((await command('graph',run.id)).checkpoint.nodes[0].output.content,'Native pinned workspace\n');assert.equal((await command('status',run.id)).state,'completed');
 const saved=await command('sessions'),history=await command('history',run.session_id);
 const changed=await proxy('changed'),attempt=await invoke(changed.port,['--workspace',workspace,'chat'],{input:'must not be admitted\n/exit\n'});assert.equal(attempt.code,1);assert.match(attempt.stderr,/authority changed/);assert.equal(changed.observations,2);assert.deepEqual(changed.posts,[]);
 const duplicate=await proxy('duplicate'),bad=await invoke(duplicate.port,['--workspace',workspace,'create-session','must not exist']);assert.equal(bad.code,1);assert.match(bad.stderr,/Duplicate workspace metadata/);assert.deepEqual(duplicate.posts,[]);
 const race=await proxy('race'),rejected=await invoke(race.port,['--workspace',workspace,'run',run.session_id,'must not be admitted']);assert.equal(rejected.code,1);assert.match(rejected.stderr,/Execution workspace changed before admission/);assert.equal(race.posts.length,1);assert.equal(race.posts[0].route,'/v1/runs');assert.equal(race.posts[0].status,409);assert.equal(race.posts[0].body.expected_workspace_authority_id,'f'.repeat(32));assert.equal(typeof race.posts[0].body.expected_workspace_id,'string');assert.equal((await command('runs',run.session_id)).length,1);assert.deepEqual(await command('sessions'),saved);assert.deepEqual(await command('history',run.session_id),history);assert.equal(await fs.readFile(path.join(workspace,'note.txt'),'utf8'),'Native pinned workspace\n');passed=true;
 console.log(JSON.stringify({actualNativeConsoleAndServer:true,selectedWorkspacePinned:true,wrongWorkspaceRefusedBeforeMutation:true,actualToolGraph:true,changedAuthorityNeverAdopted:true,duplicateMetadataRefused:true,nativeAtomicRunBindingRejectedRace:true,historyPreserved:true,providerRequests:0,installedIde:false,automaticBootstrap:false}));
}finally{for(const server of proxies){server.closeAllConnections();await new Promise(yes=>server.close(yes));}if(child.exitCode===null)child.kill();await closed;assert.equal(path.dirname(await fs.realpath(base)),parent);assert.ok(path.basename(base).startsWith('xmind-console-workspace-'));if(passed)await fs.rm(base,{recursive:true,force:true});else console.error(JSON.stringify({retainedFixture:base}));}
