// Synthetic provider/count/canonical replies and test credential. Execution,
// native file reads, clocks, ownership and embedded-xlang3 SQLite are real.
// This fixture never advances a run or checkpoint through a state shortcut.
#include "agentflow/agent_service.hpp"
#include "agentflow/agent_authority.hpp"
#include "agentflow/context_manager.hpp"
#include "agentflow/skill_context.hpp"
#include "agentflow/xlang_sqlite.hpp"
#include "nlohmann/json.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <future>
#include <iostream>
#include <map>
#include <thread>

using namespace agentflow;
using namespace std::chrono_literals;
namespace {
using Json=nlohmann::json;
const std::string key="synthetic-context-engine-key-not-live";
const std::string model="synthetic-context-engine-model";
const std::string file_bytes="Actual native context fixture file bytes\n";
void require(bool value,const char* reason){if(!value)throw std::runtime_error(reason);}
template<class E,class F>void rejects(F action,const char* reason){try{action();}catch(const E&){return;}throw std::runtime_error(reason);}
template<class F>void eventually(F action,const char* reason){const auto until=std::chrono::steady_clock::now()+20s;while(std::chrono::steady_clock::now()<until){if(action())return;std::this_thread::sleep_for(5ms);}throw std::runtime_error(reason);}
std::string read(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary);return {std::istreambuf_iterator<char>(in),std::istreambuf_iterator<char>()};}
std::string provider_identity(){return Json{{"model_id",model},{"wire","responses"}}.dump();}
std::size_t event_count(const std::vector<Event>& events,const std::string& kind){return std::count_if(events.begin(),events.end(),[&](const auto& event){return event.kind==kind;});}
std::size_t peer_count(const std::filesystem::path& root,const std::string& mode,const std::string& kind){std::ifstream in(root/"peer-audit.jsonl");std::string line;std::size_t count=0;while(std::getline(in,line)){const auto row=Json::parse(line);if(row.at("mode")==mode&&row.at("kind")==kind)++count;}return count;}
void put_key(PersistenceService& store){store.put_credential("fixture","context-provider","provider:synthetic-context-engine","Explicit synthetic provider credential",SecretBytes({reinterpret_cast<const std::uint8_t*>(key.data()),key.size()}),0).get();}
AgentSettings settings(const std::string& base,const std::filesystem::path& workspace,const std::string& mode,bool planning=false){
    AgentSettings value;value.provider={base+"/"+mode+"/responses",model,Capability::supported,Capability::supported,Capability::supported};value.provider.wire=ProviderWire::responses;value.provider.deadline=8s;value.provider.idle_timeout=6s;
    value.workspace=workspace.string();value.max_turns=8;value.max_output_tokens=128;value.run_timeout=45s;value.instructions="Explicit synthetic context engine fixture. Current native instructions and actual tool observations remain authoritative.";value.credential=CredentialReference{"fixture","context-provider","provider:synthetic-context-engine"};
    ContextRuntimePolicy context;context.buffer_tokens=20;context.compaction.retain_recent_groups=1;context.compaction.maintenance_deadline_ms=10000;
    VerifiedContextCapacity capacity;capacity.provider_identity_json=provider_identity();capacity.wire="responses";capacity.model_id=model;capacity.route_identity=context_route_identity(value.provider,provider_identity());capacity.source_binding=context_digest("Explicit synthetic independently registered capacity fixture");capacity.revision=1;capacity.verified=true;capacity.input_tokens=mode=="rolling"?200:1000;capacity.output_tokens=256;capacity.context_tokens=2048;capacity.default_output_tokens=128;
    context.model_capacities.emplace(model,capacity);value.context=context;
    if(planning){value.planning=DynamicPlanningPolicy{};value.planning->max_parent_turns=8;}
    return value;
}
ContextBinding binding(PersistenceService& store,const AgentSettings& settings){
    WorkspaceTools workspace(*settings.workspace);const auto& p=settings.context->compaction;
    return {provider_identity(),context_authority_identity(settings,settings.provider.model,workspace.identity(),agent_authority_credentials(store,settings)),p.id,p.revision,p.strategy_id,p.strategy_revision};
}
ModelMessage decode(const Message& message){const auto dto=Json::parse(message.json);require(dto.is_object()&&dto.contains("content")&&dto.at("content").is_string(),"Actual context original has no supported content");ModelMessage out;out.role=message.role=="user"?MessageRole::user:message.role=="assistant"?MessageRole::assistant:message.role=="tool"?MessageRole::tool:throw std::runtime_error("Unexpected original role");out.content=dto.at("content").get<std::string>();if(dto.contains("provider_items"))out.provider_items_json=dto.at("provider_items").dump();if(dto.contains("refusal"))out.refusal=dto.at("refusal").get<std::string>();if(dto.contains("tool_call_id"))out.tool_call_id=dto.at("tool_call_id").get<std::string>();if(dto.contains("tool_calls"))for(const auto& call:dto.at("tool_calls"))out.tool_calls.push_back({call.at("id").get<std::string>(),call.at("name").get<std::string>(),call.at("arguments").get<std::string>()});return out;}
void exact_prefix(const std::vector<Message>& old,const std::vector<Message>& now){require(now.size()>=old.size(),"Compaction cannot remove original history");for(std::size_t i=0;i<old.size();++i)require(now[i].sequence==old[i].sequence&&now[i].role==old[i].role&&now[i].json==old[i].json,"Every original message/opaque receipt/metric remains byte-exact");}
void actual_reads(const std::vector<Message>& history,std::size_t expected){std::size_t reads=0;for(const auto& row:history)if(row.role=="tool"){const auto dto=Json::parse(row.json),result=Json::parse(dto.at("content").get<std::string>());if(result.contains("path")&&result.at("path")=="README.md"){require(result.at("content")==file_bytes,"Actual native file read must observe exact disposable bytes");++reads;}}require(reads==expected,"Actual transcript read count differs from provider loop");}
void response_metrics(const std::vector<Message>& history){for(const auto& row:history)if(row.role=="assistant"){const auto dto=Json::parse(row.json);require(dto.at("usage").at("input_tokens")==37&&dto.at("usage").at("output_tokens")==5&&dto.at("usage").at("total_tokens")==42,"Actual response usage is supplied independently of count/maintenance");require(dto.contains("elapsed_ms")&&dto.contains("first_token_ms"),"Actual inference clocks must be recorded");require(dto.contains("provider_items")&&dto.at("provider_items")[0].at("type")=="reasoning","Synthetic original reasoning receipt must be privately retained");}}
struct Ledger {
    XlangSqlite sql;
    Ledger(const std::string& database,const std::vector<std::string>& imports):sql(database,imports){}
    std::int64_t integer(const std::string& query,const std::vector<SqlValue>& args={}){const auto r=sql.execute(query,args);require(r.rows.size()==1&&r.rows[0].size()==1,"Fixture count query must have one actual result");return std::get<std::int64_t>(r.rows[0][0]);}
    std::string text(const std::string& query,const std::vector<SqlValue>& args={}){const auto r=sql.execute(query,args);require(r.rows.size()==1&&r.rows[0].size()==1,"Fixture text query must have one actual result");return std::get<std::string>(r.rows[0][0]);}
};
void triplets(PersistenceService& store,const std::string& owner,std::size_t expected){std::map<std::string,std::vector<std::string>> actual;for(const auto& event:store.events(owner).get())if(event.kind=="budget.model_call.reserved"||event.kind=="budget.model_call.started"||event.kind=="budget.model_call.finished"){const auto data=Json::parse(event.json);actual[data.at("attempt_id").get<std::string>()].push_back(event.kind);}require(actual.size()==expected,"Every actual physical model call owns one reservation");for(const auto& [id,events]:actual){(void)id;require(events==std::vector<std::string>{"budget.model_call.reserved","budget.model_call.started","budget.model_call.finished"},"Successful actual physical members need exact owned reserve/start/finish order");}}

void rolling(const std::filesystem::path& root,const std::vector<std::string>& imports,const std::string& base){
    const auto workspace=root/"rolling";const auto database=(workspace/"state.sqlite").string();auto frozen=settings(base,workspace,"rolling");std::vector<Message> complete;std::string projection_bytes;ContextBinding admitted;
    {PersistenceService store(database,imports);put_key(store);store.create_session("rolling-session","Actual repeated native context engine").get();AgentRunner runner(store,frozen);runner.start("rolling-first","rolling-session","fixture-rolling-first: Read the actual README.md five times, then report actual evidence.");require(runner.execute("rolling-first").state==RunState::completed,"First real tool loop must finish after mid-run compaction");const auto first=store.history("rolling-session").get();require(first.size()==12,"Five real complete read groups and final response remain in history");actual_reads(first,5);response_metrics(first);triplets(store,"rolling-first",9);require(store.root_budget("rolling-first").get().parent_model_calls_reserved==6,"Three maintenance calls cannot consume three additional logical turns");admitted=binding(store,frozen);const auto before=store.context_snapshot({ContextScopeKind::session,"rolling-session"},admitted).get();require(before.head.revision==3&&before.head.covered_through_ordinal>=before.latest_user_ordinal,"Actual mid-run compaction reclaims groups after the original independently protected user");
        runner.start("rolling-second","rolling-session","fixture-rolling-second: Read the actual README.md twice and retain both original user objectives.");require(runner.execute("rolling-second").state==RunState::completed,"Later root must reuse and repeat the same session projection");complete=store.history("rolling-session").get();exact_prefix(first,complete);require(complete.size()==18,"Successive roots retain every actual original message");actual_reads(complete,7);response_metrics(complete);triplets(store,"rolling-second",5);const auto snapshot=store.context_snapshot(before.head.scope,admitted).get();require(snapshot.head.revision==5&&snapshot.protected_users.size()==2,"Repeated compaction retains independently pinned original users across roots");const auto old=*store.context_projection(before.head.scope,admitted).get();projection_bytes=old.projection_json;require(projection_bytes.find("1.00000000000000000001")!=std::string::npos&&projection_bytes.find("18446744073709551617")!=std::string::npos,"Canonical private metadata must retain exact non-native JSON number lexemes");
        const auto requested=store.request_context_compaction({"idle-request","fixture-controller",snapshot.head.scope,admitted,snapshot.head.revision}).get();require(requested.state=="pending"&&store.request_context_compaction({"idle-request","fixture-controller",snapshot.head.scope,admitted,snapshot.head.revision}).get().state=="pending","Authenticated duplicate manual request is idempotent");ModelRequest trusted;trusted.messages={{MessageRole::system,frozen.instructions}};trusted.tools=WorkspaceTools(workspace.string()).definitions();for(auto& definition:SkillContext::definitions())trusted.tools.push_back(std::move(definition));trusted.include_usage=true;trusted.max_output_tokens=128;const auto credential=store.resolve_credential("fixture","context-provider","provider:synthetic-context-engine").get();ContextManager manager(store,frozen.provider,*frozen.context,decode);const auto idle=manager.compact_idle(snapshot.head.scope,admitted,"actual-idle-owner",trusted,&credential);require(idle.head.revision==6&&idle.actual_usage_json==R"({"input_tokens":31,"output_tokens":7,"total_tokens":38})"&&idle.measured_preparation_elapsed_ms.has_value(),"Idle maintenance retains actual independent usage and preparation clocks");exact_prefix(complete,store.history("rolling-session").get());require(store.runs("rolling-session").get().size()==2,"Idle maintenance must not manufacture a Run or user prompt");rejects<ContextUnavailable>([&]{manager.compact_idle(snapshot.head.scope,admitted,"actual-idle-owner",trusted,&credential);},"An already-consumed idle manual request cannot replay a provider call");
        // A changed metadata snapshot fails before payload/HTTP; actual new root
        // admission, not a ledger setter, supplies the new source watermark.
        auto changed=frozen;changed.instructions+=" Changed native configured instructions.";AgentRunner incompatible(store,changed);incompatible.start("authority-refused","rolling-session","fixture-authority-refused: Never replay old opaque under changed native settings.");rejects<ContextUnavailable>([&]{store.context_group_payloads(snapshot,{snapshot.groups.back().ordinal}).get();},"A stale actual snapshot cannot load source after later user admission");require(incompatible.execute("authority-refused").state==RunState::failed,"Foreign full authority must fail before paid context operations");require(store.root_budget("authority-refused").get().model_calls_reserved==0,"Receipt incompatibility cannot reserve inference under guessed provenance");exact_prefix(complete,store.history("rolling-session").get());require(store.operations("rolling-first").get().empty()&&store.operations("rolling-second").get().empty(),"Actual read-only loops cannot fabricate an effect journal");store.close();}
    {Ledger ledger(database,imports);require(ledger.integer("SELECT count(*) FROM context_compactions WHERE state='committed'")==6&&ledger.integer("SELECT count(*) FROM context_checkpoints")==6,"All six real maintenance receipts are durable");require(ledger.integer("SELECT count(*) FROM context_measures WHERE state='finished'")==16,"Actual before/after counts are independently persisted");require(ledger.integer("SELECT count(*) FROM context_idle_owners WHERE state='completed'")==1&&ledger.integer("SELECT count(*) FROM runs WHERE id='actual-idle-owner'")==0,"Typed idle ledger stays distinct from Run identity");require(ledger.integer("SELECT count(*) FROM agent_model_call_reservations WHERE purpose='context_compaction'")==5,"Idle maintenance does not charge fictional inference/root allowance");}
    const auto requests=peer_count(root,"rolling","inference")+peer_count(root,"rolling","count")+peer_count(root,"rolling","compact");{PersistenceService store(database,imports);require(store.history("rolling-session").get().size()==19&&store.context_projection({ContextScopeKind::session,"rolling-session"},admitted).get()->head.revision==6,"Reopen preserves originals and exact committed session head");store.close();}require(requests==peer_count(root,"rolling","inference")+peer_count(root,"rolling","count")+peer_count(root,"rolling","compact"),"Recovery must never replay a completed context request");
}

void bootstrap(AgentRunner& runner,const std::string& mode,const std::string& session){runner.start(mode+"-bootstrap",session,"fixture-bootstrap: Read the actual README.md twice then finish this real seed conversation.");require(runner.execute(mode+"-bootstrap").state==RunState::completed,"Actual seed model/tool loop must finish");}
void overflow(const std::filesystem::path& root,const std::vector<std::string>& imports,const std::string& base,const std::string& mode){const auto workspace=root/mode;const auto database=(workspace/"state.sqlite").string();ContextBinding admitted;std::vector<Message> old;
    {PersistenceService store(database,imports);put_key(store);store.create_session(mode+"-session","Actual bounded overflow engine").get();auto frozen=settings(base,workspace,mode);AgentRunner runner(store,frozen);bootstrap(runner,mode,mode+"-session");old=store.history(mode+"-session").get();admitted=binding(store,frozen);runner.start(mode+"-probe",mode+"-session","fixture-probe: Test the explicitly labelled overflow protocol boundary.");const auto observed=runner.execute(mode+"-probe");require(observed.state==RunState::failed,"Second, late or generic provider failure cannot acquire a final response");exact_prefix(old,store.history(mode+"-session").get());require(store.history(mode+"-session").get().size()==old.size()+1,"Rejected inference cannot fabricate assistant/tool history");const auto budget=store.root_budget(mode+"-probe").get();require(budget.parent_model_calls_reserved==1&&budget.model_calls_reserved==(mode=="second-overflow"?3:1),"Overflow correction stays one logical step with at most one maintenance and retry");require(event_count(store.events(mode+"-probe").get(),"model.reasoning")== (mode=="late-overflow"?1u:0u),"Late synthetic provider failure must retain its actual durable reasoning evidence");store.close();}
    {Ledger ledger(database,imports);require(ledger.integer("SELECT count(*) FROM inference_steps WHERE root_run_id=?",{mode+"-probe"})==1,"Failed correction is one actual logical group");require(ledger.integer("SELECT count(*) FROM context_compactions")== (mode=="second-overflow"?1:0),"Generic/late failures cannot dispatch compaction");if(mode=="second-overflow")require(ledger.integer("SELECT rebuild_count FROM inference_steps WHERE root_run_id=?",{mode+"-probe"})==1&&ledger.integer("SELECT count(*) FROM inference_attempt_members WHERE step_id=(SELECT id FROM inference_steps WHERE root_run_id=?)",{mode+"-probe"})==2,"One recognized overflow creates exactly one separately charged physical retry");}
}

void held(const std::filesystem::path& root,const std::vector<std::string>& imports,const std::string& base){const auto workspace=root/"held";const auto database=(workspace/"state.sqlite").string();auto frozen=settings(base,workspace,"held",true);std::vector<Message> before;ContextPausePin pin;std::string request_id;
    {PersistenceService store(database,imports);put_key(store);store.create_session("held-session","Actual original signed context continuation").get();AgentService service(store,frozen,1,8);service.submit("held-bootstrap","held-session","fixture-bootstrap: Read the actual README.md twice then finish this real seed conversation.");eventually([&]{return store.run("held-bootstrap").get().state==RunState::completed&&service.idle();},"Actual planning-capable seed owner did not retire");before=store.history("held-session").get();service.submit("held-parent","held-session","fixture-held-parent: Ask the native owned human question, then continue the accepted signed call after one recognized overflow.");eventually([&]{return store.run("held-parent").get().state==RunState::paused;},"Actual signed human-only plan must close its context-bound owner");const auto plan=*store.dynamic_plan_for_root("held-parent").get();const auto questions=store.dynamic_human_requests(plan.id).get();require(questions.size()==1&&questions[0].state=="waiting","Actual parent publishes one human-owned request");request_id=questions[0].id;const auto saved=store.dynamic_context_pause("held-parent").get();require(saved.has_value(),"Clean context-enabled human pause must persist the exact native source pin");pin=*saved;require(store.root_budget("held-parent").get().model_calls_reserved==1&&store.root_budget("held-parent").get().parent_calls_held==1,"Closed pause retains one held allowance without dispatch");exact_prefix(before,store.history("held-session").get());service.close();store.close();}
    const auto paused_requests=peer_count(root,"held","inference")+peer_count(root,"held","count")+peer_count(root,"held","compact");
    {PersistenceService store(database,imports);AgentService service(store,frozen,1,8);require(store.run("held-parent").get().state==RunState::paused&&store.dynamic_context_pause("held-parent").get()->source_binding==pin.source_binding,"Reopen adopts the same exact closed context pin");require(paused_requests==peer_count(root,"held","inference")+peer_count(root,"held","count")+peer_count(root,"held","compact"),"Paused adoption must perform no provider/count/compact request");const auto plan=*store.dynamic_plan_for_root("held-parent").get();service.plan_input("held-parent",request_id,R"({"answer":"Synthetic authenticated input","n":1.00000000000000000001})","fixture-controller",plan.revision,plan.state_sequence);eventually([&]{return store.run("held-parent").get().state==RunState::completed&&service.idle();},"Same signed owner must consume exactly its held inference and one bounded physical rebuild");const auto budget=store.root_budget("held-parent").get();require(budget.model_calls_reserved==4&&budget.parent_model_calls_reserved==2&&budget.parent_calls_held==0,"Original held logical continuation includes one overflow, maintenance and one retry");const auto calls=store.dynamic_plan_calls("held-parent").get();require(calls.size()==1&&calls[0].conversation_commit_seq&&calls[0].result_event_seq&&!calls[0].continuation_attempt_id.empty(),"One actual signed call/result/continuation stays once-bound");const auto events=store.events("held-parent").get();require(event_count(events,"conversation.tool_turn")==1&&event_count(events,"plan.call.accepted")==1&&store.owned_children("held-parent").get().empty(),"Human-only context maintenance cannot create children or recommit its signed result");const auto history=store.history("held-session").get();exact_prefix(before,history);require(history.size()==before.size()+4,"Actual paused origin/result/final continuation retain normal original history");response_metrics(history);store.close();}
    {Ledger ledger(database,imports);const auto original=ledger.text("SELECT continuation_attempt_id FROM dynamic_plan_calls WHERE root_run_id='held-parent'");require(ledger.integer("SELECT count(*) FROM inference_steps WHERE root_run_id='held-parent'")==2,"Origin plus continuation retain two logical allowances");const auto step=ledger.text("SELECT inference_step_id FROM agent_model_call_reservations WHERE root_run_id='held-parent' AND attempt_id=?",{original});require(ledger.integer("SELECT rebuild_count FROM inference_steps WHERE id=?",{step})==1&&ledger.text("SELECT original_attempt_id FROM inference_steps WHERE id=?",{step})==original&&ledger.text("SELECT successful_attempt_id FROM inference_steps WHERE id=?",{step})!=original,"Rebuilt member never replaces the original signed held pointer");require(ledger.integer("SELECT count(*) FROM inference_attempt_members WHERE step_id=?",{step})==2&&ledger.text("SELECT outcome FROM inference_attempt_members WHERE step_id=? AND ordinal=0",{step})=="context_overflow"&&ledger.text("SELECT outcome FROM inference_attempt_members WHERE step_id=? AND ordinal=1",{step})=="completed","Actual rejected and successful physical outcomes stay distinct");require(ledger.integer("SELECT count(*) FROM inference_output_evidence WHERE attempt_id=?",{original})==0,"Recognized original overflow has zero durable output evidence");}
}

void held_count_failure(const std::filesystem::path& root,const std::vector<std::string>& imports,const std::string& base){
    const std::string mode="held-count-failure";
    const auto database=(root/mode/"state.sqlite").string();
    auto frozen=settings(base,root/mode,mode,true);
    std::string original;
    {
        PersistenceService store(database,imports);put_key(store);
        store.create_session("held-count-session","Actual held count-before-admission failure").get();
        AgentService service(store,frozen,1,8);
        service.submit("held-count-bootstrap","held-count-session","fixture-bootstrap: Read the actual README.md twice then finish this real seed conversation.");
        eventually([&]{return store.run("held-count-bootstrap").get().state==RunState::completed&&service.idle();},"Real held count seed must finish");
        const auto initial=store.history("held-count-session").get();
        service.submit("held-count-parent","held-count-session","fixture-held-parent: Publish the actual question; fail counting only after the signed result has committed.");
        eventually([&]{return store.run("held-count-parent").get().state==RunState::paused;},"Actual held count owner must close its human pause");
        const auto plan=*store.dynamic_plan_for_root("held-count-parent").get();
        const auto questions=store.dynamic_human_requests(plan.id).get();
        require(questions.size()==1,"One actual human request precedes count failure");
        service.plan_input("held-count-parent",questions[0].id,R"({"answer":"Synthetic authenticated input","n":1.00000000000000000001})","fixture-controller",plan.revision,plan.state_sequence);
        eventually([&]{return store.run("held-count-parent").get().state==RunState::failed&&service.idle();},"Certain count failure must retire the exact undispatched held member");
        require(service.healthy(),"Known recorded count failure is not an unrecorded generation fault");
        const auto call=store.dynamic_plan_calls("held-count-parent").get();
        require(call.size()==1&&call[0].conversation_commit_seq&&!call[0].continuation_attempt_id.empty(),"Actual joined signed call retains its consumed once-only held pointer");
        original=call[0].continuation_attempt_id;
        const auto budget=store.root_budget("held-count-parent").get();
        require(budget.model_calls_reserved==2&&budget.parent_model_calls_reserved==2&&budget.parent_calls_held==0,"Count failure cannot refund or remint the already-held logical allowance");
        const auto history=store.history("held-count-session").get();exact_prefix(initial,history);
        require(history.size()==initial.size()+3,"Only real user and signed origin/result commit; no failed continuation answer appears");
        const auto events=store.events("held-count-parent").get();
        require(event_count(events,"budget.model_call.started")==1&&event_count(events,"budget.model_call.reserved")==2&&event_count(events,"budget.model_call.finished")==2,"Original held count failure retires once without starting its inference");
        service.close();store.close();
    }
    {
        Ledger ledger(database,imports);
        require(ledger.integer("SELECT count(*) FROM context_compactions")==0&&ledger.integer("SELECT count(*) FROM inference_steps WHERE root_run_id='held-count-parent'")==1,"Failed count before maintenance cannot create a step or accepted compaction");
        require(ledger.text("SELECT state FROM agent_model_call_reservations WHERE root_run_id='held-count-parent' AND attempt_id=?",{original})=="finished"&&ledger.integer("SELECT inference_step_id IS NULL AND actual_assistant_json IS NULL FROM agent_model_call_reservations WHERE root_run_id='held-count-parent' AND attempt_id=?",{original})==1,"Exact original held member retires without invented step/response");
    }
    const auto attempts=peer_count(root,mode,"inference")+peer_count(root,mode,"count");
    {PersistenceService store(database,imports);AgentService service(store,frozen,1,8);require(service.idle()&&store.run("held-count-parent").get().state==RunState::failed,"Reopen cannot wake a consumed failed held owner");service.close();store.close();}
    require(attempts==peer_count(root,mode,"inference")+peer_count(root,mode,"count"),"Failed original held continuation cannot replay on recovery");
}

void failure(const std::filesystem::path& root,const std::vector<std::string>& imports,const std::string& base,const std::string& mode){const auto workspace=root/mode;const auto database=(workspace/"state.sqlite").string();std::vector<Message> originals;ContextBinding admitted;std::string saved_receipt;
    {PersistenceService store(database,imports);put_key(store);store.create_session(mode+"-session","Actual acknowledged maintenance failure").get();auto frozen=settings(base,workspace,mode);AgentRunner runner(store,frozen);bootstrap(runner,mode,mode+"-session");originals=store.history(mode+"-session").get();admitted=binding(store,frozen);runner.start(mode+"-probe",mode+"-session","fixture-maintenance-probe: Execute only the authenticated real pending maintenance request.");const auto snapshot=store.context_snapshot({ContextScopeKind::session,mode+"-session"},admitted).get();store.request_context_compaction({mode+"-manual","fixture-controller",snapshot.head.scope,admitted,snapshot.head.revision}).get();
        if(mode=="receipt-fault"||mode=="head-fault"){Ledger inject(database,imports);inject.sql.execute(mode=="receipt-fault"?"CREATE TRIGGER injected_fixture_receipt BEFORE INSERT ON context_checkpoints BEGIN SELECT RAISE(ABORT,'synthetic receipt fault'); END":"CREATE TRIGGER injected_fixture_head BEFORE UPDATE OF revision ON context_heads WHEN NEW.revision>OLD.revision BEGIN SELECT RAISE(ABORT,'synthetic head fault'); END");rejects<ContextOutcomeUnrecorded>([&]{runner.execute(mode+"-probe");},"Acknowledged receipt/publication fault must fail-stop the actual owner");require(store.run(mode+"-probe").get().state==RunState::running,"Unrecorded outcome cannot fabricate terminal run retirement");}
        else if(mode=="final-binding-failure"){
            {Ledger inject(database,imports);inject.sql.execute("CREATE TRIGGER injected_fixture_final_binding BEFORE UPDATE OF input_binding ON inference_attempt_members WHEN OLD.input_binding='' AND NEW.input_binding<>'' BEGIN SELECT RAISE(ABORT,'synthetic undispatched binding fault'); END");}
            require(runner.execute(mode+"-probe").state==RunState::failed,"Certain final input-binding failure must retire undispatched inference");
        }
        else require(runner.execute(mode+"-probe").state==RunState::failed,"Actual failed follow-up count must retire a known failed preparation");
        exact_prefix(originals,store.history(mode+"-session").get());require(store.history(mode+"-session").get().size()==originals.size()+1,"Maintenance never inserts a synthetic assistant or tool group");require(store.context_snapshot(snapshot.head.scope,admitted).get().head.revision==(mode=="final-binding-failure"?1:0),"Final-binding failure retains its actually committed checkpoint; other failures retain old head");store.close();}
    {Ledger ledger(database,imports);const auto state=ledger.text("SELECT state FROM context_compactions");require(state==(mode=="receipt-fault"?"started":mode=="head-fault"?"received":mode=="final-binding-failure"?"committed":"failed"),"Actual recorded maintenance state must identify acknowledgement/publication boundary");require(ledger.integer("SELECT count(*) FROM context_checkpoints")== (mode=="receipt-fault"?0:1),"Only actually durable acknowledgement may appear as a receipt");if(mode!="receipt-fault")saved_receipt=ledger.text("SELECT actual_response_json FROM context_checkpoints");require(ledger.integer("SELECT count(*) FROM agent_model_call_reservations WHERE root_run_id=?",{mode+"-probe"})==2,"Failed preparation still consumes exact funded physical capacity");if(mode=="final-binding-failure")require(ledger.text("SELECT state FROM inference_steps WHERE root_run_id=?",{mode+"-probe"})=="failed"&&ledger.integer("SELECT count(*) FROM agent_model_call_reservations WHERE root_run_id=? AND state='finished'",{mode+"-probe"})==2,"Committed-head/final-binding failure must retire both actual reserved calls without dispatch/refund");}
    const auto requests=peer_count(root,mode,"inference")+peer_count(root,mode,"count")+peer_count(root,mode,"compact");
    {PersistenceService store(database,imports);require(store.run(mode+"-probe").get().state==RunState::failed&&store.context_snapshot({ContextScopeKind::session,mode+"-session"},admitted).get().head.revision==(mode=="final-binding-failure"?1:0),"Recovery retires unfinished owner and preserves exactly its last committed head");require(store.history(mode+"-session").get().size()==originals.size()+1,"Recovery cannot replay or fabricate answer history");store.close();}
    {Ledger ledger(database,imports);if(!saved_receipt.empty())require(ledger.text("SELECT actual_response_json FROM context_checkpoints")==saved_receipt,"Reopen must preserve exact acknowledged maintenance receipt");require(ledger.integer("SELECT count(*) FROM agent_model_call_reservations WHERE state IN ('reserved','started')")==0,"Recovery retires physical ownership without refund or dispatch");}
    require(requests==peer_count(root,mode,"inference")+peer_count(root,mode,"count")+peer_count(root,mode,"compact"),"Recovery cannot reconnect or replay an unknown maintenance outcome");
}
}
int main(int argc,char** argv){if(argc!=5)return 2;try{const std::filesystem::path root=argv[1];const std::vector<std::string> imports={argv[2],argv[3]};const std::string base=argv[4];rolling(root,imports,base);held(root,imports,base);held_count_failure(root,imports,base);for(const auto* mode:{"second-overflow","late-overflow","generic-400"})overflow(root,imports,base,mode);for(const auto* mode:{"receipt-fault","head-fault","after-count-failure","final-binding-failure"})failure(root,imports,base,mode);std::cout<<"Native context engine contract passed actual repeated/mid-run/session compaction, original users and exact canonical replay, real file reads, independent counts/usage, idle manual ownership, clean signed human pause/reopen/held overflow and pre-admission count-failure retirement, second/late/generic failure refusal, full-authority/source isolation and durable receipt/publication/final-binding faults with no recovery replay. Provider replies/counts/opaque data/key are synthetic.\n";return 0;}catch(const std::exception& error){try{std::ofstream private_log(std::filesystem::u8path(argv[1])/"native-context-engine-failure-private.log",std::ios::binary);private_log<<error.what();}catch(...){}std::cerr<<"Native context engine assertion failed; diagnostic retained privately in the owned disposable fixture.\n";return 1;}}
