#include "agentflow/create_executor.hpp"
#include "agentflow/xlang_sqlite.hpp"
#include "nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <thread>
using namespace agentflow;using namespace std::chrono_literals;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Error,class Action>void rejects(Action action){try{action();}catch(const Error&){return;}throw std::runtime_error("Expected creation rejection did not occur");}
struct Directory{std::filesystem::path parent=std::filesystem::temp_directory_path(),path=parent/("xmind-create-"+std::to_string(std::random_device{}()));Directory(){require(std::filesystem::create_directory(path),"Fixture root must be newly created");}~Directory(){if(path.parent_path()==parent && path.filename().string().starts_with("xmind-create-")){std::error_code ignored;std::filesystem::remove_all(path,ignored);}}};
std::int64_t expiry(){return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()+600000;}
struct Task{std::stop_source stop;std::future<WorkspaceSnapshot> result;Task(CreateExecutor& executor,std::string id,WorkspaceCreatePlan plan,std::string run="run"):result(std::async(std::launch::async,[this,&executor,id=std::move(id),plan=std::move(plan),run=std::move(run)]()mutable{return executor.execute(id,run,std::move(plan),expiry(),stop.get_token());})){}~Task(){stop.request_stop();if(result.valid())result.wait();}};
Operation proposed(PersistenceService& store,const std::string& id){const auto deadline=std::chrono::steady_clock::now()+5s;while(std::chrono::steady_clock::now()<deadline){try{const auto op=store.operation(id).get();require(op.state==OperationState::awaiting_approval,"Creation must await approval");return op;}catch(const NotFound&){std::this_thread::sleep_for(5ms);}}throw std::runtime_error("Creation proposal deadline");}
}
int main(int argc,char** argv){if(argc!=5)return 2;try{
    {WorkspaceTools linked(argv[3]);rejects<ToolAccessDenied>([&]{linked.plan_creation("outside-link/escape.txt","must not escape");});require(!std::filesystem::exists(std::filesystem::path(argv[4])/"escape.txt"),"Rejected directory junction must not create outside the root");}
    Directory directory;const auto root=directory.path/"workspace";std::filesystem::create_directory(root);std::filesystem::create_directory(root/"sub");
    WorkspaceTools workspace(root.string());const auto database=(directory.path/"state.sqlite").string();const std::vector<std::string> roots{argv[1],argv[2]};
    {
        PersistenceService store(database,roots);CreateExecutor executor(store,workspace);store.create_session("session","Actual native creation fixture").get();store.start_prompt_run("run","session",R"({"content":"creation fixture"})").get();store.transition("run",RunState::queued,RunState::running).get();
        for(const auto* path:{"../escape.txt","/absolute.txt","sub/CON.txt","sub/trailing.","sub/alternate:stream","missing/file.txt"}){try{workspace.plan_creation(path,"fixture");throw std::runtime_error("Unsafe/missing creation path accepted");}catch(const ToolAccessDenied&){}catch(const ToolFileError&){}}
        rejects<std::invalid_argument>([&]{workspace.plan_creation("binary.txt",std::string("a\0b",3));});
        rejects<std::invalid_argument>([&]{executor.invoke("invalid","run",R"({"path":"new.txt","path":"spoof.txt","content":"fixture"})",expiry());});
        rejects<std::invalid_argument>([&]{executor.invoke("invalid","run",R"({"path":"new.txt","content":"fixture","actor":"spoof"})",expiry());});rejects<NotFound>([&]{store.operation("invalid").get();});
        const auto plan=workspace.plan_creation("sub/new.txt","real native creation\n");require(!std::filesystem::exists(root/"sub/new.txt"),"Planning must not create a file");
        Task denied(executor,"denied",plan);proposed(store,"denied");store.decide_operation("denied",OperationDecision::deny,"fixture-controller").get();rejects<PermissionDenied>([&]{denied.result.get();});require(!std::filesystem::exists(root/"sub/new.txt"),"Denied creation must not create a file");
        Task cancelled(executor,"cancelled",plan);proposed(store,"cancelled");cancelled.stop.request_stop();rejects<PermissionCancelled>([&]{cancelled.result.get();});require(!std::filesystem::exists(root/"sub/new.txt"),"Cancelled approval must not create a file");
        Task stale(executor,"stale",plan);proposed(store,"stale");{std::ofstream outside(root/"sub/new.txt");outside<<"outside writer";}
        store.decide_operation("stale",OperationDecision::allow,"fixture-controller").get();rejects<ToolContentConflict>([&]{stale.result.get();});require(workspace.read_file("sub/new.txt").content=="outside writer","Create-new must preserve outside bytes");require(store.operation("stale").get().state==OperationState::failed,"Existing entry must be a recorded precondition conflict");
        const auto parentPlan=workspace.plan_creation("sub/parent.txt","parent bound");Task parent(executor,"parent",parentPlan);proposed(store,"parent");std::filesystem::rename(root/"sub",root/"old-parent");std::filesystem::create_directory(root/"sub");store.decide_operation("parent",OperationDecision::allow,"fixture-controller").get();rejects<ToolContentConflict>([&]{parent.result.get();});require(!std::filesystem::exists(root/"sub/parent.txt") && !std::filesystem::exists(root/"old-parent/parent.txt"),"Parent replacement must not redirect creation");
        const auto actualPlan=workspace.plan_creation("sub/new.txt","actual UTF-8 bytes\n");Task allowed(executor,"allowed",actualPlan);const auto proposal=proposed(store,"allowed");const auto data=nlohmann::json::parse(proposal.spec.arguments_json);require(data["before_exists"]==false && data["parent_id"]==actualPlan.parent_id && data["after_content"]==actualPlan.content,"Creation review must retain absence, parent identity and exact bytes");require(!std::filesystem::exists(root/"sub/new.txt"),"Waiting approval must not create a file");store.decide_operation("allowed",OperationDecision::allow,"fixture-controller").get();const auto actual=allowed.result.get();require(actual.content==actualPlan.content && actual.content_sha256==actualPlan.content_sha256 && workspace.read_file("sub/new.txt").content==actualPlan.content,"Approved creation must write and read back actual bytes");require(store.operation("allowed").get().state==OperationState::succeeded,"Actual created file must have durable outcome");rejects<Conflict>([&]{executor.execute("allowed","run",actualPlan,expiry());});rejects<ToolContentConflict>([&]{workspace.plan_creation("sub/new.txt","overwrite");});
        const auto emptyPlan=workspace.plan_creation("empty.txt","");Task empty(executor,"empty",emptyPlan);proposed(store,"empty");store.decide_operation("empty",OperationDecision::allow,"fixture-controller").get();require(empty.result.get().content.empty() && std::filesystem::exists(root/"empty.txt"),"Empty creation is an actual file effect");
        const auto unicodePath=std::string("sub/")+"\xE4\xB8\xAD"+".txt",unicodeContent=std::string("actual UTF-8 ")+"\xE4\xB8\xAD"+"\n";Task unicode(executor,"unicode",workspace.plan_creation(unicodePath,unicodeContent));proposed(store,"unicode");store.decide_operation("unicode",OperationDecision::allow,"fixture-controller").get();require(unicode.result.get().content==unicodeContent && workspace.read_file(unicodePath).content==unicodeContent,"Actual Unicode path/content must survive handle-relative creation and readback");
        rejects<ToolFileError>([&]{workspace.plan_creation("generated/deep/new.txt","nested");});
        const auto nestedPlan=workspace.plan_creation("generated/deep/new.txt","actual nested bytes",{},true);
        require(nestedPlan.create_directories==std::vector<std::string>{"generated","generated/deep"}&&workspace.creation_directory(nestedPlan.path)==".","Missing parents must bind the nearest existing guidance ancestor");
        Task nestedDenied(executor,"nested-denied",nestedPlan);const auto nestedProposal=proposed(store,"nested-denied");require(nlohmann::json::parse(nestedProposal.spec.arguments_json)["create_directories"]==nestedPlan.create_directories&&!std::filesystem::exists(root/"generated"),"Proposal must disclose every directory without creating it");store.decide_operation("nested-denied",OperationDecision::deny,"fixture-controller").get();rejects<PermissionDenied>([&]{nestedDenied.result.get();});require(!std::filesystem::exists(root/"generated"),"Denial must preserve directory absence");
        Task nestedCancelled(executor,"nested-cancelled",nestedPlan);proposed(store,"nested-cancelled");nestedCancelled.stop.request_stop();rejects<PermissionCancelled>([&]{nestedCancelled.result.get();});require(!std::filesystem::exists(root/"generated"),"Cancellation must preserve directory absence");
        Task nestedAllowed(executor,"nested-allowed",nestedPlan);proposed(store,"nested-allowed");store.decide_operation("nested-allowed",OperationDecision::allow,"fixture-controller").get();require(nestedAllowed.result.get().content==nestedPlan.content&&workspace.read_file(nestedPlan.path).content==nestedPlan.content,"Approval must create actual directories and final bytes");require(nlohmann::json::parse(store.operation("nested-allowed").get().result_json)["created_directories"]==nestedPlan.create_directories,"Receipt must attribute directory effects");
        const auto staleDirectories=workspace.plan_creation("sub/concurrent/deep/file.txt","must not write",{},true);Task directoryRace(executor,"directory-race",staleDirectories);proposed(store,"directory-race");std::filesystem::create_directory(root/"sub/concurrent");{std::ofstream guide(root/"sub/concurrent/AGENTS.md");guide<<"new external guidance";}store.decide_operation("directory-race",OperationDecision::allow,"fixture-controller").get();rejects<ToolContentConflict>([&]{directoryRace.result.get();});require(!std::filesystem::exists(root/"sub/concurrent/deep"),"Newly present directories must invalidate approval before any effect");
        auto tampered=workspace.plan_creation("tampered/deep/file.txt","must not write",{},true);tampered.create_directories={"different"};rejects<ToolContentConflict>([&]{workspace.apply_creation(tampered);});require(!std::filesystem::exists(root/"tampered"),"A changed directory plan must fail before effects");
        rejects<ToolAccessDenied>([&]{workspace.plan_creation(".config/new/file.txt","private",{},true);});rejects<ToolAccessDenied>([&]{workspace.plan_creation("sub/../escape/file.txt","escape",{},true);});rejects<ToolAccessDenied>([&]{workspace.plan_creation("sub/CON/file.txt","device",{},true);});
        rejects<std::invalid_argument>([&]{executor.invoke("bad-parent-option","run",R"({"path":"invalid/file.txt","content":"x","create_parents":"true"})",expiry());});rejects<NotFound>([&]{store.operation("bad-parent-option").get();});
        store.transition("run",RunState::running,RunState::completed).get();store.start_prompt_run("fault-run","session",R"({"content":"creation journal fault"})").get();store.transition("fault-run",RunState::queued,RunState::running).get();
        {XlangSqlite inject(database,roots);inject.execute("CREATE TRIGGER reject_creation_success BEFORE UPDATE OF state ON operations WHEN NEW.id='journal-fault' AND NEW.state='succeeded' BEGIN SELECT RAISE(ABORT,'fixture creation journal fault'); END");}
        Task fault(executor,"journal-fault",workspace.plan_creation("fault-parent/deep/fault.txt","actual file before storage fault",{},true),"fault-run");proposed(store,"journal-fault");store.decide_operation("journal-fault",OperationDecision::allow,"fixture-controller").get();rejects<EditOutcomeUnrecorded>([&]{fault.result.get();});require(workspace.read_file("fault-parent/deep/fault.txt").content=="actual file before storage fault","Storage failure must not hide actual directory/file creation");require(store.operation("journal-fault").get().state==OperationState::executing,"Storage failure must preserve claim for recovery");store.close();
    }
    {PersistenceService reopened(database,roots);require(reopened.operation("journal-fault").get().state==OperationState::uncertain && reopened.run("fault-run").get().state==RunState::failed,"Reopen must quarantine interrupted creation");require(workspace.read_file("fault-parent/deep/fault.txt").content=="actual file before storage fault","Reopen must not replay or delete actual directory/file creation");require(reopened.operation("allowed").get().state==OperationState::succeeded,"Actual creation outcome must survive reopen");reopened.close();}
    std::cout<<"Native approved creation passed: actual files including empty content, exact approval, no overwrite, parent identity, denial/cancellation, storage fault and uncertain restart without replay\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
