// Repository contract: actual native persistence transactions through xlang3
// SQLite in disposable databases. Assistant DTOs, user inputs and lifecycle
// completions are explicitly synthetic repository boundary data; this test
// does not claim real provider/AgentRunner/file-tool execution.
#include "agentflow/persistence_service.hpp"
#include "agentflow/dynamic_plan.hpp"
#include "agentflow/xlang_sqlite.hpp"
#include "graph_schema_fixture.hpp"
#include "nlohmann/json.hpp"
#include <chrono>
#include <filesystem>
#include <iostream>
#include <random>
#include <thread>

using namespace agentflow;
using Json=nlohmann::json;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Error,class Action> void rejects(Action action,const char* message){try{action();}catch(const Error&){return;}throw std::runtime_error(message);}
struct Directory {
    std::filesystem::path path=std::filesystem::temp_directory_path()/("xmind-dynamic-repository-"+std::to_string(std::random_device{}()));
    Directory(){std::filesystem::create_directory(path);}
    ~Directory(){std::error_code ignored;std::filesystem::remove_all(path,ignored);}
};
std::int64_t now(){return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
const std::string authority(64,'a'),inspect_authority(64,'b'),coding_authority(64,'c');
RootBudgetSpec policy(const std::string& workspace){return {"native.dynamic-plan",1,workspace,R"({"model_id":"synthetic-repository-model","wire":"responses"})",8,2,32,600000};}
DynamicPlanCapabilities capabilities(const RootBudgetSpec& budget){
    DynamicPlanCapabilities c;c.backend_identity=authority;c.workspace_identity=budget.workspace_identity;c.provider_identity_json=budget.provider_identity_json;c.tool_catalog_json="{}";
    c.presets={{"workspace.inspect",1,true,{},4,{}},{"workspace.coding",1,false,{},16,{}}};return c;
}
void seed_root(PersistenceService& store,const std::string& root,const RootBudgetSpec& budget,const std::vector<Json>& additional_tools={}){
    store.create_session("s_"+root,"Synthetic typed plan repository").get();store.start_prompt_run(root,"s_"+root,R"({"content":"Synthetic repository plan boundary"})",budget,capabilities(budget)).get();store.transition(root,RunState::queued,RunState::running).get();
    auto b=store.root_budget(root).get();store.open_dynamic_budget_segment({root,"segment_"+root,authority,b.revision}).get();
    rejects<DynamicPlanUnavailable>([&]{store.reserve_model_call(root,root,"before_catalogue",ModelCallRole::parent).get();},"Provisional capabilities must not dispatch model attempts");
    auto catalog=Json{{"tools",Json::array({{{"name","read_file"}},{{"name","list_files"}},{{"name","search_files"}},{{"name","read_repository_instructions"}},{{"name","edit_file"}}})}};
    std::vector<DynamicPresetCapability> presets{{"workspace.inspect",1,true,{"read_file","list_files","search_files","read_repository_instructions"},4,inspect_authority},{"workspace.coding",1,false,{"read_file","list_files","search_files","read_repository_instructions","edit_file"},16,coding_authority}};
    for(const auto& tool:additional_tools){catalog["tools"].push_back(tool);presets[1].tools.push_back(tool.at("name").get<std::string>());}
    store.finalize_dynamic_capabilities(root,authority,catalog.dump(),presets).get();
}
std::string assistant(const std::string& call,const std::string& arguments,bool initial=true){
    return Json{{"content",""},{"model","synthetic-repository-model"},{"tool_calls",Json::array({{{"id",call},{"name",initial?"plan_tasks":"revise_plan"},{"arguments",arguments}}})},{"provider_items_json",R"([{"type":"reasoning","id":"synthetic-receipt","encrypted_content":"synthetic-private-opaque","summary":[]}])"}}.dump();
}
DynamicPlanChangeSpec change_spec(PersistenceService& store,const std::string& root,const std::string& call,const std::string& args,bool initial=true){
    DynamicPlanChangeSpec s;s.id="call_"+call;s.plan_id="plan_"+root;s.root_run_id=root;s.provider_tool_call_id=call;s.origin_attempt_id="attempt_"+call;s.arguments_json=args;s.parent_assistant_json=assistant(call,args,initial);s.backend_identity=authority;
    store.reserve_model_call(root,root,s.origin_attempt_id,ModelCallRole::parent).get();store.start_model_call(root,root,s.origin_attempt_id).get();store.finish_model_call(root,root,s.origin_attempt_id,s.parent_assistant_json).get();
    store.append_event(root,"tool.started",Json{{"activity_id",root+":plan:"+call},{"call_id",call},{"name",initial?"plan_tasks":"revise_plan"},{"arguments",Json::parse(args)}}.dump()).get();
    s.expected_budget_revision=store.root_budget(root).get().revision;return s;
}
Json agent(const char* id,const char* objective,const char* preset,Json dependencies=Json::array()){return {{"id",id},{"type","agent"},{"objective",objective},{"preset",preset},{"depends_on",dependencies}};}
Json human(const char* id,const char* question,Json dependencies){return {{"id",id},{"type","human"},{"question",question},{"depends_on",dependencies}};}
Json edge(const char* task,const char* requirement="success"){return {{"task",task},{"require",requirement}};}
DynamicFrontierSpec frontier(PersistenceService& store,const DynamicPlanCallRecord& call,const std::string& label,const std::string& child){
    const auto p=store.dynamic_plan(call.plan_id).get();const auto n=prepare_dynamic_node(p,label);DynamicFrontierSpec s;s.plan_id=p.id;s.plan_call_id=call.id;s.backend_identity=authority;s.expected_revision=p.revision;s.expected_state_sequence=p.state_sequence;s.expected_budget_revision=store.root_budget(p.root_run_id).get().revision;s.tasks.push_back({label,"claim_"+child,child,{},n.dependency_outputs_json,n.node.definition_revision});return s;
}
void finish_child(PersistenceService& store,const std::string& root,const std::string& child,bool success=true){
    store.transition(child,RunState::queued,RunState::running).get();const auto attempt="attempt_"+child;
    store.reserve_model_call(root,child,attempt,ModelCallRole::leaf).get();store.start_model_call(root,child,attempt).get();store.finish_model_call(root,child,attempt,R"({"content":"Synthetic repository child output","usage":{"input_tokens":7,"output_tokens":3},"elapsed_ms":11,"provider_items_json":"[{\"type\":\"reasoning\",\"encrypted_content\":\"synthetic-private-opaque\"}]"})").get();
    if(success)store.complete_run(child,R"({"content":"Synthetic repository child output","usage":{"input_tokens":7,"output_tokens":3},"elapsed_ms":11,"provider_items_json":"[{\"type\":\"reasoning\",\"encrypted_content\":\"synthetic-private-opaque\"}]"})").get();
    else store.transition(child,RunState::running,RunState::failed,R"({"reason":"synthetic_child_failure","private_detail":"never project arbitrary errors"})").get();
    const auto settled=store.settle_dynamic_child(child).get();require(settled.child_state==(success?"completed":"failed")&&settled.outcome_json.find("provider_items")==std::string::npos&&settled.outcome_json.find("private_detail")==std::string::npos,"Actual typed settlement must omit private response/error material");
}
void pause_and_restart(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    const auto budget=policy(workspace);std::string call_id,question_id;
    {
        PersistenceService store(database,imports);seed_root(store,"owner",budget);
        const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("inspect","Synthetic inspect objective","workspace.inspect"),human("question","Synthetic human question",Json::array({edge("inspect")})),agent("coding","Synthetic bounded coding objective","workspace.coding",Json::array({edge("question")}))})}}.dump();
        auto spec=change_spec(store,"owner","initial",args);auto invalid=spec;invalid.parent_assistant_json=assistant("initial",args)+" ";
        rejects<Conflict>([&]{store.accept_dynamic_plan_change(invalid).get();},"Planning must match exact actual finished response bytes");
        auto call=store.accept_dynamic_plan_change(spec).get();call_id=call.id;require(call.created&&store.root_budget("owner").get().planned_children_reserved==2&&store.root_budget("owner").get().parent_calls_held==1,"Planning must reserve total pending agents plus one exact continuation");
        rejects<Conflict>([&]{store.record_rejected_dynamic_tool_turn("owner",spec.origin_attempt_id,spec.parent_assistant_json,"invalid_plan_arguments").get();},"Accepted signed planning work must never fall through to generic rejection history");
        require(!store.accept_dynamic_plan_change(spec).get().created,"Identical accepted signed call must deduplicate");
        invalid=spec;invalid.arguments_json=args+" ";invalid.parent_assistant_json=assistant("initial",invalid.arguments_json);rejects<Conflict>([&]{store.accept_dynamic_plan_change(invalid).get();},"Changed lexical signed call must reject before replay");
        rejects<Conflict>([&]{store.reserve_model_call("owner","owner","steal_held",ModelCallRole::parent).get();},"Generic parent reservation cannot steal held signed continuation");
        auto claim=frontier(store,call,"inspect","inspect_child"),wrong=claim;wrong.tasks[0].resolved_input_json=R"({"fabricated":true})";rejects<Conflict>([&]{store.admit_dynamic_frontier(wrong).get();},"Caller must not invent dependency observations");
        wrong=claim;wrong.tasks[0].prompt_json=R"({"content":"Changed objective"})";rejects<Conflict>([&]{store.admit_dynamic_frontier(wrong).get();},"Caller must not invent child prompt");
        wrong=claim;--wrong.expected_state_sequence;rejects<DynamicPlanChanged>([&]{store.admit_dynamic_frontier(wrong).get();},"Stale metadata CAS must be typed before child admission");
        const auto admitted=store.admit_dynamic_frontier(claim).get();require(admitted.nodes.size()==1&&admitted.budget.children_admitted==1&&admitted.budget.planned_children_reserved==1,"Actual claim converts one planned allowance to spent child exactly once");
        const auto identity=store.child_admission("inspect_child").get();require(identity.kind==ChildAdmissionKind::dynamic_agent&&identity.backend_identity==inspect_authority&&identity.plan_id==call.plan_id,"Child admission must derive the bounded private preset identity");
        rejects<std::invalid_argument>([&]{store.append_event("owner","plan.child.settled","{}").get();},"Generic lifecycle append must not forge planning settlement");
        {
            XlangSqlite sql(database,imports);
            rejects<DatabaseError>([&]{sql.execute("INSERT INTO runs(id,session_id,state,parent_run_id,node_id) VALUES('rogue','s_owner','queued','owner','unknown')");},"SQL must reject unclaimed owned children");
            rejects<DatabaseError>([&]{sql.execute("UPDATE dynamic_plan_nodes SET definition_json=definition_json||' ' WHERE plan_id=? AND label='inspect'",{call.plan_id});},"SQL must protect claimed definitions");
        }
        finish_child(store,"owner","inspect_child");
        auto p=store.dynamic_plan(call.plan_id).get();DynamicHumanRequestSpec h;h.id="question_request";h.plan_id=p.id;h.plan_call_id=call.id;h.label="question";h.backend_identity=authority;h.expected_revision=p.revision;h.expected_state_sequence=p.state_sequence;h.expires_unix_ms=now()+600000;store.publish_dynamic_human(h).get();question_id=h.id;
        p=store.dynamic_plan(p.id).get();const auto b=store.root_budget("owner").get();store.suspend_dynamic_owner({p.id,call.id,"segment_owner",authority,p.revision,p.state_sequence,b.revision,125}).get();
        require(store.run("owner").get().state==RunState::paused&&store.history("s_owner").get().size()==1&&store.dynamic_budget_segment("owner").get().remaining_active_ms==600000-125,"Human pause must close active time and preserve unmatched signed call outside conversation history");
        const auto calls=store.dynamic_plan_calls("owner").get();const auto revisions=store.dynamic_plan_revisions(call.plan_id).get();require(calls.size()==1&&calls[0].id==call.id&&calls[0].parent_assistant_json==spec.parent_assistant_json&&!calls[0].conversation_commit_seq&&calls[0].result_json.empty()&&revisions.size()==1&&revisions[0].call_id==call.id&&revisions[0].accepted_event_seq==call.accepted_event_seq&&Json::parse(revisions[0].canonical_spec_json).at("nodes").size()==3,"Read-only pending call/revision accessors must correlate actual saved origin and accepted topology without a committed conversation");
        require(revisions[0].canonical_spec_json.find("provider_items")==std::string::npos&&revisions[0].canonical_spec_json.find(authority)==std::string::npos&&revisions[0].canonical_spec_json.find("outcome_json")==std::string::npos,"Accepted topology history must not include provider receipts/private authority/outcomes");rejects<std::invalid_argument>([&]{store.dynamic_plan_calls("inspect_child").get();},"Child cannot masquerade as owning plan-call root");
        store.close();
    }
    {
        PersistenceService store(database,imports);const auto call=store.dynamic_plan_call(call_id).get();auto p=store.dynamic_plan(call.plan_id).get();require(store.run("owner").get().state==RunState::paused&&p.state=="waiting_human","Only fully committed clean pause must survive actual repository recovery");
        const auto before=store.events("owner").get().size();DynamicHumanInputSpec input{p.id,question_id,R"({"choice":"continue","n":1.000000000000000000001})","synthetic_authenticated_controller",std::string(64,'d'),p.revision,p.state_sequence};
        rejects<DynamicPlanUnavailable>([&]{store.input_dynamic_human(input).get();},"Stale settings must reject answer before any transaction mutation");require(store.events("owner").get().size()==before,"Stale answer cannot append event or wake owner");
        input.backend_identity=authority;auto oversized=input;oversized.input_json=Json{{"value",std::string(8180,'\\')}}.dump();require(oversized.input_json.size()<=16384&&Json{{"human_state","answered"},{"request_id",question_id},{"input_json",oversized.input_json}}.dump().size()>32768,"Synthetic escaped input fixture must cross the encoded outcome boundary");
        rejects<std::invalid_argument>([&]{store.input_dynamic_human(oversized).get();},"Legal raw input with oversized escaped observation must reject before answer mutation");require(store.events("owner").get().size()==before&&store.dynamic_plan(p.id).get().state_sequence==p.state_sequence&&store.dynamic_human_request(p.id,question_id).get().state=="waiting"&&store.run("owner").get().state==RunState::paused,"Rejected encoded input must preserve question/checkpoint/events/paused owner");
        const auto answered=store.input_dynamic_human(input).get();require(answered.input_json==input.input_json&&store.run("owner").get().state==RunState::paused,"Human exact bytes must persist without starting active time during queueing");
        const auto answer_events=store.events("owner").get().size();store.input_dynamic_human(input).get();require(store.events("owner").get().size()==answer_events,"Duplicate identical human answer must not append or wake twice");
        p=store.dynamic_plan(p.id).get();const auto b=store.root_budget("owner").get();auto resumed=store.resume_dynamic_owner({p.id,"segment_resumed",authority,p.revision,p.state_sequence,b.revision}).get();require(resumed.run.id=="owner"&&resumed.pending_call.id==call.id&&resumed.segment.remaining_active_ms==599875&&resumed.segment.ordinal==2,"Resume must retain exact root/call and remaining active time");
        store.admit_dynamic_frontier(frontier(store,call,"coding","coding_child")).get();require(store.child_admission("coding_child").get().backend_identity==coding_authority,"Coding child uses captured bounded coding identity");finish_child(store,"owner","coding_child");
        const auto report=store.settle_dynamic_plan_step(call.id).get();require(report.ready&&report.call.result_json.find("synthetic-private-opaque")==std::string::npos&&report.call.result_json.find(authority)==std::string::npos,"Public plan report must derive actual bounded outcomes without private authority/receipts");
        {XlangSqlite sql(database,imports);sql.execute("CREATE TRIGGER reject_plan_tool_completion BEFORE INSERT ON events WHEN NEW.kind='tool.completed' BEGIN SELECT RAISE(ABORT,'synthetic tool completion journal fault'); END");}
        rejects<DynamicOutcomeUnrecorded>([&]{store.commit_dynamic_tool_turn("owner",call.id).get();},"Tool completion journal fault must fail-stop without a partial signed conversation");
        require(store.history("s_owner").get().size()==1&&!store.dynamic_plan_call(call.id).get().conversation_commit_seq,"Completion and signed assistant/tool conversation must roll back together");
        {XlangSqlite sql(database,imports);sql.execute("DROP TRIGGER reject_plan_tool_completion");}
        store.commit_dynamic_tool_turn("owner",call.id).get();const auto history=store.history("s_owner").get();require(history.size()==3&&history[1].json==call.parent_assistant_json,"Coupled planning conversation preserves exact original signed assistant");
        auto completed_count=[&]{std::size_t count=0;for(const auto& event:store.events("owner").get())if(event.kind=="tool.completed"){const auto data=Json::parse(event.json);require(data["activity_id"]=="owner:plan:initial"&&data["call_id"]=="initial"&&data["name"]=="plan_tasks"&&data["data"]==Json::parse(report.call.result_json),"Actual completion must match exact stored planning call/result");++count;}return count;};
        require(completed_count()==1,"Typed commit must publish one actual generic completion");
        store.commit_dynamic_tool_turn("owner",call.id).get();require(store.history("s_owner").get().size()==3&&completed_count()==1,"Conversation commit marker must deduplicate history and completion");
        store.reserve_dynamic_continuation(call.id,"joined_continuation").get();store.reserve_dynamic_continuation(call.id,"joined_continuation").get();rejects<Conflict>([&]{store.reserve_dynamic_continuation(call.id,"changed_continuation").get();},"Continuation must bind once to exact accepted plan call");
        store.start_model_call("owner","owner","joined_continuation").get();store.finish_model_call("owner","owner","joined_continuation",R"({"content":"Synthetic final repository answer"})").get();rejects<Conflict>([&]{store.start_model_call("owner","owner","joined_continuation").get();},"Actual finished continuation must never restart");
        store.complete_dynamic_owner("owner",R"({"content":"Synthetic final repository answer"})","segment_resumed",75).get();const auto done=store.root_budget("owner").get();require(done.children_admitted==2&&done.model_calls_reserved==4&&done.parent_model_calls_reserved==2&&done.parent_calls_held==0&&store.dynamic_budget_segment("owner").get().remaining_active_ms==599800,"Spent children/model turns and active time must survive pause with no reset/refund");store.close();
    }
    {PersistenceService store(database,imports);require(store.run("owner").get().state==RunState::completed&&store.dynamic_plan_call(call_id).get().continuation_attempt_id=="joined_continuation"&&store.owned_children("owner").get().size()==2,"Completed plan/history/ownership remain durable on actual reopen");const auto calls=store.dynamic_plan_calls("owner").get();require(calls.size()==1&&calls[0].conversation_commit_seq&&calls[0].continuation_attempt_id=="joined_continuation"&&store.dynamic_plan_revision(calls[0].plan_id,1).get().accepted_event_seq==calls[0].accepted_event_seq,"Actual call/revision read correlation must survive SQLite reopen");store.create_session("unrelated_session","Synthetic unrelated read scope").get();store.create_run("unrelated_root","unrelated_session").get();require(store.dynamic_plan_calls("unrelated_root").get().empty(),"Ordinary unrelated root must not observe another root's private call records");store.transition("unrelated_root",RunState::queued,RunState::cancelled).get();store.close();}
}
void fault_and_recovery(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    std::string call_id,plan_id;
    {
        PersistenceService store(database,imports);seed_root(store,"fault_owner",policy(workspace));
        const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("leaf","Synthetic SQL rollback objective","workspace.coding")})}}.dump();const auto spec=change_spec(store,"fault_owner","fault_initial",args);
        {XlangSqlite sql(database,imports);sql.execute("CREATE TRIGGER reject_plan_revision BEFORE INSERT ON dynamic_plan_revisions BEGIN SELECT RAISE(ABORT,'synthetic admitted revision fault'); END");}
        const auto before=store.root_budget("fault_owner").get();rejects<DatabaseError>([&]{store.accept_dynamic_plan_change(spec).get();},"Actual SQL revision fault must reject admission atomically");
        require(!store.dynamic_plan_for_root("fault_owner").get()&&store.root_budget("fault_owner").get().revision==before.revision&&store.root_budget("fault_owner").get().planned_children_reserved==0&&store.owned_children("fault_owner").get().empty(),"Rejected admission must roll back call/plan/budget/children");
        {XlangSqlite sql(database,imports);sql.execute("DROP TRIGGER reject_plan_revision");}
        const auto call=store.accept_dynamic_plan_change(spec).get();call_id=call.id;plan_id=call.plan_id;
        auto f=frontier(store,call,"leaf","fault_child");
        {XlangSqlite sql(database,imports);sql.execute("CREATE TRIGGER reject_plan_claim BEFORE INSERT ON events WHEN NEW.kind='plan.child.admitted' BEGIN SELECT RAISE(ABORT,'synthetic claim event fault'); END");}
        const auto b=store.root_budget("fault_owner").get();rejects<DatabaseError>([&]{store.admit_dynamic_frontier(f).get();},"Actual child admission event fault must roll back queued child and claim");
        require(store.owned_children("fault_owner").get().empty()&&store.root_budget("fault_owner").get().children_admitted==0&&store.root_budget("fault_owner").get().revision==b.revision,"Failed claim cannot spend or create a hidden execution");
        {XlangSqlite sql(database,imports);sql.execute("DROP TRIGGER reject_plan_claim");}
        store.admit_dynamic_frontier(f).get();store.transition("fault_child",RunState::queued,RunState::running).get();
        const OperationSpec effect{"fault_child",workspace,"replace_file","{}"};store.request_operation("fault_effect",effect,now()+60000).get();store.decide_operation("fault_effect",OperationDecision::allow,"synthetic_repository_controller").get();store.claim_operation("fault_effect",effect).get();store.finish_operation("fault_effect",OperationState::succeeded,R"({"receipt":"synthetic journal boundary acknowledgement; no filesystem effect"})").get();
        store.complete_run("fault_child",R"({"content":"Synthetic actual persisted terminal repository child"})").get();
        {
            XlangSqlite sql(database,imports);
            const auto unrelated=sql.execute("INSERT INTO events(run_id,kind,payload) VALUES('fault_owner','plan.child.settled','{}')");
            rejects<DatabaseError>([&]{sql.execute("UPDATE dynamic_plan_nodes SET state='settled',child_state='completed',outcome_json='{}',settled_event_seq=? WHERE plan_id=? AND label='leaf'",{*unrelated.last_insert_id,plan_id});},"Unrelated event cannot authorize another owner's settlement");
            sql.execute("CREATE TRIGGER reject_plan_settlement BEFORE INSERT ON events WHEN NEW.kind='plan.child.settled' AND NEW.run_id='fault_child' BEGIN SELECT RAISE(ABORT,'synthetic settlement journal fault'); END");
        }
        rejects<DynamicOutcomeUnrecorded>([&]{store.settle_dynamic_child("fault_child").get();},"Actual completed child journal fault must propagate native fail-stop");
        require(store.dynamic_plan(plan_id).get().nodes[0].state==DynamicNodeState::claimed&&store.run("fault_child").get().state==RunState::completed,"Journal failure must preserve unfinished claim and actual completed child");
        {XlangSqlite sql(database,imports);sql.execute("DROP TRIGGER reject_plan_settlement");}
        store.close();
    }
    {
        PersistenceService store(database,imports);const auto p=store.dynamic_plan(plan_id).get();require(store.run("fault_owner").get().state==RunState::failed&&p.state=="interrupted"&&p.nodes[0].child_state=="completed"&&p.nodes[0].effect_state=="succeeded"&&p.nodes[0].outcome_json.find("Synthetic actual persisted terminal repository child")!=std::string::npos&&store.operation("fault_effect").get().state==OperationState::succeeded&&store.operation("fault_effect").get().result_json==R"({"receipt":"synthetic journal boundary acknowledgement; no filesystem effect"})","Recovery must preserve authoritative operation classification/result and actual terminal history without replaying claim");
        require(store.dynamic_plan_call(call_id).get().state=="interrupted"&&store.root_budget("fault_owner").get().planned_children_reserved==0&&store.dynamic_budget_segment("fault_owner").get().state=="interrupted","Recovery retires unfinished signed call, reservations and unknown active segment");
        rejects<std::invalid_argument>([&]{store.accept_dynamic_plan_change({}).get();},"Invalid recovery replay cannot create work");store.close();
    }
}
void failure_revision(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    PersistenceService store(database,imports);seed_root(store,"revision_owner",policy(workspace));const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("failed","Synthetic failed repository node","workspace.inspect"),agent("dependent","Synthetic success-dependent objective","workspace.inspect",Json::array({edge("failed")}))})}}.dump();
    const auto first=store.accept_dynamic_plan_change(change_spec(store,"revision_owner","revision_first",args)).get();store.admit_dynamic_frontier(frontier(store,first,"failed","failed_child")).get();finish_child(store,"revision_owner","failed_child",false);
    auto p=store.dynamic_plan(first.plan_id).get();require(inspect_dynamic_plan(p).report_ready&&!inspect_dynamic_plan(p).finished,"A real failed outcome must reach the parent while its success-dependent task remains unclaimed");
    store.settle_dynamic_plan_step(first.id).get();store.commit_dynamic_tool_turn("revision_owner",first.id).get();
    const auto protected_args=Json{{"expected_revision",p.revision},{"expected_state_sequence",p.state_sequence},{"replace",Json::array({agent("failed","Synthetic forbidden protected replacement","workspace.inspect")})}}.dump();const auto protected_reply=assistant("protected_revision",protected_args,false);
    store.reserve_dynamic_continuation(first.id,"protected_revision_attempt").get();store.start_model_call(p.root_run_id,p.root_run_id,"protected_revision_attempt").get();store.finish_model_call(p.root_run_id,p.root_run_id,"protected_revision_attempt",protected_reply).get();store.append_event(p.root_run_id,"tool.started",Json{{"activity_id",p.root_run_id+":plan:protected_revision"},{"call_id","protected_revision"},{"name","revise_plan"},{"arguments_json",protected_args}}.dump()).get();
    DynamicPlanChangeSpec protected_spec;protected_spec.id="call_protected_revision";protected_spec.plan_id=p.id;protected_spec.root_run_id=p.root_run_id;protected_spec.provider_tool_call_id="protected_revision";protected_spec.origin_attempt_id="protected_revision_attempt";protected_spec.arguments_json=protected_args;protected_spec.parent_assistant_json=protected_reply;protected_spec.backend_identity=authority;protected_spec.expected_budget_revision=store.root_budget(p.root_run_id).get().revision;
    rejects<std::invalid_argument>([&]{store.accept_dynamic_plan_change(protected_spec).get();},"A fresh proposal changing a protected actual child is a preaccept model rejection");require(store.dynamic_plan(p.id).get().revision==1&&store.dynamic_plan_calls(p.root_run_id).get().size()==1&&store.dynamic_plan(p.id).get().nodes[0].child_run_id=="failed_child","Rejected protected revision cannot alter actual plan/child or invent accepted call");
    store.record_rejected_dynamic_tool_turn(p.root_run_id,"protected_revision_attempt",protected_reply,"invalid_plan_arguments").get();
    const auto revision_args=Json{{"expected_revision",p.revision},{"expected_state_sequence",p.state_sequence},{"replace",Json::array({agent("dependent","Synthetic revised observed objective","workspace.inspect",Json::array({edge("failed","observed")}))})}}.dump();const auto reply=assistant("revision_second",revision_args,false);
    store.reserve_model_call(p.root_run_id,p.root_run_id,"revision_attempt",ModelCallRole::parent).get();store.start_model_call("revision_owner","revision_owner","revision_attempt").get();store.finish_model_call("revision_owner","revision_owner","revision_attempt",reply).get();
    store.append_event("revision_owner","tool.started",Json{{"activity_id","revision_owner:plan:revision_second"},{"call_id","revision_second"},{"name","revise_plan"},{"arguments_json",revision_args}}.dump()).get();
    DynamicPlanChangeSpec spec;spec.id="call_revision_second";spec.plan_id=p.id;spec.root_run_id=p.root_run_id;spec.provider_tool_call_id="revision_second";spec.origin_attempt_id="revision_attempt";spec.arguments_json=revision_args;spec.parent_assistant_json=reply;spec.backend_identity=authority;spec.expected_budget_revision=store.root_budget(p.root_run_id).get().revision;
    const auto revised=store.accept_dynamic_plan_change(spec).get();p=store.dynamic_plan(p.id).get();require(p.revision==2&&p.nodes[0].definition_revision==1&&p.nodes[0].child_run_id=="failed_child"&&p.nodes[1].definition_revision==2&&prepare_dynamic_node(p,"dependent").dependency_outputs_json.find("failed")!=std::string::npos,"Signed revision must retain protected failed claim and replace only unclaimed definition");
    const auto calls=store.dynamic_plan_calls(p.root_run_id).get();const auto revisions=store.dynamic_plan_revisions(p.id).get();require(calls.size()==2&&calls[0].id==first.id&&calls[0].accepted_revision==1&&calls[1].id==revised.id&&calls[1].accepted_revision==2&&calls[1].parent_assistant_json==reply&&revisions.size()==2&&revisions[0].revision==1&&revisions[1].revision==2&&revisions[0].call_id==first.id&&revisions[1].call_id==revised.id&&revisions[1].accepted_event_seq==revised.accepted_event_seq,"Read accessors must retain ordered immutable actual call/revision/event correlation");
    const auto old_topology=Json::parse(revisions[0].canonical_spec_json),new_topology=Json::parse(revisions[1].canonical_spec_json);require(old_topology["nodes"][1]["depends_on"][0]["require"]=="success"&&new_topology["nodes"][1]["depends_on"][0]["require"]=="observed"&&old_topology["nodes"][0]==new_topology["nodes"][0],"Read-only topology revisions preserve original protected definition and actual changed dependency");
    rejects<NotFound>([&]{store.dynamic_plan_revision(p.id,3).get();},"Future unaccepted topology revision cannot be invented by read API");
    store.admit_dynamic_frontier(frontier(store,revised,"dependent","revised_child")).get();finish_child(store,"revision_owner","revised_child");store.settle_dynamic_plan_step(revised.id).get();store.commit_dynamic_tool_turn(p.root_run_id,revised.id).get();store.reserve_dynamic_continuation(revised.id,"final_revision_attempt").get();store.start_model_call(p.root_run_id,p.root_run_id,"final_revision_attempt").get();store.finish_model_call(p.root_run_id,p.root_run_id,"final_revision_attempt",R"({"content":"Synthetic revision completion"})").get();store.complete_dynamic_owner(p.root_run_id,R"({"content":"Synthetic revision completion"})","segment_revision_owner",10).get();
    require(store.root_budget(p.root_run_id).get().children_admitted==2&&store.root_budget(p.root_run_id).get().parent_model_calls_reserved==4,"Rejected and accepted revisions must not reset spent child or durable parent quota");store.close();
}
void migration_contract(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    std::vector<Message> saved;
    {
        PersistenceService store(database,imports);store.create_session("legacy_session","Synthetic pre-v11 migration").get();RootBudgetSpec b=policy(workspace);b.policy_id="native.delegation";store.start_prompt_run("legacy_root","legacy_session",R"({"content":"Synthetic preserved legacy prompt"})",b).get();store.transition("legacy_root",RunState::queued,RunState::running).get();store.reserve_model_call("legacy_root","legacy_root","legacy_attempt",ModelCallRole::parent).get();store.start_model_call("legacy_root","legacy_root","legacy_attempt").get();store.finish_model_call("legacy_root","legacy_root","legacy_attempt").get();store.complete_run("legacy_root",R"({"content":"Synthetic preserved legacy result"})").get();saved=store.history("legacy_session").get();store.put_information("fixture","preserved",R"({"keep":true})").get();store.close();
    }
    {XlangSqlite sql(database,imports);sql.begin();remove_dynamic_schema_fixture(sql);sql.execute("PRAGMA user_version=10");sql.execute("CREATE TABLE dynamic_plans(synthetic_ddl_conflict INTEGER)");sql.commit();}
    rejects<DatabaseError>([&]{PersistenceService rejected(database,imports);},"Actual v11 DDL conflict must abort migration");
    {XlangSqlite sql(database,imports);require(std::get<std::int64_t>(sql.execute("PRAGMA user_version").rows.at(0).at(0))==10,"Failed v11 migration must retain exact prior version");require(std::get<std::int64_t>(sql.execute("SELECT count(*) FROM pragma_table_info('agent_model_call_reservations') WHERE name='actual_assistant_json'").rows.at(0).at(0))==0&&std::get<std::int64_t>(sql.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='dynamic_capabilities'").rows.at(0).at(0))==0,"Failed migration must roll back additive columns and new tables");sql.execute("DROP TABLE dynamic_plans");}
    {
        PersistenceService store(database,imports);const auto h=store.history("legacy_session").get();require(h.size()==saved.size()&&h[0].json==saved[0].json&&h[1].json==saved[1].json&&store.information("fixture","preserved").get()==R"({"keep":true})","Actual v10-to-v11 migration preserves full saved history/config");
        const auto b=store.root_budget("legacy_root").get();require(b.spec.policy_id=="native.delegation"&&b.model_calls_reserved==1&&b.parent_model_calls_reserved==1&&b.planned_children_reserved==0&&!store.dynamic_plan_for_root("legacy_root").get(),"Legacy budget must retain actual counters without fictional dynamic backfill");rejects<NotFound>([&]{store.dynamic_capabilities("legacy_root").get();},"Legacy root cannot gain invented planning authority");
        {XlangSqlite sql(database,imports);require(std::get<std::int64_t>(sql.execute("PRAGMA user_version").rows.at(0).at(0))==12,"Successful exact old migration must reach schema12");}store.close();
    }
}
DelegationBatchSpec legacy_spec(PersistenceService& store,const std::string& root,const std::string& batch,const std::vector<std::string>& children){
    DelegationBatchSpec s;s.id=batch;s.parent_run_id=root;s.provider_tool_call_id="provider_"+batch;s.expected_budget_revision=store.root_budget(root).get().revision;Json tasks=Json::array();
    for(const auto& child:children){const auto objective="Synthetic repository legacy objective "+child;s.tasks.push_back({child,"node_"+child,child,Json{{"content",objective}}.dump(),objective});tasks.push_back({{"id",child},{"objective",objective},{"preset","workspace.inspect"}});}
    s.arguments_json=Json{{"tasks",tasks}}.dump();s.parent_assistant_json=Json{{"content",""},{"tool_calls",Json::array({{{"id",s.provider_tool_call_id},{"name","delegate_tasks"},{"arguments",s.arguments_json}}})}}.dump();return s;
}
void legacy_held_parent_quota(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    PersistenceService store(database,imports);seed_root(store,"quota_owner",policy(workspace));
    for(int i=0;i<15;++i){const auto id="quota_parent_"+std::to_string(i);store.reserve_model_call("quota_owner","quota_owner",id,ModelCallRole::parent).get();store.start_model_call("quota_owner","quota_owner",id).get();store.finish_model_call("quota_owner","quota_owner",id,R"({"content":"Synthetic parent quota DTO"})").get();}
    const auto spec=legacy_spec(store,"quota_owner","quota_legacy",{"quota_leaf"});const auto batch=store.accept_delegation_batch(spec).get();
    store.transition("quota_leaf",RunState::queued,RunState::running).get();store.complete_run("quota_leaf",R"({"content":"Synthetic legacy repository completion"})").get();store.settle_delegation_child("quota_leaf").get();const auto joined=store.settle_delegation_batch(batch.id).get();store.record_tool_turn("quota_owner",spec.parent_assistant_json,{Json{{"content",joined.result_json},{"tool_call_id",spec.provider_tool_call_id}}.dump()}).get();
    const auto before=store.root_budget("quota_owner").get();require(before.parent_model_calls_reserved==15&&before.parent_calls_held==1,"Exact last durable parent allowance must be held for ordinary delegation");
    store.reserve_model_call("quota_owner","quota_owner","quota_last_held",ModelCallRole::parent).get();store.start_model_call("quota_owner","quota_owner","quota_last_held").get();store.finish_model_call("quota_owner","quota_owner","quota_last_held",R"({"content":"Synthetic final quota DTO"})").get();
    rejects<RootBudgetExhausted>([&]{store.reserve_model_call("quota_owner","quota_owner","quota_seventeenth",ModelCallRole::parent).get();},"Durable parent quota must reject seventeenth turn after consuming legitimate held sixteenth");
    require(store.root_budget("quota_owner").get().parent_model_calls_reserved==16&&store.root_budget("quota_owner").get().parent_calls_held==0,"Held continuation consumes its existing allowance without double charging");
    store.complete_dynamic_owner("quota_owner",R"({"content":"Synthetic quota terminal"})","segment_quota_owner",1).get();store.close();
}
void uncertainty_fixed_point(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    std::string plan,call;std::int64_t sequence=0,budget_revision=0;std::size_t event_count=0;const std::string result=R"({"receipt":"synthetic uncertain operation boundary; no filesystem effect"})";
    {
        PersistenceService store(database,imports);seed_root(store,"uncertain_owner",policy(workspace));const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("coding","Synthetic uncertainty ledger objective","workspace.coding")})}}.dump();const auto accepted=store.accept_dynamic_plan_change(change_spec(store,"uncertain_owner","uncertain_origin",args)).get();plan=accepted.plan_id;call=accepted.id;store.admit_dynamic_frontier(frontier(store,accepted,"coding","uncertain_child")).get();store.transition("uncertain_child",RunState::queued,RunState::running).get();
        const OperationSpec effect{"uncertain_child",workspace,"replace_file","{}"};store.request_operation("uncertain_effect",effect,now()+60000).get();store.decide_operation("uncertain_effect",OperationDecision::allow,"synthetic_repository_controller").get();store.claim_operation("uncertain_effect",effect).get();store.finish_operation("uncertain_effect",OperationState::uncertain,result).get();store.transition("uncertain_child",RunState::running,RunState::failed,R"({"reason":"synthetic_effect_uncertain"})").get();store.settle_dynamic_child("uncertain_child").get();rejects<WorkspaceEffectUncertain>([&]{store.settle_dynamic_plan_step(call).get();},"Uncertain journal must block parent continuation");store.close();
    }
    {
        PersistenceService store(database,imports);const auto p=store.dynamic_plan(plan).get();require(p.state=="uncertain"&&p.nodes[0].effect_state=="uncertain"&&store.run("uncertain_owner").get().state==RunState::failed&&store.dynamic_plan_call(call).get().state=="interrupted","First recovery retires unfinished call while retaining actual operation quarantine");sequence=p.state_sequence;budget_revision=store.root_budget("uncertain_owner").get().revision;event_count=store.tree_events("uncertain_owner").get().size();require(store.operation("uncertain_effect").get().result_json==result,"Actual uncertainty result must remain intact");store.close();
    }
    {
        PersistenceService store(database,imports);require(store.dynamic_plan(plan).get().state_sequence==sequence&&store.root_budget("uncertain_owner").get().revision==budget_revision&&store.tree_events("uncertain_owner").get().size()==event_count&&store.operation("uncertain_effect").get().state==OperationState::uncertain&&store.operation("uncertain_effect").get().result_json==result&&store.dynamic_plan_call(call).get().state=="interrupted","Second clean reopen must be an exact metadata/audit fixed point without replay");store.close();
    }
}
void final_human_only(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace,bool expire){
    std::string plan,call;std::int64_t expiry=0;
    {
        PersistenceService store(database,imports);seed_root(store,"human_only_owner",policy(workspace));const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({human("final_question","Synthetic final human-only question",Json::array())})}}.dump();const auto accepted=store.accept_dynamic_plan_change(change_spec(store,"human_only_owner","human_only_origin",args)).get();plan=accepted.plan_id;call=accepted.id;
        auto p=store.dynamic_plan(plan).get();expiry=now()+(expire?500:600000);DynamicHumanRequestSpec h{"human_only_request",plan,"final_question",authority,call,p.revision,p.state_sequence,expiry};store.publish_dynamic_human(h).get();p=store.dynamic_plan(plan).get();const auto b=store.root_budget(p.root_run_id).get();store.suspend_dynamic_owner({plan,call,"segment_human_only_owner",authority,p.revision,p.state_sequence,b.revision,1}).get();require(store.owned_children(p.root_run_id).get().empty()&&store.root_budget(p.root_run_id).get().parent_calls_held==1,"Zero-child final question preserves exact held continuation");store.close();
    }
    if(expire)std::this_thread::sleep_until(std::chrono::system_clock::time_point(std::chrono::milliseconds(expiry+1)));
    {
        PersistenceService store(database,imports);auto p=store.dynamic_plan(plan).get();require(store.run(p.root_run_id).get().state==RunState::paused,"Actual clean zero-child human pause survives reopen");
        if(expire){const auto h=store.expire_dynamic_human(plan,"human_only_request").get();require(h.state=="expired"&&store.run(p.root_run_id).get().state==RunState::paused,"Expired question settles without reopening active time or provider transport");store.retire_dynamic_owner(p.root_run_id,RunState::failed,R"({"reason":"human_input_expired"})").get();require(store.root_budget(p.root_run_id).get().model_calls_reserved==1&&store.root_budget(p.root_run_id).get().parent_calls_held==0&&!store.dynamic_plan_call(call).get().continuation_attempt_id.size(),"Expiry retirement releases only unused held slot and dispatches no new model attempt");}
        else {store.input_dynamic_human({plan,"human_only_request",R"({"answer":"Synthetic final answer"})","synthetic_authenticated_controller",authority,p.revision,p.state_sequence}).get();p=store.dynamic_plan(plan).get();require(inspect_dynamic_plan(p).finished&&inspect_dynamic_plan(p).report_ready,"Last human answer with no ready agent must wake actual final report");const auto b=store.root_budget(p.root_run_id).get();store.resume_dynamic_owner({plan,"human_only_resumed",authority,p.revision,p.state_sequence,b.revision}).get();require(store.settle_dynamic_plan_step(call).get().ready,"Zero-child answered plan must yield real typed report");store.commit_dynamic_tool_turn(p.root_run_id,call).get();store.reserve_dynamic_continuation(call,"human_only_continuation").get();store.start_model_call(p.root_run_id,p.root_run_id,"human_only_continuation").get();store.finish_model_call(p.root_run_id,p.root_run_id,"human_only_continuation",R"({"content":"Synthetic human-only final response"})").get();store.complete_dynamic_owner(p.root_run_id,R"({"content":"Synthetic human-only final response"})","human_only_resumed",1).get();require(store.root_budget(p.root_run_id).get().model_calls_reserved==2&&store.root_budget(p.root_run_id).get().children_admitted==0&&store.history("s_human_only_owner").get().size()==4,"Exactly one parent continuation and no child is charged for human-only completion");}
        store.close();
    }
}
void shared_child_limits(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    PersistenceService store(database,imports);seed_root(store,"shared_owner",policy(workspace));const auto legacy=legacy_spec(store,"shared_owner","shared_legacy",{"old_one","old_two","old_three","old_four"});const auto batch=store.accept_delegation_batch(legacy).get();
    for(const auto& task:batch.tasks){store.transition(task.run.id,RunState::queued,RunState::running).get();store.complete_run(task.run.id,R"({"content":"Synthetic legacy ledger output"})").get();store.settle_delegation_child(task.run.id).get();}
    const auto joined=store.settle_delegation_batch(batch.id).get();store.record_tool_turn("shared_owner",legacy.parent_assistant_json,{Json{{"content",joined.result_json},{"tool_call_id",legacy.provider_tool_call_id}}.dump()}).get();
    const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("one","Synthetic dynamic one","workspace.inspect"),agent("two","Synthetic dynamic two","workspace.inspect"),agent("three","Synthetic dynamic three","workspace.inspect"),agent("four","Synthetic dynamic four","workspace.inspect")})}}.dump();
    const auto call=store.accept_dynamic_plan_change(change_spec(store,"shared_owner","shared_initial",args)).get();require(store.root_budget("shared_owner").get().children_admitted==4&&store.root_budget("shared_owner").get().planned_children_reserved==4,"Old delegation plus planned dynamic children must share the same eight total allowance");
    auto pair=frontier(store,call,"one","new_one");const auto second=frontier(store,call,"two","new_two");pair.tasks.push_back(second.tasks[0]);store.admit_dynamic_frontier(pair).get();
    const auto full=frontier(store,call,"three","new_three");rejects<Conflict>([&]{store.admit_dynamic_frontier(full).get();},"Two actual queued/running owned child records block a third frontier admission");require(store.root_budget("shared_owner").get().children_admitted==6&&store.root_budget("shared_owner").get().planned_children_reserved==2,"Rejected active frontier must preserve spent and planned counters");
    finish_child(store,"shared_owner","new_one");finish_child(store,"shared_owner","new_two");pair=frontier(store,call,"three","new_three");pair.tasks.push_back(frontier(store,call,"four","new_four").tasks[0]);store.admit_dynamic_frontier(pair).get();finish_child(store,"shared_owner","new_three");finish_child(store,"shared_owner","new_four");
    store.settle_dynamic_plan_step(call.id).get();store.commit_dynamic_tool_turn("shared_owner",call.id).get();store.reserve_dynamic_continuation(call.id,"shared_join").get();store.start_model_call("shared_owner","shared_owner","shared_join").get();store.finish_model_call("shared_owner","shared_owner","shared_join",R"({"content":"Synthetic shared budget result"})").get();
    const auto ninth=legacy_spec(store,"shared_owner","shared_ninth",{"ninth_child"});rejects<RootBudgetExhausted>([&]{store.accept_delegation_batch(ninth).get();},"A later ordinary batch cannot reset eight lifetime children consumed across both engines");require(store.root_budget("shared_owner").get().children_admitted==8&&store.owned_children("shared_owner").get().size()==8,"Rejected ninth child cannot spend, refund or create an owned run");
    store.complete_dynamic_owner("shared_owner",R"({"content":"Synthetic mixed child ledger completion"})","segment_shared_owner",1).get();store.close();
}
void shared_model_call_limit(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    PersistenceService store(database,imports);seed_root(store,"calls_owner",policy(workspace));
    auto first=legacy_spec(store,"calls_owner","calls_first",{"call_old_one","call_old_two","call_old_three","call_old_four"});
    store.reserve_model_call("calls_owner","calls_owner","calls_origin",ModelCallRole::parent).get();store.start_model_call("calls_owner","calls_owner","calls_origin").get();store.finish_model_call("calls_owner","calls_owner","calls_origin",first.parent_assistant_json).get();first.expected_budget_revision=store.root_budget("calls_owner").get().revision;const auto first_batch=store.accept_delegation_batch(first).get();
    for(const auto& task:first_batch.tasks){store.transition(task.run.id,RunState::queued,RunState::running).get();for(int i=0;i<4;++i){const auto attempt=task.run.id+"_attempt_"+std::to_string(i);store.reserve_model_call("calls_owner",task.run.id,attempt,ModelCallRole::leaf).get();store.start_model_call("calls_owner",task.run.id,attempt).get();store.finish_model_call("calls_owner",task.run.id,attempt,R"({"content":"Synthetic bounded leaf turn"})").get();}store.complete_run(task.run.id,R"({"content":"Synthetic first batch leaf output"})").get();store.settle_delegation_child(task.run.id).get();}
    const auto first_join=store.settle_delegation_batch(first_batch.id).get();store.record_tool_turn("calls_owner",first.parent_assistant_json,{Json{{"content",first_join.result_json},{"tool_call_id",first.provider_tool_call_id}}.dump()}).get();
    auto second=legacy_spec(store,"calls_owner","calls_second",{"call_new_one","call_new_two","call_new_three","call_new_four"});store.reserve_model_call("calls_owner","calls_owner","calls_second_origin",ModelCallRole::parent).get();store.start_model_call("calls_owner","calls_owner","calls_second_origin").get();store.finish_model_call("calls_owner","calls_owner","calls_second_origin",second.parent_assistant_json).get();second.expected_budget_revision=store.root_budget("calls_owner").get().revision;const auto second_batch=store.accept_delegation_batch(second).get();
    for(std::size_t child=0;child<second_batch.tasks.size();++child){const auto id=second_batch.tasks[child].run.id;store.transition(id,RunState::queued,RunState::running).get();for(int i=0;i<3;++i){const auto attempt=id+"_attempt_"+std::to_string(i);store.reserve_model_call("calls_owner",id,attempt,ModelCallRole::leaf).get();store.start_model_call("calls_owner",id,attempt).get();store.finish_model_call("calls_owner",id,attempt,R"({"content":"Synthetic bounded second leaf turn"})").get();}if(child<2){store.complete_run(id,R"({"content":"Synthetic second batch leaf output"})").get();store.settle_delegation_child(id).get();}}
    const auto left=second_batch.tasks[2].run.id,right=second_batch.tasks[3].run.id;require(store.root_budget("calls_owner").get().model_calls_reserved==30&&store.root_budget("calls_owner").get().parent_calls_held==1,"Exact shared allowance must leave one unheld call and protected final parent slot");
    auto contender=[&](const std::string& owner,const std::string& attempt){try{store.reserve_model_call("calls_owner",owner,attempt,ModelCallRole::leaf).get();return true;}catch(const RootBudgetExhausted&){return false;}};
    auto left_future=std::async(std::launch::async,[&]{return contender(left,"calls_race_left");}),right_future=std::async(std::launch::async,[&]{return contender(right,"calls_race_right");});const bool left_won=left_future.get(),right_won=right_future.get();require(left_won!=right_won&&store.root_budget("calls_owner").get().model_calls_reserved==31&&store.root_budget("calls_owner").get().parent_calls_held==1,"Two actual repository contenders must reserve only the final unheld leaf allowance");
    const auto winner=left_won?left:right,attempt=left_won?std::string("calls_race_left"):std::string("calls_race_right");store.start_model_call("calls_owner",winner,attempt).get();store.finish_model_call("calls_owner",winner,attempt,R"({"content":"Synthetic final unheld leaf turn"})").get();
    store.reserve_model_call("calls_owner","calls_owner","calls_protected_final",ModelCallRole::parent).get();rejects<RootBudgetExhausted>([&]{store.reserve_model_call("calls_owner",left,"calls_thirty_third",ModelCallRole::leaf).get();},"Protected parent slot must reach exactly32 with no33rd leaf reservation");
    for(const auto& id:{left,right}){store.complete_run(id,R"({"content":"Synthetic final second batch output"})").get();store.settle_delegation_child(id).get();}const auto second_join=store.settle_delegation_batch(second_batch.id).get();store.record_tool_turn("calls_owner",second.parent_assistant_json,{Json{{"content",second_join.result_json},{"tool_call_id",second.provider_tool_call_id}}.dump()}).get();store.start_model_call("calls_owner","calls_owner","calls_protected_final").get();store.finish_model_call("calls_owner","calls_owner","calls_protected_final",R"({"content":"Synthetic exact32 final response"})").get();const auto final=store.root_budget("calls_owner").get();require(final.model_calls_reserved==32&&final.parent_calls_held==0&&final.children_admitted==8&&final.parent_model_calls_reserved==3,"Exactly32 attempts across two batches preserve spent8 children and actual3 parent turns");store.complete_dynamic_owner("calls_owner",R"({"content":"Synthetic exact32 ledger terminal"})","segment_calls_owner",1).get();store.close();
}
void rejected_signed_turn(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    PersistenceService store(database,imports);seed_root(store,"rejected_owner",policy(workspace));const std::string raw="{synthetic-invalid-json";const auto exact=assistant("rejected_call",raw);
    store.reserve_model_call("rejected_owner","rejected_owner","rejected_origin",ModelCallRole::parent).get();store.start_model_call("rejected_owner","rejected_owner","rejected_origin").get();store.finish_model_call("rejected_owner","rejected_owner","rejected_origin",exact).get();store.append_event("rejected_owner","tool.started",Json{{"activity_id","rejected_owner:plan:rejected_call"},{"call_id","rejected_call"},{"name","plan_tasks"},{"arguments_json",raw}}.dump()).get();
    rejects<std::invalid_argument>([&]{store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact,"model-supplied-private-error").get();},"Rejected tool results must only carry native allowlisted codes");
    rejects<Conflict>([&]{store.record_rejected_dynamic_tool_turn("rejected_owner","different_origin",exact,"invalid_plan_arguments").get();},"Preaccept rejection must match actual finished attempt");
    rejects<Conflict>([&]{store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact+" ","invalid_plan_arguments").get();},"Preaccept rejection must match exact signed response bytes");
    {XlangSqlite sql(database,imports);sql.execute("CREATE TRIGGER reject_rejected_turn_marker BEFORE INSERT ON events WHEN NEW.kind='conversation.tool_turn' BEGIN SELECT RAISE(ABORT,'synthetic rejected-turn commit fault'); END");}
    rejects<DynamicOutcomeUnrecorded>([&]{store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact,"invalid_plan_arguments").get();},"Rejected-turn marker fault must roll back failed event and assistant/tool messages");
    require(store.history("s_rejected_owner").get().size()==1&&!store.dynamic_plan_for_root("rejected_owner").get(),"Failed rejection commit cannot invent accepted plan or unmatched history");std::size_t failures=0;for(const auto& event:store.events("rejected_owner").get())if(event.kind=="tool.failed")++failures;require(failures==0,"Failed rejection commit cannot leave orphan tool failure");
    {XlangSqlite sql(database,imports);sql.execute("DROP TRIGGER reject_rejected_turn_marker");}
    store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact,"invalid_plan_arguments").get();store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact,"invalid_plan_arguments").get();require(store.history("s_rejected_owner").get().size()==3&&store.history("s_rejected_owner").get()[1].json==exact&&!store.dynamic_plan_for_root("rejected_owner").get(),"Only rejected original signed turn commits once without accepted ledger/held children");failures=0;for(const auto& event:store.events("rejected_owner").get())if(event.kind=="tool.failed"){const auto data=Json::parse(event.json);require(data["data"]["error"]["code"]=="invalid_plan_arguments"&&event.json.find("synthetic-private-opaque")==std::string::npos&&event.json.find(raw)==std::string::npos,"Public failure event must include bounded code without provider opaque/raw argument material");++failures;}require(failures==1,"Rejected commit deduplicates actual tool failure");
    rejects<Conflict>([&]{store.record_rejected_dynamic_tool_turn("rejected_owner","rejected_origin",exact,"plan_changed").get();},"A repeated rejected provider call cannot change fixed failure binding");
    const auto inspect=Json{{"content",""},{"tool_calls",Json::array({{{"id","rejected_inspect"},{"name","inspect_plan"},{"arguments",R"({"unsupported":true})"}}})}}.dump();store.reserve_model_call("rejected_owner","rejected_owner","inspect_origin",ModelCallRole::parent).get();store.start_model_call("rejected_owner","rejected_owner","inspect_origin").get();store.finish_model_call("rejected_owner","rejected_owner","inspect_origin",inspect).get();store.append_event("rejected_owner","tool.started",Json{{"activity_id","rejected_owner:plan:rejected_inspect"},{"call_id","rejected_inspect"},{"name","inspect_plan"},{"arguments_json",R"({"unsupported":true})"}}.dump()).get();store.record_rejected_dynamic_tool_turn("rejected_owner","inspect_origin",inspect,"invalid_plan_arguments").get();require(store.history("s_rejected_owner").get().size()==5&&store.root_budget("rejected_owner").get().parent_calls_held==0,"Invalid inspect rejection cannot invent a held continuation");
    store.retire_dynamic_owner("rejected_owner",RunState::cancelled,R"({"reason":"synthetic_rejection_fixture_done"})","segment_rejected_owner",1).get();store.close();
}
void dynamic_effect_admission(const std::string& database,const std::vector<std::string>& imports,const std::string& workspace){
    // This is the real SQLite admission/journal boundary with explicitly
    // synthetic captured registry metadata and acknowledgements. Actual
    // Registry discovery/schema validation and filesystem effects are tested
    // by their own executor contracts; no peer/file effect occurs here.
    const std::string fingerprint(64,'d'),alias="mcp_"+fingerprint.substr(0,48);
    const std::string schema=R"({"type":"object","properties":{"n":{"minimum":1.00000000000000000001}}})";
    const Json binding={{"server_config_id","synthetic-server"},{"config_revision",3},{"peer_tool","write_file"},{"alias",alias},{"catalogue_fingerprint",fingerprint},{"protocol_version","2025-11-25"},{"input_schema_json",schema},{"output_schema_json",nullptr},{"annotations_json",R"({"readOnlyHint":false,"synthetic_number":1.00000000000000000001})"}};
    const Json entry={{"name",alias},{"description","Synthetic captured registry descriptor"},{"input_schema_json",schema},{"mcp_binding",binding}};
    PersistenceService store(database,imports);seed_root(store,"effect_owner",policy(workspace),{{{"name","create_file"}},{{"name","run_process"}},entry});
    const auto args=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("coding","Synthetic effect journal boundary","workspace.coding"),agent("inspect","Synthetic read-only boundary","workspace.inspect")})}}.dump();
    const auto call=store.accept_dynamic_plan_change(change_spec(store,"effect_owner","effect_origin",args)).get();auto pair=frontier(store,call,"coding","effect_coding_child");pair.tasks.push_back(frontier(store,call,"inspect","effect_inspect_child").tasks[0]);store.admit_dynamic_frontier(pair).get();store.transition("effect_coding_child",RunState::queued,RunState::running).get();store.transition("effect_inspect_child",RunState::queued,RunState::running).get();
    Json proposal=binding;const std::string raw=R"({"n":18446744073709551617,"decimal":1.00000000000000000001})";proposal["arguments_json"]=raw;
    const OperationSpec mcp{"effect_coding_child",workspace,"mcp_tool",proposal.dump(),{"mcp-server:synthetic-server"}};
    const auto events=store.tree_events("effect_owner").get().size();const auto budget_revision=store.root_budget("effect_owner").get().revision;int rejected=0;
    auto denied=[&](const OperationSpec& spec){rejects<Conflict>([&]{store.request_operation("forbidden_effect_"+std::to_string(rejected++),spec,now()+60000).get();},"Invalid dynamic effect mapping/binding must reject before proposal");require(store.operations("effect_coding_child").get().empty()&&store.operations("effect_inspect_child").get().empty()&&store.tree_events("effect_owner").get().size()==events&&store.root_budget("effect_owner").get().revision==budget_revision,"Rejected effects must not create approvals, audit or budget mutations");};
    for(const auto* tool:{"edit_file","unknown_effect","read_file"})denied({"effect_coding_child",workspace,tool,"{}"});
    denied({"effect_coding_child",workspace,alias,proposal.dump(),mcp.resources});
    auto wrong=mcp;wrong.workspace="different-workspace";denied(wrong);
    for(const auto* tool:{"replace_file","create_file","run_process"})denied({"effect_inspect_child",workspace,tool,"{}"});wrong=mcp;wrong.run_id="effect_inspect_child";denied(wrong);
    const std::vector<std::pair<std::string,Json>> drift={{"server_config_id","other-server"},{"config_revision",4},{"config_revision",3.0},{"peer_tool","other_tool"},{"alias","mcp_"+std::string(48,'e')},{"alias","mcp_"+std::string(48,'D')},{"catalogue_fingerprint",fingerprint.substr(0,63)+"e"},{"protocol_version","2025-03-26"},{"input_schema_json"," "+schema},{"output_schema_json",R"({"type":"object"})"},{"annotations_json",R"({"readOnlyHint":true})"}};
    for(const auto& [field,value]:drift){auto changed=proposal;changed[field]=value;wrong=mcp;wrong.arguments_json=changed.dump();denied(wrong);}
    for(const auto* field:{"server_config_id","input_schema_json","catalogue_fingerprint","arguments_json"}){auto changed=proposal;changed.erase(field);wrong=mcp;wrong.arguments_json=changed.dump();denied(wrong);}
    auto changed=proposal;changed["model_grant"]="replace_file";wrong=mcp;wrong.arguments_json=changed.dump();denied(wrong);
    for(const auto& resources:std::vector<std::vector<std::string>>{{},{"mcp-server:other-server"},{"mcp-server:synthetic-server","extra-resource"}}){wrong=mcp;wrong.resources=resources;denied(wrong);}
    {
        XlangSqlite sql(database,imports);
        rejects<DatabaseError>([&]{sql.execute("UPDATE dynamic_plan_nodes SET claim_id='forged_claim' WHERE plan_id=? AND label='coding'",{call.plan_id});},"SQL must retain immutable native claim identity");
        rejects<DatabaseError>([&]{sql.execute("UPDATE dynamic_capabilities SET capabilities_json=capabilities_json WHERE root_run_id='effect_owner'");},"SQL cannot reseal private catalogue authority after admission");
    }
    // Native adapter/model-name mapping is now admitted through real journal
    // decisions/claims. The acknowledgement remains labelled synthetic.
    const OperationSpec replacement{"effect_coding_child",workspace,"replace_file","{}"};const auto accepted=store.request_operation("mapped_replace",replacement,now()+60000).get();require(accepted.spec.tool=="replace_file"&&accepted.state==OperationState::awaiting_approval,"edit_file preset must authorize only the native replace_file journal");store.decide_operation("mapped_replace",OperationDecision::allow,"synthetic_repository_controller").get();store.claim_operation("mapped_replace",replacement).get();store.finish_operation("mapped_replace",OperationState::succeeded,R"({"receipt":"synthetic admission acknowledgement; no filesystem effect"})").get();
    for(const auto* tool:{"create_file","run_process"}){const auto id="mapped_"+std::string(tool);store.request_operation(id,{"effect_coding_child",workspace,tool,"{}"},now()+60000).get();store.decide_operation(id,OperationDecision::deny,"synthetic_repository_controller").get();}
    const auto actual_mcp=store.request_operation("mapped_mcp",mcp,now()+60000).get();require(Json::parse(actual_mcp.spec.arguments_json)["arguments_json"]==raw&&actual_mcp.spec.resources==mcp.resources,"MCP admission must retain exact raw numeric payload and captured server resource");store.decide_operation("mapped_mcp",OperationDecision::deny,"synthetic_repository_controller").get();
    store.complete_run("effect_coding_child",R"({"content":"Synthetic journal boundary completion"})").get();store.settle_dynamic_child("effect_coding_child").get();rejects<Conflict>([&]{store.request_operation("after_settlement",replacement,now()+60000).get();},"A retired actual child claim cannot acquire a later effect");store.complete_run("effect_inspect_child",R"({"content":"Synthetic read-only boundary completion"})").get();store.settle_dynamic_child("effect_inspect_child").get();store.retire_dynamic_owner("effect_owner",RunState::cancelled,R"({"reason":"synthetic_effect_boundary_done"})","segment_effect_owner",1).get();
    // Missing/corrupt trusted metadata is rejected even when a matching alias
    // exists in the preset. These are synthetic persisted boundary fixtures,
    // not descriptions produced by the native Registry's fingerprint builder.
    auto invalid_entry=[&](const std::string& root,Json captured){
        seed_root(store,root,policy(workspace),{captured});const auto definition=Json{{"expected_revision",0},{"expected_state_sequence",0},{"add",Json::array({agent("coding","Synthetic invalid captured binding","workspace.coding")})}}.dump();const auto accepted_call=store.accept_dynamic_plan_change(change_spec(store,root,root+"_origin",definition)).get();const auto child=root+"_child";store.admit_dynamic_frontier(frontier(store,accepted_call,"coding",child)).get();store.transition(child,RunState::queued,RunState::running).get();auto spec=mcp;spec.run_id=child;if(captured.contains("mcp_binding")){auto value=captured["mcp_binding"];value["arguments_json"]=raw;spec.arguments_json=value.dump();}
        const auto count=store.events(root).get().size();rejects<Conflict>([&]{store.request_operation(root+"_invalid",spec,now()+60000).get();},"A preset alias alone cannot mint a native MCP grant");require(store.operations(child).get().empty()&&store.events(root).get().size()==count,"Invalid sealed metadata cannot create any proposal");store.transition(child,RunState::running,RunState::failed,R"({"reason":"synthetic_invalid_binding_done"})").get();store.settle_dynamic_child(child).get();store.retire_dynamic_owner(root,RunState::cancelled,R"({"reason":"synthetic_invalid_binding_done"})","segment_"+root,1).get();
    };
    auto missing=entry;missing.erase("mcp_binding");invalid_entry("binding_missing",missing);
    auto corrupt=entry;corrupt["mcp_binding"]["catalogue_fingerprint"]=std::string(64,'e');invalid_entry("binding_fingerprint",corrupt);
    corrupt=entry;corrupt["input_schema_json"]=" "+schema;invalid_entry("binding_schema",corrupt);
    store.close();
}
}
int main(int argc,char** argv){
    if(argc!=3)return 2;
    try{Directory dir;const std::vector<std::string> imports{argv[1],argv[2]};pause_and_restart((dir.path/"plan.sqlite").string(),imports,dir.path.string());fault_and_recovery((dir.path/"fault.sqlite").string(),imports,dir.path.string());failure_revision((dir.path/"revision.sqlite").string(),imports,dir.path.string());migration_contract((dir.path/"migration.sqlite").string(),imports,dir.path.string());legacy_held_parent_quota((dir.path/"quota.sqlite").string(),imports,dir.path.string());uncertainty_fixed_point((dir.path/"uncertain.sqlite").string(),imports,dir.path.string());final_human_only((dir.path/"human-only.sqlite").string(),imports,dir.path.string(),false);final_human_only((dir.path/"human-expired.sqlite").string(),imports,dir.path.string(),true);shared_child_limits((dir.path/"shared-children.sqlite").string(),imports,dir.path.string());shared_model_call_limit((dir.path/"shared-calls.sqlite").string(),imports,dir.path.string());rejected_signed_turn((dir.path/"rejected.sqlite").string(),imports,dir.path.string());dynamic_effect_admission((dir.path/"effect-admission.sqlite").string(),imports,dir.path.string());std::cout<<"Dynamic plan repository contract passed: real xlang3 SQLite signed-call ownership, shared budget, exact human pause/recovery/continuation, revision, native effect mapping/registry binding, SQL-fault rollback and migration; synthetic repository DTOs only\n";return 0;}
    catch(const std::exception& error){std::cerr<<error.what()<<"\n";return 1;}
}
