// Synthetic provider replies/signatures/credentials and bespoke MCP descriptors.
// Actual AgentService, fresh MCP subprocesses, controller approvals, file effects,
// dependent native reads and embedded xlang3 SQLite; no manual run transitions.
#include "agentflow/agent_service.hpp"
#include "agentflow/dynamic_plan.hpp"
#include "nlohmann/json.hpp"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <thread>

using namespace agentflow;
using namespace std::chrono_literals;
namespace {
using Json=nlohmann::json;
const std::string provider_key="synthetic-dynamic-mcp-provider-not-live";
const std::string connector_key="synthetic-dynamic-mcp-connector-not-live";
const std::string effect="Actual dynamic coding MCP bytes\n";
// Only fixture-authored constant messages may enter public CI diagnostics.
// Library errors and provider/peer payloads remain in the private fixture log.
struct ContractFailure : std::runtime_error {using std::runtime_error::runtime_error;};
void require(bool value,const char* reason){if(!value)throw ContractFailure(reason);}
template<class Error,class Action>void rejects(Action action,const char* reason){try{action();}catch(const Error&){return;}throw std::runtime_error(reason);}
template<class Action>void eventually(Action action,const char* reason){const auto until=std::chrono::steady_clock::now()+15s;while(std::chrono::steady_clock::now()<until){if(action())return;std::this_thread::sleep_for(5ms);}throw ContractFailure(reason);}
bool terminal(RunState state){return state==RunState::completed||state==RunState::failed||state==RunState::cancelled;}
std::string read(const std::filesystem::path& path){std::ifstream stream(path,std::ios::binary);return {std::istreambuf_iterator<char>(stream),std::istreambuf_iterator<char>()};}
std::size_t audit_count(const std::filesystem::path& root,const std::string& kind){std::ifstream stream(root/"mcp-audit.jsonl");std::size_t count=0;std::string line;while(std::getline(stream,line))if(Json::parse(line).at("kind")==kind)count++;return count;}
std::size_t event_count(const std::vector<Event>& events,const std::string& kind){return std::count_if(events.begin(),events.end(),[&](const auto& event){return event.kind==kind;});}
const DynamicNodeRecord& node(const DynamicPlanRecord& plan,const std::string& label){const auto found=std::find_if(plan.nodes.begin(),plan.nodes.end(),[&](const auto& item){return item.definition.label==label;});if(found==plan.nodes.end())throw std::runtime_error("Actual dynamic node missing");return *found;}
void put_key(PersistenceService& store,const std::string& scope,const std::string& id,const std::string& purpose,const std::string& key){store.put_credential(scope,id,purpose,"Explicit synthetic test credential",SecretBytes({reinterpret_cast<const std::uint8_t*>(key.data()),key.size()}),0).get();}
void metrics(const Message& message,std::int64_t input,std::int64_t output){const auto row=Json::parse(message.json);require(row.at("usage").at("input_tokens")==input&&row.at("usage").at("output_tokens")==output,"Actual per-owner supplied metrics differ");require(row.contains("elapsed_ms")&&row.contains("first_token_ms")&&!row.at("usage").contains("total_tokens"),"Measured timings and absent totals must remain truthful");}
void private_absent(PersistenceService& store,const std::string& root){for(const auto& event:store.tree_events(root,0,256).get())require(event.json.find(provider_key)==std::string::npos&&event.json.find(connector_key)==std::string::npos,"Private credentials must not enter owned events");for(const auto& child:store.owned_children(root).get())for(const auto& row:store.owned_child_history(root,child.run.id).get())require(row.json.find(provider_key)==std::string::npos&&row.json.find(connector_key)==std::string::npos,"Private credentials must not enter child history");for(const auto& row:store.run_history(root).get())require(row.json.find(provider_key)==std::string::npos&&row.json.find(connector_key)==std::string::npos,"Private credentials must not enter root history");}
AgentSettings settings(PersistenceService& store,char** argv,const std::string& mode,const std::filesystem::path& workspace){
    AgentSettings value;value.provider={std::string(argv[6])+"/"+mode+"/messages","synthetic-dynamic-mcp",Capability::supported,Capability::supported,Capability::supported};value.provider.wire=ProviderWire::anthropic_messages;value.provider.deadline=10s;value.provider.idle_timeout=8s;
    value.workspace=workspace.string();value.approved_edits=false;value.max_turns=8;value.max_output_tokens=256;value.run_timeout=40s;value.instructions="Explicit synthetic provider/MCP fixture. Use only actual native outcomes; peer acknowledgement is not independent verification.";value.credential=CredentialReference{"fixture","provider","provider:synthetic-dynamic-mcp"};
    const Json desired{{"servers",Json::array({{{"id","dynamic-peer"},{"transport","stdio"},{"executable",argv[2]},{"working_directory",workspace.string()},{"arguments",Json::array({argv[3],"--mcp",mode,workspace.string()})},{"credentials",Json::array({{{"name","MCP_TEST_KEY"},{"scope","server"},{"id","connector"}}})}}})}};
    value.mcp_servers=McpConfigurationStore(store).apply(desired.dump());require(value.mcp_servers.size()==1&&value.mcp_servers[0].revision==1,"Actual native MCP configuration must assign its immutable revision");put_key(store,"fixture","provider","provider:synthetic-dynamic-mcp",provider_key);put_key(store,"server","connector",mcp_credential_purpose(value.mcp_servers[0],"MCP_TEST_KEY"),connector_key);return value;
}
void binding(PersistenceService& store,const std::string& root,const Operation& operation){
    const auto plan=store.dynamic_plan_for_root(root).get();require(plan.has_value(),"Actual accepted plan must exist before an effect proposal");const auto& coding=node(*plan,"write");require(coding.claim_revision==1&&coding.definition_revision==1&&!coding.claim_id.empty()&&operation.spec.run_id==coding.child_run_id&&operation.spec.run_id!=root&&operation.spec.tool=="mcp_tool","Actual MCP proposal must belong to the captured dynamic coding claim");
    const auto admission=store.child_admission(coding.child_run_id).get();require(admission.kind==ChildAdmissionKind::dynamic_agent&&admission.plan_id==plan->id&&admission.claim_id==coding.claim_id&&admission.preset_id=="workspace.coding","Actual child admission must bind the same plan, claim and coding preset");
    const auto proposal=Json::parse(operation.spec.arguments_json);require(proposal.size()==11&&proposal.at("protocol_version")=="2025-11-25"&&proposal.at("server_config_id")=="dynamic-peer"&&proposal.at("config_revision")==1&&proposal.at("instructions").at("version")==1&&proposal.at("instructions").at("directory")==".","Actual approval must contain the full native binding, exact raw arguments and native guidance precondition");
    const auto catalogue=Json::parse(plan->capabilities.tool_catalog_json);const auto alias=proposal.at("alias").get<std::string>();const auto found=std::find_if(catalogue.at("tools").begin(),catalogue.at("tools").end(),[&](const auto& tool){return tool.at("name")==alias;});require(found!=catalogue.at("tools").end()&&found->contains("mcp_binding"),"MCP effect alias must be captured in the actual private root catalogue");auto actual=proposal;actual.erase("arguments_json");actual.erase("instructions");require(actual.size()==9&&actual==found->at("mcp_binding"),"Every actual approval binding field must equal the sealed native registry snapshot");
    const auto raw=proposal.at("arguments_json").get<std::string>();require(raw.find("1.00000000000000000001")!=std::string::npos&&raw.find("\"pa\\u0074h\"")!=std::string::npos&&Json::parse(raw).at("body")==effect,"Raw exact decimal and escaped argument keys must survive provider, approval and MCP paths");require(operation.spec.resources==std::vector<std::string>{"mcp-server:dynamic-peer"}&&operation.spec.workspace==plan->capabilities.workspace_identity,"Actual effect ownership must bind its verified workspace and configured server domain");require(Json::parse(proposal.at("annotations_json").get<std::string>()).at("readOnlyHint")==true,"Untrusted read-only annotation must not skip effect approval");
}
void scenario(char** argv,const std::string& mode){
    const auto workspace=std::filesystem::u8path(argv[1])/mode;require(std::filesystem::create_directory(workspace),"Each scenario needs a fresh disposable workspace");const auto database=(workspace/"state.sqlite").string();const std::vector<std::string> imports={argv[4],argv[5]};const std::string root=mode+"-root";AgentSettings frozen;std::string operation_id,child_id;std::vector<Message> saved_root_history,saved_child_history;std::string saved_result;
    const bool success=mode=="success",denied=mode=="denied",drift=mode=="protocol-drift",cancel=mode=="cancel",lost=mode=="lost-reply";
    {
        PersistenceService store(database,imports);frozen=settings(store,argv,mode,workspace);store.create_session(mode+"-session","Actual dynamic coding MCP fixture").get();AgentService service(store,frozen,2,8);require(service.supports_dynamic_planning()&&audit_count(workspace,"started")==0,"Service metadata/admission must not launch an MCP peer");service.submit(root,mode+"-session","Explicit synthetic dynamic MCP parent: plan the registered coding work and report actual outcomes.");
        if(!drift){std::optional<Operation> proposed;eventually([&]{for(const auto& child:store.owned_children(root).get())for(const auto& operation:store.operations(child.run.id).get())if(operation.state==OperationState::awaiting_approval){proposed=operation;return true;}return false;},"Actual dynamic coding child did not request MCP effect approval");binding(store,root,*proposed);operation_id=proposed->id;child_id=proposed->spec.run_id;require(audit_count(workspace,"called")==0&&!std::filesystem::exists(workspace/"effect.txt"),"No actual peer dispatch/file effect may precede the controller decision");
            const auto pending=store.dynamic_plan_for_root(root).get();if(success||lost)require(node(*pending,"verify").claim_revision==0,"Success-dependent read cannot be admitted before the coding effect settles");
            if(cancel)service.cancel(root);else store.decide_operation(proposed->id,denied?OperationDecision::deny:OperationDecision::allow,"fixture-controller").get();
        }
        eventually([&]{return terminal(store.run(root).get().state);},"Actual MCP coding plan did not retire");eventually([&]{return service.idle();},"Native service did not relinquish the retired owner");require(service.healthy(),"Recorded effect uncertainty/configuration refusal must not masquerade as an unrecorded outcome fault");const auto plan=store.dynamic_plan_for_root(root).get();require(plan.has_value(),"Actual accepted plan missing after retirement");const auto& coding=node(*plan,"write");child_id=coding.child_run_id;const auto children=store.owned_children(root).get();require(children.size()==(success?2u:1u)&&coding.definition.preset_id=="workspace.coding","Only actual ready dynamic children are admitted");require(store.operations(root).get().empty(),"MCP effect approval belongs to its coding child, not the parent");const auto root_history=store.run_history(root).get(),coding_history=store.owned_child_history(root,child_id).get();const auto budget=store.root_budget(root).get();const auto expected_calls=success?6:denied?4:2;require(budget.model_calls_reserved==expected_calls&&budget.parent_model_calls_reserved==((success||denied||drift)?2:1)&&budget.children_admitted==children.size()&&budget.parent_calls_held==0,"Actual model/child reservations and held continuation must be consumed exactly once");
        if(success||denied||drift){require(store.run(root).get().state==RunState::completed&&root_history.size()==4,"Completed observation must commit one signed parent plan/result pair and one continuation");require(event_count(store.events(root).get(),"conversation.tool_turn")==1&&event_count(store.events(root).get(),"plan.call.accepted")==1,"Planning admission and signed tool turn must be once-only");metrics(root_history[1],17,6);metrics(root_history.back(),19,7);}
        if(success||denied){require(coding.child_state=="completed"&&coding_history.size()==4,"Coding child retains an honest independent MCP tool loop");metrics(coding_history[1],11,4);metrics(coding_history.back(),13,5);const auto actual=store.operation(operation_id).get();require(actual.state==(success?OperationState::succeeded:OperationState::denied)&&actual.decision_actor=="fixture-controller","Actual operation journal must retain the real controller decision/outcome");
            const auto child_result=Json::parse(Json::parse(coding_history[2].json).at("content").get<std::string>());if(success){const auto acknowledged=Json::parse(actual.result_json);require(acknowledged.at("acknowledged_by_peer")==true&&acknowledged.at("independently_verified")==false&&child_result==acknowledged,"Peer acknowledgement stays unverified even after separate native verification");require(read(workspace/"effect.txt")==effect&&audit_count(workspace,"called")==1,"One actual approved peer call must produce the actual bytes");const auto& verify=node(*plan,"verify");require(verify.child_state=="completed"&&verify.definition.preset_id=="workspace.inspect"&&verify.claim_revision==1,"A success-dependent registered inspector must actually run");const auto rows=store.owned_child_history(root,verify.child_run_id).get();require(rows.size()==4&&Json::parse(Json::parse(rows[2].json).at("content").get<std::string>()).at("content")==effect,"Independent native read must observe the actual peer-written file bytes");require(event_count(store.events(verify.child_run_id).get(),"mcp.connecting")==0&&store.operations(verify.child_run_id).get().empty(),"Read-only verifier cannot inherit MCP launch or effect authority");metrics(rows[1],7,2);metrics(rows.back(),9,3);require(coding.effect_state=="succeeded"&&verify.effect_state=="none","Actual MCP effect and independent read have distinct outcomes");}
            else require(child_result.at("error").at("code")=="permission_denied"&&coding.effect_state=="cancelled"&&audit_count(workspace,"called")==0&&!std::filesystem::exists(workspace/"effect.txt"),"Denied approval produces an honest tool error with no peer dispatch/effect");
        }else if(drift){require(coding.child_state=="failed"&&coding.effect_state=="none"&&coding_history.size()==1&&store.operations(child_id).get().empty(),"Same-alias protocol-binding drift must fail before child provider/approval/dispatch");const auto events=store.events(child_id).get();const auto failure=std::find_if(events.begin(),events.end(),[](const auto& event){return event.kind=="run.failed";});require(failure!=events.end()&&Json::parse(failure->json).at("reason")=="dynamic_configuration_changed","Captured full binding mismatch must have its actual configuration refusal");require(audit_count(workspace,"called")==0&&!std::filesystem::exists(workspace/"effect.txt"),"Protocol drift cannot dispatch an external effect");}
        else{require(store.run(root).get().state==(cancel?RunState::cancelled:RunState::failed)&&root_history.size()==1&&coding_history.size()==1,"Interrupted accepted call cannot acquire fake tool-turn history or a continuation");const auto actual=store.operation(operation_id).get();require(actual.state==(cancel?OperationState::cancelled:OperationState::uncertain),"Pre-dispatch cancellation and uncertain dispatched effects are distinct journals");if(cancel)require(audit_count(workspace,"called")==0&&!std::filesystem::exists(workspace/"effect.txt"),"Cancellation while waiting must not dispatch MCP");else{require(coding.state==DynamicNodeState::uncertain&&coding.effect_state=="uncertain"&&coding.child_state=="failed"&&node(*plan,"verify").claim_revision==0,"Actual lost reply quarantines the coding node and suppresses dependent verification");require(audit_count(workspace,"called")==1&&read(workspace/"effect.txt")==effect,"Lost acknowledgement must preserve the actual external effect");rejects<Conflict>([&]{store.decide_operation(operation_id,OperationDecision::allow,"fixture-controller").get();},"An uncertain consumed approval cannot be replayed");saved_result=actual.result_json;}}
        const auto events=store.events(child_id).get();if(!drift){require(event_count(events,"operation.awaiting_approval")==1,"One actual MCP proposal must own its durable approval event");require(event_count(events,"operation.executing")==((success||lost)?1u:0u),"Only actually approved dispatch acquires the durable effect claim");require(event_count(events,success?"operation.succeeded":denied?"operation.denied":cancel?"operation.cancelled":"operation.uncertain")==1,"Actual operation outcome must be journaled once");}private_absent(store,root);saved_root_history=root_history;saved_child_history=coding_history;service.close();store.close();
    }
    if(lost||cancel){const auto starts=audit_count(workspace,"started"),calls=audit_count(workspace,"called");PersistenceService store(database,imports);AgentService service(store,frozen,2,8);require(service.idle()&&store.run(root).get().state==(cancel?RunState::cancelled:RunState::failed)&&store.operation(operation_id).get().state==(cancel?OperationState::cancelled:OperationState::uncertain),"Reopen must preserve actual terminal owners and consumed journals");require(store.run_history(root).get().size()==saved_root_history.size()&&store.owned_child_history(root,child_id).get().size()==saved_child_history.size()&&store.root_budget(root).get().model_calls_reserved==2,"Reopen must not fabricate history/model attempts");if(lost)require(store.operation(operation_id).get().result_json==saved_result&&read(workspace/"effect.txt")==effect,"Quarantined actual effect and reply-loss record must survive reopen");service.close();store.close();require(audit_count(workspace,"started")==starts&&audit_count(workspace,"called")==calls,"Recovery/adoption must not reconnect or replay the uncertain/cancelled effect");}
}
}
int main(int argc,char** argv){if(argc!=7)return 2;try{for(const auto* mode:{"success","denied","protocol-drift","cancel","lost-reply"})scenario(argv,mode);std::cout<<"Native dynamic MCP coding contract passed actual full-binding rediscovery, independently approved peer write and dependent native read, denied/cancelled no dispatch, same-alias protocol drift before child provider, uncertain lost reply and reopen without replay. Provider/credentials/bespoke peer descriptors are synthetic; actual native/files/embedded xlang3 SQLite, no upstream SDK/live/IDE claim.\n";return 0;}catch(const std::exception& error){try{std::ofstream private_log(std::filesystem::u8path(argv[1])/"native-contract-failure-private.log",std::ios::binary);private_log<<error.what();}catch(...){}if(const auto* fixture=dynamic_cast<const ContractFailure*>(&error))std::cerr<<"Native dynamic MCP fixture assertion: "<<fixture->what()<<"\n";else std::cerr<<"Native dynamic MCP library failure; diagnostic details retained privately in the disposable fixture.\n";return 1;}}
