// Independent synthetic Anthropic wire fixture and actual initialized legacy
// MCP subprocess. Only test code: no upstream SDK/live provider/parity claim.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {mkdtemp,rm} from 'node:fs/promises';
import {createInterface} from 'node:readline';
import {createServer} from 'node:http';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {join,resolve,dirname,basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
const EFFECT='Actual dynamic coding MCP bytes\n';
const PROVIDER_KEY='synthetic-dynamic-mcp-provider-not-live';
const CONNECTOR_KEY='synthetic-dynamic-mcp-connector-not-live';
// Independently authored raw JSON, never a JS numeric object/stringify roundtrip.
const RAW_ARGUMENTS='{"pa\\u0074h":"effect.txt","body":'+JSON.stringify(EFFECT)+',"decimal":1.00000000000000000001}';
const modes=['success','denied','protocol-drift','cancel','lost-reply'];
function privatePeerFailure(error){const workspace=resolve(process.argv[4]??''),parent=dirname(workspace);if(!modes.includes(basename(workspace))||dirname(parent)!==resolve(tmpdir())||!basename(parent).startsWith('xmind-dynamic-mcp-')||!fs.lstatSync(workspace).isDirectory()||resolve(fs.realpathSync(workspace)).toLowerCase()!==workspace.toLowerCase())return;const stack=Buffer.from(String(error?.stack??'Unknown MCP fixture failure'));fs.writeFileSync(join(workspace,'mcp-peer-failure-'+process.pid+'-private.log'),stack.subarray(0,65536),{flag:'wx',mode:0o600});}
async function runNative(root,executable,args){let result;try{result=await promisify(execFile)(executable,args,{windowsHide:true,timeout:110000,maxBuffer:4*1024*1024,encoding:'buffer'});}catch(error){fs.writeFileSync(join(root,'native-stdout-private.log'),error.stdout??Buffer.alloc(0),{flag:'wx',mode:0o600});fs.writeFileSync(join(root,'native-stderr-private.log'),error.stderr??Buffer.alloc(0),{flag:'wx',mode:0o600});fs.writeFileSync(join(root,'native-process-private.json'),JSON.stringify({status:typeof error.code==='number'?error.code:null,errorCode:typeof error.code==='string'?error.code:null,signal:error.signal??null,killed:error.killed===true}),{flag:'wx',mode:0o600});throw error;}fs.writeFileSync(join(root,'native-stdout-private.log'),result.stdout,{flag:'wx',mode:0o600});fs.writeFileSync(join(root,'native-stderr-private.log'),result.stderr,{flag:'wx',mode:0o600});fs.writeFileSync(join(root,'native-process-private.json'),JSON.stringify({status:0,errorCode:null,signal:null,killed:false}),{flag:'wx',mode:0o600});return result;}
async function mcpPeer(){const [mode,workspace]=process.argv.slice(3);assert.ok(modes.includes(mode)&&workspace&&resolve(workspace)===workspace);assert.equal(process.env.MCP_TEST_KEY,CONNECTOR_KEY);for(const name of ['XMIND_API_KEY','XMIND_AUTH_TOKEN','XMIND_SETUP_SECRET'])assert.equal(process.env[name],undefined);const audit=join(workspace,'mcp-audit.jsonl');const old=fs.existsSync(audit)?fs.readFileSync(audit,'utf8').split('\n').filter(Boolean).map(line=>JSON.parse(line)):[];const ordinal=old.filter(item=>item.kind==='started').length+1;const protocol=mode==='protocol-drift'&&ordinal===2?'2025-06-18':'2025-11-25';const record=kind=>fs.appendFileSync(audit,JSON.stringify({kind,ordinal,protocol})+'\n');const send=value=>process.stdout.write(JSON.stringify({jsonrpc:'2.0',...value})+'\n');record('started');let initialized=false,ack=false,listed=false,called=false;const tool={name:'fixture.write_file',description:'Explicit bespoke fixture performs real append despite untrusted readOnlyHint',inputSchema:{type:'object',properties:{path:{type:'string',const:'effect.txt'},body:{type:'string',const:EFFECT},decimal:{type:'number'}},required:['path','body','decimal'],additionalProperties:false},outputSchema:{type:'object',properties:{bytes:{type:'integer',minimum:1}},required:['bytes'],additionalProperties:false},annotations:{readOnlyHint:true}};
 for await(const line of createInterface({input:process.stdin})){const request=JSON.parse(line);assert.equal(request.jsonrpc,'2.0');if(request.method==='server/discover'){send({id:request.id,error:{code:-32601,message:'Explicit legacy fixture'}});}else if(request.method==='initialize'){assert.equal(initialized,false);assert.equal(request.params.protocolVersion,'2025-11-25');initialized=true;record('initialize');send({id:request.id,result:{protocolVersion:protocol,capabilities:{tools:{}},serverInfo:{name:'explicit-dynamic-coding-fixture',version:'synthetic'}}});}else if(request.method==='notifications/initialized'){assert.ok(initialized&&!ack);ack=true;record('initialized');}else if(request.method==='tools/list'){assert.ok(ack&&!listed);listed=true;record('listed');send({id:request.id,result:{tools:[tool]}});}else if(request.method==='tools/call'){assert.ok(ack&&listed&&!called);called=true;assert.equal(ordinal,2,'Only fresh coding child may dispatch the effect');assert.ok(mode==='success'||mode==='lost-reply');assert.equal(request.params.name,tool.name);assert.equal(request.params._meta,undefined);assert.deepEqual(Object.keys(request.params.arguments).sort(),['body','decimal','path']);assert.equal(request.params.arguments.path,'effect.txt');assert.equal(request.params.arguments.body,EFFECT);assert.ok(line.includes('1.00000000000000000001'));assert.ok(line.includes('"pa\\u0074h"'));record('called');fs.appendFileSync(join(workspace,'effect.txt'),request.params.arguments.body);if(mode==='lost-reply')process.exit(0);send({id:request.id,result:{content:[{type:'text',text:'Explicit acknowledgement after actual file append'}],structuredContent:{bytes:Buffer.byteLength(EFFECT)}}});}else throw Error('Unexpected actual MCP fixture method');}record('closed');}
const event=value=>'event: '+value.type+'\ndata: '+JSON.stringify(value)+'\n\n';
function responseWire(owner,mode,count,input,output,name,call,raw,text){const signature='synthetic-'+mode+'-'+owner+'-'+count;let wire=event({type:'message_start',message:{id:'synthetic-dynamic-mcp-message',type:'message',role:'assistant',model:'synthetic-dynamic-mcp',content:[],stop_reason:null,stop_sequence:null,usage:{input_tokens:input,output_tokens:0}}})+event({type:'content_block_start',index:0,content_block:{type:'thinking',thinking:'',signature:''}})+event({type:'content_block_delta',index:0,delta:{type:'thinking_delta',thinking:'Explicit synthetic independent '+owner+' reasoning'}})+event({type:'content_block_delta',index:0,delta:{type:'signature_delta',signature}})+event({type:'content_block_stop',index:0});
 if(name){const half=Math.floor(raw.length/2);wire+=event({type:'content_block_start',index:1,content_block:{type:'tool_use',id:call,name,input:{}}})+event({type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:raw.slice(0,half)}})+event({type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:raw.slice(half)}})+event({type:'content_block_stop',index:1});}else wire+=event({type:'content_block_start',index:1,content_block:{type:'text',text:''}})+event({type:'content_block_delta',index:1,delta:{type:'text_delta',text}})+event({type:'content_block_stop',index:1});return wire+event({type:'message_delta',delta:{stop_reason:name?'tool_use':'end_turn',stop_sequence:null},usage:{output_tokens:output}})+event({type:'message_stop'});}
async function wrapper(){const [executable,modules,stdlib]=process.argv.slice(2);assert.ok(executable&&modules&&stdlib);const root=await mkdtemp(join(tmpdir(),'xmind-dynamic-mcp-'));const requests=[],counts=new Map(),aliases=new Map();let failure,succeeded=false;const reads=['read_repository_instructions','read_file','list_files','search_files'];const peer=createServer((request,response)=>{const chunks=[];let size=0;request.on('data',bytes=>{size+=bytes.length;if(size>1024*1024)request.destroy();else chunks.push(bytes);});request.on('end',()=>{try{const match=/^\/(success|denied|protocol-drift|cancel|lost-reply)\/messages$/.exec(request.url);assert.ok(match);const mode=match[1];assert.equal(request.method,'POST');assert.equal(request.headers['x-api-key'],PROVIDER_KEY);assert.equal(request.headers.authorization,undefined);const rawBody=Buffer.concat(chunks).toString('utf8');assert.ok(!rawBody.includes(PROVIDER_KEY)&&!rawBody.includes(CONNECTOR_KEY));const body=JSON.parse(rawBody);assert.equal(body.model,'synthetic-dynamic-mcp');assert.equal(body.stream,true);const names=body.tools.map(tool=>tool.name).sort(),parent=names.includes('plan_tasks'),mcp=names.filter(name=>/^mcp_[a-f0-9]{48}$/.test(name)),owner=parent?'parent':mcp.length?'coding':'verify';const key=mode+'/'+owner,count=(counts.get(key)??0)+1;counts.set(key,count);requests.push({mode,owner,count});assert.ok(count<=2,'No owner may retry the synthetic provider');const toolResults=body.messages.flatMap(message=>message.content??[]).filter(block=>block.type==='tool_result'),last=toolResults.at(-1);const thinking=body.messages.filter(message=>message.role==='assistant').flatMap(message=>message.content??[]).filter(block=>block.type==='thinking');for(const receipt of thinking)assert.ok(receipt.signature.startsWith('synthetic-'+mode+'-'+owner+'-'),'Signed provider continuation belongs only to its actual owner');let wire;
 if(parent){assert.equal(mcp.length,1);assert.deepEqual(names,[...reads,mcp[0],'plan_tasks','revise_plan','inspect_plan'].sort());if(count===1){assert.equal(last,undefined);aliases.set(mode,mcp[0]);const nodes=[{id:'write',type:'agent',preset:'workspace.coding',objective:'Explicit synthetic coding fixture: use the offered MCP alias to append exactly the requested fixture bytes.',depends_on:[]}];if(mode==='success'||mode==='lost-reply')nodes.push({id:'verify',type:'agent',preset:'workspace.inspect',objective:'Read effect.txt using the native read_file tool and report the actual bytes, independently of peer acknowledgement.',depends_on:[{task:'write',require:'success'}]});wire=responseWire(owner,mode,count,17,6,'plan_tasks',mode+'-plan-origin',JSON.stringify({expected_revision:0,expected_state_sequence:0,add:nodes}));}else{assert.ok(['success','denied','protocol-drift'].includes(mode),'Cancellation/uncertainty cannot dispatch a parent continuation');assert.equal(mcp[0],aliases.get(mode),'Parent catalogue refetch remains exact');assert.equal(last.tool_use_id,mode+'-plan-origin');const report=JSON.parse(last.content);assert.equal(report.finished,true);const coding=report.nodes.find(node=>node.id==='write');assert.equal(coding.child_state,mode==='protocol-drift'?'failed':'completed');assert.equal(coding.effect_state,mode==='success'?'succeeded':mode==='denied'?'cancelled':'none');if(mode==='success')assert.equal(report.nodes.find(node=>node.id==='verify').child_state,'completed');wire=responseWire(owner,mode,count,19,7,undefined,undefined,undefined,'Explicit synthetic parent observed the actual native '+mode+' results.');}}
 else if(owner==='coding'){assert.notEqual(mode,'protocol-drift','Same alias with changed private protocol binding rejects before child provider');assert.equal(mcp.length,1);assert.equal(mcp[0],aliases.get(mode));assert.deepEqual(names,[...reads,mcp[0]].sort());if(count===1){assert.equal(last,undefined);wire=responseWire(owner,mode,count,11,4,mcp[0],mode+'-mcp-origin',RAW_ARGUMENTS);}else{assert.ok(mode==='success'||mode==='denied');assert.equal(last.tool_use_id,mode+'-mcp-origin');const output=JSON.parse(last.content);if(mode==='success'){assert.equal(output.acknowledged_by_peer,true);assert.equal(output.independently_verified,false);assert.equal(JSON.parse(output.response_json).result.structuredContent.bytes,Buffer.byteLength(EFFECT));}else assert.equal(output.error.code,'permission_denied');wire=responseWire(owner,mode,count,13,5,undefined,undefined,undefined,mode==='success'?'Actual peer acknowledged its append; separate native read is still required.':'Actual native controller denied this effect; no peer dispatch occurred.');}}
 else{assert.equal(mode,'success','Uncertain or denied work cannot be presented as an independently verified write');assert.deepEqual(names,[...reads].sort(),'Read-only inspector has exactly four native reads, no MCP or orchestration');if(count===1){assert.equal(last,undefined);wire=responseWire(owner,mode,count,7,2,'read_file','native-verification-origin','{"path":"effect.txt"}');}else{assert.equal(last.tool_use_id,'native-verification-origin');assert.equal(JSON.parse(last.content).content,EFFECT);wire=responseWire(owner,mode,count,9,3,undefined,undefined,undefined,'Independent native read observed the actual file bytes.');}}
 response.writeHead(200,{'Content-Type':'text/event-stream'});const bytes=Buffer.from(wire);for(let offset=0;offset<bytes.length;offset+=13)response.write(bytes.subarray(offset,offset+13));response.end();}catch(error){failure??=error;response.destroy();}});});await new Promise(resolve=>peer.listen(0,'127.0.0.1',resolve));
 try{const result=await runNative(root,executable,[root,process.execPath,fileURLToPath(import.meta.url),modules,stdlib,'http://127.0.0.1:'+peer.address().port]);if(failure)throw failure;assert.deepEqual(Object.fromEntries(counts),{'success/parent':2,'success/coding':2,'success/verify':2,'denied/parent':2,'denied/coding':2,'protocol-drift/parent':2,'cancel/parent':1,'cancel/coding':1,'lost-reply/parent':1,'lost-reply/coding':1});assert.equal(requests.length,16);const discoveries={success:3,denied:3,'protocol-drift':3,cancel:2,'lost-reply':2};let calls=0,totalPeers=0;for(const mode of modes){const workspace=join(root,mode),audit=fs.readFileSync(join(workspace,'mcp-audit.jsonl'),'utf8').split('\n').filter(Boolean).map(line=>JSON.parse(line));for(const kind of ['started','initialize','initialized','listed'])assert.equal(audit.filter(item=>item.kind===kind).length,discoveries[mode],mode+': exact actual discovery/handshake count');const actualCalls=audit.filter(item=>item.kind==='called').length;assert.equal(actualCalls,mode==='success'||mode==='lost-reply'?1:0);calls+=actualCalls;totalPeers+=discoveries[mode];if(actualCalls)assert.equal(fs.readFileSync(join(workspace,'effect.txt'),'utf8'),EFFECT);else assert.equal(fs.existsSync(join(workspace,'effect.txt')),false);if(mode==='protocol-drift')assert.deepEqual(audit.filter(item=>item.kind==='listed').map(item=>item.protocol),['2025-11-25','2025-06-18','2025-11-25'],'Only fresh coding child protocol drifts; same alias/descriptors and parent refetch remain exact');}assert.equal(calls,2);assert.equal(totalPeers,13);process.stdout.write(result.stdout);succeeded=true;}catch(error){fs.writeFileSync(join(root,'peer-contract-failure-private.log'),String((failure??error)?.stack??'Unknown fixture failure')+'\n'+String(error.stdout??'')+'\n'+String(error.stderr??''),{flag:'wx',mode:0o600});process.stderr.write('Dynamic MCP fixture failed; disposable diagnostic files retained at '+root+'\n');throw Error('Explicit synthetic dynamic MCP fixture failed; private diagnostic files retained.');}finally{await new Promise(resolve=>peer.close(resolve));assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-dynamic-mcp-'));if(succeeded)await rm(root,{recursive:true,force:true});}}
try{if(process.argv[2]==='--mcp')await mcpPeer();else await wrapper();}catch(error){if(process.argv[2]==='--mcp')try{privatePeerFailure(error);}catch{}process.stderr.write('Explicit synthetic dynamic MCP peer/contract failed; no raw values printed.\n');process.exitCode=1;}
