#include "agentflow/gemini_history.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
#include <stdexcept>
using namespace agentflow;using Json=nlohmann::json;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void request_rejects(F action){try{action();}catch(const std::invalid_argument&){return;}throw std::runtime_error("Expected Gemini request/history rejection");}
template<class F>void protocol_rejects(F action){try{action();}catch(const ModelProtocolError&){return;}throw std::runtime_error("Expected Gemini completion rejection");}
template<class F>void incompatible(F action){try{action();}catch(const IncompatibleProviderHistory&){return;}throw std::runtime_error("Expected incompatible provider history");}
GeminiCompletion decode(const std::string& parts,const std::string& reason="STOP",const std::string& usage="null"){
    std::string wire="data: {\"candidates\":[{\"content\":{\"role\":\"model\",\"parts\":"+parts+"},\"finishReason\":\""+reason+"\"}],\"modelVersion\":\"synthetic-gemini\",\"responseId\":\"synthetic-response\"";
    if(usage!="null")wire+=",\"usageMetadata\":"+usage;wire+="}\n\n";GeminiStream stream([](const auto&){});stream.feed(wire);return stream.finish();
}
// Reproduce the actual AgentRunner persistence shape: structured provider items
// are parsed and dumped while tool argument payloads stay string-valued.
ModelMessage persist(const ModelCompletion& completion){
    Json stored={{"content",completion.content},{"provider_items",Json::parse(completion.provider_items_json)},{"tool_calls",Json::array()}};
    for(const auto& call:completion.tool_calls)stored["tool_calls"].push_back({{"id",call.id},{"name",call.name},{"arguments",call.arguments_json}});
    const auto loaded=Json::parse(stored.dump());ModelMessage result;result.role=MessageRole::assistant;result.content=loaded["content"].get<std::string>();result.provider_items_json=loaded["provider_items"].dump();
    for(const auto& call:loaded["tool_calls"])result.tool_calls.push_back({call["id"].get<std::string>(),call["name"].get<std::string>(),call["arguments"].get<std::string>()});return result;
}
ModelMessage output(const std::string& id,const std::string& text){ModelMessage result;result.role=MessageRole::tool;result.tool_call_id=id;result.content=text;return result;}
ModelRequest conversation(const ModelMessage& assistant){ModelRequest request;request.messages={{MessageRole::user,"Synthetic task"},assistant};return request;}
void replace_receipt(ModelMessage& message,const std::function<void(Json&)>& mutation){auto items=Json::parse(message.provider_items_json);mutation(items[0]);message.provider_items_json=items.dump();}
}
int main(){try{
    const std::string precise=R"({"n":1.2345678901234567890123456789,"large":18446744073709551615,"nested":[{"value":"brace } and escaped \""}]})";
    const std::string metadata=R"({"weight":1.2345678901234567890123456789,"nested":{"large":18446744073709551615}})";
    const std::string parts=std::string(R"([{"text":"Synthetic hidden thought","thought":true,"thoughtSignature":"aGlkZGVu"},{"text":"Visible 雪 ","thought":false,"partMetadata":)")+metadata+R"(},{"thoughtSignature":"dGFpbA==","thought":false,"partMetadata":{"n":1.2345678901234567890123456789}},{"text":"","thoughtSignature":"ZW1wdHk="},{"functionCall":{"name":"same_tool","ar\u0067s":)"+precise+R"(},"thoughtSignature":"Y2FsbA=="},{"functionCall":{"name":"same_tool"},"thought":true},{"functionCall":{"name":"with_id","id":"provider-real-id","args":{"other":2}}},{"text":""}])";
    const auto raw=decode(parts,"STOP",R"({"promptTokenCount":12,"candidatesTokenCount":3,"totalTokenCount":77,"cachedContentTokenCount":2,"thoughtsTokenCount":4,"toolUsePromptTokenCount":1})");
    int allocated=0;auto factory=[&]{return "native-call-"+std::to_string(++allocated);};const auto completed=gemini_model_completion(raw,factory);
    require(allocated==3&&completed.content=="Visible 雪 "&&completed.finish_reason=="tool_calls"&&completed.refusal.empty(),"Native IDs must come from the factory and hidden text must remain outside visible content");
    require(completed.tool_calls.size()==3&&completed.tool_calls[0].arguments_json==precise&&completed.tool_calls[1].arguments_json=="{}"&&completed.tool_calls[2].id=="native-call-3","Tool execution requires exact supplied arguments and separate internal identities");
    const auto saved=Json::parse(completed.provider_items_json);require(saved.size()==1&&saved[0]["type"]=="gemini_content"&&saved[0]["parts_json"].is_string()&&saved[0]["parts_json"]==parts,"Provider parts must be stored as an exact raw JSON string");
    require(saved[0]["bindings"][0]["part_index"]==4&&saved[0]["bindings"][1]["part_index"]==5&&saved[0]["bindings"][2]["part_index"]==6&&saved[0]["model_version"]=="synthetic-gemini","Receipt bindings must use original part indexes and retain supplied metadata");
    const auto usage=Json::parse(completed.usage_json);require(usage["prompt_tokens"]==12&&usage["completion_tokens"]==3&&usage["total_tokens"]==77&&usage["prompt_tokens_details"]["cached_tokens"]==2&&usage["completion_tokens_details"]["reasoning_tokens"]==4&&usage["toolUsePromptTokenCount"]==1&&gemini_model_usage(raw.usage_json)==completed.usage_json,"Only supplied actual counts map to the same completion/event usage, including the provider's supplied total");
    auto assistant=persist(completed);require(Json::parse(assistant.provider_items_json)[0]["parts_json"]==parts&&assistant.tool_calls[0].arguments_json==precise,"AgentRunner-shaped JSON parse/dump must not round replay argument or metadata numbers");
    ModelRequest request;request.include_usage=true;request.max_output_tokens=256;request.tools={{"same_tool","Synthetic tool","{}"},{"with_id","Synthetic identified tool","{}"}};
    request.messages={{MessageRole::system,"Synthetic first instruction"},{MessageRole::system,"Synthetic second instruction"},{MessageRole::user,"Synthetic task"},assistant,
        output("native-call-3","third result"),output("native-call-2",R"({"number":1.2345678901234567890123456789})"),output("native-call-1","first result")};
    const auto replay=gemini_model_request(request,Capability::supported);require(replay.contents.size()==3&&replay.system_instructions.size()==2&&replay.max_output_tokens==256&&replay.tools.size()==2,"Native request fields must reach the dedicated Gemini fields");
    const auto& model=replay.contents[1].parts;require(model.size()==8&&model[0].thought==true&&model[1].thought==false&&!model[3].thought&&model[2].kind==GeminiPartKind::signature&&model[3].text.empty()&&model[7].text.empty(),"Part kinds, signed/unsigned empty text, boundaries and thought optionality must replay exactly");
    require(model[1].part_metadata_json==metadata&&model[4].object_json==precise&&!model[4].call_id&&model[5].arguments_omitted&&model[6].call_id=="provider-real-id","Raw metadata, arguments, omitted args and optional provider IDs must remain unchanged");
    const auto encoded=serialize_gemini_request(replay);const auto body=Json::parse(encoded);const auto& wire_model=body["contents"][1]["parts"];const auto& responses=body["contents"][2]["parts"];
    require(encoded.find(precise)!=std::string::npos&&encoded.find(metadata)!=std::string::npos&&encoded.find("native-call-")==std::string::npos,"Native internal IDs cannot become provider IDs and raw numeric tokens cannot be rewritten");
    require(!wire_model[4]["functionCall"].contains("id")&&!wire_model[5]["functionCall"].contains("id")&&!wire_model[5]["functionCall"].contains("args")&&wire_model[6]["functionCall"]["id"]=="provider-real-id","Replay must never invent missing provider identity or arguments");
    require(responses.size()==3&&responses[0]["functionResponse"]["response"]["output"]=="first result"&&responses[1]["functionResponse"]["response"]["output"].is_string()&&responses[1]["functionResponse"]["response"]["output"]==request.messages[5].content&&responses[2]["functionResponse"]["response"]["output"]=="third result","Out-of-order same-name anonymous results must be replayed in original call order with string outputs");
    require(!responses[0]["functionResponse"].contains("id")&&!responses[1]["functionResponse"].contains("id")&&responses[2]["functionResponse"]["id"]=="provider-real-id","Result correlation must preserve provider ID presence independently from native result arrival order");

    // WorkspaceTools::invoke(read_file) returns a JSON string with path/content;
    // AgentRunner then places that entire string in a native tool message. A
    // near-limit text file with quote bytes expands again when Gemini wraps it.
    const std::string escaped_file(1024*1024-64,'"');const auto native_read_result=Json{{"path","fixture-escaped.txt"},{"content",escaped_file}}.dump();
    auto read_completion=gemini_model_completion(decode(R"([{"functionCall":{"name":"read_file","args":{"path":"fixture-escaped.txt"}},"thoughtSignature":"cmVhZA=="}])"),[]{return "native-read-call";});auto read_request=conversation(persist(read_completion));read_request.messages.push_back(output("native-read-call",native_read_result));read_request.tools={{"read_file","Synthetic native-shaped read result","{}"}};
    const auto read_replay=gemini_model_request(read_request,Capability::supported);require(read_replay.contents[2].parts[0].object_json.size()>1024*1024,"Escaped native read-result fixture must exercise the former response object limit");const auto read_body=Json::parse(serialize_gemini_request(read_replay));const auto& read_response=read_body["contents"][2]["parts"][0]["functionResponse"]["response"]["output"];
    require(read_response.is_string()&&read_response==native_read_result&&Json::parse(read_response.get<std::string>())["content"]==escaped_file,"Near-limit escaped read output must survive native history wrapping and continuation without parsing its string into provider data");

    auto partial=decode(R"([{"text":"Real supplied fixture"}])","STOP",R"({"promptTokenCount":0})");auto only_input=gemini_model_completion(partial,{});auto partial_usage=Json::parse(only_input.usage_json);require(partial_usage["prompt_tokens"]==0&&!partial_usage.contains("completion_tokens")&&!partial_usage.contains("total_tokens")&&!partial_usage.contains("prompt_tokens_details"),"Unknown output, total and details must remain absent while a supplied zero is retained");
    partial.usage_json="null";require(gemini_model_completion(partial,{}).usage_json=="null","Missing usage cannot become fabricated zeros");partial.usage_json="{}";require(gemini_model_completion(partial,{}).usage_json=="null","Empty supplied usage object contains no known counts");
    partial.usage_json=R"({"cachedContentTokenCount":2,"thoughtsTokenCount":3})";partial_usage=Json::parse(gemini_model_completion(partial,{}).usage_json);require(!partial_usage.contains("prompt_tokens")&&!partial_usage.contains("completion_tokens")&&!partial_usage.contains("total_tokens")&&partial_usage["output_tokens_details"]["reasoning_tokens"]==3,"Details cannot imply unknown top-level counters");
    auto empty=decode("[]","STOP",R"({"totalTokenCount":5})");int empty_allocations=0;const auto empty_native=gemini_model_completion(empty,[&]{++empty_allocations;return "unused";});auto empty_request=conversation(persist(empty_native));const auto empty_replay=gemini_model_request(empty_request,Capability::supported);
    require(empty_native.content.empty()&&empty_native.tool_calls.empty()&&empty_allocations==0&&Json::parse(empty_native.usage_json)["total_tokens"]==5&&Json::parse(empty_native.provider_items_json)[0]["parts_json"]=="[]"&&empty_replay.contents.size()==1,"Empty natural STOP must persist real usage/receipt while replay omits only absent model content");
    Json fragmented_parts=Json::array();for(int index=0;index<129;++index)fragmented_parts.push_back({{"text","x"}});const auto fragmented=gemini_model_completion(decode(fragmented_parts.dump()),{});const auto fragmented_replay=gemini_model_request(conversation(persist(fragmented)),Capability::unknown);require(fragmented.content==std::string(129,'x')&&fragmented_replay.contents[1].parts.size()==129,"Many streamed model part boundaries must survive native persistence and request replay");
    auto limited=decode(R"([{"functionCall":{"name":"same_tool","args":{}}}])","MAX_TOKENS");int limited_allocations=0;auto truncated=gemini_model_completion(limited,[&]{++limited_allocations;return "unused";});require(truncated.finish_reason=="length"&&truncated.tool_calls.empty()&&limited_allocations==0&&Json::parse(truncated.provider_items_json)[0]["bindings"].empty(),"Truncation cannot expose executable tools or allocate identities");incompatible([&]{gemini_model_request(conversation(persist(truncated)),Capability::supported);});

    auto corrupted=raw;corrupted.content="Modified visible text";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.function_calls[0].arguments_json="{}";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.function_calls[2].id="different-provider-id";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.function_calls[0].name="different_tool";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.finish_reason="stop";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.provider_finish_reason="SAFETY";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});
    protocol_rejects([&]{gemini_model_completion(raw,{});});protocol_rejects([&]{gemini_model_completion(raw,[]{return "duplicate";});});protocol_rejects([&]{gemini_model_completion(raw,[]{return "invalid\nidentity";});});protocol_rejects([&]{gemini_model_completion(raw,[]{throw std::runtime_error("private factory detail");return std::string{};});});
    for(const auto& invalid_usage:{R"({"promptTokenCount":-1})",R"({"totalTokenCount":9007199254740992})",R"({"candidatesTokenCount":1.5})",R"({"thoughtsTokenCount":true})",R"({"promptTokenCount":1,"promptTokenCount":2})",R"({"invented_total":2})"}){corrupted=raw;corrupted.usage_json=invalid_usage;protocol_rejects([&]{gemini_model_completion(corrupted,factory);});}
    for(const auto& invalid_parts:{R"([{"text":"x","text":"x"}])",R"([{"thoughtSignature":""}])",R"([{"thought":"false","text":"x"}])",R"([{"partMetadata":{}}])",R"([{"inlineData":{"data":"unsupported"}}])",R"([{"text":"x","functionCall":{"name":"same_tool"}}])",R"([{"functionCall":{"name":"same_tool","args":[]}}])",R"([{"functionCall":{"name":"same_tool","args":{"x":1,"x":2}}}])"}){corrupted=raw;corrupted.parts_json=invalid_parts;protocol_rejects([&]{gemini_model_completion(corrupted,factory);});}
    corrupted=raw;corrupted.parts_json=std::string(8*1024*1024+1,' ');protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.parts_json=std::string("[{\"text\":\"")+char(0xff)+"\"}]";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});
    std::string deep="{}";for(int depth=0;depth<17;++depth)deep="{\"nested\":"+deep+"}";corrupted=raw;corrupted.parts_json="[{\"functionCall\":{\"name\":\"same_tool\",\"args\":"+deep+"}}]";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});corrupted=raw;corrupted.parts_json="[{\"text\":\"x\",\"partMetadata\":"+deep+"}]";protocol_rejects([&]{gemini_model_completion(corrupted,factory);});

    auto bad=request;bad.messages[3].content="Modified visible text";incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[3].tool_calls[0].id="wrong-native-id";incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[3].tool_calls[0].arguments_json="{}";incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[3].tool_calls[0].name="wrong_name";incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[3].provider_items_json="[]";incompatible([&]{gemini_model_request(bad,Capability::supported);});
    for(const auto& mutation:std::vector<std::function<void(Json&)>>{
        [](Json& item){item["type"]="function_call";},[](Json& item){item["bindings"][0]["part_index"]=5;},[](Json& item){item["bindings"][1]["tool_call_id"]="native-call-1";},[](Json& item){item["bindings"].erase(0);},[](Json& item){item["bindings"][0]["secret"]="unexpected";},[](Json& item){item["extra"]="unexpected";},[](Json& item){item["parts_json"]=Json::array();},[](Json& item){item["parts_json"]=R"([{"text":"x","text":"x"}])";},[](Json& item){item["provider_finish_reason"]="MAX_TOKENS";}}){bad=request;replace_receipt(bad.messages[3],mutation);incompatible([&]{gemini_model_request(bad,Capability::supported);});}
    bad=request;bad.messages[3].provider_items_json=R"([{"type":"gemini_content","type":"gemini_content"}])";incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[2].provider_items_json=assistant.provider_items_json;incompatible([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[4].provider_items_json=assistant.provider_items_json;incompatible([&]{gemini_model_request(bad,Capability::supported);});
    bad=request;bad.messages.pop_back();request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[6].tool_call_id="native-call-2";request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[4].tool_call_id="unknown-call";request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[5].role=MessageRole::user;request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages.push_back(output("native-call-1","orphan result"));request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[4].tool_calls=assistant.tool_calls;request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[3].refusal="unsupported refusal";request_rejects([&]{gemini_model_request(bad,Capability::supported);});
    bad=request;bad.messages[0].role=MessageRole::developer;request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages.push_back({MessageRole::system,"late instruction"});request_rejects([&]{gemini_model_request(bad,Capability::supported);});bad=request;bad.messages[2].tool_call_id="misplaced";request_rejects([&]{gemini_model_request(bad,Capability::supported);});request_rejects([&]{gemini_model_request(request,Capability::unknown);});request_rejects([&]{gemini_model_request(request,Capability::unsupported);});
    auto repeated=request;repeated.messages.insert(repeated.messages.end(),request.messages.begin()+3,request.messages.end());incompatible([&]{gemini_model_request(repeated,Capability::supported);});
    ModelRequest legacy;legacy.messages={{MessageRole::system,"Synthetic instruction"},{MessageRole::user,"Synthetic question"},{MessageRole::assistant,"Ordinary legacy text"},{MessageRole::user,"Synthetic continuation"}};require(gemini_model_request(legacy,Capability::unknown).contents.size()==3,"Plain legacy text without provider items remains ordinary model content");
    bool redacted=false;try{auto private_failure=raw;private_failure.parts_json=R"([{"private_provider_detail":"never reflect this"}])";gemini_model_completion(private_failure,factory);}catch(const ModelProtocolError& e){redacted=std::string(e.what()).find("never reflect this")==std::string::npos;}require(redacted,"Bridge diagnostics cannot echo raw provider/history data");
    std::cout<<"Native Gemini history bridge passed synthetic precise signed parts, AgentRunner-shaped parse/dump replay, native/provider identity separation, out-of-order anonymous results, supplied usage, empty STOP, truncation and malformed/corrupt/foreign history checks. No agent execution, live model inference or enrollment tested.\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
