#include "agentflow/gemini_request.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
#include <stdexcept>
using namespace agentflow;using Json=nlohmann::json;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F action){try{action();}catch(const std::invalid_argument&){return;}throw std::runtime_error("Expected Gemini request rejection");}
GeminiPart text(std::string value){GeminiPart part;part.text=std::move(value);return part;}
GeminiPart function(GeminiPartKind kind,std::string name,std::string payload,std::optional<std::string> id={}){GeminiPart part;part.kind=kind;part.name=std::move(name);part.object_json=std::move(payload);part.call_id=std::move(id);return part;}
}
int main(){try{
    GeminiRequest request;request.system_instructions={"Synthetic backend instruction"};request.contents={{GeminiRole::user,{text("Synthetic Unicode: 雪 and \"quoted\" text")}}};
    auto body=Json::parse(serialize_gemini_request(request));require(body.at("contents")[0].at("role")=="user"&&body.at("contents")[0].at("parts")[0].at("text")==request.contents[0].parts[0].text,"Gemini caller text must survive native serialization");require(body.at("systemInstruction").at("parts")[0].at("text")==request.system_instructions[0],"System instructions require their dedicated field");require(!body.contains("model")&&!body.contains("stream")&&!body.contains("generationConfig")&&!body.contains("tools"),"Unrequested fields and transport configuration must remain absent");
    request.max_output_tokens=64;body=Json::parse(serialize_gemini_request(request));require(body.at("generationConfig").at("maxOutputTokens")==64,"Explicit output limit must survive");request.max_output_tokens=0;rejects([&]{serialize_gemini_request(request);});request.max_output_tokens.reset();
    request.tools={{"read_file","Synthetic declared tool",R"({"type":"object","properties":{"path":{"type":"string"}},"required":["path"]})"}};rejects([&]{serialize_gemini_request(request);});request.function_calls=Capability::supported;body=Json::parse(serialize_gemini_request(request));require(body.at("tools")[0].at("functionDeclarations")[0].contains("parametersJsonSchema"),"Gemini declarations must use the JSON Schema field");
    const auto precise=R"({"n":1.2345678901234567890123456789,"large":18446744073709551615})";
    auto first=function(GeminiPartKind::function_call,"read_file",precise,"provider-call-1");first.thought_signature="c3ludGhldGljLXNpZ25hdHVyZQ==";
    request.contents.push_back({GeminiRole::model,{first,function(GeminiPartKind::function_call,"read_file",R"({"path":"second.txt"})","provider-call-2")}});
    request.contents.push_back({GeminiRole::user,{function(GeminiPartKind::function_response,"read_file",R"({"content":"second fixture"})","provider-call-2"),function(GeminiPartKind::function_response,"read_file",R"({"content":"first fixture"})","provider-call-1")}});
    const auto encoded=serialize_gemini_request(request);body=Json::parse(encoded);require(encoded.find(precise)!=std::string::npos,"Function numeric tokens must not be rounded or rewritten");require(body.at("contents")[1].at("parts")[0].at("thoughtSignature")==*first.thought_signature,"Opaque signature must replay exactly");require(body.at("contents")[2].at("parts")[0].at("functionResponse").at("id")=="provider-call-2","Out-of-order identified results must retain provider correlation");
    auto invalid=request;invalid.contents[2].parts.pop_back();rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[2].parts[0].name="different_function";rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[1].parts[1].call_id="provider-call-1";rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[1].parts[0].object_json=R"({"n":1,"n":2})";rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[1].parts[0].object_json="[]";rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[2].parts[0].thought_signature="invalid-user-signature";rejects([&]{serialize_gemini_request(invalid);});
    GeminiRequest anonymous;anonymous.function_calls=Capability::supported;anonymous.contents={{GeminiRole::user,{text("Synthetic task")}},{GeminiRole::model,{function(GeminiPartKind::function_call,"read_file","{}")}}, {GeminiRole::user,{function(GeminiPartKind::function_response,"read_file",R"({"ok":true})")}}};body=Json::parse(serialize_gemini_request(anonymous));require(!body.at("contents")[1].at("parts")[0].at("functionCall").contains("id")&&!body.at("contents")[2].at("parts")[0].at("functionResponse").contains("id"),"Absent provider IDs cannot be invented");
    invalid=request;invalid.tools.push_back(invalid.tools.front());rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[0].role=static_cast<GeminiRole>(999);rejects([&]{serialize_gemini_request(invalid);});invalid=request;invalid.contents[0].parts[0].text=std::string(4*1024*1024+1,'x');rejects([&]{serialize_gemini_request(invalid);});
    std::cout<<"Native Gemini body component passed synthetic text/system/schema/function correlation, exact numeric/signature replay and malformed/unsupported request rejection. No provider transport, stream or live model acceptance tested.\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
