#include "agentflow/gemini_stream.hpp"
#include "nlohmann/json.hpp"
#include <algorithm>
#include <iostream>
using namespace agentflow;using Json=nlohmann::json;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
std::string frame(const std::string& json){return "data: "+json+"\n\n";}
std::string chunk(const Json& parts,const std::string& reason=""){Json candidate={{"index",0},{"content",{{"role","model"},{"parts",parts}}}};if(!reason.empty())candidate["finishReason"]=reason;return frame(Json{{"candidates",Json::array({candidate})},{"modelVersion","fixture-gemini"},{"responseId","fixture-response"}}.dump());}
void rejects(const std::string& wire){bool failed=false;int done=0;GeminiStream decoder([&](const auto& e){if(e.kind=="model.done")++done;});try{decoder.feed(wire);decoder.finish();}catch(const ModelProtocolError&){failed=true;}require(failed&&done==0,"Invalid Gemini stream cannot acknowledge completion");}
}
int main(){try{
    const auto wire=chunk(Json::array({{{"text","Unicode 雪 "},{"thought",false}}}))+chunk(Json::array({{{"text","answer"},{"thoughtSignature","c3ludGhldGlj"}}}),"STOP");
    for(std::size_t width:{1,2,7,31,4096}){std::vector<ModelEvent> events;GeminiStream decoder([&](const auto& e){events.push_back(e);});for(std::size_t offset=0;offset<wire.size();offset+=width)decoder.feed(std::string_view(wire).substr(offset,width));require(std::none_of(events.begin(),events.end(),[](const auto& e){return e.kind=="model.done";}),"Gemini completion requires validated EOF");const auto result=decoder.finish();decoder.finish();require(result.content=="Unicode 雪 answer"&&result.finish_reason=="stop"&&result.usage_json=="null"&&result.model_version=="fixture-gemini"&&result.response_id=="fixture-response","Gemini text/identity/unknown usage must remain exact");require(Json::parse(result.parts_json).size()==2&&Json::parse(result.parts_json)[1]["thoughtSignature"]=="c3ludGhldGlj","Signed parts cannot be merged");require(std::count_if(events.begin(),events.end(),[](const auto& e){return e.kind=="model.done";})==1,"Repeated finish cannot repeat acknowledgement");}
    for(std::size_t length=0;length<wire.size();++length)rejects(wire.substr(0,length));
    std::vector<ModelEvent> observed;GeminiStream thoughts([&](const auto& e){observed.push_back(e);});thoughts.feed(chunk(Json::array({{{"text","Synthetic hidden thought"},{"thought",true},{"thoughtSignature","c2ln"}},{{"text","Visible"},{"thought",false}},{{"thoughtSignature","dGFpbA=="}}}),"STOP"));const auto thought=thoughts.finish();require(thought.content=="Visible"&&Json::parse(thought.parts_json).size()==3,"Thought/signature-only parts remain in replay history, outside visible text");for(const auto& e:observed)require(e.json.find("Synthetic hidden thought")==std::string::npos,"Hidden thoughts must not leak into ordinary model events");
    const std::string precise=R"({"n":1.2345678901234567890123456789,"large":18446744073709551615,"nested":[{"quoted":"brace } and escaped \""}]})";
    const auto call=std::string(R"({"candidates":[{"content":{"role":"model","parts":[{"functionCall":{"name":"read_file","id":"provider-id","ar\u0067s":)")+precise+R"(},"thoughtSignature":"c2ln"},{"functionCall":{"name":"read_file"}}]},"finishReason":"STOP"}]})";
    GeminiStream tools([](const auto&){});tools.feed(frame(call));const auto completed=tools.finish();require(completed.finish_reason=="tool_calls"&&completed.function_calls.size()==2&&completed.function_calls[0].id=="provider-id"&&completed.function_calls[0].arguments_json==precise&&!completed.function_calls[1].id&&!completed.function_calls[1].arguments_json,"Calls must preserve exact argument tokens and absent IDs/args");require(completed.parts_json.find(precise)!=std::string::npos,"Original history precision must survive");
    GeminiStream limited([](const auto&){});limited.feed(chunk(Json::array({{{"functionCall",{{"name","read_file"},{"args",Json::object()}}}}}),"MAX_TOKENS"));require(limited.finish().finish_reason=="length"&&limited.finish().function_calls.empty(),"Truncation cannot expose executable calls");
    GeminiStream usage([](const auto&){});usage.feed(frame(R"({"usageMetadata":{"promptTokenCount":12,"candidatesTokenCount":1,"thoughtsTokenCount":2}})")+wire+frame(R"({"usageMetadata":{"candidatesTokenCount":8,"totalTokenCount":99,"cachedContentTokenCount":4}})"));require(Json::parse(usage.finish().usage_json)==Json{{"promptTokenCount",12},{"candidatesTokenCount",8},{"thoughtsTokenCount",2},{"totalTokenCount",99},{"cachedContentTokenCount",4}},"Cumulative supplied usage must retain actual counters without summing or fabricating totals");
    auto crlf=wire;for(std::size_t p=0;(p=crlf.find('\n',p))!=std::string::npos;p+=2)crlf.replace(p,1,"\r\n");GeminiStream bom([](const auto&){});bom.feed(std::string("\xEF\xBB\xBF")+": heartbeat\r\n\r\n"+crlf);require(bom.finish().content=="Unicode 雪 answer","BOM/comments/CRLF must preserve the response");
    rejects(frame(R"({"candidates":[{"finishReason":"STOP"},{"finishReason":"STOP"}]})"));rejects(frame(R"({"candidates":[{"index":1,"finishReason":"STOP"}]})"));rejects(frame(R"({"candidates":[{"finishReason":"SAFETY"}]})"));rejects(wire+wire);rejects(frame(R"({"promptFeedback":{"blockReason":"SAFETY"}})"));rejects(frame(R"({"error":{"message":"private provider error"}})"));rejects(frame(R"({"candidates":[],"candidates":[]})"));rejects(frame(R"({"usageMetadata":{"promptTokenCount":-1}})"));rejects(frame(R"({"usageMetadata":{"promptTokenCount":12}})")+wire+frame(R"({"usageMetadata":{"promptTokenCount":11}})"));rejects(chunk(Json::array({{{"inlineData",{{"data","unsupported media"}}}}}),"STOP"));rejects(chunk(Json::array({{{"text","conflict"},{"functionCall",{{"name","tool"}}}}}),"STOP"));rejects(frame("[DONE]"));rejects("data: "+std::string(1024*1024+1,'x'));
    rejects(wire+frame(R"({"responseId":"different-response"})"));rejects(chunk(Json::array({{{"text","invalid thought flag"},{"thought","true"}}}),"STOP"));rejects(chunk(Json::array({{{"thoughtSignature",""}}}),"STOP"));rejects(chunk(Json::array({{{"functionCall",{{"name","read_file"},{"id","duplicate"}}}},{{"functionCall",{{"name","read_file"},{"id","duplicate"}}}}}),"STOP"));rejects(frame(R"({"candidates":[{"content":{"parts":[{"functionCall":{"name":"read_file","args":{"n":1,"n":2}}}]},"finishReason":"STOP"}]})"));
    GeminiStream unfinished([](const auto&){});unfinished.feed(frame(R"({"candidates":[{"finishReason":"FINISH_REASON_UNSPECIFIED"}]})")+wire);require(unfinished.finish().content=="Unicode 雪 answer","Unspecified reason is an intermediate chunk, not terminal acknowledgement");
    bool redacted=false;GeminiStream error([](const auto&){});try{error.feed(frame(R"({"error":{"message":"private provider error"}})"));}catch(const ModelProtocolError& e){redacted=std::string(e.what()).find("private provider error")==std::string::npos;}require(redacted,"Protocol diagnostics cannot reflect private provider messages");
    Json deep_metadata=Json::object();for(int depth=0;depth<18;++depth)deep_metadata={{"nested",deep_metadata}};rejects(chunk(Json::array({{{"text","Metadata fixture"},{"partMetadata",deep_metadata}}}),"STOP"));
    std::cout<<"Native Gemini SSE component passed synthetic fragmented Unicode, thought/signature history, precise optional function identity/arguments, actual cumulative usage, EOF/truncation and malformed/unsupported lifecycle checks. No transport, agent integration or live inference tested.\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
