#include "agentflow/gemini_provider.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
using namespace agentflow;using Json=nlohmann::json;
namespace {void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}}
int main(int argc,char** argv){if(argc!=2)return 2;try{
    const std::string base=argv[1],token="gemini-wire-fixture-not-a-real-key";SecretBytes secret({reinterpret_cast<const std::uint8_t*>(token.data()),token.size()});
    GeminiProviderConfig config{base+"/v1beta","fixture-gemini"};GeminiRequest request;request.function_calls=Capability::supported;request.system_instructions={"Native fixture instructions"};GeminiPart prompt;prompt.text="Read fixture";request.contents={{GeminiRole::user,{prompt}}};request.tools={{"read_file","Read a file",R"({"type":"object","properties":{"path":{"type":"string"}},"required":["path"]})"}};request.max_output_tokens=64;
    int done=0,finished=0;const auto sink=[&](const ModelEvent& event){if(event.kind=="model.done")++done;if(event.kind=="model.finish")++finished;};
    auto result=complete_gemini(config,request,&secret,sink);require(done==1&&finished==1&&result.finish_reason=="tool_calls"&&result.function_calls.size()==1,"Native Gemini transport must acknowledge only validated offered calls");
    require(result.function_calls[0].id=="provider-call"&&result.function_calls[0].name=="read_file"&&result.function_calls[0].arguments_json==R"({"path":"README","n":1.2345678901234567890123456789})","Gemini transport must preserve exact provider identity/arguments");
    require(Json::parse(result.usage_json)==Json{{"promptTokenCount",8},{"candidatesTokenCount",5}}&&result.model_version=="fixture-gemini","Gemini transport must retain supplied usage and model version");
    GeminiPart call;call.kind=GeminiPartKind::function_call;call.name=result.function_calls[0].name;call.call_id=result.function_calls[0].id;call.object_json=*result.function_calls[0].arguments_json;call.thought_signature=Json::parse(result.parts_json)[0]["thoughtSignature"].get<std::string>();
    GeminiPart response;response.kind=GeminiPartKind::function_response;response.name=call.name;response.call_id=call.call_id;response.object_json=R"({"content":"actual fixture result"})";request.contents.push_back({GeminiRole::model,{call}});request.contents.push_back({GeminiRole::user,{response}});
    config.endpoint_base=base+"/continuation/v1beta";done=finished=0;result=complete_gemini(config,request,&secret,sink);require(done==1&&finished==1&&result.content=="Fixture complete"&&result.function_calls.empty()&&result.finish_reason=="stop","Native Gemini continuation must decode actual peer text");request.contents.resize(1);
    for(const auto* route:{"unknown","incomplete","late-error","blocked"}){config.endpoint_base=base+"/"+route+"/v1beta";done=finished=0;bool rejected=false;try{complete_gemini(config,request,&secret,sink);}catch(const ModelProtocolError&){rejected=true;}require(rejected&&done==0&&finished==0,"Unvalidated/unoffered Gemini turns must not acknowledge completion");}
    for(const auto* route:{"unauthorized","redirect"}){config.endpoint_base=base+"/"+route+"/v1beta";done=finished=0;bool rejected=false;try{complete_gemini(config,request,&secret,sink);}catch(const ProviderHttpError& e){rejected=e.status==(std::string(route)=="redirect"?307:401);}require(rejected&&done==0&&finished==0,"Gemini transport must preserve HTTP status without completion");}
    config.endpoint_base=base+"/must-not-arrive/v1beta";
    for(int mode=0;mode<6;++mode){auto selected=config;auto invalid=request;if(mode==0)invalid.function_calls=Capability::unknown;if(mode==1)selected.model="../different";if(mode==2)selected.endpoint_base+="?key=forbidden-query";if(mode==3)selected.model="models/fixture/other";if(mode==4)selected.deadline=std::chrono::milliseconds(0);bool rejected=false;try{complete_gemini(selected,invalid,mode==5?nullptr:&secret,sink);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"Invalid Gemini binding/capability/credential must fail before wire");}
    std::stop_source cancelled;cancelled.request_stop();bool stopped=false;try{complete_gemini(config,request,&secret,sink,cancelled.get_token());}catch(const TransportCancelled&){stopped=true;}require(stopped,"Cancelled Gemini admission must make no request");
    auto normalized=config;normalized.model="models/fixture-gemini";normalized.endpoint_base+='/';require(gemini_stream_endpoint(normalized)==gemini_stream_endpoint(config),"Optional models prefix/trailing base slash must bind the same resource");
    std::cout<<"Native Gemini request/HTTP/SSE boundary passed against an independent synthetic peer, including exact signed continuation, header-only key, offered-call validation, failure/cancellation and no redirect/retry. No agent enrollment or live inference tested.\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
