#include "agentflow/gemini_provider.hpp"
#include "nlohmann/json.hpp"
#include <iostream>
using namespace agentflow;using Json=nlohmann::json;
namespace {void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}}
int main(int argc,char** argv){if(argc!=2)return 2;try{
    const std::string base=argv[1],token="gemini-wire-fixture-not-a-real-key";SecretBytes secret({reinterpret_cast<const std::uint8_t*>(token.data()),token.size()});
    GeminiProviderConfig config{base+"/v1beta","fixture-gemini"};GeminiRequest request;request.function_calls=Capability::supported;request.system_instructions={"Native fixture instructions"};GeminiPart prompt;prompt.text="Read fixture";request.contents={{GeminiRole::user,{prompt}}};request.tools={{"read_file","Read a file",R"({"type":"object","properties":{"path":{"type":"string"}},"required":["path"]})"}};request.max_output_tokens=64;
    int done=0,finished=0;const auto sink=[&](const ModelEvent& event){if(event.kind=="model.done")++done;if(event.kind=="model.finish")++finished;};
    auto result=complete_gemini(config,request,&secret,sink);require(done==1&&finished==1&&result.finish_reason=="tool_calls"&&result.function_calls.size()==1,"Native Gemini transport must acknowledge only validated offered calls");
    require(result.function_calls[0].id=="provider-call"&&result.function_calls[0].name=="read_file"&&result.function_calls[0].arguments_json==R"({"path":"README","n":1.2345678901234567890123456789})","Gemini transport must preserve exact provider identity/arguments");
    require(Json::parse(result.usage_json)==Json{{"promptTokenCount",8},{"candidatesTokenCount",5}}&&result.model_version=="fixture-gemini","Gemini transport must retain supplied usage and model version");
    GeminiPart call;call.kind=GeminiPartKind::function_call;call.name=result.function_calls[0].name;call.call_id=result.function_calls[0].id;call.object_json=*result.function_calls[0].arguments_json;call.thought_signature=Json::parse(result.parts_json)[0]["thoughtSignature"].get<std::string>();
    GeminiPart response;response.kind=GeminiPartKind::function_response;response.name=call.name;response.call_id=call.call_id;response.object_json=R"({"content":"actual fixture result"})";request.contents.push_back({GeminiRole::model,{call}});request.contents.push_back({GeminiRole::user,{response}});
    config.endpoint_base=base+"/continuation/v1beta";done=finished=0;result=complete_gemini(config,request,&secret,sink);require(done==1&&finished==1&&result.content=="Fixture complete"&&result.function_calls.empty()&&result.finish_reason=="stop","Native Gemini continuation must decode actual peer text");request.contents.resize(1);
    for(const auto* route:{"unknown","incomplete","late-error","blocked"}){config.endpoint_base=base+"/"+route+"/v1beta";done=finished=0;bool rejected=false;try{complete_gemini(config,request,&secret,sink);}catch(const ModelProtocolError&){rejected=true;}require(rejected&&done==0&&finished==0,"Unvalidated/unoffered Gemini turns must not acknowledge completion");}
    for(const auto* route:{"unauthorized","redirect"}){config.endpoint_base=base+"/"+route+"/v1beta";done=finished=0;bool rejected=false;try{complete_gemini(config,request,&secret,sink);}catch(const ProviderHttpError& e){rejected=e.status==(std::string(route)=="redirect"?307:401);}require(rejected&&done==0&&finished==0,"Gemini transport must preserve HTTP status without completion");}
    config.endpoint_base=base+"/must-not-arrive/v1beta";
    for(int mode=0;mode<6;++mode){auto selected=config;auto invalid=request;if(mode==0)invalid.function_calls=Capability::unknown;if(mode==1)selected.model="../different";if(mode==2)selected.endpoint_base+="?key=forbidden-query";if(mode==3)selected.model="models/fixture/other";if(mode==4)selected.deadline=std::chrono::milliseconds(0);bool rejected=false;try{complete_gemini(selected,invalid,mode==5?nullptr:&secret,sink);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"Invalid Gemini binding/capability/credential must fail before wire");}
    std::stop_source cancelled;cancelled.request_stop();bool stopped=false;try{complete_gemini(config,request,&secret,sink,cancelled.get_token());}catch(const TransportCancelled&){stopped=true;}require(stopped,"Cancelled Gemini admission must make no request");
    auto normalized=config;normalized.model="models/fixture-gemini";normalized.endpoint_base+='/';require(gemini_stream_endpoint(normalized)==gemini_stream_endpoint(config),"Optional models prefix/trailing base slash must bind the same resource");
    ChatProviderConfig common_config{base+"/common/v1beta","fixture-gemini",Capability::supported,Capability::supported,Capability::supported};common_config.wire=ProviderWire::gemini_generate_content;
    ModelRequest common{{{MessageRole::system,"Native fixture instructions"},{MessageRole::user,"Read fixture"}},request.tools,true,64};std::vector<ModelEvent> common_events;const auto common_sink=[&](const ModelEvent& event){sink(event);common_events.push_back(event);};done=finished=0;auto mapped=complete_model(common_config,common,&secret,common_sink);require(done==1&&finished==1&&mapped.tool_calls.size()==1&&mapped.tool_calls[0].id.starts_with("gm_")&&mapped.tool_calls[0].id!="provider-call","Common Gemini gateway must allocate a separate native tool identity");require(mapped.tool_calls[0].arguments_json==R"({"path":"README","n":1.2345678901234567890123456789})","Common gateway must retain exact argument tokens");const auto mapped_usage=Json::parse(mapped.usage_json);require(mapped_usage["prompt_tokens"]==8&&mapped_usage["completion_tokens"]==5&&!mapped_usage.contains("total_tokens"),"Common Gemini usage must map supplied counters without inventing totals");
    require(common_events.size()>=4&&common_events[common_events.size()-3].kind=="model.tool_delta"&&common_events[common_events.size()-2].kind=="model.finish"&&common_events.back().kind=="model.done","Common tool callback must precede validated finish/done");const auto delta=Json::parse(common_events[common_events.size()-3].json);require(delta["id"]==mapped.tool_calls[0].id&&delta["arguments"]==mapped.tool_calls[0].arguments_json,"Common tool callbacks must carry exact native identities and argument strings");bool usage_observed=false;for(const auto& event:common_events)if(event.kind=="model.usage"){const auto observed=Json::parse(event.json);require(observed["prompt_tokens"]==8&&observed["completion_tokens"]==5&&!observed.contains("total_tokens"),"Observed usage callback must use the same supplied native counters");usage_observed=true;}require(usage_observed,"Actual socket usage callback must reach the native gateway sink");
    // Exercise the same JSON envelope round trip used by persisted agent history.
    const auto saved=Json::parse(Json{{"provider_items",Json::parse(mapped.provider_items_json)}}.dump())["provider_items"].dump();common.messages.push_back({MessageRole::assistant,mapped.content,mapped.tool_calls,{},mapped.refusal,saved});common.messages.push_back({MessageRole::tool,"actual fixture result",{},mapped.tool_calls[0].id});common_config.endpoint=base+"/common-continuation/v1beta";done=finished=0;mapped=complete_model(common_config,common,&secret,sink);require(done==1&&finished==1&&mapped.content=="Fixture complete"&&mapped.tool_calls.empty(),"Common native Gemini conversation must resume from its checked signed receipt");
    std::cout<<"Native Gemini request/HTTP/SSE boundary passed against an independent synthetic peer, including exact signed continuation, header-only key, offered-call validation, failure/cancellation and no redirect/retry. No agent enrollment or live inference tested.\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
