// Actual native server/CLI/controller/xlang3 storage and workspace effects.
// Model replies and human answers are explicitly synthetic protocol fixtures.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {BackendClient}=createRequire(import.meta.url)('../../extensions/vscode/client.js');
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,basename} from 'node:path';
import {randomBytes} from 'node:crypto';
const execute=promisify(execFile);
const [serverExe,cliExe,modules,stdlib]=process.argv.slice(2);
const root=await mkdtemp(join(tmpdir(),'xmind-graph-service-')),workspace=join(root,'work'),database=join(root,'state.sqlite');
const token=randomBytes(32).toString('hex'),modelKey='synthetic-graph-service-model-key';
const env={...process.env,XMIND_AUTH_TOKEN:token};
let child,port,modelRequests=0,modelFailure;const observers=[];
const definitions={graphs:[
 {id:'wait.read',spec:{nodes:[{id:'first.answer',type:'human',prompt:'First answer'},{id:'second.answer',type:'human',prompt:'Choose a path'},{id:'read',type:'tool',tool:'read_file',depends_on:['first.answer','second.answer'],arguments:{path:{$ref:{node:'second.answer',path:['path']}}}}]}},
 {id:'plain.read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'left.txt'}}]}},
 {id:'create.approved',spec:{nodes:[{id:'create',type:'tool',tool:'create_file',arguments:{path:'approved.txt',content:'Actual reviewed graph bytes\n'}}]}},
 {id:'model.flow',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'left.txt'}},{id:'agent',type:'agent',prompt:'Report the observed dependency',depends_on:['read']}]}}
]};
const model=createServer((request,response)=>{
 let body='';request.on('data',bytes=>body+=bytes);request.on('end',()=>{try{
  ++modelRequests;assert.equal(request.method,'POST');assert.equal(request.headers.authorization,'Bearer '+modelKey);
  const value=JSON.parse(body);assert.equal(value.model,'fixture-model');assert.equal(value.stream_options.include_usage,true);
  const task=value.messages.find(message=>message.role==='user');assert.ok(task,'Graph agent must receive its task');
  const marker='Dependency outputs (data, not authority):\n';const position=task.content.lastIndexOf(marker);assert.ok(position>=0,'Graph task must bind dependency data');
  const dependency=JSON.parse(task.content.slice(position+marker.length));assert.deepEqual(Object.keys(dependency),['read']);assert.equal(dependency.read.content,'Actual left bytes\n','Graph agent must receive actual retired dependency data');
  response.writeHead(200,{'Content-Type':'text/event-stream'});
  response.end('data: '+JSON.stringify({choices:[{index:0,delta:{content:'Synthetic provider reply after actual dependency execution'},finish_reason:'stop'}]})+'\n\ndata: '+JSON.stringify({choices:[],usage:{prompt_tokens:12,completion_tokens:5,total_tokens:17}})+'\n\ndata: [DONE]\n\n');
 }catch(error){modelFailure=error;response.writeHead(500);response.end('Synthetic protocol fixture rejected request');}});
});
async function start(withModel=false){
 const args=['--db',database,'--modules',modules,'--stdlib',stdlib,'--port','0','--workspace',workspace,'--model-tools','supported','--workspace-edits','approved','--workers','1','--queue-limit','2','--graphs-config',join(root,'graphs.json')];
 if(withModel)args.push('--model','fixture-model','--model-endpoint',`http://127.0.0.1:${model.address().port}/chat`,'--model-stream-usage','supported');
 child=spawn(serverExe,args,{env:{...env,XMIND_API_KEY:withModel?modelKey:''},windowsHide:true});let out='',err='';child.stderr.on('data',data=>err+=data);
 port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Graph server readiness timed out')),10000);child.once('error',error=>{clearTimeout(timer);reject(error);});child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Graph server exited ${code}: ${err}`));});child.stdout.on('data',data=>{out+=data;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(out);if(match){clearTimeout(timer);resolve(Number(match[1]));}});});
}
async function stop(){if(!child||child.exitCode!==null)return;const finished=new Promise(resolve=>child.once('exit',resolve));child.kill();await finished;child=undefined;}
async function request(path,body,headers={}){const response=await fetch(`http://127.0.0.1:${port}${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(10000)});return {status:response.status,data:await response.json()};}
async function cli(...args){const result=await execute(cliExe,[String(port),...args],{env,windowsHide:true,timeout:12000});return JSON.parse(result.stdout);}
async function scriptedChat(commands,expectedExit=0){
 const process=spawn(cliExe,[String(port),'chat'],{env,windowsHide:true});let output='',errors='';process.stdout.on('data',bytes=>output+=bytes);process.stderr.on('data',bytes=>errors+=bytes);
 const timer=setTimeout(()=>process.kill(),12000),ended=new Promise((yes,no)=>{process.once('error',no);process.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal});});});process.stdin.end(commands.join('\n')+'\n');
 const result=await ended;assert.equal(result.signal,null,errors);assert.equal(result.code,expectedExit,errors);return {records:output.trim().split('\n').filter(Boolean).map(line=>JSON.parse(line)),errors};
}
async function interactiveGraph(id,mode='input'){
 const process=spawn(cliExe,[String(port),'chat'],{env,windowsHide:true}),records=[];let pending='',errors='',failure,foreignSent=false,raced=false;
 process.stderr.on('data',bytes=>errors+=bytes);process.stdout.on('data',bytes=>{pending+=bytes;let newline;while((newline=pending.indexOf('\n'))>=0){const line=pending.slice(0,newline);pending=pending.slice(newline+1);try{const record=JSON.parse(line);records.push(record);
  if(record.type==='graph_human_review'){assert.equal(record.root_run_id,id);assert.ok(Number.isSafeInteger(record.checkpoint_revision)&&record.checkpoint_revision>0);assert.ok(record.steps.length);
   if(mode==='detach')process.stdin.end('/exit\n');else if(mode==='cancel')process.stdin.write('/cancel\n');else if(mode==='race'&&!raced){raced=true;assert.equal(record.steps[0].node_id,'first.answer');request('/v1/graph-runs/'+id+'/human/first.answer',{input:{accepted:true},expected_checkpoint_revision:record.checkpoint_revision}).then(result=>{assert.equal(result.status,200);process.stdin.write('/input first.answer {"accepted":false}\n');}).catch(error=>{failure=error;process.kill();});}else if(mode!=='race'&&!foreignSent){foreignSent=true;process.stdin.write('/input foreign-fixture-node {}\n');}else {const node=record.steps[0].node_id;assert.ok(['first.answer','second.answer'].includes(node));process.stdin.write('/input '+node+' '+JSON.stringify(node==='first.answer'?{accepted:true}:{path:'left.txt'})+'\n');}
  }
  if(record.type==='operation_review'){assert.equal(mode,'approve');assert.equal(record.operation.tool,'create_file');assert.equal(JSON.parse(record.operation.arguments_json).path,'approved.txt');process.stdin.write('/allow '+record.operation.id+'\n');}
  if(record.type==='turn_finished')process.stdin.end('/exit\n');
 }catch(error){failure=error;process.kill();}}});
 const timer=setTimeout(()=>process.kill(),12000),ended=new Promise((yes,no)=>{process.once('error',no);process.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal});});});process.stdin.write('/graph-watch '+id+'\n');const result=await ended;if(failure)throw failure;assert.equal(result.signal,null,errors);assert.equal(result.code,mode==='detach'?1:mode==='cancel'?2:0,errors);assert.ok(!records.some(record=>record.type==='run'),'Attachment must not admit another run');assert.equal(records.find(record=>record.type==='run_attached').run.id,id);return {records,errors};
}
function observe(id,after=0){const process=spawn(cliExe,[String(port),'graph-watch',id,String(after)],{env,windowsHide:true}),events=[];let pending='',error='';process.stdout.on('data',bytes=>{pending+=bytes;const lines=pending.split('\n');pending=lines.pop();for(const line of lines)if(line.trim())events.push(JSON.parse(line));});process.stderr.on('data',bytes=>error+=bytes);const ended=new Promise((yes,no)=>{process.once('error',no);process.once('close',(code,signal)=>yes({code,signal,error}));});const result={process,events,ended};observers.push(result);return result;}
async function waitEvent(observer,predicate){const deadline=Date.now()+10000;while(!observer.events.some(predicate)){if(observer.process.exitCode!==null||observer.process.signalCode!==null)throw new Error('Graph observer exited before expected event');if(Date.now()>=deadline)throw new Error('Graph observer event deadline');await new Promise(resolve=>setTimeout(resolve,10));}}
async function stopObserver(observer){if(observer.process.exitCode===null&&observer.process.signalCode===null)observer.process.kill();return observer.ended;}
async function state(id,wanted){const deadline=Date.now()+10000;for(;;){const result=await request('/v1/graph-runs/'+id);assert.equal(result.status,200);if(result.data.run.state===wanted)return result.data;if(['failed','cancelled','completed'].includes(result.data.run.state)&&result.data.run.state!==wanted)throw new Error('Unexpected graph retirement: '+result.data.run.state);if(Date.now()>=deadline)throw new Error('Graph did not reach '+wanted);await new Promise(resolve=>setTimeout(resolve,5));}}
async function session(id){assert.equal((await request('/v1/sessions',{id,title:'Actual graph controller fixture'})).status,201);}
async function submit(id,session,graph='wait.read'){return request('/v1/graph-runs',{id,session_id:session,graph_id:graph,graph_revision:1,prompt:'Actual graph service fixture task'});}
try {
 await mkdir(workspace);await writeFile(join(workspace,'left.txt'),'Actual left bytes\n');await writeFile(join(workspace,'right.txt'),'Actual right bytes\n');await writeFile(join(root,'graphs.json'),JSON.stringify(definitions));
 await new Promise(resolve=>model.listen(0,'127.0.0.1',resolve));await start();
 assert.equal((await request('/v1/graphs',undefined,{Authorization:''})).status,401);
 const catalogue=await cli('graphs');assert.equal(catalogue.graphs.length,4);assert.equal(catalogue.graphs.find(graph=>graph.id==='model.flow').executable,false);assert.equal(catalogue.graphs.find(graph=>graph.id==='plain.read').executable,true);
 const beforeRejectedGraphs=await cli('sessions'),rejectedGraphs=await scriptedChat(['/graphs','/graph missing.fixture request','/graph model.flow request','/graph wait.read   ','/exit']);
 assert.deepEqual(rejectedGraphs.records.find(record=>record.type==='graphs').catalogue,catalogue);assert.match(rejectedGraphs.errors,/Graph was not found/);assert.match(rejectedGraphs.errors,/Graph cannot execute/);assert.match(rejectedGraphs.errors,/nonempty request/);assert.ok(!rejectedGraphs.records.some(record=>record.type==='session'||record.type==='run'));assert.deepEqual(await cli('sessions'),beforeRejectedGraphs,'Invalid or unavailable graphs cannot create placeholder conversations');
 const launchedGraph=await scriptedChat(['/graph plain.read Read actual graph dependency','/history','/runs','/exit']),launchedRun=launchedGraph.records.find(record=>record.type==='run').run;
 assert.equal(launchedGraph.records.filter(record=>record.type==='run').length,1);assert.equal(launchedRun.graph_root,true);assert.equal(launchedGraph.records.find(record=>record.type==='turn_finished').exit_status,0);const launchedDone=await state(launchedRun.id,'completed');assert.equal(launchedDone.graph_id,'plain.read');assert.equal(launchedDone.graph_revision,catalogue.graphs.find(graph=>graph.id==='plain.read').revision);assert.equal(launchedDone.checkpoint.nodes[0].output.content,'Actual left bytes\n');assert.equal((await cli('sessions')).find(session=>session.id===launchedRun.session_id).title,'Read actual graph dependency');assert.deepEqual(launchedGraph.records.find(record=>record.type==='history').history,await cli('history',launchedRun.session_id));assert.deepEqual((await cli('runs',launchedRun.session_id)).map(run=>run.id),[launchedRun.id],'Session run catalogue contains roots only');assert.equal((await cli('graph-children',launchedRun.id)).length,1,'The actual read child belongs to its graph root');assert.deepEqual(launchedGraph.records.find(record=>record.type==='runs').runs,await cli('runs',launchedRun.session_id));assert.equal(modelRequests,0,'Tool-only console graph launch requires no provider inference');
 const composedGraph=await scriptedChat(['/compose plain.read','Composed graph 雪','','/exit','//send','//discard','/send','/history','/runs','/exit']);
 const composedRoots=composedGraph.records.filter(record=>record.type==='run');assert.equal(composedRoots.length,1);const composedRoot=composedRoots[0].run;assert.equal(composedRoot.graph_root,true);
 const composedDone=await state(composedRoot.id,'completed');assert.equal(composedDone.graph_id,'plain.read');assert.equal(composedDone.graph_revision,catalogue.graphs.find(graph=>graph.id==='plain.read').revision);assert.equal(composedDone.checkpoint.nodes[0].output.content,'Actual left bytes\n');
 const composedHistory=await cli('history',composedRoot.session_id);assert.equal(composedHistory.find(message=>message.role==='user').data.content,'Composed graph 雪\n\n/exit\n/send\n/discard\n');assert.equal((await cli('graph-children',composedRoot.id)).length,1);assert.equal(modelRequests,0,'Composed tool-only graph cannot invent a provider request');
 const beforeInvalidCompose=await cli('sessions'),invalidCompose=await scriptedChat(['/compose missing.fixture','Keep this in an explicit graph','/send','/exit']);assert.ok(!invalidCompose.records.some(record=>record.type==='session'||record.type==='run'));assert.deepEqual(await cli('sessions'),beforeInvalidCompose,'Unknown graph cannot silently admit a single agent');
 const viewClient=new BackendClient(`http://127.0.0.1:${port}`,()=>token);assert.deepEqual((await viewClient.graphs()).graphs,catalogue.graphs,'Actual extension client must receive the native graph catalogue');
 await session('first');await session('second');await session('third');
 assert.equal((await request('/v1/graph-runs',{id:'spoof',session_id:'first',graph_id:'wait.read',graph_revision:1,prompt:'fixture',spec:definitions.graphs[0].spec})).status,400);
 assert.equal((await request('/v1/graph-runs',{id:'stale',session_id:'first',graph_id:'wait.read',graph_revision:99,prompt:'fixture'})).status,409);
 assert.equal((await submit('no-model','first','model.flow')).status,503);assert.deepEqual(await cli('runs','first'),[]);
 assert.equal((await submit('first-root','first')).status,202);let first=await state('first-root','paused');assert.deepEqual(await cli('graph-children','first-root'),[]);
 const beforeBusyRuns=await cli('runs','first'),beforeBusyHistory=await cli('history','first'),beforeBusyEvents=await cli('graph-events','first-root');
 const busyChat=await scriptedChat(['/session first','/graph plain.read Keep this rejected graph request','/runs','/history','/exit'],1);
 assert.deepEqual(busyChat.records.find(record=>record.type==='run_rejected'),{type:'run_rejected',session_id:'first',http_status:409,prompt:'Keep this rejected graph request',graph_id:'plain.read'});assert.match(busyChat.errors,/no automatic retry/);assert.ok(!busyChat.records.some(record=>record.type==='run'||record.type==='turn_finished'));assert.deepEqual(busyChat.records.find(record=>record.type==='runs').runs,beforeBusyRuns);assert.deepEqual(busyChat.records.filter(record=>record.type==='history').at(-1).history,beforeBusyHistory);assert.deepEqual(await cli('runs','first'),beforeBusyRuns);assert.deepEqual(await cli('history','first'),beforeBusyHistory);assert.deepEqual(await cli('graph-events','first-root'),beforeBusyEvents);assert.equal(modelRequests,0,'Rejected graph admission and subsequent inspection cannot invoke inference');
 const pausedObserver=observe('first-root');await waitEvent(pausedObserver,event=>event.run_id==='first-root'&&event.kind==='run.paused');await stopObserver(pausedObserver);assert.equal((await cli('graph','first-root')).run.state,'paused','Closing the graph observer must not cancel native ownership');const resumeCursor=pausedObserver.events.at(-1).seq;
 for(const source of ['{"accepted":true,"accepted":false}','{"nested":{"path":"left.txt","path":"right.txt"}}',JSON.stringify({nested:Array.from({length:18}).reduce(value=>({nested:value}),{})})]){
  await writeFile(join(root,'invalid-answer.json'),source);await assert.rejects(cli('graph-input','first-root','first.answer',String(first.checkpoint_revision),join(root,'invalid-answer.json')),error=>error.code===1&&/duplicate keys|nesting exceeds/.test(error.stderr));assert.equal((await cli('graph','first-root')).checkpoint_revision,first.checkpoint_revision,'Rejected ambiguous/deep input must not mutate the graph checkpoint');
 }
 assert.equal((await submit('second-root','second')).status,202);await state('second-root','paused');
 assert.equal((await submit('not-admitted','third','plain.read')).status,503);assert.deepEqual(await cli('runs','third'),[],'Paused ownership must count toward capacity');
 assert.equal((await request('/v1/provider/configuration',{model:'fixture-model',api_key:modelKey,expected_revision:0})).status,409,'Provider generation cannot change while a graph is owned');assert.equal((await request('/v1/provider/configuration')).data.revision,0);
 assert.equal((await request('/v1/graph-runs/first-root/human/first.answer',{input:{accepted:true},expected_checkpoint_revision:first.checkpoint_revision,actor:'spoof'})).status,400);
 for(const input_json of ['{"accepted":true,"accepted":false}','[]','not JSON']){await assert.rejects(viewClient.graphInput('first-root','first.answer',input_json,first.checkpoint_revision),error=>error.status===400);assert.equal((await cli('graph','first-root')).checkpoint_revision,first.checkpoint_revision);}
 assert.equal((await request('/v1/graph-runs/first-root/human/first.answer',{input:{accepted:true},input_json:'{}',expected_checkpoint_revision:first.checkpoint_revision})).status,400);
 const partial=await viewClient.graphInput('first-root','first.answer','{"accepted":true}',first.checkpoint_revision);assert.equal(partial.run.state,'paused');first=partial;
 assert.equal((await request('/v1/graph-runs/first-root/human/second.answer',{input:{path:'right.txt'},expected_checkpoint_revision:first.checkpoint_revision-1})).status,409);
 await stop();await start();first=await state('first-root','paused');assert.equal(first.checkpoint.nodes[0].state,'completed');assert.equal(first.checkpoint.nodes[1].state,'waiting_human');
 await writeFile(join(root,'answer.json'),JSON.stringify({path:'right.txt'}));await cli('graph-input','first-root','second.answer',String(first.checkpoint_revision),join(root,'answer.json'));
 first=await state('first-root','completed');assert.equal(first.checkpoint.nodes[2].output.content,'Actual right bytes\n');const actualChildren=await cli('graph-children','first-root');assert.equal(actualChildren.length,1);assert.equal(first.run.graph_root,true);assert.equal(first.run.parent_id,'');assert.equal(actualChildren[0].graph_root,false);assert.equal(actualChildren[0].parent_id,'first-root');assert.equal(actualChildren[0].node_id,'read');assert.equal((await cli('status',actualChildren[0].id)).node_id,'read');
 const history=await cli('history','first');assert.equal(history.length,2);assert.equal(history[1].data.source,'graph_join');assert.ok(!('usage' in history[1].data));
 const childHistory=await cli('graph-child-history','first-root',actualChildren[0].id);assert.equal(childHistory.at(-1).data.content,'Actual right bytes\n');assert.ok(!childHistory.some(item=>item.data.source==='graph_join'));assert.equal((await request('/v1/graph-runs/second-root/children/'+actualChildren[0].id+'/history')).status,404);
 const events=await cli('graph-events','first-root');assert.ok(events.some(event=>event.kind==='graph.human.input'&&event.data.actor==='local-owner'));assert.ok(events.some(event=>event.run_id!=='first-root'));assert.ok(!events.some(event=>event.run_id==='second-root'));
 const resumedObserver=observe('first-root',resumeCursor),resumedExit=await resumedObserver.ended;assert.equal(resumedExit.code,0);assert.ok(resumedObserver.events.length>0);const owned=new Set(['first-root',...actualChildren.map(child=>child.id)]);let previous=resumeCursor;for(const event of resumedObserver.events){assert.ok(event.seq>previous);previous=event.seq;assert.ok(owned.has(event.run_id));}assert.ok(resumedObserver.events.some(event=>event.run_id===actualChildren[0].id),'Graph watch must include actual child execution events');assert.ok(resumedObserver.events.some(event=>event.run_id==='first-root'&&event.kind==='run.completed'),'Graph watcher must drain terminal events');assert.deepEqual(resumedObserver.events,events.filter(event=>event.seq>resumeCursor),'Cursor reconnection must replay exactly the remaining persisted graph events');
 const caughtUp=observe('first-root',previous);assert.equal((await caughtUp.ended).code,0);assert.deepEqual(caughtUp.events,[]);const childObserver=observe(actualChildren[0].id);const rejected=await childObserver.ended;assert.equal(rejected.code,1);assert.match(rejected.error,/graph root/);assert.deepEqual(childObserver.events,[]);
 await cli('cancel','second-root');await state('second-root','cancelled');assert.equal((await request('/v1/graph-runs/second-root/human/first.answer',{input:{accepted:true},expected_checkpoint_revision:3})).status,404);
 const cancelledObserver=observe('second-root');assert.equal((await cancelledObserver.ended).code,2);assert.ok(cancelledObserver.events.some(event=>event.run_id==='second-root'&&event.kind==='run.cancelled'));
 const plain=await cli('graph-run','third','plain.read','1','Read actual workspace data');const plainDone=await state(plain.id,'completed');assert.equal(plainDone.checkpoint.nodes[0].output.content,'Actual left bytes\n');
 // Exercise pause/input scheduling against real concurrent worker observations.
 for(let i=0;i<12;++i){const id='wake-'+i,s='wake-session-'+i;await session(s);assert.equal((await submit(id,s)).status,202);let root=await state(id,'paused');root=(await request(`/v1/graph-runs/${id}/human/first.answer`,{input:{accepted:true},expected_checkpoint_revision:root.checkpoint_revision})).data;const input=await request(`/v1/graph-runs/${id}/human/second.answer`,{input:{path:'left.txt'},expected_checkpoint_revision:root.checkpoint_revision});assert.equal(input.status,200);const done=await state(id,'completed');assert.equal(done.checkpoint.nodes[2].output.content,'Actual left bytes\n');assert.equal((await cli('graph-children',id)).length,1);}
 await session('console-human');assert.equal((await submit('console-human-root','console-human')).status,202);await state('console-human-root','paused');
 const detachedGraph=await interactiveGraph('console-human-root','detach');assert.ok(!detachedGraph.records.some(record=>record.type==='graph_input_result'||record.type==='turn_finished'));assert.equal((await cli('graph','console-human-root')).run.state,'paused');
 const consoleHuman=await interactiveGraph('console-human-root');assert.match(consoleHuman.errors,/No input sent/);const reviews=consoleHuman.records.filter(record=>record.type==='graph_human_review');assert.equal(reviews[0].checkpoint_revision,reviews[1].checkpoint_revision,'Foreign input cannot mutate the displayed checkpoint');assert.equal(consoleHuman.records.filter(record=>record.type==='graph_input_result').length,2);assert.equal((await state('console-human-root','completed')).checkpoint.nodes[2].output.content,'Actual left bytes\n');assert.equal((await cli('runs','console-human')).filter(run=>run.graph_root).length,1);assert.equal(modelRequests,0,'Model-free interactive graphs must not synthesize inference');
 await session('console-race');assert.equal((await submit('console-race-root','console-race')).status,202);await state('console-race-root','paused');const consoleRace=await interactiveGraph('console-race-root','race');assert.match(consoleRace.errors,/HTTP 409/);assert.equal(consoleRace.records.filter(record=>record.type==='graph_input_result').length,1,'Rejected stale input cannot be replayed automatically');const raceDone=await state('console-race-root','completed');assert.equal(raceDone.checkpoint.nodes.find(node=>node.id==='first.answer').output.accepted,true);assert.equal(raceDone.checkpoint.nodes[2].output.content,'Actual left bytes\n');
 await session('console-cancel');assert.equal((await submit('console-cancel-root','console-cancel')).status,202);await state('console-cancel-root','paused');const consoleCancelled=await interactiveGraph('console-cancel-root','cancel');assert.ok(consoleCancelled.records.some(record=>record.kind==='run.cancelled'));assert.equal(consoleCancelled.records.filter(record=>record.type==='graph_input_result'||record.type==='operation_decision_result').length,0);assert.deepEqual(consoleCancelled.records.find(record=>record.type==='run_cancel_result').result,{id:'console-cancel-root',cancellation_requested:true});assert.equal((await cli('graph','console-cancel-root')).run.state,'cancelled');
 await session('effect');const effect=(await submit('effect-root','effect','create.approved')).data;let operation;const until=Date.now()+10000;
 while(!operation){const children=await cli('graph-children',effect.id);for(const branch of children)operation=(await cli('operations',branch.id)).find(item=>item.state==='awaiting_approval');if(Date.now()>=until)throw new Error('Graph effect approval timed out');if(!operation)await new Promise(resolve=>setTimeout(resolve,5));}
 await assert.rejects(readFile(join(workspace,'approved.txt')),error=>error.code==='ENOENT');const consoleEffect=await interactiveGraph(effect.id,'approve');assert.equal(consoleEffect.records.find(record=>record.type==='operation_review').operation.id,operation.id);await state(effect.id,'completed');assert.equal(await readFile(join(workspace,'approved.txt'),'utf8'),'Actual reviewed graph bytes\n');
 // A configured graph agent uses actual native provider sockets and retains
 // child usage separately; only this protocol peer's reply/counts are synthetic.
 await stop();await start(true);await session('model');const agent=await cli('graph-run','model','model.flow','1','Observe an actual dependency');await state(agent.id,'completed');if(modelFailure)throw modelFailure;assert.equal(modelRequests,1);const branches=await cli('graph-children',agent.id);assert.equal(branches.length,2);assert.ok((await cli('graph-events',agent.id)).some(event=>event.kind==='model.usage'));const modelHistory=await cli('history','model');assert.ok(!('usage' in modelHistory[1].data));
 const agentHistory=await cli('graph-child-history',agent.id,branches.find(child=>child.node_id==='agent').id);assert.equal(agentHistory.at(-1).data.usage.prompt_tokens,12);assert.equal(agentHistory.at(-1).data.usage.completion_tokens,5);assert.equal(agentHistory.at(-1).data.content,'Synthetic provider reply after actual dependency execution');
 console.log('Native graph service HTTP/CLI passed actual catalog admission, actor/stale rejection, paused capacity/provider ownership, restart, human resume, real dependency reads, repeated scheduling, root cancellation, separately approved creation, graph-watch child ownership/cursor reconnect/terminal drain/disconnect without cancellation, and configured agent transport with synthetic provider data.');
} finally {for(const observer of observers)await stopObserver(observer);await stop();model.closeAllConnections();await new Promise(resolve=>model.close(resolve));assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-graph-service-'));await rm(root,{recursive:true,force:true});}
