#include "agentflow/graph_runner.hpp"
#include "nlohmann/json.hpp"
#include "agentflow/xlang_sqlite.hpp"
#include "agentflow/edit_executor.hpp"
#include <filesystem>
#include <future>
#include <thread>
#include <iostream>
using namespace agentflow;using Json=nlohmann::json;
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
struct Task{std::stop_source stop;std::future<Run> result;Task(GraphRunner& runner,std::string id):result(std::async(std::launch::async,[this,&runner,id=std::move(id)]{return runner.execute(id,stop.get_token());})){}~Task(){stop.request_stop();if(result.valid())result.wait();}};
Operation approval(PersistenceService& store,const std::string& root){const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(std::chrono::steady_clock::now()<deadline){for(const auto& child:store.children(root).get())for(const auto& op:store.operations(child.id).get())if(op.state==OperationState::awaiting_approval)return op;std::this_thread::sleep_for(std::chrono::milliseconds(5));}throw std::runtime_error("Graph approval did not arrive");}
int main(int argc,char** argv){if(argc!=5)return 2;try{
 const auto database=(std::filesystem::u8path(argv[1])/"runner.sqlite").string();const std::vector<std::string> imports{argv[2],argv[3]};
 PersistenceService store(database,imports);AgentSettings settings;settings.provider.model="fixture-model";settings.provider.endpoint=argv[4];settings.provider.tools=Capability::supported;settings.workspace=argv[1];settings.run_timeout=std::chrono::seconds(15);GraphRunner runner(store,settings,2);
 const GraphPlan plan(R"({"nodes":[
  {"id":"read","type":"tool","tool":"read_file","arguments":{"path":"left.txt"}},
  {"id":"left","type":"agent","prompt":"parallel-left","depends_on":["read"]},
  {"id":"right","type":"agent","prompt":"parallel-right","depends_on":["read"]},
  {"id":"review","type":"human","prompt":"Choose the next file","depends_on":["left","right"]},
  {"id":"chosen","type":"tool","tool":"read_file","depends_on":["review"],"arguments":{"path":{"$ref":{"node":"review","path":["path"]}}}},
  {"id":"excluded","type":"tool","tool":"read_file","depends_on":["review"],"when":{"node":"review","path":["path"],"equals":"never.txt"},"arguments":{"path":"never.txt"}}
 ]})");
 runner.validate(plan);store.create_session("main","Real graph execution with synthetic inference").get();store.start_graph_run("root","main","fixture",1,plan,R"({"content":"root actual graph task","model_id":"fixture-model"})").get();
 require(runner.execute("root").state==RunState::paused,"Human step must pause after observed agent joins");auto root=store.graph_run("root").get();require(!root.input_json.empty(),"Immutable graph input must be retained");auto checkpoint=Json::parse(root.checkpoint_json);require(checkpoint["nodes"][0]["output"]["content"]=="Actual left file\n","Direct graph tool must use actual workspace content");require(store.children("root").get().size()==3,"Human node must not masquerade as executable child");
 store.input_graph_human("root","review",R"({"path":"right.txt"})","local-owner",root.checkpoint_revision).get();require(runner.execute("root").state==RunState::completed,"Resumed graph must run the typed-reference tool and finish");root=store.graph_run("root").get();checkpoint=Json::parse(root.checkpoint_json);require(checkpoint["nodes"][4]["output"]["content"]=="Actual right file\n" && checkpoint["nodes"][5]["state"]=="skipped","Actual human data must resolve tool argument and condition");require(store.children("root").get().size()==4,"Skipped tool must never be admitted");const auto history=store.history("main").get();require(history.size()==2 && Json::parse(history.back().json)["source"]=="graph_join","Root history must retain its own observed join only");require(!Json::parse(history.back().json).contains("usage"),"Graph must not fabricate aggregate token metrics");
 const GraphPlan missing(R"({"nodes":[{"id":"bad","type":"tool","tool":"read_file","arguments":{"path":"missing.txt"}},{"id":"after","type":"tool","tool":"read_file","depends_on":["bad"],"arguments":{"path":"right.txt"}}]})");
 store.create_session("failure","Actual missing file").get();store.start_graph_run("failed-root","failure","missing",1,missing,R"({"content":"read missing file"})").get();require(runner.execute("failed-root").state==RunState::failed,"Failed actual tool must fail root");require(store.children("failed-root").get().size()==1,"Dependent work must not dispatch after failure");
 store.create_session("cancel","Cancellation before dispatch").get();store.start_graph_run("cancel-root","cancel","missing",1,missing,R"({"content":"cancel"})").get();std::stop_source stop;stop.request_stop();require(runner.execute("cancel-root",stop.get_token()).state==RunState::cancelled && store.children("cancel-root").get().empty(),"Cancelled root must retire without tool dispatch");
 const GraphPlan concurrentHuman(R"({"nodes":[{"id":"gate","type":"human","prompt":"Wait while unrelated read runs"},{"id":"read","type":"tool","tool":"read_file","arguments":{"path":"right.txt"}}]})");store.create_session("parallel-human","Human and executable branches").get();store.start_graph_run("parallel-human-root","parallel-human","mixed",1,concurrentHuman,R"({"content":"pause after other branch retires"})").get();require(runner.execute("parallel-human-root").state==RunState::paused,"Settling the last concurrent child must persist human pause");const auto waiting=store.graph_run("parallel-human-root").get();store.input_graph_human("parallel-human-root","gate",R"({"accepted":true})","fixture-controller",waiting.checkpoint_revision).get();require(runner.execute("parallel-human-root").state==RunState::completed,"Concurrent human branch must resume without replaying read");require(store.children("parallel-human-root").get().size()==1,"Human resume must not repeat retired independent child");
 const GraphPlan badReference(R"({"nodes":[{"id":"read","type":"tool","tool":"read_file","arguments":{"path":"left.txt"}},{"id":"bad","type":"tool","tool":"read_file","depends_on":["read"],"arguments":{"path":{"$ref":{"node":"read","path":["unavailable"]}}}}]})");store.create_session("bad-reference","Unavailable actual dependency path").get();store.start_graph_run("bad-reference-root","bad-reference","bad-reference",1,badReference,R"({"content":"do not invent missing data"})").get();require(runner.execute("bad-reference-root").state==RunState::failed && store.children("bad-reference-root").get().size()==1,"Missing dependency data must retire root without dispatch or invented values");
 settings.approved_edits=true;GraphRunner effects(store,settings);
 const GraphPlan creation(R"({"nodes":[{"id":"create","type":"tool","tool":"create_file","arguments":{"path":"created.txt","content":"Actual graph creation\n"}},{"id":"read","type":"tool","tool":"read_file","depends_on":["create"],"arguments":{"path":"created.txt"}}]})");
 store.create_session("effect","Actual graph approval").get();store.start_graph_run("effect-root","effect","create",1,creation,R"({"content":"create a file after approval"})").get();Task create(effects,"effect-root");const auto grant=approval(store,"effect-root");require(!std::filesystem::exists(std::filesystem::u8path(argv[1])/"created.txt"),"Graph proposal must not create before approval");store.decide_operation(grant.id,OperationDecision::allow,"fixture-controller").get();require(create.result.get().state==RunState::completed && store.operation(grant.id).get().state==OperationState::succeeded,"Actual approved graph effect must finish before dependency read");WorkspaceTools files(argv[1]);require(files.read_file("created.txt").content=="Actual graph creation\n","Graph must write actual reviewed file bytes");
 const GraphPlan cancelledCreation(R"({"nodes":[{"id":"create","type":"tool","tool":"create_file","arguments":{"path":"cancelled.txt","content":"must not exist"}}]})");store.create_session("cancel-effect","Cancellation during approval").get();store.start_graph_run("cancel-effect-root","cancel-effect","cancel-create",1,cancelledCreation,R"({"content":"cancel pending approval"})").get();Task pending(effects,"cancel-effect-root");approval(store,"cancel-effect-root");pending.stop.request_stop();require(pending.result.get().state==RunState::cancelled && !std::filesystem::exists(std::filesystem::u8path(argv[1])/"cancelled.txt"),"Graph cancellation must drain its waiting effect without dispatch");
 const GraphPlan faultCreation(R"({"nodes":[{"id":"create","type":"tool","tool":"create_file","arguments":{"path":"fault.txt","content":"Actual bytes before journal fault"}}]})");store.create_session("fault-effect","Actual journal failure").get();store.start_graph_run("fault-root","fault-effect","fault-create",1,faultCreation,R"({"content":"retain uncertain actual effect"})").get();{XlangSqlite inject(database,imports);inject.execute("CREATE TRIGGER graph_effect_journal_fault BEFORE UPDATE OF state ON operations WHEN NEW.state='succeeded' BEGIN SELECT RAISE(ABORT,'graph runner actual journal fixture failure'); END");}Task fault(effects,"fault-root");const auto faultGrant=approval(store,"fault-root");store.decide_operation(faultGrant.id,OperationDecision::allow,"fixture-controller").get();bool unrecorded=false;try{fault.result.get();}catch(const EditOutcomeUnrecorded&){unrecorded=true;}require(unrecorded && files.read_file("fault.txt").content=="Actual bytes before journal fault" && store.operation(faultGrant.id).get().state==OperationState::executing,"Graph must preserve actual effect and unfinished journal instead of invented failure");{XlangSqlite inject(database,imports);inject.execute("DROP TRIGGER graph_effect_journal_fault");}
 store.close();{PersistenceService reopened(database,imports);require(reopened.operation(faultGrant.id).get().state==OperationState::uncertain && reopened.run("fault-root").get().state==RunState::failed,"Restart must quarantine unfinished graph effect");require(files.read_file("fault.txt").content=="Actual bytes before journal fault","Recovery must not replay graph creation");reopened.close();}
 std::cout<<"Native graph runner passed actual workspace reads, concurrent agent transport, durable human pause/resume, typed references, conditional skip, observed joins, failure/cancellation, separately approved file creation, approval cancellation and actual effect journal fault/recovery without replay. Provider replies are synthetic fixture data.\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
