// Actual native view, production editor host adapter, native controller and backend.
// VS Code API configuration is a fixture; no installed/rendered IDE claim.
// Actual unified binary, protected native rendezvous, backend ownership,
// embedded-xlang3 SQLite and native tool graph. Package provenance/notices are
// fixtures; no live provider, installed editor or release acceptance is claimed.
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {stageNativeRuntime} from '../../extensions/vscode/scripts/package-native-runtime.mjs';
import {existsSync} from 'node:fs';
import {exerciseNativeSidebar} from './native_sidebar_subscription.mjs';
const [program,dll,modules,stdlib]=process.argv.slice(2);assert.ok(stdlib);
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-local-view-')),workspace=path.join(base,'workspace 雪'),workspace2=path.join(base,'second workspace'),profiles=path.join(base,'profiles'),bundle=path.join(base,'bundle'),runtime=path.join(base,'runtime'),graphs=path.join(base,'graphs.json'),sha=b=>createHash('sha256').update(b).digest('hex');
await fs.mkdir(workspace);await fs.mkdir(workspace2);await fs.mkdir(bundle);await fs.writeFile(path.join(workspace,'note.txt'),'Actual managed native workspace\n');await fs.writeFile(path.join(workspace2,'note.txt'),'Second native workspace profile\n');await fs.writeFile(graphs,JSON.stringify({graphs:[{id:'profile.read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'note.txt'}}]}},{id:'profile.wait.read',spec:{nodes:[{id:'gate',type:'human',prompt:'Continue the actual native read'},{id:'read',type:'tool',tool:'read_file',depends_on:['gate'],arguments:{path:'note.txt'}}]}},{id:'profile.wait.write',spec:{nodes:[{id:'gate',type:'human',prompt:'Continue to an explicitly approved creation'},{id:'create',type:'tool',tool:'create_file',depends_on:['gate'],arguments:{path:'sidebar-created.txt',content:'Actual sidebar approved bytes 雪\n'}}]}}]}));const files={};
for(const[name,source]of [['xmind.exe',program],['xlang3_runtime.dll',dll],['xlang3.exe',path.join(path.dirname(modules),'xlang3.exe')],...['xlang_json.x3pkg.dll','xlang_sqlite3.x3pkg.dll'].map(n=>['modules/'+n,path.join(modules,n)])]){const bytes=await fs.readFile(source);await fs.mkdir(path.dirname(path.join(bundle,name)),{recursive:true});await fs.writeFile(path.join(bundle,name),bytes);files[name]=sha(bytes);}
const notice=Buffer.from('Synthetic native profile contract provenance and notice. Not a release package.');await fs.mkdir(path.join(bundle,'licenses'));await fs.writeFile(path.join(bundle,'licenses/NOTICE.txt'),notice);files['licenses/NOTICE.txt']=sha(notice);
const source=Buffer.from(JSON.stringify({schemaVersion:1,platform:'win32',arch:'x64',bridgeEnabled:false,nativeRevision:'a'.repeat(40),sdkRevision:'b'.repeat(40),files}));const sourceFile=path.join(base,'source-manifest.json');await fs.writeFile(sourceFile,source);
cp.execFileSync(process.execPath,[new URL("../../views/browser/build.mjs",import.meta.url).pathname.slice(1),path.join(base,"browser-assets")],{windowsHide:true,stdio:"ignore"});
await stageNativeRuntime({explicitStage:true,bundle,bundleManifest:sourceFile,bundleManifestSha256:sha(source),stdlibSource:stdlib,stdlibLicense:await fs.access(path.join(path.dirname(stdlib),'LICENSE')).then(()=>path.join(path.dirname(stdlib),'LICENSE'),()=>path.join(path.dirname(stdlib),'LICENSE.txt')),out:runtime});
const exe=path.join(runtime,'xmind.exe'),env={...process.env};for(const key of Object.keys(env))if(key==='XMIND_AUTH_TOKEN'||key==='XMIND_API_KEY'||key.startsWith('XMIND_UI_'))delete env[key];const pids=new Set();let passed=false;const managers=[],observationAborts=[];let browser;
function invoke(args,{input='',root=profiles,cwd=workspace}={}){return new Promise((yes,no)=>{const child=cp.spawn(exe,['--profile-root',root,...args],{cwd,env,windowsHide:true});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.once('error',no);const timer=setTimeout(()=>child.kill(),60000);child.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal,stdout,stderr});});child.stdin.end(input);});}
async function command(...args){const result=await invoke(args);assert.equal(result.code,0,result.stderr);assert.equal(result.signal,null);return JSON.parse(result.stdout);}
async function inspect(){const value=await command('profile-info');pids.add(value.process_id);return value;}
async function stop(pid){const check=cp.spawnSync(exe,['admin','inspect-owner-process',String(pid)],{env,windowsHide:true,encoding:'utf8'});assert.equal(check.status,0,check.stderr);process.kill(pid);const result=cp.spawnSync(exe,['admin','observe-owner-exit',String(pid),JSON.parse(check.stdout).process_birth,'10000'],{env,windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).exited,true);pids.delete(pid);}

const {createRequire}=await import('node:module'),require=createRequire(import.meta.url);
const {WorkspaceBackend}=require('../../extensions/vscode/workspace-backend.js');
const {resolveNativeRuntime}=require('../../extensions/vscode/native-runtime.js');
const {BackendClient,EventStreamSubscription}=require('../../extensions/vscode/client.js');
const {BrowserController,BrowserSessionClient}=require('../../views/browser/browser.js');
const {createBrowserServer}=await import('../../views/browser/server.mjs');
const secrets=new Map(),state=new Map(),settings={runtimeDirectory:runtime,stdlibSource:'',providerConfigPath:'',workspaceEdits:true};
const context={extensionUri:{fsPath:path.join(base,'extension')},globalStorageUri:{fsPath:path.join(base,'view-hosts')},workspaceState:{get:k=>state.get(k),update:async(k,v)=>state.set(k,v)},secrets:{get:async k=>secrets.get(k),store:async(k,v)=>secrets.set(k,v),delete:async k=>secrets.delete(k)},globalState:{get:()=>{throw Error('Editor owner registry must not be read');},update:()=>{throw Error('Editor owner registry must not be written');}}};
const vscode={env:{},workspace:{isTrusted:true,workspaceFolders:[{name:'Actual native view',uri:{scheme:'file',fsPath:workspace,toString:()=> 'file:///'+workspace}}],getConfiguration:()=>({inspect:k=>({globalValue:settings[k]})})}};
const manager=()=>{const m=new WorkspaceBackend(vscode,context,resolveNativeRuntime,{profileRoot:profiles,env,spawn:(program,args,options)=>{const readyParent=path.dirname(args[args.indexOf('--ready-file')+1]);assert.equal(existsSync(readyParent),false,'The editor must leave protected rendezvous directory creation to native');const child=cp.spawn(program,args,{...options,stdio:['ignore','ignore','pipe']});child.stderr.on('data',bytes=>process.stderr.write(bytes));return child;}});managers.push(m);return m;};
const client=owner=>new BackendClient(owner.origin,()=>context.secrets.get('xmind.auth:'+owner.origin));
async function waitFor(read,label){const deadline=Date.now()+15000;while(Date.now()<deadline){const value=await read();if(value)return value;await new Promise(resolve=>setTimeout(resolve,40));}throw new Error('Timed out: '+label);}
try{
 const unsafeReady=path.join(workspace,'ready.json'),beforeStartup=cp.spawnSync(exe,['view','--workspace',workspace,'--profile-root',profiles,'--ready-file',unsafeReady],{env:{...env,XMIND_VIEW_TOKEN:'d'.repeat(64)},windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(beforeStartup.status,2,beforeStartup.stderr);assert.match(beforeStartup.stderr,/overlaps/);await assert.rejects(fs.stat(profiles),{code:'ENOENT'});await assert.rejects(fs.stat(unsafeReady),{code:'ENOENT'});
 const first=await command('--graphs-config',graphs,'profile-info');pids.add(first.process_id);const secondProfileResult=await invoke(['profile-info'],{cwd:workspace2});assert.equal(secondProfileResult.code,0,secondProfileResult.stderr);const secondProfile=JSON.parse(secondProfileResult.stdout);pids.add(secondProfile.process_id);assert.equal(secondProfile.workspace,await fs.realpath(workspace2));
 const host=manager(),owner=await host.connect(),access=await context.secrets.get('xmind.auth:'+owner.origin);assert.equal(owner.backendPid,first.process_id);assert.equal(owner.profileDirectory,first.profile_directory);assert.equal((await fetch(owner.origin+'/v1/health')).status,401);assert.equal((await fetch(owner.origin+'/v1/health',{headers:{Authorization:'Bearer '+access,Origin:'http://untrusted.invalid'}})).status,403);
 const ready=await fs.readFile(path.join(owner.privateDirectory,'ready.json'),'utf8');assert.ok(!ready.includes(access));assert.ok(!ready.includes('"auth"'));assert.ok(!ready.includes('"token"'));
 const native=client(owner).bindWorkspace(host),title='Shared console and editor native profile 雪 "quoted"',session=await native.createSession(title);assert.equal(session.title,title);assert.ok((await command('sessions')).some(s=>s.id===session.id&&s.title===title));
 // Exercise body reading in the actual native adapter, including chunked UTF-8.
 const chunkedTitle='Chunked native view write 雪',chunkedBytes=Buffer.from(JSON.stringify({title:chunkedTitle}));
 const chunked=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},duplex:'half',body:new ReadableStream({start(controller){for(let i=0;i<chunkedBytes.length;i+=7)controller.enqueue(chunkedBytes.subarray(i,i+7));controller.close();}})});assert.equal(chunked.status,201,await chunked.clone().text());const chunkedSession=await chunked.json();assert.equal(chunkedSession.title,chunkedTitle);assert.ok((await command('sessions')).some(s=>s.id===chunkedSession.id&&s.title===chunkedTitle));
 const malformed=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{"title":'});assert.equal(malformed.status,400);
 const oversized=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'x'.repeat(1024*1024+1)});assert.equal(oversized.status,413);assert.equal((await command('sessions')).length,2);
 const graph=(await native.graphs()).graphs.find(g=>g.id==='profile.read'),run=await native.graphRun(session.id,graph.id,graph.revision,'Read the actual shared workspace');let outcome;const until=Date.now()+15000;while(Date.now()<until){outcome=await native.graph(run.id);if(outcome.run.state==='completed')break;await new Promise(r=>setTimeout(r,40));}assert.equal(outcome.run.state,'completed');assert.equal(outcome.checkpoint.nodes[0].output.content,'Actual managed native workspace\n');
 const streamFrames=async(origin,route,headers)=>{const response=await fetch(origin+route,{headers,signal:AbortSignal.timeout(15000)});assert.equal(response.status,200,await response.clone().text());assert.equal(response.headers.get('content-type'),'text/event-stream');return (await response.text()).split('\n\n').filter(frame=>frame.startsWith('event:')||frame.startsWith('id:')).map(frame=>{const lines=frame.split('\n'),value={};for(const line of lines){if(line.startsWith('id: '))value.id=Number(line.slice(4));if(line.startsWith('event: '))value.type=line.slice(7);if(line.startsWith('data: '))value.data=JSON.parse(line.slice(6));}return value;});};
 const accessHeaders={Authorization:'Bearer '+access},recorded=await native.graphEvents(run.id,0),streamRoute='/v1/graph-runs/'+run.id+'/events/stream';
 const frames=await streamFrames(owner.origin,streamRoute+'?after=0',accessHeaders);assert.equal(frames[0].type,'observation');assert.equal(frames[0].data.run.id,run.id);assert.equal(frames[0].data.scope,'graph');assert.deepEqual(frames.filter(f=>f.type==='committed').map(f=>{assert.equal(f.id,f.data.seq);return f.data;}),recorded);assert.equal(frames.at(-1).data.reason,'terminal');const last=recorded.at(-1).seq;
 const clientEvents=[],clientStream=await native.eventStream(run.id,{scope:'graph',session_id:session.id,onEvent:event=>clientEvents.push(event)});assert.deepEqual(clientEvents,recorded);assert.equal(clientStream.reason,'terminal');assert.equal(clientStream.cursor,last);assert.equal(clientStream.observation.run.session_id,session.id);
 const clientReplay=[],resumedStream=await native.eventStream(run.id,{scope:'graph',session_id:session.id,after:last,onEvent:event=>clientReplay.push(event)});assert.deepEqual(clientReplay,[]);assert.equal(resumedStream.cursor,last);assert.equal(resumedStream.reason,'terminal');
 const subscribed=[];let subscription;const subscribedEnd=await new Promise((yes,no)=>{const timer=setTimeout(()=>{subscription?.dispose();no(Error('Actual native subscription timed out'));},15000);subscription=new EventStreamSubscription({current:()=>true,onEvent:event=>subscribed.push(event),onEnd:result=>{clearTimeout(timer);yes(result);},onError:error=>{clearTimeout(timer);no(error);}});subscription.watch({client:native,root:run.id,session:session.id,scope:'graph',generation:1,after:0});}).finally(()=>subscription?.dispose());assert.deepEqual(subscribed,recorded);assert.equal(subscribedEnd.cursor,last);assert.equal(subscribedEnd.reason,'terminal');
 const replay=await streamFrames(owner.origin,streamRoute,{...accessHeaders,'Last-Event-ID':String(last)});assert.equal(replay.filter(f=>f.type==='committed').length,0);assert.equal(replay.at(-1).data.after,last);
 assert.deepEqual((await streamFrames(owner.origin,'/v1/runs/'+run.id+'/tree-events/stream',accessHeaders)).filter(f=>f.type==='committed').map(f=>f.data),recorded);
 assert.deepEqual((await streamFrames(owner.origin,'/v1/runs/'+run.id+'/events/stream',accessHeaders)).filter(f=>f.type==='committed').map(f=>f.data),await native.events(run.id,0));
 for(const suffix of ['?after=-1','?after=1&after=2','?after=9007199254740992','?unknown=1','?after='+String(last+1000)])assert.equal((await fetch(owner.origin+streamRoute+suffix,{headers:accessHeaders})).status,400);
 assert.equal((await fetch(owner.origin+streamRoute+'?after=0',{headers:{...accessHeaders,'Last-Event-ID':String(last)}})).status,400);assert.equal((await fetch(owner.origin+'/v1/runs/missing/events/stream',{headers:accessHeaders})).status,404);
 const originalHistory=await native.history(session.id),scope=host.stateFields();assert.deepEqual(await command('history',session.id),originalHistory);
 assert.equal((await fetch(owner.origin+'/v1/backend/owner/quiesce',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{}'})).status,401);
 const invalidGrant=await fetch(owner.origin+'/v1/view-sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{"origin":"http://127.0.0.1:19000","origin":"http://127.0.0.1:19000"}'});assert.equal(invalidGrant.status,400);
 browser=await createBrowserServer({backend:owner.origin,assetRoot:path.join(base,'browser-assets')});const browserOrigin=await browser.listen();
 const connected=await fetch(browserOrigin+'/ui/session',{method:'POST',headers:{Authorization:'Bearer '+access,Origin:browserOrigin,'Content-Type':'application/json'},body:'{}'});assert.equal(connected.status,200,await connected.text());let cookie=connected.headers.get('set-cookie').split(';')[0];
 const workspaces=await fetch(browserOrigin+'/ui/workspaces',{headers:{Cookie:cookie,Origin:browserOrigin,'Sec-Fetch-Site':'same-origin'}});assert.equal(workspaces.status,200,await workspaces.clone().text());const workspaceCatalogue=await workspaces.json(),workspaceRoot=await fs.realpath(workspace),workspace2Root=await fs.realpath(workspace2);assert.equal(workspaceCatalogue.selected_workspace_id,(await native.workspace()).workspace_id);assert.equal(workspaceCatalogue.workspaces.length,2);assert.ok(workspaceCatalogue.workspaces.some(value=>value.name===path.basename(workspace)&&value.root===workspaceRoot));assert.ok(workspaceCatalogue.workspaces.some(value=>value.name===path.basename(workspace2)&&value.root===workspace2Root));
 const rejectedSelection=await fetch(browserOrigin+'/ui/workspaces/select',{method:'POST',headers:{Cookie:cookie,Origin:browserOrigin,'Sec-Fetch-Site':'same-origin','Content-Type':'application/json'},body:JSON.stringify({workspace_id:'windows-local-file-v1:unknown'})});assert.equal(rejectedSelection.status,404);assert.equal((await fetch(browserOrigin+'/v1/health',{headers:{Cookie:cookie,'Sec-Fetch-Site':'same-origin'}})).status,200);
 const browserSessions=await fetch(browserOrigin+'/v1/sessions',{headers:{Cookie:cookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(browserSessions.status,200);assert.ok((await browserSessions.json()).some(s=>s.id===session.id));
 const cookieFrames=await streamFrames(browserOrigin,streamRoute+'?after=0',{Cookie:cookie,'Sec-Fetch-Site':'same-origin'});assert.deepEqual(cookieFrames.filter(f=>f.type==='committed').map(f=>f.data),recorded);assert.deepEqual(await native.graphEvents(run.id,0),recorded);assert.deepEqual(await native.history(session.id),originalHistory);
 // Exercise the production browser controller and reader while the actual
 // native graph remains paused, then through real human input and tool effect.
 // Instrumentation records transport calls; it does not supply domain replies.
 const streamSession=await native.createSession('Actual native browser subscription'),waitGraph=(await native.graphs()).graphs.find(value=>value.id==='profile.wait.read'),waiting=await native.graphRun(streamSession.id,waitGraph.id,waitGraph.revision,'Wait, then read the real file');
 await waitFor(async()=>{const value=await native.graph(waiting.id);return value.run.state==='paused'&&value;},'native human pause');
 const feeds=[],actualEvents=[],browserClient=new BrowserSessionClient(browserOrigin,{fetchImpl:(url,options)=>fetch(url,{...options,headers:{...options.headers,Cookie:cookie,'Sec-Fetch-Site':'same-origin',Origin:browserOrigin}})}),observedClient=Object.create(browserClient);
 observedClient.eventStream=(id,options)=>{const feed={id,signal:options.signal,after:options.after,observed:false};feeds.push(feed);return browserClient.eventStream(id,{...options,onObservation:async value=>{await options.onObservation?.(value);feed.observed=true;},onEvent:async event=>{actualEvents.push(event);await options.onEvent(event);}});};
 const firstMessages=[],firstView=new BrowserController(observedClient,message=>firstMessages.push(message));
 try{await firstView.initialize({session:streamSession.id,run:waiting.id});const pausedEvents=await native.graphEvents(waiting.id,0);await waitFor(()=>firstView.subscription?.cursor===pausedEvents.at(-1).seq,'actual paused feed delivery');assert.equal(feeds.length,1);assert.equal((await native.graph(waiting.id)).run.state,'paused');
  const port=Number(new URL(browserOrigin).port);await browser.close();browser=await createBrowserServer({backend:owner.origin,assetRoot:path.join(base,'browser-assets')});assert.equal(await browser.listen(port),browserOrigin);await waitFor(()=>feeds.length>=2&&feeds.at(-1).observed&&firstView.subscription?.cursor===pausedEvents.at(-1).seq&&!feeds.at(-1).signal.aborted,'actual gateway restart scoped replay');assert.equal(feeds.at(-1).after,pausedEvents.at(-1).seq);assert.equal(firstView.session,streamSession.id);assert.equal(firstView.runId,waiting.id);assert.equal((await native.graph(waiting.id)).run.state,'paused');
  firstView.dispose();assert.equal(feeds.at(-1).signal.aborted,true);assert.equal((await native.graph(waiting.id)).run.state,'paused');assert.equal((await native.graphChildren(waiting.id)).length,0);}
 finally{firstView.dispose();}
 const detachedFeedCount=feeds.length;
 const resumedMessages=[],resumedView=new BrowserController(observedClient,message=>resumedMessages.push(message));
 try{await resumedView.initialize({session:streamSession.id,run:waiting.id});await waitFor(()=>feeds.length===detachedFeedCount+1,'reattached native browser feed');const before=await native.graphEvents(waiting.id,0);await waitFor(()=>resumedView.subscription?.cursor===before.at(-1).seq,'reattached paused feed replay');
  await resumedView.handle({type:'graph-input',root:waiting.id,node:'gate',input_json:'{"continue":true}',revision:resumedView.graph.checkpoint_revision});
  const finished=await waitFor(async()=>{const value=await native.graph(waiting.id);return value.run.state==='completed'&&value;},'actual graph tool completion');assert.equal(finished.checkpoint.nodes.find(node=>node.id==='read').output.content,'Actual managed native workspace\n');
  await waitFor(()=>resumedMessages.findLast(message=>message.type==='status')?.text==='completed'&&!resumedView.subscription?.pin,'browser terminal snapshot');assert.ok(actualEvents.some(event=>event.seq>before.at(-1).seq),'A committed event must arrive incrementally after human input');assert.ok(!resumedMessages.some(message=>message.type==='error'),JSON.stringify(resumedMessages.filter(message=>message.type==='error')));
  const displayed=resumedMessages.filter(message=>['event','graph-event'].includes(message.type)).map(message=>message.event.seq);assert.equal(new Set(displayed).size,displayed.length);assert.deepEqual(resumedMessages.findLast(message=>message.type==='transcript').history,await native.history(streamSession.id));assert.equal((await native.graphChildren(waiting.id)).length,1);assert.ok(!(await native.graphEvents(waiting.id,0)).some(event=>event.kind==='run.cancelled'));
 }finally{resumedView.dispose();}
 const sidebarSession=await native.createSession('Actual production sidebar subscription'),sidebarRun=await native.graphRun(sidebarSession.id,waitGraph.id,waitGraph.revision,'Wait for actual sidebar input');await waitFor(async()=>{const value=await native.graph(sidebarRun.id);return value.run.state==='paused'&&value;},'sidebar graph pause');const sidebarEvidence=await exerciseNativeSidebar({runtime,workspace,profileRoot:profiles,storage:path.join(base,'sidebar-storage'),env,native,session:sidebarSession,run:sidebarRun});assert.equal(sidebarEvidence.actualSidebarHumanToolCompletion,true);
 const writeGraph=(await native.graphs()).graphs.find(value=>value.id==='profile.wait.write');assert.equal(writeGraph.executable,true);const writeSession=await native.createSession('Actual sidebar approved creation'),writeRun=await native.graphRun(writeSession.id,writeGraph.id,writeGraph.revision,'Propose and explicitly approve the actual file');await waitFor(async()=>{const value=await native.graph(writeRun.id);return value.run.state==='paused'&&value;},'sidebar creation human pause');const writeEvidence=await exerciseNativeSidebar({runtime,workspace,profileRoot:profiles,storage:path.join(base,'sidebar-write-storage'),env,native,session:writeSession,run:writeRun,write:{path:'sidebar-created.txt',content:'Actual sidebar approved bytes 雪\n'}});assert.equal(writeEvidence.actualCreationReceiptMatchesDisk,true);
 const delegated=cookie.slice(cookie.indexOf('=')+1);assert.equal((await fetch(first.origin+'/v1/sessions',{headers:{Authorization:'View '+delegated,'X-XMind-View-Origin':browserOrigin}})).status,200);
 // Two actual paused feeds consume the shared stream leases, while ordinary
 // commands retain capacity. Abort one observation; revoke the other by its
 // actual native view owner's exit. Neither action cancels the graph.
 const revocationRun=await native.graphRun(streamSession.id,waitGraph.id,waitGraph.revision,'Wait through view access revocation');await waitFor(async()=>{const value=await native.graph(revocationRun.id);return value.run.state==='paused'&&value;},'revocation graph pause');
 const viewHeaders={Authorization:'View '+delegated,'X-XMind-View-Origin':browserOrigin},viewClient=new BackendClient(first.origin,()=>access,(url,options)=>fetch(url,{...options,headers:{...options.headers,...viewHeaders}})),leaseAbort=new AbortController(),revokeAbort=new AbortController();
 observationAborts.push(leaseAbort,revokeAbort);let observedOne,observedTwo;const observationOne=new Promise(resolve=>observedOne=resolve),observationTwo=new Promise(resolve=>observedTwo=resolve);
 const leaseFeed=viewClient.eventStream(revocationRun.id,{scope:'graph',session_id:streamSession.id,signal:leaseAbort.signal,onObservation:observedOne,onEvent:()=>{}}).then(result=>({result}),error=>({error}));
 const revokeFeed=viewClient.eventStream(revocationRun.id,{scope:'graph',session_id:streamSession.id,signal:revokeAbort.signal,onObservation:observedTwo,onEvent:()=>{}}).then(result=>({result}),error=>({error}));
 let leaseTimer;try{await Promise.race([Promise.all([observationOne,observationTwo]),new Promise((_,reject)=>{leaseTimer=setTimeout(()=>reject(Error('Native lease observations timed out')),10000);})]);}finally{clearTimeout(leaseTimer);}
 const saturated=await fetch(first.origin+'/v1/graph-runs/'+revocationRun.id+'/events/stream?after=0',{headers:viewHeaders,signal:AbortSignal.timeout(5000)});assert.equal(saturated.status,503);assert.equal((await fetch(first.origin+'/v1/sessions',{headers:viewHeaders,signal:AbortSignal.timeout(5000)})).status,200);leaseAbort.abort();const detached=await leaseFeed;assert.ok(detached.error,'Aborting observation must interrupt its reader');assert.equal((await native.graph(revocationRun.id)).run.state,'paused');
 const workspaceB=workspaceCatalogue.workspaces.find(value=>value.root===workspace2Root),oldWorkspaceCookie=cookie,workspaceSwitch=await fetch(browserOrigin+'/ui/workspaces/select',{method:'POST',headers:{Cookie:cookie,Origin:browserOrigin,'Sec-Fetch-Site':'same-origin','Content-Type':'application/json'},body:JSON.stringify({workspace_id:workspaceB.workspace_id})});assert.equal(workspaceSwitch.status,200,await workspaceSwitch.clone().text());const switchedWorkspace=await workspaceSwitch.json();assert.equal(switchedWorkspace.workspace.workspace_id,workspaceB.workspace_id);cookie=workspaceSwitch.headers.get('set-cookie').split(';')[0];assert.notEqual(cookie,oldWorkspaceCookie);assert.ok(!JSON.stringify(switchedWorkspace).includes(cookie.slice(cookie.indexOf('=')+1)));const activeWorkspace=await fetch(browserOrigin+'/v1/workspace',{headers:{Cookie:cookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(activeWorkspace.status,200);assert.equal((await activeWorkspace.json()).root,workspace2Root);const secondSessions=await fetch(browserOrigin+'/v1/sessions',{headers:{Cookie:cookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(secondSessions.status,200);assert.deepEqual(await secondSessions.json(),[]);assert.equal((await fetch(browserOrigin+'/v1/health',{headers:{Cookie:oldWorkspaceCookie,'Sec-Fetch-Site':'same-origin'}})).status,401);assert.ok((await native.sessions()).some(value=>value.id===session.id));assert.deepEqual(await native.history(session.id),originalHistory);
 const viewIdentity=cp.spawnSync(exe,['admin','inspect-owner-process',String(owner.pid)],{env,encoding:'utf8',windowsHide:true});assert.equal(viewIdentity.status,0);host.dispose();const closed=cp.spawnSync(exe,['admin','observe-owner-exit',String(owner.pid),JSON.parse(viewIdentity.stdout).process_birth,'10000'],{env,encoding:'utf8',windowsHide:true});assert.equal(closed.status,0);assert.equal(JSON.parse(closed.stdout).exited,true);
 const revoked=await revokeFeed;revokeAbort.abort();assert.ok(!revoked.error,revoked.error?.message);assert.equal(revoked.result.reason,'reauthenticate');assert.equal((await command('graph',revocationRun.id)).run.state,'paused');assert.equal((await command('graph',revocationRun.id)).checkpoint.nodes.find(node=>node.id==='read').state,'pending');
 assert.equal((await fetch(first.origin+'/v1/sessions',{headers:{Authorization:'View '+delegated,'X-XMind-View-Origin':browserOrigin}})).status,401);await browser.close();browser=undefined;
 assert.equal((await inspect()).process_id,first.process_id);const reload=manager(),second=await reload.connect();assert.equal(second.backendPid,first.process_id);assert.equal(second.profileDirectory,first.profile_directory);assert.deepEqual(reload.stateFields(),scope);assert.deepEqual(await client(second).history(session.id),originalHistory);assert.ok((await client(second).sessions()).some(s=>s.id===session.id));
 passed=true;console.log(JSON.stringify({...sidebarEvidence,...writeEvidence,actualNativeView:true,unsafeRendezvousRejectedBeforeBackendStartup:true,actualProductionEditorHostAdapter:true,actualSharedConsoleBackend:true,actualToolGraph:true,browserCookieAccess:true,actualBrowserControllerStreaming:true,actualGatewayRestartScopedReplay:true,actualPausedFeedDetachAndReattach:true,actualHumanResumeIncrementalEvents:true,actualStreamCapacityAndCommandFairness:true,actualStreamReauthenticationAfterViewExit:true,backendTokenNeverExported:true,ownerControlRejected:true,duplicateGrantRejected:true,processBoundViewRevokedAfterExit:true,sameProfileAndHistoryAcrossHostReload:true,providerRequests:0,installedIde:false,renderedUi:false}));
}finally{for(const abort of observationAborts)abort.abort();for(const m of managers)m.dispose();if(browser)await browser.close();for(const pid of [...pids])try{await stop(pid);}catch(error){console.error('Owned profile cleanup: '+error.message);passed=false;}assert.equal(path.dirname(await fs.realpath(base)),parent);assert.ok(path.basename(base).startsWith('xmind-local-view-'));if(passed)await fs.rm(base,{recursive:true,force:true});else console.error(JSON.stringify({retainedFixture:base}));}
