// Actual unified binary, protected native rendezvous, backend ownership,
// embedded-xlang3 SQLite and native tool graph. Package provenance/notices are
// fixtures; no live provider, installed editor or release acceptance is claimed.
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {stageNativeRuntime} from '../../extensions/vscode/scripts/package-native-runtime.mjs';
const [program,dll,modules,stdlib]=process.argv.slice(2);assert.ok(stdlib);
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-local-profile-')),workspace=path.join(base,'workspace 雪'),profiles=path.join(base,'profiles'),bundle=path.join(base,'bundle'),runtime=path.join(base,'runtime'),graphs=path.join(base,'graphs.json'),sha=b=>createHash('sha256').update(b).digest('hex');
await fs.mkdir(workspace);await fs.mkdir(bundle);await fs.writeFile(path.join(workspace,'note.txt'),'Actual managed native workspace\n');await fs.writeFile(graphs,JSON.stringify({graphs:[{id:'profile.read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'note.txt'}}]}}]}));const files={};
for(const[name,source]of [['xmind.exe',program],['xlang3_runtime.dll',dll],['xlang3.exe',path.join(path.dirname(modules),'xlang3.exe')],...['xlang_json.x3pkg.dll','xlang_sqlite3.x3pkg.dll'].map(n=>['modules/'+n,path.join(modules,n)])]){const bytes=await fs.readFile(source);await fs.mkdir(path.dirname(path.join(bundle,name)),{recursive:true});await fs.writeFile(path.join(bundle,name),bytes);files[name]=sha(bytes);}
const notice=Buffer.from('Synthetic native profile contract provenance and notice. Not a release package.');await fs.mkdir(path.join(bundle,'licenses'));await fs.writeFile(path.join(bundle,'licenses/NOTICE.txt'),notice);files['licenses/NOTICE.txt']=sha(notice);
const source=Buffer.from(JSON.stringify({schemaVersion:1,platform:'win32',arch:'x64',bridgeEnabled:false,nativeRevision:'a'.repeat(40),sdkRevision:'b'.repeat(40),files}));const sourceFile=path.join(base,'source-manifest.json');await fs.writeFile(sourceFile,source);
await stageNativeRuntime({explicitStage:true,bundle,bundleManifest:sourceFile,bundleManifestSha256:sha(source),stdlibSource:stdlib,stdlibLicense:await fs.access(path.join(path.dirname(stdlib),'LICENSE')).then(()=>path.join(path.dirname(stdlib),'LICENSE'),()=>path.join(path.dirname(stdlib),'LICENSE.txt')),out:runtime});
const exe=path.join(runtime,'xmind.exe'),env={...process.env};for(const key of Object.keys(env))if(key==='XMIND_AUTH_TOKEN'||key==='XMIND_API_KEY'||key.startsWith('XMIND_UI_'))delete env[key];const pids=new Set();let passed=false;
function invoke(args,{input='',root=profiles,cwd=workspace}={}){return new Promise((yes,no)=>{const child=cp.spawn(exe,['--profile-root',root,...args],{cwd,env,windowsHide:true});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.once('error',no);const timer=setTimeout(()=>child.kill(),90000);child.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal,stdout,stderr});});child.stdin.end(input);});}
async function command(...args){const result=await invoke(args);assert.equal(result.code,0,result.stderr);assert.equal(result.signal,null);return JSON.parse(result.stdout);}
async function inspect(){const value=await command('profile-info');pids.add(value.process_id);return value;}
async function stop(pid){const check=cp.spawnSync(exe,['admin','inspect-owner-process',String(pid)],{env,windowsHide:true,encoding:'utf8'});assert.equal(check.status,0,check.stderr);process.kill(pid);const result=cp.spawnSync(exe,['admin','observe-owner-exit',String(pid),JSON.parse(check.stdout).process_birth,'10000'],{env,windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).exited,true);pids.delete(pid);}
try{
 const invalid=await invoke(['unknown-command']);assert.equal(invalid.code,1);await assert.rejects(fs.stat(profiles),{code:'ENOENT'});
 const emptyCatalogue=await invoke(['workspaces']);assert.equal(emptyCatalogue.code,0,emptyCatalogue.stderr);assert.deepEqual(JSON.parse(emptyCatalogue.stdout),{workspaces:[]});await assert.rejects(fs.stat(profiles),{code:'ENOENT'});
 const first=await invoke(['--graphs-config',graphs,'profile-info']);assert.equal(first.code,0,first.stderr);const started=JSON.parse(first.stdout);pids.add(started.process_id);assert.equal(started.started,true);assert.equal(started.workspace,await fs.realpath(workspace));assert.ok(started.profile_directory.startsWith(profiles+path.sep));assert.ok(!Object.hasOwn(started,'auth'));assert.equal((await fetch(started.origin+'/v1/health')).status,401);
 const catalogue=await invoke(['workspaces']);assert.equal(catalogue.code,0,catalogue.stderr);const known=JSON.parse(catalogue.stdout).workspaces;assert.equal(known.length,1);assert.equal(known[0].root,await fs.realpath(workspace));assert.equal(known[0].name,path.basename(workspace));assert.match(known[0].workspace_id,/^windows-local-file-v1:/);assert.ok(!catalogue.stdout.includes('auth'));assert.ok(!catalogue.stdout.includes(started.profile_directory));assert.equal((await inspect()).process_id,started.process_id);
 const clients=await Promise.all(Array.from({length:4},()=>invoke(['profile-info'])));for(const result of clients){assert.equal(result.code,0,result.stderr);const connected=JSON.parse(result.stdout);assert.equal(connected.origin,started.origin);assert.equal(connected.process_id,started.process_id);assert.equal(connected.profile_directory,started.profile_directory);assert.equal(connected.started,false);}
 const stateFile=path.join(started.profile_directory,'profile.state'),sealed=await fs.readFile(stateFile),opaque=JSON.parse(sealed);assert.deepEqual(Object.keys(opaque).sort(),['ciphertext','protection']);assert.equal(opaque.protection,'windows-dpapi-user-v1');assert.ok(!sealed.includes(Buffer.from('"auth"')));assert.ok(!sealed.includes(Buffer.from(workspace)));
 assert.deepEqual(await command('sessions'),[]);const session=await command('create-session','Managed native profile');const graph=(await command('graphs')).graphs.find(g=>g.id==='profile.read');assert.ok(graph);const run=await command('graph-run',session.id,graph.id,String(graph.revision),'Read the managed workspace');let record;const until=Date.now()+15000;while(Date.now()<until){record=await command('graph',run.id);if(record.run.state==='completed')break;}assert.equal(record.run.state,'completed');assert.equal(record.checkpoint.nodes[0].output.content,'Actual managed native workspace\n');const saved=await command('sessions'),history=await command('history',session.id);
 const terminal=await invoke([],{input:'/exit\n'});assert.equal(terminal.code,0,terminal.stderr);assert.equal((await inspect()).process_id,started.process_id);
 const changed=await invoke(['--read-only','profile-info']);assert.equal(changed.code,2);assert.match(changed.stderr,/edit policy changed/);assert.equal((await inspect()).process_id,started.process_id);assert.deepEqual(await command('sessions'),saved);
 const damaged=structuredClone(opaque);damaged.ciphertext=(damaged.ciphertext[0]==='0'?'1':'0')+damaged.ciphertext.slice(1);await fs.writeFile(stateFile,JSON.stringify(damaged));const refusal=await invoke(['profile-info']);assert.equal(refusal.code,2);await fs.writeFile(stateFile,sealed);assert.equal((await inspect()).process_id,started.process_id);assert.deepEqual(await command('history',session.id),history);
 await stop(started.process_id);const restarted=await inspect();assert.equal(restarted.started,true);assert.notEqual(restarted.process_id,started.process_id);assert.equal(restarted.profile_directory,started.profile_directory);assert.deepEqual(await command('sessions'),saved);assert.deepEqual(await command('history',session.id),history);assert.equal((await command('graph',run.id)).run.state,'completed');
 const overlap=await invoke(['profile-info'],{root:path.join(workspace,'private')});assert.equal(overlap.code,2);assert.match(overlap.stderr,/overlaps/);await assert.rejects(fs.stat(path.join(workspace,'private')),{code:'ENOENT'});passed=true;
 console.log(JSON.stringify({actualManagedNativeStartup:true,authenticatedNativeOwnerVerified:true,concurrentReattachmentSameOwner:true,encryptedRendezvous:true,consoleDetachKeepsOwner:true,changedPolicyAndDamagedRecordRefused:true,actualToolGraph:true,sameSqliteProfileAfterObservedExit:true,historyExactAfterRestart:true,privateStorageExclusion:true,providerRequests:0,releasePackage:false,installedIde:false}));
}finally{for(const pid of [...pids])try{await stop(pid);}catch(error){console.error('Owned profile cleanup: '+error.message);passed=false;}assert.equal(path.dirname(await fs.realpath(base)),parent);assert.ok(path.basename(base).startsWith('xmind-local-profile-'));if(passed)await fs.rm(base,{recursive:true,force:true});else console.error(JSON.stringify({retainedFixture:base}));}
