// Actual native view, production editor host adapter, native controller and backend.
// VS Code API configuration is a fixture; no installed/rendered IDE claim.
// Actual unified binary, protected native rendezvous, backend ownership,
// embedded-xlang3 SQLite and native tool graph. Package provenance/notices are
// fixtures; no live provider, installed editor or release acceptance is claimed.
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {stageNativeRuntime} from '../../extensions/vscode/scripts/package-native-runtime.mjs';
import {existsSync} from 'node:fs';
const [program,dll,modules,stdlib]=process.argv.slice(2);assert.ok(stdlib);
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-local-view-')),workspace=path.join(base,'workspace 雪'),profiles=path.join(base,'profiles'),bundle=path.join(base,'bundle'),runtime=path.join(base,'runtime'),graphs=path.join(base,'graphs.json'),sha=b=>createHash('sha256').update(b).digest('hex');
await fs.mkdir(workspace);await fs.mkdir(bundle);await fs.writeFile(path.join(workspace,'note.txt'),'Actual managed native workspace\n');await fs.writeFile(graphs,JSON.stringify({graphs:[{id:'profile.read',spec:{nodes:[{id:'read',type:'tool',tool:'read_file',arguments:{path:'note.txt'}}]}}]}));const files={};
for(const[name,source]of [['xmind.exe',program],['xlang3_runtime.dll',dll],['xlang3.exe',path.join(path.dirname(modules),'xlang3.exe')],...['xlang_json.x3pkg.dll','xlang_sqlite3.x3pkg.dll'].map(n=>['modules/'+n,path.join(modules,n)])]){const bytes=await fs.readFile(source);await fs.mkdir(path.dirname(path.join(bundle,name)),{recursive:true});await fs.writeFile(path.join(bundle,name),bytes);files[name]=sha(bytes);}
const notice=Buffer.from('Synthetic native profile contract provenance and notice. Not a release package.');await fs.mkdir(path.join(bundle,'licenses'));await fs.writeFile(path.join(bundle,'licenses/NOTICE.txt'),notice);files['licenses/NOTICE.txt']=sha(notice);
const source=Buffer.from(JSON.stringify({schemaVersion:1,platform:'win32',arch:'x64',bridgeEnabled:false,nativeRevision:'a'.repeat(40),sdkRevision:'b'.repeat(40),files}));const sourceFile=path.join(base,'source-manifest.json');await fs.writeFile(sourceFile,source);
cp.execFileSync(process.execPath,[new URL("../../views/browser/build.mjs",import.meta.url).pathname.slice(1),path.join(base,"browser-assets")],{windowsHide:true,stdio:"ignore"});
await stageNativeRuntime({explicitStage:true,bundle,bundleManifest:sourceFile,bundleManifestSha256:sha(source),stdlibSource:stdlib,stdlibLicense:await fs.access(path.join(path.dirname(stdlib),'LICENSE')).then(()=>path.join(path.dirname(stdlib),'LICENSE'),()=>path.join(path.dirname(stdlib),'LICENSE.txt')),out:runtime});
const exe=path.join(runtime,'xmind.exe'),env={...process.env};for(const key of Object.keys(env))if(key==='XMIND_AUTH_TOKEN'||key==='XMIND_API_KEY'||key.startsWith('XMIND_UI_'))delete env[key];const pids=new Set();let passed=false;const managers=[];let browser;
function invoke(args,{input='',root=profiles,cwd=workspace}={}){return new Promise((yes,no)=>{const child=cp.spawn(exe,['--profile-root',root,...args],{cwd,env,windowsHide:true});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.once('error',no);const timer=setTimeout(()=>child.kill(),60000);child.once('close',(code,signal)=>{clearTimeout(timer);yes({code,signal,stdout,stderr});});child.stdin.end(input);});}
async function command(...args){const result=await invoke(args);assert.equal(result.code,0,result.stderr);assert.equal(result.signal,null);return JSON.parse(result.stdout);}
async function inspect(){const value=await command('profile-info');pids.add(value.process_id);return value;}
async function stop(pid){const check=cp.spawnSync(exe,['admin','inspect-owner-process',String(pid)],{env,windowsHide:true,encoding:'utf8'});assert.equal(check.status,0,check.stderr);process.kill(pid);const result=cp.spawnSync(exe,['admin','observe-owner-exit',String(pid),JSON.parse(check.stdout).process_birth,'10000'],{env,windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).exited,true);pids.delete(pid);}

const {createRequire}=await import('node:module'),require=createRequire(import.meta.url);
const {WorkspaceBackend}=require('../../extensions/vscode/workspace-backend.js');
const {resolveNativeRuntime}=require('../../extensions/vscode/native-runtime.js');
const {BackendClient}=require('../../extensions/vscode/client.js');
const {createBrowserServer}=await import('../../views/browser/server.mjs');
const secrets=new Map(),state=new Map(),settings={runtimeDirectory:runtime,stdlibSource:'',providerConfigPath:'',workspaceEdits:true};
const context={extensionUri:{fsPath:path.join(base,'extension')},globalStorageUri:{fsPath:path.join(base,'view-hosts')},workspaceState:{get:k=>state.get(k),update:async(k,v)=>state.set(k,v)},secrets:{get:async k=>secrets.get(k),store:async(k,v)=>secrets.set(k,v),delete:async k=>secrets.delete(k)},globalState:{get:()=>{throw Error('Editor owner registry must not be read');},update:()=>{throw Error('Editor owner registry must not be written');}}};
const vscode={env:{},workspace:{isTrusted:true,workspaceFolders:[{name:'Actual native view',uri:{scheme:'file',fsPath:workspace,toString:()=> 'file:///'+workspace}}],getConfiguration:()=>({inspect:k=>({globalValue:settings[k]})})}};
const manager=()=>{const m=new WorkspaceBackend(vscode,context,resolveNativeRuntime,{profileRoot:profiles,env,spawn:(program,args,options)=>{const readyParent=path.dirname(args[args.indexOf('--ready-file')+1]);assert.equal(existsSync(readyParent),false,'The editor must leave protected rendezvous directory creation to native');const child=cp.spawn(program,args,{...options,stdio:['ignore','ignore','pipe']});child.stderr.on('data',bytes=>process.stderr.write(bytes));return child;}});managers.push(m);return m;};
const client=owner=>new BackendClient(owner.origin,()=>context.secrets.get('xmind.auth:'+owner.origin));
try{
 const unsafeReady=path.join(workspace,'ready.json'),beforeStartup=cp.spawnSync(exe,['view','--workspace',workspace,'--profile-root',profiles,'--ready-file',unsafeReady],{env:{...env,XMIND_VIEW_TOKEN:'d'.repeat(64)},windowsHide:true,encoding:'utf8',timeout:15000});assert.equal(beforeStartup.status,2,beforeStartup.stderr);assert.match(beforeStartup.stderr,/overlaps/);await assert.rejects(fs.stat(profiles),{code:'ENOENT'});await assert.rejects(fs.stat(unsafeReady),{code:'ENOENT'});
 const first=await command('--graphs-config',graphs,'profile-info');pids.add(first.process_id);
 const host=manager(),owner=await host.connect(),access=await context.secrets.get('xmind.auth:'+owner.origin);assert.equal(owner.backendPid,first.process_id);assert.equal(owner.profileDirectory,first.profile_directory);assert.equal((await fetch(owner.origin+'/v1/health')).status,401);assert.equal((await fetch(owner.origin+'/v1/health',{headers:{Authorization:'Bearer '+access,Origin:'http://untrusted.invalid'}})).status,403);
 const ready=await fs.readFile(path.join(owner.privateDirectory,'ready.json'),'utf8');assert.ok(!ready.includes(access));assert.ok(!ready.includes('"auth"'));assert.ok(!ready.includes('"token"'));
 const native=client(owner).bindWorkspace(host),title='Shared console and editor native profile 雪 "quoted"',session=await native.createSession(title);assert.equal(session.title,title);assert.ok((await command('sessions')).some(s=>s.id===session.id&&s.title===title));
 // Exercise body reading in the actual native adapter, including chunked UTF-8.
 const chunkedTitle='Chunked native view write 雪',chunkedBytes=Buffer.from(JSON.stringify({title:chunkedTitle}));
 const chunked=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},duplex:'half',body:new ReadableStream({start(controller){for(let i=0;i<chunkedBytes.length;i+=7)controller.enqueue(chunkedBytes.subarray(i,i+7));controller.close();}})});assert.equal(chunked.status,201,await chunked.clone().text());const chunkedSession=await chunked.json();assert.equal(chunkedSession.title,chunkedTitle);assert.ok((await command('sessions')).some(s=>s.id===chunkedSession.id&&s.title===chunkedTitle));
 const malformed=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{"title":'});assert.equal(malformed.status,400);
 const oversized=await fetch(owner.origin+'/v1/sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'x'.repeat(1024*1024+1)});assert.equal(oversized.status,413);assert.equal((await command('sessions')).length,2);
 const graph=(await native.graphs()).graphs.find(g=>g.id==='profile.read'),run=await native.graphRun(session.id,graph.id,graph.revision,'Read the actual shared workspace');let outcome;const until=Date.now()+15000;while(Date.now()<until){outcome=await native.graph(run.id);if(outcome.run.state==='completed')break;await new Promise(r=>setTimeout(r,40));}assert.equal(outcome.run.state,'completed');assert.equal(outcome.checkpoint.nodes[0].output.content,'Actual managed native workspace\n');
 const originalHistory=await native.history(session.id),scope=host.stateFields();assert.deepEqual(await command('history',session.id),originalHistory);
 assert.equal((await fetch(owner.origin+'/v1/backend/owner/quiesce',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{}'})).status,401);
 const invalidGrant=await fetch(owner.origin+'/v1/view-sessions',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:'{"origin":"http://127.0.0.1:19000","origin":"http://127.0.0.1:19000"}'});assert.equal(invalidGrant.status,400);
 browser=await createBrowserServer({backend:owner.origin,assetRoot:path.join(base,'browser-assets')});const browserOrigin=await browser.listen();
 const connected=await fetch(browserOrigin+'/ui/session',{method:'POST',headers:{Authorization:'Bearer '+access,Origin:browserOrigin,'Content-Type':'application/json'},body:'{}'});assert.equal(connected.status,200,await connected.text());const cookie=connected.headers.get('set-cookie').split(';')[0];
 const browserSessions=await fetch(browserOrigin+'/v1/sessions',{headers:{Cookie:cookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(browserSessions.status,200);assert.ok((await browserSessions.json()).some(s=>s.id===session.id));
 const delegated=cookie.slice(cookie.indexOf('=')+1);assert.equal((await fetch(first.origin+'/v1/sessions',{headers:{Authorization:'View '+delegated,'X-XMind-View-Origin':browserOrigin}})).status,200);
 const viewIdentity=cp.spawnSync(exe,['admin','inspect-owner-process',String(owner.pid)],{env,encoding:'utf8',windowsHide:true});assert.equal(viewIdentity.status,0);host.dispose();const closed=cp.spawnSync(exe,['admin','observe-owner-exit',String(owner.pid),JSON.parse(viewIdentity.stdout).process_birth,'10000'],{env,encoding:'utf8',windowsHide:true});assert.equal(closed.status,0);assert.equal(JSON.parse(closed.stdout).exited,true);
 assert.equal((await fetch(first.origin+'/v1/sessions',{headers:{Authorization:'View '+delegated,'X-XMind-View-Origin':browserOrigin}})).status,401);await browser.close();browser=undefined;
 assert.equal((await inspect()).process_id,first.process_id);const reload=manager(),second=await reload.connect();assert.equal(second.backendPid,first.process_id);assert.equal(second.profileDirectory,first.profile_directory);assert.deepEqual(reload.stateFields(),scope);assert.deepEqual(await client(second).history(session.id),originalHistory);assert.ok((await client(second).sessions()).some(s=>s.id===session.id));
 passed=true;console.log(JSON.stringify({actualNativeView:true,unsafeRendezvousRejectedBeforeBackendStartup:true,actualProductionEditorHostAdapter:true,actualSharedConsoleBackend:true,actualToolGraph:true,browserCookieAccess:true,backendTokenNeverExported:true,ownerControlRejected:true,duplicateGrantRejected:true,processBoundViewRevokedAfterExit:true,sameProfileAndHistoryAcrossHostReload:true,providerRequests:0,installedIde:false,renderedUi:false}));
}finally{for(const m of managers)m.dispose();if(browser)await browser.close();for(const pid of [...pids])try{await stop(pid);}catch(error){console.error('Owned profile cleanup: '+error.message);passed=false;}assert.equal(path.dirname(await fs.realpath(base)),parent);assert.ok(path.basename(base).startsWith('xmind-local-view-'));if(passed)await fs.rm(base,{recursive:true,force:true});else console.error(JSON.stringify({retainedFixture:base}));}
