// Production extension/controller, WorkspaceBackend, client and compiled native
// runtime. VS Code API/webview are explicitly fixtures; no rendered IDE claim.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),clientModule=require('../../extensions/vscode/client.js');
const {WorkspaceBackend}=require('../../extensions/vscode/workspace-backend.js');
const extensionFile=path.resolve(import.meta.dirname,'../../extensions/vscode/extension.js');
const extensionRequire=createRequire(extensionFile);
const wait=async(read,label)=>{const until=Date.now()+15000;while(Date.now()<until){const value=await read();if(value)return value;await new Promise(resolve=>setTimeout(resolve,40));}throw Error('Native sidebar timeout: '+label);};
export async function exerciseNativeSidebar({runtime,workspace,profileRoot,storage,env,native,session,run}){
 const commands=new Map(),secrets=new Map(),state=new Map(),views=[],managers=[],feeds=[],errors=[];let provider;
 const settings={backendMode:'workspace',runtimeDirectory:runtime,stdlibSource:'',providerConfigPath:'',workspaceEdits:true};
 const uri=file=>({scheme:'file',fsPath:file,toString:()=> 'file:///'+file});
 const disposable=()=>({dispose(){}});
 const context={extensionMode:1,extensionUri:uri(path.dirname(extensionFile)),globalStorageUri:uri(storage),subscriptions:[],workspaceState:{get:key=>state.get(key),update:async(key,value)=>state.set(key,value)},secrets:{get:async key=>secrets.get(key),store:async(key,value)=>secrets.set(key,value),delete:async key=>secrets.delete(key)},globalState:{get:()=>{throw Error('Native must own backend discovery');},update:()=>{throw Error('Native must own backend discovery');}}};
 const makeView=()=>{const view={posted:[],webview:{cspSource:'https://native-sidebar-fixture',asWebviewUri:value=>value,postMessage:message=>{view.posted.push(message);return Promise.resolve(true);},onDidReceiveMessage:callback=>{view.receive=callback;return disposable();}},onDidDispose:callback=>{view.close=callback;return disposable();},show(){}};views.push(view);return view;};
 const vscode={ExtensionMode:{Development:2},ConfigurationTarget:{Global:1},Uri:{parse:value=>({toString:()=>value}),joinPath:(root,...parts)=>uri(path.join(root.fsPath,...parts))},env:{},workspace:{isTrusted:true,workspaceFolders:[{name:'Actual native sidebar',uri:uri(workspace)}],getConfiguration:()=>({inspect:key=>({globalValue:settings[key]})}),onDidChangeWorkspaceFolders:()=>disposable(),onDidChangeConfiguration:()=>disposable(),registerTextDocumentContentProvider:()=>disposable()},window:{registerWebviewViewProvider:(id,value)=>{assert.equal(id,'xmind.workspace');provider=value;return disposable();},showErrorMessage:message=>{errors.push(message);return undefined;},showInputBox:async()=>{throw Error('Native sidebar must use its protected view credential');},showInformationMessage:async()=>undefined},commands:{registerCommand:(id,callback)=>{commands.set(id,callback);return disposable();},executeCommand:async id=>{if(id==='xmind.workspace.focus')provider.resolveWebviewView(makeView());else assert.ok(['workbench.view.extension.xmind','workbench.view.explorer'].includes(id),'Unexpected fixture UI command');}}};
 class NativeWorkspaceBackend extends WorkspaceBackend {constructor(api,ctx,resolveRuntime){super(api,ctx,resolveRuntime,{profileRoot,env});managers.push(this);}}
 class ObservedClient extends clientModule.BackendClient {eventStream(id,options){const feed={id,signal:options.signal,after:options.after,events:[],observed:false};feeds.push(feed);return super.eventStream(id,{...options,onObservation:async value=>{await options.onObservation?.(value);feed.observed=true;},onEvent:async event=>{await options.onEvent(event);feed.events.push(event);}});}}
 const sandbox={module:{exports:{}},URL,setTimeout,clearTimeout,setInterval:()=>{throw Error('The production sidebar must not start a periodic observation timer');},clearInterval(){},require:name=>name==='vscode'?vscode:name==='./client'?{...clientModule,BackendClient:ObservedClient}:name==='./workspace-backend'?{...extensionRequire(name),WorkspaceBackend:NativeWorkspaceBackend}:extensionRequire(name)};
 vm.runInNewContext(await fs.readFile(extensionFile,'utf8'),sandbox,{filename:extensionFile});
 try{
  await sandbox.module.exports.activate(context);await commands.get('agentflow.open')();assert.deepEqual(errors,[]);assert.equal(views.length,1);let view=views.at(-1);view.receive({type:'ready'});view.receive({type:'select',id:session.id});
  await wait(()=>view.posted.findLast(message=>message.type==='graph'&&message.record.run.id===run.id)?.record.run.state==='paused'&&feeds.at(-1)?.observed,'actual paused sidebar');const old=view,oldReceive=view.receive,oldFeed=feeds.at(-1),before=await native.graphEvents(run.id,0);
  await wait(()=>oldFeed.events.at(-1)?.seq===before.at(-1).seq||oldFeed.after===before.at(-1).seq,'actual sidebar committed replay');old.close();assert.equal(oldFeed.signal.aborted,true);assert.equal((await native.graph(run.id)).run.state,'paused');assert.equal((await native.graphChildren(run.id)).length,0);
  await commands.get('agentflow.open')();view=views.at(-1);assert.notEqual(view,old);view.receive({type:'ready'});view.receive({type:'select',id:session.id});await wait(()=>view.posted.findLast(message=>message.type==='graph'&&message.record.run.id===run.id)?.record.run.state==='paused'&&feeds.at(-1)?.observed,'actual reattached sidebar');
  const record=view.posted.findLast(message=>message.type==='graph').record;oldReceive({type:'graph-input',root:run.id,node:'gate',input_json:'{"continue":true}',revision:record.checkpoint_revision});await new Promise(resolve=>setTimeout(resolve,100));assert.equal((await native.graph(run.id)).run.state,'paused');
  view.receive({type:'graph-input',root:run.id,node:'gate',input_json:'{"continue":true}',revision:record.checkpoint_revision});const finished=await wait(async()=>{const value=await native.graph(run.id);return value.run.state==='completed'&&value;},'actual sidebar human/tool completion');assert.equal(finished.checkpoint.nodes.find(node=>node.id==='read').output.content,'Actual managed native workspace\n');
  await wait(()=>view.posted.findLast(message=>message.type==='status')?.text==='completed'&&view.posted.some(message=>message.type==='transcript'),'actual terminal sidebar');assert.ok(feeds.flatMap(feed=>feed.events).some(event=>event.seq>before.at(-1).seq));assert.equal((await native.graphChildren(run.id)).length,1);assert.deepEqual(JSON.parse(JSON.stringify(view.posted.findLast(message=>message.type==='transcript').history)),await native.history(session.id));assert.ok(!view.posted.some(message=>message.type==='error'),JSON.stringify(view.posted.filter(message=>message.type==='error')));view.close();
  assert.deepEqual(errors,[]);return {actualProductionExtensionController:true,actualNativeSidebarSubscription:true,actualSidebarDetachReattach:true,retiredSidebarCannotSubmitInput:true,actualSidebarHumanToolCompletion:true,installedIde:false,renderedIde:false,providerRequests:0};
 }finally{for(const item of context.subscriptions)item.dispose?.();for(const manager of managers)manager.dispose();}
}
