#include "agentflow/provider_setup.hpp"
#include "agentflow/xlang_sqlite.hpp"
#include "agentflow/http_server.hpp"
#include "httplib.h"
#include "nlohmann/json.hpp"
#include <filesystem>
#include <iostream>
#include <thread>
using namespace agentflow;using Json=nlohmann::json;
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Error,class Action>void rejects(Action action){try{action();}catch(const Error&){return;}throw std::runtime_error("Expected provider setup rejection");}
SecretBytes key(){const std::string fixture="synthetic-provider-setup-key";return SecretBytes({reinterpret_cast<const std::uint8_t*>(fixture.data()),fixture.size()});}
struct Access{HttpServer server;int port;std::thread worker;Access(PersistenceService& store,ProviderRuntime& runtime):server(store,"synthetic-provider-setup-server-access-token",&runtime,nullptr,{}, {},{},&runtime),port(server.bind(0)) {worker=std::thread([this]{server.listen();});}~Access(){server.stop();if(worker.joinable())worker.join();}};
int main(int argc,char** argv){if(argc!=5)return 2;try{
 const auto database=(std::filesystem::u8path(argv[1])/"provider.sqlite").string();const std::vector<std::string> imports{argv[2],argv[3]};
 {PersistenceService store(database,imports);AgentSettings base;ProviderRuntime runtime(store,base,2,128,argv[4],std::string(argv[4])+"/models");require(!runtime.available() && runtime.models().empty() && runtime.configuration().revision==0,"Fresh provider must remain unavailable");rejects<RunUnavailable>([&]{runtime.submit("not-admitted","none","fixture");});Access access(store,runtime);httplib::Client client("127.0.0.1",access.port);client.set_connection_timeout(5);client.set_read_timeout(5);const httplib::Headers authorization{{"Authorization","Bearer synthetic-provider-setup-server-access-token"}};
  const auto unauthorized=client.Get("/v1/provider/configuration");require(unauthorized && unauthorized->status==401,"Provider metadata/setup must require local-owner authentication");const auto initial=client.Get("/v1/provider/configuration",authorization);require(initial && initial->status==200 && Json::parse(initial->body)["configured"]==false,"Actual native setup metadata must remain unconfigured before enrollment");
  const auto redirect=client.Post("/v1/provider/configuration",authorization,R"({"model":"fixture-model","api_key":"synthetic-provider-setup-key","expected_revision":0,"endpoint":"https://outside.invalid"})","application/json");require(redirect && redirect->status==400,"Client must not replace backend provider destination");
  const auto anonymous=client.Post("/v1/provider/models",R"({"api_key":"synthetic-provider-setup-key","expected_revision":0})","application/json");require(anonymous && anonymous->status==401,"Discovery must require backend authentication");
  const auto spoof=client.Post("/v1/provider/models",authorization,R"({"api_key":"synthetic-provider-setup-key","expected_revision":0,"endpoint":"https://outside.invalid"})","application/json");require(spoof && spoof->status==400,"Discovery destination remains native policy");
  const auto discovered=client.Post("/v1/provider/models",authorization,R"({"api_key":"synthetic-provider-setup-key","expected_revision":0})","application/json");require(discovered && discovered->status==200 && Json::parse(discovered->body)==Json{{"models",Json::array({Json{{"id","fixture-model"}},Json{{"id","fixture-other"}}})}},"Discovery must return actual sorted deduplicated peer model IDs only");require(!runtime.available() && store.credentials("server").get().empty(),"Discovery must not configure or persist a key");
  for(const auto* invalid:{"fixture-rejected-key","fixture-malformed-key"}){const auto failure=client.Post("/v1/provider/models",authorization,Json{{"api_key",invalid},{"expected_revision",0}}.dump(),"application/json");require(failure && failure->status==502 && failure->body.find(invalid)==std::string::npos,"Provider failure must not echo its key or response payload");
    if(std::string(invalid)=="fixture-rejected-key"){
      const auto fields=Json::parse(failure->body);require(fields["provider_status"]==401 && fields["provider_error_type"]=="authentication_error" && fields["provider_error_code"]=="invalid_api_key","Discovery must preserve safe provider diagnostics");
      require(!fields.contains("provider_error_param") && fields["detail"].get<std::string>().find("invalid_api_key")!=std::string::npos,"Unknown parameters must be omitted while safe identifiers remain visible to existing clients");
    }
  }
  const auto staleDiscovery=client.Post("/v1/provider/models",authorization,R"({"api_key":"synthetic-provider-setup-key","expected_revision":1})","application/json");require(staleDiscovery && staleDiscovery->status==409,"Discovery must reject a stale provider revision before external access");
  const auto missingKey=client.Post("/v1/provider/models",authorization,R"({"expected_revision":0})","application/json");require(missingKey && missingKey->status==400,"Fresh setup requires a key; omitted key must not produce an unauthenticated provider request");rejects<std::invalid_argument>([&]{runtime.configure("sk-fixture-private-key",key(),0);});rejects<std::invalid_argument>([&]{runtime.configure("synthetic-provider-setup-key",key(),0);});
  const auto setup=client.Post("/v1/provider/configuration",authorization,R"({"model":"fixture-model","api_key":"synthetic-provider-setup-key","expected_revision":0})","application/json");require(setup && setup->status==200 && Json::parse(setup->body)["revision"]==1 && runtime.available(),"Actual authenticated encrypted setup must activate native service");require(setup->body.find("synthetic-provider-setup-key")==std::string::npos,"Setup response must not echo the provider secret");const auto saved=store.information("native-provider","active").get();require(saved.find("synthetic-provider-setup-key")==std::string::npos,"Public configuration must not retain plaintext key");const auto credentials=store.credentials("server").get();require(credentials.size()==1,"Setup must use encrypted backend credential repository");rejects<Conflict>([&]{runtime.configure("fixture-other",key(),0);});
  store.create_session("session","Actual runtime setup with synthetic inference").get();const auto run=runtime.submit("run","session","Actual provider setup fixture task");rejects<Conflict>([&]{runtime.configure("fixture-other",key(),1);});std::cout<<"fixture-release\n"<<std::flush;
  const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(10);Run state=run;while(state.state==RunState::queued || state.state==RunState::running){require(std::chrono::steady_clock::now()<deadline,"Configured native run timed out");std::this_thread::sleep_for(std::chrono::milliseconds(5));state=store.run(run.id).get();}require(state.state==RunState::completed,"Actual configured native transport must complete");
  require(runtime.configuration().configured,"Runtime lost provider configuration");
  {XlangSqlite inject(database,imports);inject.execute("CREATE TRIGGER reject_provider_setup BEFORE UPDATE ON information WHEN NEW.category='native-provider' BEGIN SELECT RAISE(ABORT,'actual provider setup fixture failure'); END");}
  // Worker retirement may lag its final ledger row. Wait for a configuration
  // attempt to cross the idle boundary, without changing the active record.
  bool fault=false;const auto idleDeadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(!fault){try{runtime.configure("fixture-other",key(),1);}catch(const Conflict&){require(std::chrono::steady_clock::now()<idleDeadline,"Worker did not release provider ownership");std::this_thread::sleep_for(std::chrono::milliseconds(5));}catch(const DatabaseError&){fault=true;}}
  require(store.information("native-provider","active").get()==saved && runtime.configuration().model=="fixture-model","Failed actual configuration transaction must retain old service and credential reference");{XlangSqlite inject(database,imports);inject.execute("DROP TRIGGER reject_provider_setup");}
 }
 {PersistenceService store(database,imports);ProviderRuntime reopened(store,{},2,128,argv[4],std::string(argv[4])+"/models");require(reopened.available() && reopened.configuration().revision==1 && reopened.models().front()=="fixture-model","Actual reopen must restore model and encrypted credential");Access access(store,reopened);httplib::Client client("127.0.0.1",access.port);client.set_read_timeout(5);const httplib::Headers authorization{{"Authorization","Bearer synthetic-provider-setup-server-access-token"}};const auto discovery=client.Post("/v1/provider/models",authorization,R"({"expected_revision":1})","application/json");require(discovery && discovery->status==200,"Discovery must resolve encrypted saved key after restart without sending key to client");const auto configured=client.Post("/v1/provider/configuration",authorization,R"({"model":"fixture-other","expected_revision":1})","application/json");require(configured && configured->status==200 && reopened.configuration().revision==2 && reopened.models().front()=="fixture-other","Selection must reuse saved encrypted key without another password input");std::cout<<"fixture-cli-port:"<<access.port<<'\n'<<std::flush;std::string observed;require(static_cast<bool>(std::getline(std::cin,observed)) && observed=="fixture-cli-done","Actual CLI discovery fixture failed or did not report completion");}
 // Inject a key-shaped legacy identity, distinct from the fixture credential.
 // This checks masking/repair without making secure-erasure claims about pages.
 {PersistenceService store(database,imports);auto legacy=Json::parse(store.information("native-provider","active").get());legacy["model"]="sk-fixture-legacy-identity";store.put_information("native-provider","active",legacy.dump()).get();}
 {PersistenceService store(database,imports);ProviderRuntime legacy(store,{},2,128,argv[4],std::string(argv[4])+"/models");require(legacy.configuration().configured && legacy.configuration().model.empty() && legacy.models().empty() && !legacy.available(),"An older credential accidentally entered as model must not be advertised or enable inference");const auto models=legacy.discover(SecretBytes(std::span<const std::uint8_t>{}),2);require(models.size()==2,"Legacy repair must reuse encrypted key for actual discovery");const auto repaired=legacy.configure("fixture-model",SecretBytes(std::span<const std::uint8_t>{}),2);require(repaired.revision==3 && legacy.available(),"Actual discovered selection must repair legacy enrollment");}
 const auto wireDatabase=(std::filesystem::u8path(argv[1])/"wire.sqlite").string(),chatEndpoint=std::string(argv[4]),responsesEndpoint=chatEndpoint+"/responses";
 {
   PersistenceService store(wireDatabase,imports);ProviderRuntime routed(store,{},2,128,chatEndpoint,chatEndpoint+"/models",responsesEndpoint);
   const auto original=routed.configure("fixture-model",key(),0);require(original.wire==ProviderWire::chat_completions && original.endpoint==chatEndpoint,"Custom backend must retain its configured chat endpoint");
   const auto oldRecord=Json::parse(store.information("native-provider","active").get());
   const auto selected=routed.configure("gpt-5.6-sol",SecretBytes(std::span<const std::uint8_t>{}),1);
   const auto newRecord=Json::parse(store.information("native-provider","active").get());
   require(selected.wire==ProviderWire::responses && selected.endpoint==responsesEndpoint && selected.revision==2,"Reasoning model enrollment must use the approved native Responses route");
   require(newRecord["wire"]=="responses" && oldRecord["credential_id"]!=newRecord["credential_id"],"Wire change must persist a newly bound credential identity");
   Access access(store,routed);httplib::Client client("127.0.0.1",access.port);const auto metadata=client.Get("/v1/provider/configuration",httplib::Headers{{"Authorization","Bearer synthetic-provider-setup-server-access-token"}});require(metadata && Json::parse(metadata->body)["wire"]=="responses","Clients must observe the selected wire without receiving the key");
   store.create_session("wire-session","Synthetic provider enrollment protocol fixture").get();const auto admitted=routed.submit("wire-run","wire-session","Responses enrollment fixture");
   auto observed=admitted;const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);
   while(observed.state==RunState::queued||observed.state==RunState::running){require(std::chrono::steady_clock::now()<deadline,"Enrolled Responses request did not settle");std::this_thread::sleep_for(std::chrono::milliseconds(5));observed=store.run(admitted.id).get();}
   require(observed.state==RunState::completed,"Saved-provider routing must complete through actual native Responses transport");
   const auto history=store.history("wire-session").get();require(history.size()==2 && Json::parse(history.back().json)["usage"]["prompt_tokens"]==11,"Enrolled Responses output must persist actual supplied usage");
 }
 {
   PersistenceService store(wireDatabase,imports);ProviderRuntime reopened(store,{},2,128,chatEndpoint,chatEndpoint+"/models",responsesEndpoint);
   require(reopened.available() && reopened.configuration().wire==ProviderWire::responses && reopened.configuration().endpoint==responsesEndpoint,"Restart must restore Responses routing and its saved credential");
   require(store.run("wire-run").get().state==RunState::completed && store.history("wire-session").get().size()==2,"Reopen must retain the real Responses conversation without replay");
   const auto savedWire=store.information("native-provider","active").get();
   {XlangSqlite inject(wireDatabase,imports);inject.execute("CREATE TRIGGER reject_wire_setup BEFORE UPDATE ON information WHEN NEW.category='native-provider' BEGIN SELECT RAISE(ABORT,'actual wire publication failure'); END");}
   rejects<DatabaseError>([&]{reopened.configure("fixture-model",SecretBytes(std::span<const std::uint8_t>{}),2);});
   require(store.information("native-provider","active").get()==savedWire && reopened.configuration().wire==ProviderWire::responses && reopened.configuration().revision==2,"Failed wire publication must preserve the previous route and credential reference");
   {XlangSqlite inject(wireDatabase,imports);inject.execute("DROP TRIGGER reject_wire_setup");}
   store.create_session("wire-rollback-session","Synthetic rollback transport fixture").get();const auto rollbackRun=reopened.submit("wire-rollback-run","wire-rollback-session","Responses enrollment fixture");auto rollbackState=rollbackRun;const auto rollbackDeadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);
   while(rollbackState.state==RunState::queued||rollbackState.state==RunState::running){require(std::chrono::steady_clock::now()<rollbackDeadline,"Preserved wire transport did not settle");std::this_thread::sleep_for(std::chrono::milliseconds(5));rollbackState=store.run(rollbackRun.id).get();}
   require(rollbackState.state==RunState::completed,"Previous Responses service and saved credential must remain usable after publication failure");
   ProviderSetupMetadata restored;bool changed=false;const auto idleDeadline=std::chrono::steady_clock::now()+std::chrono::seconds(5);
   while(!changed){try{restored=reopened.configure("fixture-model",SecretBytes(std::span<const std::uint8_t>{}),2);changed=true;}catch(const Conflict&){require(std::chrono::steady_clock::now()<idleDeadline,"Wire worker did not release ownership");std::this_thread::sleep_for(std::chrono::milliseconds(5));}}
   require(restored.wire==ProviderWire::chat_completions && restored.endpoint==chatEndpoint,"Legacy selection must rebind the saved credential to the approved Chat route");
 }
 {
   PersistenceService store(wireDatabase,imports);auto value=Json::parse(store.information("native-provider","active").get());value["wire"]="responses";value["endpoint"]="https://unapproved.invalid/v1/responses";store.put_information("native-provider","active",value.dump()).get();
   rejects<DatabaseError>([&]{ProviderRuntime invalid(store,{},2,128,chatEndpoint,chatEndpoint+"/models",responsesEndpoint);});
 }
 std::cout<<"Provider setup passed actual native discovery/transport, encrypted xlang3 storage, saved-key reuse, native wire routing/rebinding/reopen, unapproved endpoint rejection, legacy selection repair, stale/active configuration rejection, actual SQL write fault preservation and persisted reopen. Provider response/key are synthetic fixture data.\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
