// Actual compiled server/CLI and encrypted xlang3 storage. The key/model are
// synthetic fixture data; this contract never requests external inference.
import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,dirname,basename} from 'node:path';import {randomBytes} from 'node:crypto';
const [server,cli,modules,stdlib]=process.argv.slice(2),root=await mkdtemp(join(tmpdir(),'xmind-provider-cli-')),token=randomBytes(32).toString('hex'),secret='synthetic-cli-provider-key',database=join(root,'state.sqlite'),env={...process.env,XMIND_AUTH_TOKEN:token};let backend,port;
async function start(){backend=spawn(server,['--db',database,'--modules',modules,'--stdlib',stdlib,'--port','0'],{env,windowsHide:true});let out='',err='';backend.stderr.on('data',data=>err+=data);port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Provider CLI server readiness timed out')),10000);backend.once('error',error=>{clearTimeout(timer);reject(error);});backend.once('exit',code=>{clearTimeout(timer);reject(new Error(`Provider CLI server exited ${code}: ${err}`));});backend.stdout.on('data',data=>{out+=data;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(out);if(match){clearTimeout(timer);resolve(Number(match[1]));}});});}
async function stop(){if(!backend)return;if(backend.exitCode===null){const exited=new Promise(resolve=>backend.once('exit',resolve));backend.kill();await exited;}backend=undefined;}
function invoke(args,extra={},status=0){const result=spawnSync(cli,[String(port),...args],{env:{...env,...extra},encoding:'utf8',windowsHide:true,timeout:15000});if(result.error)throw result.error;assert.equal(result.status,status,result.stderr);assert.ok(!result.stdout.includes(secret)&&!result.stderr.includes(secret),'CLI output must not disclose fixture key');return status===0?JSON.parse(result.stdout):result;}
try{
 await start();const initial=invoke(['provider']);assert.equal(initial.configured,false);assert.equal(initial.revision,0);invoke(['configure-provider','fixture-model','FIXTURE_PROVIDER_KEY','0'],{},1);assert.equal(invoke(['provider']).revision,0);for(const variable of ['XMIND_AUTH_TOKEN','xmind_auth_token','XMIND_UI_BOOTSTRAP_TOKEN'])invoke(['configure-provider','fixture-model',variable,'0'],{},1);
 const configured=invoke(['configure-provider','fixture-model','FIXTURE_PROVIDER_KEY','0'],{FIXTURE_PROVIDER_KEY:secret});assert.equal(configured.configured,true);assert.equal(configured.revision,1);assert.equal(configured.model,'fixture-model');assert.equal(invoke(['health']).agent_execution,true);assert.deepEqual(invoke(['models']).models,[{id:'fixture-model'}]);invoke(['configure-provider','fixture-alternate','FIXTURE_PROVIDER_KEY','0'],{FIXTURE_PROVIDER_KEY:secret},1);assert.equal(invoke(['provider']).model,'fixture-model');assert.deepEqual(invoke(['sessions']),[],'Enrollment must not fabricate a conversation or response');
 await stop();assert.ok(!(await readFile(database)).includes(Buffer.from(secret)),'Actual native credential DB must not contain plaintext fixture key');await start();assert.equal(invoke(['provider']).revision,1);assert.equal(invoke(['health']).agent_execution,true);await stop();process.stdout.write('Native provider CLI passed authenticated enrollment, private environment input, empty/stale rejection, actual encrypted DB storage and model restore. Key/model are synthetic; no live provider acceptance claimed.\n');
}finally{await stop();assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-provider-cli-'));await rm(root,{recursive:true,force:true});}
