// Independent synthetic Responses wire peer. Product execution is native C++;
// actual reads, tools, credentials and persistence use the production backend.
import assert from 'node:assert/strict';import {createServer} from 'node:http';import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname,basename,resolve} from 'node:path';
import {randomBytes} from 'node:crypto';import {setTimeout as delay} from 'node:timers/promises';
const [server,cli,modules,stdlib]=process.argv.slice(2),root=await mkdtemp(join(tmpdir(),'xmind-responses-')),workspace=join(root,'workspace');
const token=randomBytes(32).toString('hex'),key='synthetic-responses-key',env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
let child,port,peerError;const requests=[],held=[],opaqueFlows=new Map();
function output(response,id,items,{incomplete=false,terminalItems,usage={input_tokens:17,output_tokens:8,total_tokens:25,input_tokens_details:{cached_tokens:5},output_tokens_details:{reasoning_tokens:3}}}={}){const terminal=structuredClone(terminalItems??items);let sequence=0;const send=(type,fields)=>response.write(`event: ${type}\ndata: ${JSON.stringify({type,sequence_number:sequence++,...fields})}\n\n`);send('response.created',{response:{id,model:'synthetic-responses-model',status:'in_progress'}});
 for(let index=0;index<items.length;++index){const item=items[index],base={output_index:index,item_id:item.id};const added={...item,status:'in_progress'};if(item.type==='message')added.content=[];else if(item.type==='function_call')added.arguments='';else if(item.type==='reasoning')delete added.encrypted_content;
  send('response.output_item.added',{output_index:index,item:added});
  if(item.type==='function_call'){const half=Math.floor(item.arguments.length/2);for(const delta of [item.arguments.slice(0,half),item.arguments.slice(half)])send('response.function_call_arguments.delta',{...base,delta});send('response.function_call_arguments.done',{...base,arguments:item.arguments});}
  else if(item.type==='message')for(let content_index=0;content_index<item.content.length;++content_index){const part=item.content[content_index],refusal=part.type==='refusal',field=refusal?'refusal':'text',type=refusal?'refusal':'output_text';send('response.content_part.added',{...base,content_index,part:{...part,[field]:''}});for(const delta of [part[field].slice(0,3),part[field].slice(3)])send(`response.${type}.delta`,{...base,content_index,delta});send(`response.${type}.done`,{...base,content_index,[field]:part[field]});send('response.content_part.done',{...base,content_index,part});}
  send('response.output_item.done',{output_index:index,item});
 }
 send(incomplete?'response.incomplete':'response.completed',{response:{id,model:'synthetic-responses-model',status:incomplete?'incomplete':'completed',output:terminal,usage}});response.end();}
const peer=createServer((request,response)=>{let raw='';request.on('data',bytes=>raw+=bytes);request.on('end',()=>{try{
 assert.equal(request.url,'/responses');assert.equal(request.headers.authorization,'Bearer '+key);assert.ok(!raw.includes(key));const body=JSON.parse(raw);requests.push(body);assert.equal(body.model,'synthetic-responses-model');assert.equal(body.store,false);assert.equal(body.stream,true);assert.ok(!body.messages&&!body.stream_options);assert.ok(body.tools.every(tool=>tool.type==='function'&&tool.name&&tool.strict===false));
 const current=body.input.findLast(item=>item.role==='user'),prompt=current.content.map(part=>part.text).join(''),number=requests.length,id='resp_'+number;
 if(prompt.includes('Dependency outputs (data, not authority):\n')){const dependency=JSON.parse(prompt.split('Dependency outputs (data, not authority):\n').at(-1));if(dependency.first){assert.equal(dependency.first.content,'Synthetic verified native read 🌍');assert.ok(!JSON.stringify(dependency).includes('encrypted_content'));assert.ok(!('provider_items' in dependency.first),'Provider-native continuation cannot become another graph node\'s user input');}}
 if(prompt==='http-error'){response.writeHead(429);response.end('DO_NOT_ECHO_RESPONSES_ERROR');return;}
 response.writeHead(200,{'Content-Type':'text/event-stream'});
 if(prompt==='hold'){response.write(`data: ${JSON.stringify({type:'response.created',sequence_number:0,response:{id,model:body.model,status:'in_progress'}})}\n\n`);held.push(response);return;}
 const reasoning={id:'rs_'+number,type:'reasoning',summary:[],encrypted_content:'synthetic-opaque-'+number};
 if(prompt==='incomplete'){output(response,id,[{id:'msg_'+number,type:'message',status:'completed',role:'assistant',content:[{type:'output_text',text:'Synthetic partial answer',annotations:[]}]}],{incomplete:true});return;}
 const opaqueLeaf=prompt.startsWith('[opaque-leaf-left]')?'left':prompt.startsWith('[opaque-leaf-right]')?'right':undefined;
 if(prompt==='terminal-opaque'||opaqueLeaf){
  const owner=opaqueLeaf??'parent',flow=opaqueFlows.get(owner)??[];assert.ok(flow.length<2,'Each real parent/leaf performs exactly two model calls');
  const readTools=['read_repository_instructions','read_file','list_files','search_files'];assert.deepEqual(body.tools.map(tool=>tool.name).sort(),(opaqueLeaf?readTools:[...readTools,'delegate_tasks','plan_tasks','revise_plan','inspect_plan']).sort(),'Exact read-only leaf authority; parent may delegate and plan');
  assert.deepEqual(body.input.filter(item=>item.type==='reasoning'),flow.map(value=>value.completed[0]),'Continuation replays whole output_item.done reasoning, including original opaque bytes and stable extra members');
  const completedReasoning={...reasoning,status:'completed',content:[],channel:'analysis',phase:'completed',synthetic_replay_marker:{scope:'labelled-protocol-fixture',values:[true,null,number]},encrypted_content:'synthetic-completed-opaque-'+number};
  const call=(callId,name,args)=>({id:'fc_'+number,type:'function_call',call_id:callId,name,arguments:JSON.stringify(args),status:'completed'}),message=text=>({id:'msg_'+number,type:'message',status:'completed',role:'assistant',content:[{type:'output_text',text,annotations:[]}]});let item;
  const last=body.input.findLast(value=>value.type==='function_call_output');
  if(opaqueLeaf){
   if(!flow.length){assert.equal(last,undefined);item=call('opaque-'+opaqueLeaf+'-read','read_file',{path:opaqueLeaf+'.txt'});}
   else{assert.equal(last.call_id,'opaque-'+opaqueLeaf+'-read');assert.equal(JSON.parse(last.output).content,'Actual opaque '+opaqueLeaf+' fixture bytes\n');assert.deepEqual(body.input.findLast(value=>value.type==='function_call'),flow[0].completed[1]);item=message('Observed actual opaque '+opaqueLeaf+' read');}
  }else if(!flow.length){assert.equal(last,undefined);item=call('opaque-parent-delegate','delegate_tasks',{tasks:[{id:'inspect-left',objective:'[opaque-leaf-left] Read left.txt and report actual contents.',preset:'workspace.inspect'},{id:'inspect-right',objective:'[opaque-leaf-right] Read right.txt and report actual contents.',preset:'workspace.inspect'}]});}
  else{assert.equal(last.call_id,'opaque-parent-delegate');assert.deepEqual(body.input.findLast(value=>value.type==='function_call'),flow[0].completed[1]);const joined=JSON.parse(last.output);assert.equal(joined.source,'native_delegation');assert.equal(joined.children.length,2);for(const result of joined.children){assert.equal(result.child_state,'completed');assert.equal(result.preset_id,'workspace.inspect');assert.equal(result.preset_revision,1);assert.equal(result.usage.prompt_tokens,11);assert.equal(result.usage.completion_tokens,5);}assert.deepEqual(new Set(joined.children.map(value=>value.content)),new Set(['Observed actual opaque left read','Observed actual opaque right read']));assert.ok(!last.output.includes('encrypted_content')&&!last.output.includes('provider_items'),'Leaf provider continuation stays in its own history');item=message('Joined actual two opaque-compatible native reads');}
  const completed=[completedReasoning,item],terminalItems=structuredClone(completed);terminalItems[0].encrypted_content='synthetic-terminal-opaque-'+number;assert.notEqual(terminalItems[0].encrypted_content,completed[0].encrypted_content);
  const usage={input_tokens:opaqueLeaf?11:19,output_tokens:opaqueLeaf?5:7,total_tokens:opaqueLeaf?16:26,input_tokens_details:{cached_tokens:opaqueLeaf?2:4},output_tokens_details:{reasoning_tokens:opaqueLeaf?1:2}};flow.push({completed,terminalItems,usage});opaqueFlows.set(owner,flow);output(response,id,completed,{terminalItems,usage});return;
 }
 if(prompt.startsWith('terminal-')){
  assert.ok(body.tools.some(tool=>tool.name==='delegate_tasks'),'Use the actual configured native delegation path');
  const call={id:'fc_'+number,type:'function_call',call_id:'call_'+number,name:'delegate_tasks',arguments:JSON.stringify({tasks:[{id:'inspect',objective:'SYNTHETIC_DELEGATED_OBJECTIVE_NOT_A_DIAGNOSTIC_VALUE',preset:'workspace.inspect'}]}),status:'completed'};
  const items=[reasoning,call],terminalItems=structuredClone(items);
  if(prompt==='terminal-metadata')terminalItems[1].phase='SYNTHETIC_PRIVATE_PHASE_'+key;
  else if(prompt==='terminal-unlisted'){const name='SYNTHETIC_PRIVATE_MEMBER_'+key;items[1][name]='SYNTHETIC_PRIVATE_MEMBER_BEFORE';terminalItems[1][name]='SYNTHETIC_PRIVATE_MEMBER_AFTER';}
  else if(prompt==='terminal-arguments')terminalItems[1].arguments=JSON.stringify({tasks:[{id:'changed',objective:'SYNTHETIC_PRIVATE_TERMINAL_ARGUMENT',preset:'workspace.inspect'}]});
  else if(prompt==='terminal-id')terminalItems[1].id='SYNTHETIC_PRIVATE_CHANGED_ID';
  else if(prompt==='terminal-call-id')terminalItems[1].call_id='SYNTHETIC_PRIVATE_CHANGED_CALL';
  else if(prompt==='terminal-name')terminalItems[1].name='read_file';
  else if(prompt==='terminal-type')terminalItems[1].type='reasoning';
  else if(prompt==='terminal-status')terminalItems[1].status='in_progress';
  else if(prompt==='terminal-summary')terminalItems[0].summary=[{type:'summary_text',text:'SYNTHETIC_PRIVATE_SUMMARY'}];
  else if(prompt==='terminal-reasoning-unlisted'){const name='SYNTHETIC_PRIVATE_REASONING_MEMBER_'+key;items[0][name]='before';terminalItems[0][name]='after';terminalItems[0].encrypted_content='synthetic-terminal-opaque-'+number;}
  else if(prompt==='terminal-opaque-empty')terminalItems[0].encrypted_content='';
  else if(prompt==='terminal-opaque-null')terminalItems[0].encrypted_content=null;
  else if(prompt==='terminal-opaque-number')terminalItems[0].encrypted_content=5;
  else if(prompt==='terminal-opaque-absent')delete terminalItems[0].encrypted_content;
  else if(prompt==='terminal-call-opaque'){items[1].encrypted_content='SYNTHETIC_PRIVATE_CALL_BEFORE_'+key;terminalItems[1].encrypted_content='SYNTHETIC_PRIVATE_CALL_AFTER_'+key;}
  else throw new Error('Unexpected terminal diagnostic fixture');
  output(response,id,items,{terminalItems});return;
 }
 if(body.input.at(-1).type==='function_call_output'){
  const last=body.input.at(-1);assert.equal(JSON.parse(last.output).content,'Actual Responses workspace content\n');const previous=body.input.findLast(item=>item.type==='function_call');assert.equal(previous.call_id,last.call_id);assert.ok(body.input.some(item=>item.type==='reasoning'&&item.encrypted_content.startsWith('synthetic-opaque-')),'Completed reasoning must survive tool continuation');
  output(response,id,[reasoning,{id:'msg_'+number,type:'message',status:'completed',role:'assistant',content:[{type:'output_text',text:'Synthetic verified native read 🌍',annotations:[]}]}]);
 }else output(response,id,[reasoning,{id:'fc_'+number,type:'function_call',call_id:'call_'+number,name:prompt==='unknown-tool'?'unadvertised_function':'read_file',arguments:'{"path":"README.md"}',status:'completed'}]);
 }catch(error){peerError=error;response.destroy();}});});
async function start(withKey=false){child=spawn(server,['--db',join(root,'state.sqlite'),'--modules',modules,'--stdlib',stdlib,'--port','0','--model','synthetic-responses-model','--model-endpoint',`http://127.0.0.1:${peer.address().port}/responses`,'--model-wire','responses','--model-tools','supported','--model-stream-usage','supported','--workspace',workspace,'--credential-id','responses-credential','--graphs-config',join(root,'graphs.json')],{env:withKey?{...env,XMIND_API_KEY:key}:env,windowsHide:true});let stderr='';child.stderr.on('data',bytes=>stderr+=bytes);port=await new Promise((yes,no)=>{let stdout='';const timer=setTimeout(()=>no(new Error('Native readiness '+stderr)),15000);child.once('error',error=>{clearTimeout(timer);no(error);});child.once('exit',code=>{clearTimeout(timer);no(new Error('Native exit '+code+': '+stderr));});child.stdout.on('data',bytes=>{stdout+=bytes;const match=/listening on http:\/\/127\.0\.0\.1:(\d+)/.exec(stdout);if(match){clearTimeout(timer);yes(Number(match[1]));}});});}
async function stop(){if(child&&child.exitCode===null){const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;}child=null;}
async function api(path,body){const response=await fetch(`http://127.0.0.1:${port}${path}`,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});assert.ok(response.ok,await response.clone().text());return response.json();}
function command(...args){const result=spawnSync(cli,[String(port),...args],{env,encoding:'utf8',windowsHide:true,timeout:15000});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout);}
async function until(read,predicate){const deadline=Date.now()+15000;while(Date.now()<deadline){if(peerError)throw peerError;const value=await read();if(predicate(value))return value;await delay(15);}throw new Error('Responses observation deadline');}
async function run(id,prompt,state='completed'){await api('/v1/sessions',{id,title:id});const value=command('run',id,prompt);await until(()=>api('/v1/runs/'+value.id),record=>record.state===state);return value;}
function opaqueHistory(history,owner){
 assert.deepEqual(history.map(item=>item.role),['user','assistant','tool','assistant']);const flow=opaqueFlows.get(owner);assert.equal(flow.length,2);
 for(const [index,record]of history.filter(item=>item.role==='assistant').entries()){
  assert.deepEqual(record.data.provider_items,flow[index].completed,'Whole completed reasoning item is authoritative in persisted history');assert.notDeepEqual(record.data.provider_items,flow[index].terminalItems,'Terminal ciphertext never replaces completed-item continuation');
  assert.equal(record.data.usage.prompt_tokens,owner==='parent'?19:11);assert.equal(record.data.usage.completion_tokens,owner==='parent'?7:5);assert.equal(record.data.usage.total_tokens,owner==='parent'?26:16);assert.equal(record.data.usage.completion_tokens_details.reasoning_tokens,owner==='parent'?2:1);
  assert.ok(Number.isFinite(record.data.elapsed_ms)&&record.data.elapsed_ms>=0&&Number.isFinite(record.data.first_token_ms)&&record.data.first_token_ms>=0);
 }
 assert.ok(!JSON.stringify(history).includes(key));
}
function ownedAttemptAudit(events,owner,rootId,role){
 const stages=['reserved','started','finished'].map(stage=>events.filter(event=>event.kind==='budget.model_call.'+stage));assert.deepEqual(stages.map(values=>values.length),[2,2,2]);
 for(const reserved of stages[0]){assert.match(reserved.data.attempt_id,/^[a-f0-9]{32}$/);const started=stages[1].find(event=>event.data.attempt_id===reserved.data.attempt_id),finished=stages[2].find(event=>event.data.attempt_id===reserved.data.attempt_id);assert.ok(started&&finished&&reserved.seq<started.seq&&started.seq<finished.seq);for(const event of [reserved,started,finished]){assert.equal(event.run_id,owner);assert.equal(event.data.root_run_id,rootId);assert.equal(event.data.role,role);}assert.equal(finished.data.was_started,true);}
 assert.equal(events.filter(event=>event.kind==='model.done').length,2);assert.equal(events.filter(event=>event.kind==='model.usage').length,2);assert.equal(events.filter(event=>event.kind==='model.protocol_diagnostic').length,0);
 const expected=role==='parent'?19:11;for(const event of events.filter(event=>event.kind==='model.usage'))assert.equal(event.data.prompt_tokens,expected,'Each owner retains per-response metrics, with no root aggregation');
}
async function ownedTree(rootId){const events=[];let cursor=0;for(;;){const page=await api('/v1/runs/'+rootId+'/tree-events?after='+cursor);assert.ok(page.length<=256);for(const event of page){assert.ok(event.seq>cursor);cursor=event.seq;events.push(event);}if(page.length<256)return events;}}
try{
 await mkdir(workspace);await writeFile(join(workspace,'README.md'),'Actual Responses workspace content\n');for(const side of ['left','right'])await writeFile(join(workspace,side+'.txt'),'Actual opaque '+side+' fixture bytes\n');await writeFile(join(root,'graphs.json'),JSON.stringify({graphs:[{id:'responses.flow',spec:{nodes:[{id:'first',type:'agent',prompt:'Read README'},{id:'second',type:'agent',prompt:'Read README and inspect the first result',depends_on:['first']}]}}]}));await new Promise(resolve=>peer.listen(0,'127.0.0.1',resolve));await start(true);
 const first=await run('responses-coding','Read README');const history=command('history','responses-coding');assert.deepEqual(history.map(item=>item.role),['user','assistant','tool','assistant']);assert.equal(JSON.parse(history[2].data.content).content,'Actual Responses workspace content\n');assert.equal(history[1].data.provider_items[0].encrypted_content,'synthetic-opaque-1');assert.equal(history[3].data.usage.prompt_tokens,17);assert.equal(history[3].data.usage.completion_tokens,8);assert.equal(history[3].data.usage.completion_tokens_details.reasoning_tokens,3);assert.equal(history[3].data.content,'Synthetic verified native read 🌍');assert.ok(history[3].data.elapsed_ms>=0&&history[3].data.first_token_ms>=0);assert.ok(!JSON.stringify(history).includes(key));
 const events=command('events',first.id);assert.ok(events.some(item=>item.kind==='tool.completed'));assert.equal(events.filter(item=>item.kind==='model.done').length,2);assert.equal(events.at(-1).kind,'run.completed');
 await stop();await start();assert.deepEqual(command('history','responses-coding'),history);const again=command('run','responses-coding','Read again after restart');await until(()=>api('/v1/runs/'+again.id),record=>record.state==='completed');assert.ok(requests[2].input.some(item=>item.type==='reasoning'&&item.encrypted_content==='synthetic-opaque-1'),'Opaque continuation must survive native SQLite reopen');
 await api('/v1/sessions',{id:'responses-graph',title:'Responses graph'});const graph=command('graph-run','responses-graph','responses.flow','1','Perform native file reads');await until(()=>api('/v1/runs/'+graph.id),record=>record.state==='completed');const children=command('graph-children',graph.id);assert.equal(children.length,2);for(const child of children){const recorded=command('graph-child-history',graph.id,child.id);assert.ok(recorded.at(-1).data.provider_items.some(item=>item.type==='reasoning'&&item.encrypted_content));assert.equal(recorded.at(-1).data.usage.completion_tokens,8);}assert.ok(!JSON.stringify(command('history','responses-graph')).includes('encrypted_content'),'Graph join must not project provider continuations into its answer');
 for(const prompt of ['unknown-tool','incomplete','http-error']){const before=requests.length,value=await run(prompt,prompt,'failed');assert.equal(requests.length,before+1,'Failed/partial Responses must not silently retry');const events=command('events',value.id);assert.ok(!events.some(item=>item.kind==='tool.started'));assert.ok(!JSON.stringify(events).includes('DO_NOT_ECHO_RESPONSES_ERROR'));assert.equal(command('history',prompt).filter(item=>item.role==='assistant').length,0);
  if(prompt==='incomplete'){const failure=events.find(item=>item.kind==='run.failed');assert.equal(failure.data.reason,'model_protocol_error');assert.equal(failure.data.protocol_error_code,'responses_provider_incomplete');}
 }
 assert.equal((await api('/v1/health')).agent_delegation,true);
 const opaqueBefore=requests.length,opaqueRun=await run('terminal-opaque','terminal-opaque');assert.equal(requests.length,opaqueBefore+6,'One parent and two real read-only leaves each perform two model calls');assert.equal(opaqueRun.graph_root,false);
 const opaqueChildren=command('children',opaqueRun.id);assert.equal(opaqueChildren.length,2);assert.deepEqual(new Set(opaqueChildren.map(item=>item.task_id)),new Set(['inspect-left','inspect-right']));assert.deepEqual(opaqueChildren,await api('/v1/runs/'+opaqueRun.id+'/children'));
 const opaqueParentHistory=command('history','terminal-opaque');opaqueHistory(opaqueParentHistory,'parent');const opaqueParentEvents=command('events',opaqueRun.id);ownedAttemptAudit(opaqueParentEvents,opaqueRun.id,opaqueRun.id,'parent');assert.deepEqual(command('operations',opaqueRun.id),[]);
 const joined=JSON.parse(opaqueParentHistory[2].data.content);assert.equal(joined.source,'native_delegation');assert.equal(joined.children.length,2);assert.ok(!JSON.stringify(joined).includes('encrypted_content')&&!JSON.stringify(joined).includes('provider_items'));
 const opaqueChildHistories=new Map(),opaqueChildEvents=new Map();
 for(const record of opaqueChildren){
  assert.equal(record.kind,'delegated_leaf');assert.equal(record.run.parent_id,opaqueRun.id);assert.equal(record.run.session_id,'terminal-opaque');assert.equal(record.run.state,'completed');assert.equal(record.preset_id,'workspace.inspect');assert.equal(record.preset_revision,1);const owner=record.task_id==='inspect-left'?'left':'right';
  const history=command('child-history',opaqueRun.id,record.run.id);opaqueHistory(history,owner);assert.deepEqual(history,await api('/v1/runs/'+opaqueRun.id+'/children/'+record.run.id+'/history'));assert.equal(JSON.parse(history[2].data.content).content,'Actual opaque '+owner+' fixture bytes\n');assert.deepEqual(command('operations',record.run.id),[]);
  const events=command('events',record.run.id);ownedAttemptAudit(events,record.run.id,opaqueRun.id,'leaf');assert.deepEqual(events.filter(event=>event.kind==='tool.started').map(event=>event.data.name),['read_file']);assert.deepEqual(events.filter(event=>event.kind==='tool.completed').map(event=>event.data.name),['read_file']);
  const result=joined.children.find(item=>item.child_run_id===record.run.id);assert.equal(events.filter(event=>event.kind==='delegation.child.settled').length,1);assert.deepEqual(events.find(event=>event.kind==='delegation.child.settled').data,result);assert.equal(result.task_id,record.task_id);assert.equal(result.child_state,'completed');for(const name of ['content','model','usage','elapsed_ms','first_token_ms'])assert.deepEqual(result[name],history.at(-1).data[name],'Join derives this child’s actual last assistant response');opaqueChildHistories.set(record.run.id,history);opaqueChildEvents.set(record.run.id,events);
 }
 const accepted=opaqueParentEvents.filter(event=>event.kind==='delegation.batch.accepted'),settled=opaqueParentEvents.filter(event=>event.kind==='delegation.batch.settled');assert.equal(accepted.length,1);assert.equal(settled.length,1);assert.equal(accepted[0].data.batch_id,joined.batch_id);assert.deepEqual(settled[0].data.result,joined);assert.equal(opaqueParentEvents.filter(event=>event.kind==='delegation.child.settled').length,0,'Child settlements belong to their own durable owners');assert.ok(opaqueParentEvents.filter(event=>event.kind==='budget.model_call.reserved').at(-1).seq>settled[0].seq,'Parent continuation follows observed leaf settlement');
 const opaqueTreeEvents=await ownedTree(opaqueRun.id);assert.equal(opaqueTreeEvents.filter(event=>event.kind==='delegation.child.settled').length,2);assert.deepEqual(command('tree-events',opaqueRun.id,'0'),opaqueTreeEvents.slice(0,256));assert.equal(new Set(opaqueTreeEvents.filter(event=>event.kind==='budget.model_call.reserved').map(event=>event.data.attempt_id)).size,6);assert.deepEqual(new Set(opaqueTreeEvents.map(event=>event.run_id)),new Set([opaqueRun.id,...opaqueChildren.map(record=>record.run.id)]));
 const opaqueRequestCount=requests.length;await stop();await start();assert.equal(requests.length,opaqueRequestCount,'Reopen does not replay successful parent/leaf model calls');assert.deepEqual(command('history','terminal-opaque'),opaqueParentHistory);assert.deepEqual(command('children',opaqueRun.id),opaqueChildren);assert.deepEqual(command('events',opaqueRun.id),opaqueParentEvents);assert.deepEqual(await ownedTree(opaqueRun.id),opaqueTreeEvents);for(const record of opaqueChildren){assert.deepEqual(command('child-history',opaqueRun.id,record.run.id),opaqueChildHistories.get(record.run.id));assert.deepEqual(command('events',record.run.id),opaqueChildEvents.get(record.run.id));}
 const rejectedTerminals=[],labels=['id','type','status','call_id','name','arguments','role','content','summary','encrypted_content','channel','phase'];
 const allowedTypes=new Set(['absent','null','object','array','string','boolean','integer','unsigned_integer','number','unsupported']);
 for(const [prompt,position,changed,unlistedEqual]of [
  ['terminal-metadata',1,['phase'],true],['terminal-unlisted',1,[],false],['terminal-arguments',1,['arguments'],true],['terminal-id',1,['id'],true],['terminal-call-id',1,['call_id'],true],['terminal-name',1,['name'],true],['terminal-type',1,['type'],true],['terminal-status',1,['status'],true],['terminal-summary',0,['summary'],true],['terminal-reasoning-unlisted',0,['encrypted_content'],false],['terminal-opaque-empty',0,['encrypted_content'],true],['terminal-opaque-null',0,['encrypted_content'],true],['terminal-opaque-number',0,['encrypted_content'],true],['terminal-opaque-absent',0,['encrypted_content'],true],['terminal-call-opaque',1,['encrypted_content'],true],
 ]){
  const before=requests.length,value=await run(prompt,prompt,'failed');assert.equal(requests.length,before+1,'Terminal mismatch cannot retry or start a child provider request');
  const events=command('events',value.id),diagnostics=events.filter(event=>event.kind==='model.protocol_diagnostic');assert.equal(diagnostics.length,1);
  const diagnostic=diagnostics[0].data,encoded=JSON.stringify(diagnostic);assert.ok(Buffer.byteLength(encoded,'utf8')<=4096);
  assert.deepEqual(Object.keys(diagnostic).sort(),['code','output_index','item_present','item_done','completed_snapshot_type','terminal_snapshot_type','fields','changed_fields','unlisted_fields_equal'].sort());
  assert.equal(diagnostic.code,'responses_terminal_mismatch');assert.equal(diagnostic.output_index,position);assert.equal(diagnostic.item_present,true);assert.equal(diagnostic.item_done,true);assert.equal(diagnostic.completed_snapshot_type,'object');assert.equal(diagnostic.terminal_snapshot_type,'object');
  assert.deepEqual(diagnostic.fields.map(field=>field.field),labels);for(const field of diagnostic.fields){assert.deepEqual(Object.keys(field).sort(),['field','completed_present','completed_type','terminal_present','terminal_type','equal'].sort());for(const name of ['completed_present','terminal_present','equal'])assert.equal(typeof field[name],'boolean');assert.ok(allowedTypes.has(field.completed_type)&&allowedTypes.has(field.terminal_type));}
  assert.deepEqual(diagnostic.changed_fields,changed);assert.deepEqual(diagnostic.fields.filter(field=>!field.equal).map(field=>field.field),changed);assert.equal(diagnostic.unlisted_fields_equal,unlistedEqual);
  if(prompt==='terminal-metadata'){const field=diagnostic.fields.find(field=>field.field==='phase');assert.equal(field.completed_present,false);assert.equal(field.completed_type,'absent');assert.equal(field.terminal_present,true);assert.equal(field.terminal_type,'string');}
  for(const marker of [key,'SYNTHETIC_PRIVATE_','SYNTHETIC_DELEGATED_OBJECTIVE_NOT_A_DIAGNOSTIC_VALUE','delegate_tasks','fc_'+(before+1),'call_'+(before+1),'rs_'+(before+1)])assert.ok(!encoded.includes(marker),'Diagnostic cannot include provider IDs, names, arguments, opaque values or unlisted keys');
  // Earlier model.tool_delta intentionally contains the tool argument prefix;
  // the new diagnostic alone must be value-free. Credentials never appear in events.
  assert.ok(!JSON.stringify(events).includes(key));
  assert.ok(!events.some(event=>['tool.started','tool.completed','tool.failed','model.usage','model.finish','model.done','run.completed','delegation.batch.accepted','delegation.child.admitted'].includes(event.kind)));
  const failure=events.at(-1);assert.equal(failure.kind,'run.failed');assert.equal(failure.data.reason,'model_protocol_error');assert.equal(failure.data.protocol_error_code,'responses_terminal_mismatch');
  for(const kind of ['budget.model_call.reserved','budget.model_call.started','budget.model_call.finished'])assert.equal(events.filter(event=>event.kind===kind).length,1);
  assert.deepEqual(command('history',prompt).map(item=>item.role),['user']);assert.deepEqual(await api('/v1/runs/'+value.id+'/children'),[]);assert.deepEqual(command('operations',value.id),[]);
  assert.equal(await readFile(join(workspace,'README.md'),'utf8'),'Actual Responses workspace content\n');for(const side of ['left','right'])assert.equal(await readFile(join(workspace,side+'.txt'),'utf8'),'Actual opaque '+side+' fixture bytes\n');assert.deepEqual((await readdir(workspace)).sort(),['README.md','left.txt','right.txt']);
  rejectedTerminals.push({prompt,runId:value.id,events});
 }
 await stop();await start();
 for(const rejected of rejectedTerminals){assert.deepEqual(command('events',rejected.runId),rejected.events,'The actual bounded diagnostic and failed lifecycle persist through native SQLite reopen');assert.deepEqual(command('history',rejected.prompt).map(item=>item.role),['user']);assert.deepEqual(await api('/v1/runs/'+rejected.runId+'/children'),[]);}
 await api('/v1/sessions',{id:'cancel-responses',title:'cancel'});const cancelled=command('run','cancel-responses','hold');await until(()=>held.length,value=>value>0);command('cancel',cancelled.id);await until(()=>api('/v1/runs/'+cancelled.id),value=>value.state==='cancelled');
 console.log('Native Responses agent passed actual CLI/HTTP admission, real workspace read/tool loop, reasoning-only terminal ciphertext compatibility with exact completed-item continuation through a real two-leaf read/join, six owned audited model calls with independent per-response metrics, encrypted history reopen without parent/child replay, exact supplied token metrics, encrypted backend credential reuse, restart conversation replay, actual persisted bounded value-free terminal diagnostics for independently constructed metadata/identity/call/summary/unlisted/argument/invalid-opaque mismatches, strict failed delegation before tools or children with user-only history and no retry/effect/invented usage, unsupported tool and incomplete/provider-error rejection, and cancellation. Model output and opaque reasoning are synthetic; live-provider/full frontier coverage remains unverified.');
}finally{for(const response of held)response.destroy();await stop();await new Promise(resolve=>peer.close(resolve));assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('xmind-responses-'));await rm(root,{recursive:true,force:true});}
