// Actual Windows C++ verifier and OS file handles. Metadata/unused package
// members are synthetic integrity fixtures. This is not a runnable SDK package,
// provider execution, installation, retirement or migration acceptance.
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import cp from 'node:child_process';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import readline from 'node:readline';
const [program,runtimeDll]=process.argv.slice(2);if(!program||!runtimeDll||process.platform!=='win32')throw Error('Windows compiled verifier and allowed SDK DLL required');
const parent=await fs.realpath(os.tmpdir()),base=await fs.mkdtemp(path.join(parent,'xmind-generation-contract-'));assert.equal(await fs.realpath(base),base);const sha=b=>crypto.createHash('sha256').update(b).digest('hex');let index=0;const children=new Set();
async function fixture(){const root=path.join(base,`generation-${++index}-写-😀`);await fs.mkdir(root);const content={'xmind.exe':await fs.readFile(program),'xlang3_runtime.dll':await fs.readFile(runtimeDll),'xlang3.exe':Buffer.from('inert fixture SDK executable'),'modules/xlang_json.x3pkg.dll':Buffer.from('inert fixture JSON module'),'modules/xlang_sqlite3.x3pkg.dll':Buffer.from('inert fixture SQLite module'),'stdlib/os.py':Buffer.from('# synthetic integrity fixture\n'),'stdlib/json/__init__.py':Buffer.from('# synthetic integrity fixture\n'),'stdlib/encodings/__init__.py':Buffer.from('# synthetic integrity fixture\n'),'stdlib/importlib/__init__.py':Buffer.from('# synthetic integrity fixture\n'),'licenses/NOTICE.txt':Buffer.from('Synthetic integrity fixture; no package compatibility endorsement.'),'README.txt':Buffer.from('Owned integrity fixture only.'),'provenance.json':Buffer.from('{"syntheticIntegrityFixture":true}')};for(const [name,bytes]of Object.entries(content)){await fs.mkdir(path.dirname(path.join(root,name)),{recursive:true});await fs.writeFile(path.join(root,name),bytes,{flag:'wx'});}const manifest={schemaVersion:1,platform:'win32',arch:'x64',bridgeEnabled:false,nativeRevision:'a'.repeat(40),sdkRevision:'b'.repeat(40),sourceManifestSha256:'c'.repeat(64),files:Object.fromEntries(Object.entries(content).map(([n,b])=>[n,sha(b)]))};await save(root,manifest);return {root,manifest};}
async function save(root,manifest){const bytes=Buffer.from(JSON.stringify(manifest));await fs.writeFile(path.join(root,'native-runtime-manifest.json'),bytes);return sha(bytes);}
async function run(root,digest,mode='verify',excluded,rootImage=['self','loaded','managed','managedhold'].includes(mode)){const exe=rootImage?path.join(root,'xmind.exe'):program;const args=[root,digest,mode,...(excluded?[excluded]:[])];const child=cp.spawn(exe,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});children.add(child);let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);const result=await new Promise((yes,no)=>{const timer=setTimeout(()=>{child.kill();},8000);child.once('error',e=>{clearTimeout(timer);no(e);});child.once('close',code=>{clearTimeout(timer);children.delete(child);yes({code,stdout,stderr});});});return result;}
async function accepted(item,self=false,mode=self?'self':'verify'){const digest=sha(await fs.readFile(path.join(item.root,'native-runtime-manifest.json'))),result=await run(item.root,digest,mode);assert.equal(result.code,0,result.stderr||result.stdout);const actual=JSON.parse(result.stdout.trim());assert.equal(actual.verified,true);assert.equal(actual.manifest_sha256,digest);assert.equal(actual.self_verified,self);assert.equal(actual.root,item.root);assert.match(actual.root_identity,/^windows-runtime-file-v1:\d+:\d+$/);}
async function rejected(item,{digest,excluded,mode='verify',rootImage}={}){const actual=await run(item.root,digest??sha(await fs.readFile(path.join(item.root,'native-runtime-manifest.json'))),mode,excluded,rootImage??['self','loaded'].includes(mode));assert.equal(actual.code,3,actual.stderr||actual.stdout);assert.equal(JSON.parse(actual.stdout.trim()).verified,false);}
try {
 const legacyExtra=await fixture();const legacyBytes=Buffer.from('inert rejected legacy launcher');await fs.writeFile(path.join(legacyExtra.root,'xmind_server.exe'),legacyBytes);legacyExtra.manifest.files['xmind_server.exe']=sha(legacyBytes);await save(legacyExtra.root,legacyExtra.manifest);await rejected(legacyExtra);
 const unsupported=await fixture();unsupported.manifest.schemaVersion=2;await save(unsupported.root,unsupported.manifest);await rejected(unsupported);
 const positive=await fixture();await accepted(positive);await accepted(positive,true);await accepted(positive,false,'loaded');
 const managed=await fixture(),managedDigest=sha(await fs.readFile(path.join(managed.root,'native-runtime-manifest.json')));const managedChild=cp.spawn(path.join(managed.root,'xmind.exe'),[managed.root,managedDigest,'managedhold'],{windowsHide:true,stdio:['pipe','pipe','pipe']});children.add(managedChild);const managedLines=[];let managedRemainder='';managedChild.stdout.on('data',b=>{managedRemainder+=b;for(;;){const newline=managedRemainder.indexOf('\n');if(newline<0)break;managedLines.push(managedRemainder.slice(0,newline).trim());managedRemainder=managedRemainder.slice(newline+1);}});const managedNext=()=>managedLines.length?Promise.resolve(managedLines.shift()):new Promise((yes,no)=>{const timer=setTimeout(()=>no(Error('Managed-copy verifier did not respond')),5000);managedChild.stdout.once('data',()=>{clearTimeout(timer);yes(managedLines.shift());});});const managedExit=new Promise((yes,no)=>{managedChild.once('error',no);managedChild.once('close',code=>{children.delete(managedChild);yes(code);});});assert.equal(JSON.parse(await managedNext()).verified,true);await fs.appendFile(path.join(managed.root,'stdlib/os.py'),'# tampered managed copy\n');managedChild.stdin.write('revalidate\n');assert.equal(await managedExit,3,'Explicit owner revalidation must still hash every managed-copy file');
 const unicodeFile=await fixture();const unicodeBytes=Buffer.from('# synthetic Unicode filename fixture\n');await fs.writeFile(path.join(unicodeFile.root,'stdlib','模块.py'),unicodeBytes);unicodeFile.manifest.files['stdlib/模块.py']=sha(unicodeBytes);await save(unicodeFile.root,unicodeFile.manifest);await accepted(unicodeFile);
 await rejected(positive,{digest:'d'.repeat(64)});await rejected(positive,{excluded:base});await rejected(positive,{excluded:positive.root});
 const bridge=await fixture();bridge.manifest.bridgeEnabled=true;await save(bridge.root,bridge.manifest);await rejected(bridge);
 const altered=await fixture();await fs.appendFile(path.join(altered.root,'stdlib/os.py'),'# changed bytes\n');await rejected(altered);
 const incomplete=await fixture();delete incomplete.manifest.files['xmind.exe'];await fs.unlink(path.join(incomplete.root,'xmind.exe'));await save(incomplete.root,incomplete.manifest);await rejected(incomplete);
 const missingPure=await fixture();delete missingPure.manifest.files['stdlib/os.py'];await fs.unlink(path.join(missingPure.root,'stdlib/os.py'));await save(missingPure.root,missingPure.manifest);await rejected(missingPure);
 const extra=await fixture();await fs.writeFile(path.join(extra.root,'unexpected.txt'),'inert');await rejected(extra);
 const privateConfig=await fixture();await fs.mkdir(path.join(privateConfig.root,'.config'));await fs.writeFile(path.join(privateConfig.root,'.config','providers.yaml'),'synthetic fixture only');await rejected(privateConfig);
 const badName=await fixture();badName.manifest.files['stdlib/../escape.py']='e'.repeat(64);await save(badName.root,badName.manifest);await rejected(badName);
 const nativeExtension=await fixture();nativeExtension.manifest.files['stdlib/unsafe.pyd']='e'.repeat(64);await save(nativeExtension.root,nativeExtension.manifest);await rejected(nativeExtension);
 const collision=await fixture();collision.manifest.files['stdlib/OS.py']=collision.manifest.files['stdlib/os.py'];await save(collision.root,collision.manifest);await rejected(collision);
 const duplicate=await fixture();const duplicated=JSON.stringify(duplicate.manifest).replace('"bridgeEnabled":false','"bridgeEnabled":false,"bridgeEnabled":false');await fs.writeFile(path.join(duplicate.root,'native-runtime-manifest.json'),duplicated);await rejected(duplicate);
 const alias=path.join(base,'root-alias');await fs.symlink(positive.root,alias,'junction');await rejected({...positive,root:alias});
 const parentAlias=path.join(base,'parent-alias');await fs.symlink(base,parentAlias,'junction');await rejected({...positive,root:path.join(parentAlias,path.basename(positive.root))});await fs.unlink(parentAlias);
 const linked=await fixture();await fs.link(path.join(linked.root,'stdlib/os.py'),path.join(base,'hardlink-alias.py'));await rejected(linked);
 const wrongImage=await fixture();await rejected(wrongImage,{mode:'current'});await rejected(wrongImage,{mode:'loaded',rootImage:false});const result=await run(wrongImage.root,sha(await fs.readFile(path.join(wrongImage.root,'native-runtime-manifest.json'))),'verify');assert.equal(result.code,0);
 // Keep actual verifier handles alive while attempting to modify source.
 const held=await fixture(),digest=sha(await fs.readFile(path.join(held.root,'native-runtime-manifest.json'))),child=cp.spawn(program,[held.root,digest,'hold'],{windowsHide:true,stdio:['pipe','pipe','pipe']});children.add(child);const lines=[];let remainder='';const waiters=[];child.stdout.on('data',b=>{remainder+=b;for(;;){const newline=remainder.indexOf('\n');if(newline<0)break;const line=remainder.slice(0,newline).trim();remainder=remainder.slice(newline+1);lines.push(line);waiters.shift()?.(line);}});const nextLine=()=>lines.length?Promise.resolve(lines.shift()):new Promise((yes,no)=>{const timer=setTimeout(()=>no(Error('Owned verifier did not respond')),5000);waiters.push(line=>{clearTimeout(timer);lines.shift();yes(line);});});const closed=new Promise((yes,no)=>{child.once('error',no);child.once('close',code=>{children.delete(child);yes(code);});});assert.equal(JSON.parse(await nextLine()).verified,true);const control=path.join(base,'control.state'),pending=path.join(base,'control.pending');await fs.writeFile(control,'old state');await fs.writeFile(pending,'new state');await fs.rename(pending,control);assert.equal(await fs.readFile(control,'utf8'),'new state');await assert.rejects(fs.rename(held.root,held.root+'-renamed'),e=>['EACCES','EPERM','EBUSY'].includes(e.code));const pinned=path.join(held.root,'stdlib/os.py');for(const action of [()=>fs.appendFile(pinned,'changed'),()=>fs.unlink(pinned),()=>fs.rename(pinned,path.join(held.root,'stdlib/renamed.py'))])await assert.rejects(action(),e=>['EACCES','EPERM','EBUSY'].includes(e.code));child.stdin.write('revalidate\n');assert.equal(JSON.parse(await nextLine()).revalidated,true);await fs.writeFile(path.join(held.root,'new-untracked.txt'),'inert fixture');child.stdin.write('revalidate\n');assert.equal(JSON.parse(await nextLine()).verified,false);assert.equal(await closed,3);
 const late=await fixture(),lateDigest=sha(await fs.readFile(path.join(late.root,'native-runtime-manifest.json'))),lateChild=cp.spawn(program,[late.root,lateDigest,'hold'],{windowsHide:true,stdio:['pipe','pipe','pipe']});children.add(lateChild);const reader=readline.createInterface({input:lateChild.stdout}),iterator=reader[Symbol.asyncIterator](),lateExit=new Promise((yes,no)=>{lateChild.once('error',no);lateChild.once('close',code=>{children.delete(lateChild);yes(code);});});assert.equal(JSON.parse((await iterator.next()).value).verified,true);let linkedDuringHold=false;try{await fs.link(path.join(late.root,'stdlib/os.py'),path.join(base,'late-hardlink.py'));linkedDuringHold=true;}catch(error){assert.ok(['EACCES','EPERM','EBUSY'].includes(error.code));}lateChild.stdin.write('revalidate\n');const lateObservation=JSON.parse((await iterator.next()).value);if(linkedDuringHold){assert.equal(lateObservation.verified,false);assert.equal(await lateExit,3);}else{assert.equal(lateObservation.revalidated,true);lateChild.stdin.write('quit\n');assert.equal(await lateExit,0);}reader.close();
 console.log(JSON.stringify({actualWindowsVerifier:true,actualLoadedImageVerification:true,loadedImageOnlyCheck:true,unicodeRoot:true,unicodeFilename:true,pinnedSourceWriteDeleteRenameRejected:true,pinnedRuntimeRootRenameRejected:true,ancestorControlAtomicReplaceAllowed:true,lateInventoryChangeRejected:true,lateHardlinkCreated:linkedDuringHold,lateHardlinkPreventedOrDetected:true,syntheticPackageMetadata:true,providerRequests:0,cpythonExecuted:false,installed:false}));
} finally {
 for(const child of children){const exit=new Promise(resolve=>child.once('close',resolve));child.kill();await exit;}assert.equal(await fs.realpath(base),base);assert.equal(path.dirname(base),parent);assert.ok(path.basename(base).startsWith('xmind-generation-contract-'));assert.ok(!(await fs.lstat(base)).isSymbolicLink());await fs.rm(base,{recursive:true,force:true});
}
