// Actual native C++/embedded-xlang3 catalogue, CLI and authenticated browser
// routing. Guide content/endpoint/adapter assets are synthetic test fixtures;
// no inference, script execution or rendered view acceptance is claimed.
import assert from 'node:assert/strict';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import fs from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {randomBytes} from 'node:crypto';
import {request as rawRequest} from 'node:http';
import {createRequire} from 'node:module';
import {createBrowserServer} from '../../views/browser/server.mjs';
const require=createRequire(import.meta.url),{BackendClient}=require('../../extensions/vscode/client.js'),execute=promisify(execFile);
const [server,cli,modules,stdlib]=process.argv.slice(2),parent=await fs.realpath(tmpdir()),root=await fs.mkdtemp(path.join(parent,'xmind-skill-catalogue-')),workspace=path.join(root,'workspace'),skills=path.join(workspace,'.agents/skills'),assets=path.join(root,'assets');
await fs.mkdir(skills,{recursive:true});await fs.mkdir(assets);
for(const name of ['index.html','browser.js','browser.css','chat.js','chat.css','client.js','marked.js','purify.js'])await fs.writeFile(path.join(assets,name),'Synthetic routing fixture; not rendered UI.\n',{flag:'wx'});
const explicit='---\nname: Explicit guide\ndescription: Synthetic catalogue metadata\nautoinvoke: false\n---\nSynthetic body must not appear in a catalogue.\n',disabled='---\nname: Disabled guide\ndisable-model-invocation: true\n---\nSynthetic disabled body must not be invoked.\n';
await fs.mkdir(path.join(skills,'explicit'));await fs.writeFile(path.join(skills,'explicit/SKILL.md'),explicit,{flag:'wx'});await fs.writeFile(path.join(skills,'disabled.md'),disabled,{flag:'wx'});
const token=randomBytes(32).toString('hex'),env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
let child,exitPromise,exited,view,activeCookie;
async function stop(){if(view){await view.close();view=undefined;}if(child&&!exited){child.kill();let timer;try{await Promise.race([exitPromise,new Promise((_,no)=>{timer=setTimeout(()=>no(Error('Owned native catalogue fixture still running')),10000);})]);}finally{clearTimeout(timer);}assert.ok(exited);}}
async function start(mode,extra){exited=false;const log=await fs.open(path.join(root,mode+'-server.log'),'wx');child=spawn(server,['--db',path.join(root,mode+'.sqlite'),'--modules',modules,'--stdlib',stdlib,'--workspace',workspace,'--port','0',...extra],{env,windowsHide:true,stdio:['ignore','pipe',log.fd]});await log.close();exitPromise=new Promise((yes,no)=>{child.once('error',no);child.once('exit',(code,signal)=>{exited=true;yes({code,signal});});});
 return new Promise((yes,no)=>{let output='';const timer=setTimeout(()=>no(Error('Native catalogue fixture startup deadline')),15000);child.stdout.on('data',bytes=>{output+=bytes;if(output.length>65536){clearTimeout(timer);no(Error('Unexpected native fixture output'));return;}const match=/listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(output);if(match){clearTimeout(timer);yes(match[1]);}});child.once('error',e=>{clearTimeout(timer);no(e);});child.once('exit',()=>{clearTimeout(timer);no(Error('Native catalogue fixture exited before readiness'));});});
}
try{
 for(const [mode,extra]of [['profile',[]],['platform',['--model','synthetic-catalogue-model','--model-endpoint','http://127.0.0.1:1/chat/completions','--model-tools','supported']]]){
  const origin=await start(mode,extra),headers={Authorization:'Bearer '+token},client=new BackendClient(origin,()=>token),binding=await client.workspace();assert.equal(binding.configured,true);
  assert.equal((await fetch(origin+'/v1/workspace/skills')).status,401);
  const catalogue=await client.skills();assert.equal(catalogue.workspace_id,binding.workspace_id);assert.equal(catalogue.authority_id,binding.authority_id);assert.equal(catalogue.skills.length,2);
  assert.equal(catalogue.skills.find(s=>s.id==='explicit').autoinvoke,false);assert.equal(catalogue.skills.find(s=>s.id==='disabled').model_invocable,false);assert.ok(!JSON.stringify(catalogue).includes('Synthetic body'));assert.ok(!JSON.stringify(catalogue).includes('Synthetic disabled body'));assert.ok(catalogue.skills.every(s=>!Object.hasOwn(s,'content')&&!Object.hasOwn(s,'body')));
  // fetch normalizes away an empty trailing query. Send this exact request
  // target through raw HTTP so the backend, not the URL serializer, is tested.
  const emptyQueryStatus=await new Promise((yes,no)=>{const request=rawRequest({hostname:'127.0.0.1',port:new URL(origin).port,path:'/v1/workspace/skills?',headers},response=>{response.resume();response.once('end',()=>yes(response.statusCode));});request.once('error',no);request.end();});assert.equal(emptyQueryStatus,400);
  for(const suffix of ['?id=disabled','?path=../.config/providers.yaml'])assert.equal((await fetch(origin+'/v1/workspace/skills'+suffix,{headers})).status,400);
  const nativeCli=await execute(cli,[new URL(origin).port,'skills'],{env,windowsHide:true,timeout:15000});assert.deepEqual(JSON.parse(nativeCli.stdout),catalogue);
  const interactive=await new Promise((yes,no)=>{const process=execFile(cli,[new URL(origin).port,'chat'],{env,windowsHide:true,timeout:15000},(error,stdout)=>error?no(error):yes(stdout));process.stdin.end('/skills\n/exit\n');});
  const chatRecords=interactive.trim().split(/\r?\n/).map(line=>JSON.parse(line));assert.equal(chatRecords.length,1);assert.equal(chatRecords[0].type,'workspace_skills');assert.deepEqual(chatRecords[0].catalogue,catalogue);
  assert.deepEqual(await client.sessions(),[],'Catalogue inspection and console /skills must not admit a session');
  view=await createBrowserServer({backend:origin,assetRoot:assets});const viewOrigin=await view.listen(),viewHeaders={Origin:viewOrigin,'Content-Type':'application/json','Sec-Fetch-Site':'same-origin'};
  const enrolled=await fetch(viewOrigin+'/ui/session',{method:'POST',headers:{...viewHeaders,Authorization:'Bearer '+token},body:'{}'});assert.equal(enrolled.status,200);activeCookie=enrolled.headers.get('set-cookie').split(';')[0];
  const observed=await fetch(viewOrigin+'/v1/workspace/skills',{headers:{Cookie:activeCookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(observed.status,200);assert.deepEqual(await observed.json(),catalogue);
  assert.equal((await fetch(viewOrigin+'/v1/workspace/skills',{method:'POST',headers:{...viewHeaders,Cookie:activeCookie},body:'{}'})).status,404);
  assert.equal((await fetch(viewOrigin+'/v1/workspace/skills?path=other',{headers:{Cookie:activeCookie,'Sec-Fetch-Site':'same-origin'}})).status,400);
  await fs.writeFile(path.join(skills,'explicit/SKILL.md'),explicit.replace('Explicit guide','Current guide'));
  assert.equal((await client.skills()).skills.find(s=>s.id==='explicit').name,'Current guide');
  await fs.writeFile(path.join(skills,'explicit.md'),explicit,{flag:'wx'});assert.equal((await fetch(origin+'/v1/workspace/skills',{headers})).status,409,'Ambiguous current sources cannot yield a partial catalogue');await fs.unlink(path.join(skills,'explicit.md'));
  await fs.writeFile(path.join(skills,'malformed.md'),'---\nname: [not, scalar]\n---\nSynthetic invalid guide',{flag:'wx'});assert.equal((await fetch(origin+'/v1/workspace/skills',{headers})).status,409);await fs.unlink(path.join(skills,'malformed.md'));
  assert.deepEqual(await client.sessions(),[],'Scoped catalogue inspection must leave sessions empty');
  await fs.writeFile(path.join(skills,'explicit/SKILL.md'),explicit);
  const session=await client.createSession('Synthetic explicit skill controls');const sessionPath='/v1/sessions/'+session.id+'/skills';
  assert.equal((await fetch(origin+sessionPath)).status,401);assert.equal((await fetch(origin+'/v1/sessions/absent/skills',{headers})).status,404);
  const initial=await client.sessionSkills(session.id);assert.equal(initial.revision,0);assert.deepEqual(initial.ids,[]);assert.equal(initial.editable,true);assert.equal(initial.workspace_id,binding.workspace_id);assert.equal(initial.authority_id,binding.authority_id);
  const attached=await client.replaceSessionSkills(session.id,['disabled'],initial);assert.equal(attached.revision,1);assert.deepEqual(attached.ids,['disabled']);assert.deepEqual(attached.manual_ids,['disabled']);assert.ok(!JSON.stringify(attached).includes('Synthetic disabled body'));assert.deepEqual(await client.sessionSkills(session.id),attached);
  const change={ids:[],expected_revision:attached.revision,expected_workspace_id:binding.workspace_id,expected_workspace_authority_id:binding.authority_id};
  for(const [data,status] of [[{...change,expected_revision:0},409],[{...change,expected_workspace_authority_id:'f'.repeat(32)},409],[{...change,ids:['absent']},409],[{...change,ids:['disabled','disabled']},400],[{...change,manual_ids:['disabled']},400],[{...change,ids:['../.config/providers.yaml']},400],[{...change,ids:[3]},400]])assert.equal((await fetch(origin+sessionPath,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(data)})).status,status);
  assert.deepEqual(await client.sessionSkills(session.id),attached,'Rejected writes cannot change selection or revision');
  const scopedHeaders={...viewHeaders,Cookie:activeCookie};const scoped=await fetch(viewOrigin+sessionPath,{headers:{Cookie:activeCookie,'Sec-Fetch-Site':'same-origin'}});assert.equal(scoped.status,200);assert.deepEqual(await scoped.json(),attached);
  const cleared=await fetch(viewOrigin+sessionPath,{method:'POST',headers:scopedHeaders,body:JSON.stringify(change)});assert.equal(cleared.status,200);const clearState=await cleared.json();assert.equal(clearState.revision,2);assert.deepEqual(clearState.ids,[]);
  assert.equal((await fetch(viewOrigin+sessionPath,{method:'POST',headers:{Cookie:activeCookie,'Content-Type':'application/json'},body:JSON.stringify({...change,expected_revision:2})})).status,403);
  assert.equal((await fetch(viewOrigin+sessionPath+'?other=scope',{headers:{Cookie:activeCookie,'Sec-Fetch-Site':'same-origin'}})).status,400);
  const recovered=await client.replaceSessionSkills(session.id,['disabled'],await client.sessionSkills(session.id));await fs.writeFile(path.join(skills,'broken.md'),'---\nname: [invalid, shape]\n---\nSynthetic broken guide',{flag:'wx'});assert.equal((await fetch(origin+'/v1/workspace/skills',{headers})).status,409);const recoveryClear=await client.replaceSessionSkills(session.id,[],recovered);assert.deepEqual(recoveryClear.ids,[]);assert.equal(recoveryClear.revision,recovered.revision+1,'A broken catalogue cannot trap a session in its saved attachments');await fs.unlink(path.join(skills,'broken.md'));
  const unicodeId='Résumé Review',unicodeGuide=path.join(skills,unicodeId+'.md');await fs.writeFile(unicodeGuide,disabled,{flag:'wx'});
  const cliArguments=[new URL(origin).port],cliOptions={env,windowsHide:true,timeout:15000};
  const cliObserved=JSON.parse((await execute(cli,[...cliArguments,'session-skills',session.id],cliOptions)).stdout);assert.deepEqual(cliObserved,await client.sessionSkills(session.id));
  const snapshot=path.join(root,mode+'-observed-Résumé.json');await fs.writeFile(snapshot,JSON.stringify(cliObserved),{flag:'wx'});
  const chosen=JSON.parse((await execute(cli,[...cliArguments,'set-skills',session.id,snapshot,'disabled',unicodeId],cliOptions)).stdout);assert.deepEqual(new Set(chosen.ids),new Set(['disabled',unicodeId]));assert.deepEqual(new Set(chosen.manual_ids),new Set(chosen.ids));assert.equal(chosen.revision,cliObserved.revision+1,'Actual Unicode batch arguments and snapshot paths must preserve exact native ids');
  await assert.rejects(execute(cli,[...cliArguments,'set-skills',session.id,snapshot],cliOptions),error=>error.code===1&&error.stderr.includes('409'));assert.deepEqual(await client.sessionSkills(session.id),chosen,'CLI cannot silently rebase a stale observed snapshot');
  const utf16=path.join(root,mode+'-observed-utf16.json');await fs.writeFile(utf16,Buffer.concat([Buffer.from([255,254]),Buffer.from(JSON.stringify(chosen),'utf16le')]),{flag:'wx'});const emptied=JSON.parse((await execute(cli,[...cliArguments,'set-skills',session.id,utf16],cliOptions)).stdout);assert.deepEqual(emptied.ids,[]);assert.equal(emptied.revision,chosen.revision+1);
  const malformed=path.join(root,mode+'-invalid-snapshot.json'),privateMarker='Synthetic-private-parser-marker-do-not-echo';await fs.writeFile(malformed,'{"secret":"'+privateMarker+'",',{flag:'wx'});await assert.rejects(execute(cli,[...cliArguments,'set-skills',session.id,malformed],cliOptions),error=>error.code===1&&error.stderr.includes('Invalid session skill snapshot JSON')&&!error.stderr.includes(privateMarker)&&!error.stdout.includes(privateMarker));
  const other=await client.createSession('Synthetic isolated CLI selection');await fs.writeFile(snapshot,JSON.stringify({...emptied,session_id:other.id}));await assert.rejects(execute(cli,[...cliArguments,'set-skills',session.id,snapshot,'disabled'],cliOptions),error=>error.code===1&&error.stderr.includes('snapshot'));assert.deepEqual(await client.sessionSkills(session.id),emptied);
  const chatOutput=await new Promise((yes,no)=>{const process=execFile(cli,[...cliArguments,'chat',session.id],cliOptions,(error,stdout,stderr)=>error?no(error):yes({stdout,stderr}));process.stdin.end('/session-skills\n/attach-skill '+unicodeId+'\n/remove-skill '+unicodeId+'\n/attach-skill disabled\n/clear-skills\n/session '+other.id+'\n/attach-skill explicit\n/session-skills\n/exit\n');});
  const selections=chatOutput.stdout.trim().split(/\r?\n/).map(line=>JSON.parse(line)).filter(record=>record.type==='session_skills').map(record=>record.selection);assert.ok(selections.some(s=>s.session_id===session.id&&s.ids.includes(unicodeId)));assert.ok(selections.some(s=>s.session_id===session.id&&s.ids.length===0));assert.deepEqual(selections.at(-1).ids,['explicit']);assert.equal(selections.at(-1).session_id,other.id);assert.deepEqual((await client.sessionSkills(session.id)).ids,[],'Conversation change cannot carry a previous session selection');
  const concurrent=execFile(cli,[...cliArguments,'chat',session.id],cliOptions);let concurrentOut='',concurrentError='';concurrent.stdout.on('data',b=>concurrentOut+=b);concurrent.stderr.on('data',b=>concurrentError+=b);const concurrentExit=new Promise((yes,no)=>{concurrent.once('error',no);concurrent.once('exit',(code,signal)=>yes({code,signal}));});concurrent.stdin.write('/session-skills\n');
  const readDeadline=Date.now()+10000;while(!concurrentOut.includes('"type":"session_skills"')&&Date.now()<readDeadline)await new Promise(r=>setTimeout(r,20));assert.ok(concurrentOut.includes('"type":"session_skills"'),'Actual console snapshot not observed');const outside=await client.replaceSessionSkills(session.id,['disabled'],await client.sessionSkills(session.id));concurrent.stdin.write('/attach-skill explicit\n');
  const rejectDeadline=Date.now()+10000;while(!concurrentError.includes('Skill change rejected (HTTP 409)')&&Date.now()<rejectDeadline)await new Promise(r=>setTimeout(r,20));assert.ok(concurrentError.includes('Skill change rejected (HTTP 409)'));assert.deepEqual(await client.sessionSkills(session.id),outside,'Interactive stale write must not replay or overwrite another view');concurrent.stdin.end('/session-skills\n/clear-skills\n/exit\n');assert.equal((await concurrentExit).code,0,'An explicit refreshed successful write recovers the interactive result');assert.deepEqual((await client.sessionSkills(session.id)).ids,[]);
  const failedChat=await new Promise(yes=>{const process=execFile(cli,[...cliArguments,'chat',session.id],cliOptions,(error,stdout,stderr)=>yes({error,stdout,stderr}));process.stdin.end('/attach-skill absent-guide\n/exit\n');});assert.equal(failedChat.error?.code,1);assert.ok(failedChat.stderr.includes('HTTP 409'));assert.deepEqual((await client.sessionSkills(session.id)).ids,[]);
  await fs.unlink(unicodeGuide);
  assert.deepEqual(await client.runs(session.id),[],'Manual selection must not simulate inference or admit runs');
  await stop();
 }
 // No configured root must fail explicitly rather than choosing a directory.
 exited=false;const noRoot=spawn(server,['--db',path.join(root,'unbound.sqlite'),'--modules',modules,'--stdlib',stdlib,'--port','0'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});child=noRoot;exitPromise=new Promise((yes,no)=>{noRoot.once('error',no);noRoot.once('exit',()=>{exited=true;yes();});});
 const origin=await new Promise((yes,no)=>{let output='';const timer=setTimeout(()=>no(Error('Unbound native startup deadline')),15000);noRoot.stdout.on('data',b=>{output+=b;const m=/listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(output);if(m){clearTimeout(timer);yes(m[1]);}});noRoot.once('error',e=>{clearTimeout(timer);no(e);});});assert.equal((await fetch(origin+'/v1/workspace/skills',{headers:{Authorization:'Bearer '+token}})).status,503);await stop();
 console.log('Native skill catalogue passed actual configured/unconfigured-provider roots, exact workspace authority, native CLI and real scoped browser cookies, fresh source discovery, value-free metadata, read-only routes, malformed/ambiguous rejection and absent-root failure. Guides/assets/endpoint are synthetic; no inference or rendered UI claimed.');
}finally{await stop();const actual=await fs.realpath(root);assert.equal(actual,root);assert.equal(path.dirname(actual),parent);assert.ok(path.basename(actual).startsWith('xmind-skill-catalogue-'));await fs.rm(actual,{recursive:true});}
