#include "agentflow/skill_context.hpp"
#include "agentflow/repository_instruction_context.hpp"
#include "nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
using namespace agentflow;
using Json=nlohmann::json;
namespace {
void need(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class Error,class Action>void rejects(Action action){try{action();}catch(const Error&){return;}throw std::runtime_error("Expected native skill rejection did not occur");}
void write(const std::filesystem::path& file,const std::string& text){std::ofstream out(file,std::ios::binary|std::ios::trunc);out.write(text.data(),text.size());out.close();need(bool(out),"Fixture write failed");}
std::string guide(const std::string& body){return "---\nname: inspect\ndescription: Synthetic native skill fixture\nmetadata:\n  fixture: explicitly synthetic\n---\n"+body;}
}
int main(int argc,char** argv){if(argc!=2&&argc!=3)return 2;try{
    const auto root=std::filesystem::u8path(argv[1]);WorkspaceTools workspace(root.string());SkillContext skills(workspace);
    if(argc==3){need(std::string(argv[2])=="--catalogue","Unknown fixture mode");std::cout<<skills.catalogue_json()<<'\n';return 0;}
    need(Json::parse(skills.catalogue_json())["skills"].empty()&&skills.prepare().empty(),"Absent skill roots must not manufacture guidance");
    const auto directory=root/".agents"/"skills"/"inspect",file=directory/"SKILL.md";std::filesystem::create_directories(directory);
    write(file,guide("Synthetic active instructions: inspect only actual returned bytes.\n"));
    const auto catalogue=Json::parse(skills.catalogue_json());need(catalogue["skills"].size()==1&&catalogue["skills"][0]["id"]=="inspect", "Native discovery must use current verified workspace files");
    const auto advertised=skills.prepare();need(advertised.find("Synthetic native skill fixture")!=std::string::npos&&advertised.find("Synthetic active instructions")==std::string::npos,"Discovery must advertise metadata without activating body instructions");
    rejects<std::invalid_argument>([&]{skills.activate(R"({"id":"inspect","path":"../outside"})");});rejects<std::invalid_argument>([&]{skills.activate(R"({"id":"inspect","id":"other"})");});rejects<ToolAccessDenied>([&]{skills.activate(R"({"id":"missing"})");});
    need(skills.activation_directory(R"({"id":"inspect"})")==".agents/skills/inspect","Activation must derive its directory from Native discovery");
    const auto requested=Json::parse(skills.activate(R"({"id":"inspect"})"));need(requested["effect_permission"]==false&&!skills.ready(),"Loading must not grant effect authority or deliver guidance within the same model batch");
    need(skills.prepare().find("Synthetic active instructions")!=std::string::npos&&skills.ready(),"Next native provider context must deliver the current active body");
    const auto condition=skills.precondition();condition.verify({});need(condition.metadata_json.find("Synthetic active instructions")==std::string::npos&&Json::parse(condition.metadata_json)[0]["content_sha256"].get<std::string>().size()==64,"Approval must retain source identity/hash metadata, never body text");
    const auto before_rejected_load=skills.metadata();rejects<ToolFileError>([&]{skills.activate(R"({"id":"inspect"})",{},1);});need(skills.ready()&&skills.metadata()==before_rejected_load,"A rejected load must preserve already delivered guidance and readiness");
    {
        const auto skill_root=directory.parent_path();for(const auto* name:{"big-one","big-two","big-three"}){const auto path=skill_root/name;need(std::filesystem::create_directory(path),"Budget fixtures must be fresh directories");write(path/"SKILL.md",std::string("---\nname: ")+name+"\ndescription: Synthetic aggregate budget fixture\n---\n"+std::string(12000,'x'));}
        SkillContext bounded(workspace);bounded.prepare();bounded.activate(R"({"id":"big-one"})");bounded.prepare();bounded.activate(R"({"id":"big-two"})");bounded.prepare();const auto retained=bounded.metadata();rejects<ToolFileError>([&]{bounded.activate(R"({"id":"big-three"})");});need(bounded.ready()&&bounded.metadata()==retained,"Aggregate overflow must be rejected before activating a third guide or retiring existing guidance");
        for(const auto* name:{"big-one","big-two","big-three"}){const auto path=std::filesystem::weakly_canonical(skill_root/name);need(path.parent_path()==std::filesystem::weakly_canonical(skill_root)&&path.filename()==name,"Unsafe budget fixture cleanup path");std::filesystem::remove_all(path);}
    }
    write(file,guide("Synthetic changed instructions.\n"));need(!skills.ready(),"Changed source bytes must retire delivered guidance");rejects<ToolGuidanceChanged>([&]{condition.verify({});});need(skills.prepare().find("Synthetic changed instructions")!=std::string::npos&&skills.ready(),"Refresh must replace the old active body");
    RepositoryInstructionContext repository(workspace,workspace.repository_instructions());repository.prepare();repository.skills().activate(R"({"id":"inspect"})");need(!repository.ready("."),"Repository dispatch must defer pending skill delivery");repository.prepare();need(repository.ready("."),"Delivered skill context permits ordinary repository readiness");const auto bound=repository.precondition(".");need(Json::parse(bound.metadata_json)["skills"].size()==1,"Native effects must bind active skill snapshots into durable approval metadata");
    rejects<ToolFileError>([&]{repository.activate_skill(R"({"id":"inspect"})",65536);});need(repository.ready("."),"Combined instruction overflow must leave the delivered repository/skill context usable");
    write(file,guide("Synthetic newer instructions.\n"));rejects<ToolGuidanceChanged>([&]{bound.verify({});});repository.prepare();
    const auto saved=repository.skills().selections();SkillContext restored(workspace);restored.restore(saved);need(!restored.ready(),"Restored selection must reach a fresh model request before dispatch");need(restored.prepare().find("Synthetic newer instructions")!=std::string::npos&&restored.ready(),"Restoration must reread the current verified source body");
    rejects<ToolAccessDenied>([&]{auto foreign=saved;foreign.workspace_id="synthetic-foreign-workspace";restored.restore(foreign);});need(restored.ready(),"Foreign restoration failure must preserve delivered guidance");
    rejects<std::invalid_argument>([&]{auto duplicate=saved;duplicate.ids.push_back(duplicate.ids.front());restored.restore(duplicate);});need(restored.ready(),"Duplicate restoration failure must not change guidance");
    std::stop_source stopped;stopped.request_stop();rejects<ToolCancelled>([&]{skills.catalogue_json(stopped.get_token());});
    for(const auto& text:{std::string("name: inspect\ndescription: missing delimiter"),std::string("---\nname: inspect\nname: inspect\ndescription: duplicate\n---\nbody"),std::string("---\nname: [invalid-name-shape]\ndescription: invalid display name\n---\nbody"),std::string("---\nname: inspect\ndescription: &hidden bound\nlicense: *hidden\n---\nbody"),std::string("---\nname: inspect\ndescription: [nested, sequence]\n---\nbody"),std::string("---\nname: inspect\ndescription: okay\nautoinvoke: perhaps\n---\nbody"),std::string("---\nname: inspect\ndescription: okay\n---\n  \n")}){write(file,text);rejects<ToolFileError>([&]{skills.catalogue_json();});}
    write(file,"---\nname: inspect\ndescription: Manual-only fixture\nautoinvoke: false\n---\nSynthetic manual-only instructions.\n");SkillContext explicit_only(workspace);const auto explicit_only_catalogue=Json::parse(explicit_only.catalogue_json());need(explicit_only_catalogue["skills"][0]["model_invocable"]==true&&explicit_only_catalogue["skills"][0]["autoinvoke"]==false&&explicit_only.prepare().empty(),"Automatic suggestion policy must not forbid explicit loading");explicit_only.activate(R"({"id":"inspect"})");need(!explicit_only.ready()&&explicit_only.prepare().find("Synthetic manual-only instructions")!=std::string::npos&&explicit_only.ready(),"Explicitly referenced nonautomatic guides retain the native delivery barrier");
    write(file,"---\nname: inspect\ndescription: Pinned metadata policy fixture\nmetadata:\n  opencode/autoinvoke: \" False \"\n---\nSynthetic metadata-selected instructions.\n");SkillContext metadata_selected(workspace);need(Json::parse(metadata_selected.catalogue_json())["skills"][0]["autoinvoke"]==false&&metadata_selected.prepare().empty(),"Pinned normalized metadata flag must hide automatic suggestions");metadata_selected.activate(R"({"id":"inspect"})");need(metadata_selected.prepare().find("Synthetic metadata-selected instructions")!=std::string::npos&&metadata_selected.ready(),"Pinned metadata cannot block an explicitly selected guide");
    write(file,"---\nname: inspect\ndescription: Native disabled fixture\nautoinvoke: true\ndisable-model-invocation: true\n---\nSynthetic disabled instructions.\n");SkillContext disabled(workspace);need(Json::parse(disabled.catalogue_json())["skills"][0]["model_invocable"]==false&&disabled.prepare().empty(),"Explicit native disable remains a loading prohibition");rejects<ToolAccessDenied>([&]{disabled.activate(R"({"id":"inspect"})");});
    const SkillSelections manual{workspace.identity(),{"inspect"},{"inspect"}};disabled.restore(manual);need(!disabled.ready(),"User attachment still requires fresh delivery");need(disabled.prepare().find("Synthetic disabled instructions")!=std::string::npos&&disabled.ready(),"An explicit user attachment can deliver a model-disabled guide");need(disabled.selections().manual_ids==manual.manual_ids,"Explicit provenance must survive preparation");const auto manual_condition=disabled.precondition();manual_condition.verify({});rejects<ToolAccessDenied>([&]{disabled.activate(R"({"id":"inspect"})");});need(disabled.ready(),"A model cannot independently activate even its already user-attached disabled guide");
    write(file,"---\ndisable-model-invocation: true\n---\nChanged manual guide.\n");rejects<ToolGuidanceChanged>([&]{manual_condition.verify({});});disabled.restore({workspace.identity(),{}, {}});need(disabled.prepare().empty()&&disabled.ready(),"Explicit removal must retire the prior guidance");
    rejects<ToolGuidanceChanged>([&]{SkillContext no_manual(workspace);no_manual.restore({workspace.identity(),{"inspect"},{}});});
    write(file,guide("Restored fixture\n"));std::filesystem::remove(file);rejects<ToolGuidanceChanged>([&]{repository.prepare();});
    write(file,"---\nname: inspect\n---\nSynthetic explicitly selected guide without a description.\n");SkillContext undescribed(workspace);const auto explicit_catalogue=Json::parse(undescribed.catalogue_json());need(explicit_catalogue["skills"].size()==1&&!explicit_catalogue["skills"][0].contains("description")&&undescribed.prepare().empty(),"An absent description must remain absent and cannot become an automatic suggestion");undescribed.activate(R"({"id":"inspect"})");need(undescribed.prepare().find("Synthetic explicitly selected guide without a description")!=std::string::npos&&undescribed.ready(),"Explicit invocation must load an available undescribed guide through ordinary delivery rules");std::filesystem::remove(file);
    need(Json::parse(SkillContext(workspace).catalogue_json())["skills"].empty(),"Missing final SKILL.md is absent, not invented cached guidance");
    {
        const auto skill_root=directory.parent_path(),flat=skill_root/"Quick Review.md",legacy=skill_root/"Legacy_Name",group=skill_root/"group",nested=group/"deep"/"ops",root_guide=skill_root/"SKILL.md";
        const auto long_id=std::string(80,'A');const auto long_directory=skill_root/long_id;
        const std::string unicode_id="R\xc3\xa9sum\xc3\xa9";const auto unicode_directory=skill_root/std::filesystem::u8path(unicode_id);
        std::filesystem::create_directories(legacy);std::filesystem::create_directories(nested);std::filesystem::create_directories(long_directory);std::filesystem::create_directories(unicode_directory);
        write(flat,"---\nname: Human readable review\ndescription: Synthetic flat guide fixture\n---\nSynthetic flat skill body.\n");
        write(legacy/"SKILL.md","---\ndescription: Synthetic default display name\n---\nSynthetic legacy-named skill body.\n");
        write(nested/"SKILL.md","---\nname: Deployment review\ndescription: Synthetic nested guide fixture\n---\nSynthetic nested skill body.\n");
        write(root_guide,"---\n---\nSynthetic root guide with empty metadata.\n");write(long_directory/"SKILL.md","---\n---\nSynthetic long catalogue id.\n");write(unicode_directory/"SKILL.md","---\n---\nSynthetic Unicode catalogue id.\n");
        SkillContext formats(workspace);const auto current=Json::parse(formats.catalogue_json());need(current["skills"].size()==6,"Native source formats must produce the complete current catalogue");
        auto found=[&](const std::string& id){for(const auto& skill:current["skills"])if(skill["id"]==id)return skill;throw std::runtime_error("Expected discovered native skill id missing");};
        need(found("Quick Review")["name"]=="Human readable review"&&found("Legacy_Name")["name"]=="Legacy_Name"&&found("ops")["name"]=="Deployment review"&&found("skills")["name"]=="skills"&&found(long_id)["name"]==long_id&&found(unicode_id)["name"]==unicode_id,"Stable file-derived ids and display names must remain separate, with optional name defaults");
        need(formats.activation_directory(R"({"id":"Quick Review"})")==".agents/skills"&&formats.activation_directory(R"({"id":"ops"})")==".agents/skills/group/deep/ops","Explicit activation derives flat/nested base directories from the actual catalogue");
        formats.activate(R"({"id":"Quick Review"})");formats.activate(Json{{"id",long_id}}.dump());formats.activate(Json{{"id",unicode_id}}.dump());need(!formats.ready(),"New formats retain the provider delivery barrier");const auto prepared=formats.prepare();need(formats.ready()&&prepared.find("Human readable review")!=std::string::npos&&prepared.find("Synthetic flat skill body")!=std::string::npos&&prepared.find("Synthetic long catalogue id")!=std::string::npos&&prepared.find("Synthetic Unicode catalogue id")!=std::string::npos,"Current source names and bodies must reach native context through ordinary activation");
        const auto snapshot=formats.precondition();write(flat,"---\nname: Updated review\n---\nSynthetic changed flat guide.\n");rejects<ToolGuidanceChanged>([&]{snapshot.verify({});});
        const auto collision=skill_root/"Legacy_Name.md";write(collision,"---\n---\nSynthetic colliding guide.\n");rejects<ToolFileError>([&]{formats.catalogue_json();});std::filesystem::remove(collision);
        for(const auto& path:{flat,root_guide}){const auto checked=std::filesystem::weakly_canonical(path);need(checked.parent_path()==std::filesystem::weakly_canonical(skill_root),"Unsafe owned format file cleanup");std::filesystem::remove(checked);}
        for(const auto& path:{legacy,group,long_directory,unicode_directory}){const auto checked=std::filesystem::weakly_canonical(path);need(checked.parent_path()==std::filesystem::weakly_canonical(skill_root)&&checked!=std::filesystem::weakly_canonical(skill_root),"Unsafe owned format directory cleanup");std::filesystem::remove_all(checked);}
    }
    need(Json::parse(SkillContext(workspace).catalogue_json())["skills"].empty(),"Removed format fixtures cannot survive in a cached catalogue");
    std::cout<<"Native workspace skills passed: verified discovery, bounded frontmatter, delivery barriers, source refresh and approval binding; no live model or script executed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
