#include "agentflow/legacy_owner.hpp"
#include "agentflow/records.hpp"
#include "agentflow/context_records.hpp"
#include "nlohmann/json.hpp"
#include <algorithm>
#include <type_traits>
namespace agentflow {
namespace {
using Json=nlohmann::json;
void nonce(const std::string& value){if(value.size()!=32||value.find_first_not_of("0123456789abcdef")!=std::string::npos)throw std::invalid_argument("Invalid legacy operator ticket");}
std::int64_t integer(const SqlValue& v){if(!std::holds_alternative<std::int64_t>(v))throw DatabaseError("Invalid legacy repository metadata");return std::get<std::int64_t>(v);}
std::string text(const SqlValue& v){if(!std::holds_alternative<std::string>(v))throw DatabaseError("Invalid legacy repository text");return std::get<std::string>(v);}
Json cell(const SqlValue& v){return std::visit([](const auto& value)->Json{using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,std::nullptr_t>)return {{"type","null"}};else if constexpr(std::is_same_v<T,SqlBytes>)return {{"type","bytes"},{"value",Json::binary(value)}};else return {{"type",std::is_same_v<T,std::string>?"text":std::is_same_v<T,double>?"real":"integer"},{"value",value}};},v);}
Json table_snapshot(XlangSqlite& db,const std::string& table){
    if(table.empty()||table.size()>128||table.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")!=std::string::npos)throw DatabaseError("Unsupported legacy table name");
    const auto schema=db.execute("PRAGMA table_info(\""+table+"\")");Json columns=Json::array();for(const auto& row:schema.rows){Json r=Json::array();for(const auto& v:row)r.push_back(cell(v));columns.push_back(r);}if(columns.empty())throw DatabaseError("Legacy snapshot table is absent");
    const auto data=db.execute(table=="information"?"SELECT * FROM information WHERE category NOT IN ('native-backend-owner','native-legacy-owner')":"SELECT * FROM \""+table+"\"");
    std::vector<std::string> rows;std::size_t bytes=0;for(const auto& row:data.rows){Json r=Json::array();for(const auto& v:row)r.push_back(cell(v));auto raw=r.dump();bytes+=raw.size();if(bytes>128*1024*1024||rows.size()>=1000000)throw DatabaseError("Legacy table snapshot exceeds limits");rows.push_back(std::move(raw));}std::sort(rows.begin(),rows.end());
    return {{"columns",columns},{"rows",rows.size()},{"digest",context_digest(Json(rows).dump())}};
}
Json pending(XlangSqlite& db){const auto raw=legacy_owner_record(db);if(!raw||raw->size()>512*1024)throw Conflict("Legacy operator ticket is absent or invalid");const auto value=Json::parse(*raw);if(value.dump()!=*raw||value.at("version")!=1||value.size()!=7)throw DatabaseError("Invalid saved legacy operator record");nonce(value.at("ticket_id"));decode_backend_owner_target(value.at("target").dump());return value;}
void verify_snapshot(XlangSqlite& db,const Json& snapshot){if(!snapshot.is_object()||snapshot.empty()||snapshot.size()>256)throw DatabaseError("Invalid legacy data snapshot");for(const auto& item:snapshot.items())if(table_snapshot(db,item.key())!=item.value())throw Conflict("Legacy saved records changed before activation");}
}
std::optional<std::string> legacy_owner_record(XlangSqlite& db){if(db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='information'").rows.empty())return {};const auto rows=db.execute("SELECT payload FROM information WHERE category=? AND id='pending'",{std::string(legacy_owner_category)}).rows;return rows.empty()?std::optional<std::string>{}:text(rows[0][0]);}
void require_legacy_database_idle(XlangSqlite& db){
    const auto version=integer(db.execute("PRAGMA user_version").rows.at(0).at(0));if((version<12||version>14)||integer(db.execute("PRAGMA application_id").rows.at(0).at(0))!=0x584d494e)throw DatabaseError("Legacy owner handoff requires an existing xMind schema 12, 13 or 14 repository");
    for(const auto* sql:{"SELECT id FROM runs WHERE state IN ('queued','running','paused') LIMIT 1","SELECT id FROM operations WHERE state IN ('awaiting_approval','ready','executing','uncertain') LIMIT 1","SELECT attempt_id FROM agent_model_call_reservations WHERE state IN ('reserved','started') LIMIT 1","SELECT id FROM delegation_batches WHERE state IN ('accepted','working') LIMIT 1","SELECT id FROM dynamic_plans WHERE state IN ('active','waiting_human','uncertain') LIMIT 1","SELECT label FROM dynamic_plan_nodes WHERE state IN ('claimed','waiting_human','uncertain') LIMIT 1","SELECT id FROM dynamic_plan_calls WHERE state IN ('accepted','report_ready') LIMIT 1","SELECT id FROM agent_budget_segments WHERE state='open' LIMIT 1","SELECT root_run_id FROM dynamic_owner_pauses WHERE state='paused' LIMIT 1","SELECT id FROM context_idle_owners WHERE state='active' LIMIT 1","SELECT id FROM context_compactions WHERE state IN ('reserved','started','received') LIMIT 1","SELECT id FROM context_manual_requests WHERE state IN ('pending','claimed') LIMIT 1","SELECT id FROM context_measures WHERE state IN ('reserved','started') LIMIT 1","SELECT id FROM inference_steps WHERE state IN ('reserved','started') LIMIT 1"})if(!db.execute(sql).rows.empty())throw Conflict("Legacy execution or maintenance ownership is still active");
}
std::string snapshot_legacy_database(XlangSqlite& db){Json snapshot=Json::object();for(const auto& row:db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").rows){if(snapshot.size()>=256)throw DatabaseError("Legacy repository has too many tables");const auto name=text(row.at(0));snapshot[name]=table_snapshot(db,name);}return snapshot.dump();}
void publish_legacy_owner_ticket(XlangSqlite& db,const BackendLease& lease,const LegacyOwnerBootstrap& boot,const LegacyOwnerSource& source,const std::string& snapshot){
    nonce(boot.ticket_id);if(!source.process_id||source.process_birth.empty()||source.process_birth.size()>20||source.process_birth.find_first_not_of("0123456789")!=std::string::npos||source.server_sha256.size()!=64||source.server_sha256.find_first_not_of("0123456789abcdef")!=std::string::npos)throw std::invalid_argument("Invalid observed legacy source");
    require_legacy_database_idle(db);if(legacy_owner_record(db))throw Conflict("A legacy operator ticket is already pending");verify_snapshot(db,Json::parse(snapshot));
    const auto owner=db.execute("SELECT payload FROM information WHERE category='native-backend-owner' AND id='owner'").rows;if(!owner.empty()&&Json::parse(text(owner[0][0])).at("quiesced")!=false)throw Conflict("Existing closed native ownership cannot be replaced by a legacy ticket");
    const Json record={{"version",1},{"ticket_id",boot.ticket_id},{"target",Json::parse(encode_backend_owner_target(boot.target))},{"database_path",lease.canonical_database_path()},{"schema_version",integer(db.execute("PRAGMA user_version").rows[0][0])},{"source",{{"process_id",source.process_id},{"process_birth",source.process_birth},{"server_sha256",source.server_sha256}}},{"snapshot",Json::parse(snapshot)}};
    if(record.dump().size()>512*1024)throw DatabaseError("Legacy migration record exceeds limits");db.execute("INSERT INTO information(category,id,payload) VALUES(?,'pending',?)",{std::string(legacy_owner_category),record.dump()});
}
void require_legacy_owner_bootstrap(XlangSqlite& db,const BackendLease& lease,const LegacyOwnerBootstrap& boot){const auto value=pending(db);nonce(boot.ticket_id);if(value.at("ticket_id")!=boot.ticket_id||decode_backend_owner_target(value.at("target").dump())!=boot.target||value.at("database_path")!=lease.canonical_database_path())throw Conflict("Legacy operator ticket, target or database binding changed");require_legacy_database_idle(db);verify_snapshot(db,value.at("snapshot"));}
void verify_legacy_owner_saved_records(XlangSqlite& db){require_legacy_database_idle(db);verify_snapshot(db,pending(db).at("snapshot"));}
void consume_legacy_owner_ticket(XlangSqlite& db,const std::string& ticket){if(pending(db).at("ticket_id")!=ticket)throw Conflict("Legacy operator ticket changed");if(db.execute("DELETE FROM information WHERE category=? AND id='pending'",{std::string(legacy_owner_category)}).affected_rows!=1)throw Conflict("Legacy operator ticket disappeared");}
}
