// Dedicated local view/runtime preview. User VS Code profiles are not touched.
import {spawn} from 'node:child_process';import {mkdir,readFile,writeFile,copyFile,readdir,open,stat} from 'node:fs/promises';import {randomBytes,randomUUID} from 'node:crypto';
import {resolve,join} from 'node:path';import {fileURLToPath} from 'node:url';import {createBrowserServer} from '../views/browser/server.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),options=new Map();for(let i=2;i<process.argv.length;i+=2){if(!['--backend','--state','--assets','--server','--modules','--stdlib','--port','--provider-config'].includes(process.argv[i])||!process.argv[i+1]||options.has(process.argv[i]))throw new Error('Invalid browser launcher arguments');options.set(process.argv[i],process.argv[i+1]);}
if(options.has('--backend')&&options.has('--provider-config'))throw new Error('Provider YAML is imported by a newly launched native backend');
const state=resolve(options.get('--state')||join(root,'.agentflow/browser-ui')),assets=resolve(options.get('--assets')||join(root,'.agentflow/browser-assets'));await mkdir(state,{recursive:true});let origin=options.get('--backend'),pid;
if(!origin){
 const native=resolve(options.get('--server')||join(root,'build/a2a-native/Release/xmind_server.exe')),modules=resolve(options.get('--modules')||join(root,'../xlang3/build/Release/modules')),stdlib=resolve(options.get('--stdlib')||'C:/Python/Python314/Lib');
 const activePath=join(state,'active.json');let existing;try{existing=JSON.parse(await readFile(activePath,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}
 if(existing){const token=await readFile(join(state,'auth.token'),'utf8');try{const response=await fetch(existing.backend,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(1500)});if(response.status===404){const health=await fetch(existing.backend+'/v1/health',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(1500)});if(health.ok){origin=existing.backend;pid=existing.nativePid;}}}catch{}
  if(!origin)throw new Error('Existing browser runtime is unavailable. Inspect its recorded native PID before restarting; the launcher will not replace its state automatically.');
 }
 if(!origin){
  const token=randomBytes(32).toString('hex'),runtime=join(state,'runtime-'+randomUUID());await mkdir(join(runtime,'modules'),{recursive:true});for(const file of ['xmind_server.exe','xmind_schema_worker.exe','xlang3_runtime.dll'])await copyFile(join(resolve(native,'..'),file),join(runtime,file));for(const file of await readdir(modules))if(file.endsWith('.dll'))await copyFile(join(modules,file),join(runtime,'modules',file));await writeFile(join(state,'auth.token'),token,{mode:0o600});
  const stderr=await open(join(state,'native-error.log'),'a'),stdout=await open(join(state,'native.log'),'a');const env={...process.env,XMIND_AUTH_TOKEN:token};delete env.XMIND_API_KEY;
  const args=['--db',join(state,'state.sqlite'),'--modules',join(runtime,'modules'),'--stdlib',stdlib,'--port','0','--workspace',root,'--model-tools','supported','--graphs-config',join(root,'doc/examples/read-repository-file.graphs.json')];
  let providerConfig=options.get('--provider-config');
  if(!providerConfig){const candidate=join(root,'.config/providers.yaml');try{if((await stat(candidate)).isFile())providerConfig=candidate;}catch(error){if(error.code!=='ENOENT')throw error;}}
  if(providerConfig)args.push('--provider-config',resolve(providerConfig));
  const child=spawn(join(runtime,'xmind_server.exe'),args,{env,detached:true,windowsHide:true,stdio:['ignore','pipe',stderr.fd]});await stderr.close();pid=child.pid;let source='';origin=await new Promise((yes,no)=>{const timer=setTimeout(()=>no(new Error('Native browser runtime readiness timed out')),15000);child.once('error',error=>{clearTimeout(timer);no(error);});child.once('exit',code=>{clearTimeout(timer);no(new Error('Native browser runtime exited '+code));});child.stdout.on('data',bytes=>{stdout.write(bytes);source+=bytes;const match=/listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(source);if(match){clearTimeout(timer);yes(match[1]);}});});child.unref();
 }
}
const view=await createBrowserServer({backend:origin,assetRoot:assets}),url=await view.listen(Number(options.get('--port')||0))+'/ui/';await writeFile(join(state,'active.json'),JSON.stringify({url,backend:origin,nativePid:pid,viewPid:process.pid,assets,credentialFile:origin&&!options.has('--backend')?join(state,'auth.token'):undefined},null,2));console.log('xMind Browser ready at '+url);console.log('Native runtime '+origin+' · browser access token remains in the private launch-state directory.');
