const {test}=require('node:test'),assert=require('node:assert/strict');const {BrowserController}=require('../browser.js');
const {planFixture,inputMessage}=require('../../../extensions/vscode/tests/plan-fixture');
test('browser user skill commands use the selected session and stop publishing after disposal',async()=>{
 const workspace_id='windows-local-file-v1:synthetic-browser',authority_id='a'.repeat(32),calls=[],posted=[];let selection={session_id:'session',workspace_id,authority_id,ids:[],manual_ids:[],revision:0,editable:true};
 const client={health:async()=>({agent_execution:false,skill_controls:true}),graphs:async()=>({graphs:[]}),sessions:async()=>[{id:'session',title:'Synthetic skill view'}],history:async()=>[],runs:async()=>[],skills:async()=>({workspace_id,authority_id,skills:[{id:'manual',name:'User guide',path:'.agents/skills/manual.md',model_invocable:false}]}),sessionSkills:async()=>selection,replaceSessionSkills:async(session,ids,observed)=>{calls.push({session,ids,observed});selection={...selection,ids,manual_ids:ids,revision:observed.revision+1};return selection;}};
 const view=new BrowserController(client,m=>posted.push(m));try{await view.initialize({session:'session'});assert.equal(posted.findLast(m=>m.type==='skills').selection.revision,0);await view.handle({type:'skills-change',session:'session',revision:0,ids:['manual']});assert.equal(calls.length,1);assert.equal(calls[0].session,'session');assert.deepEqual(posted.findLast(m=>m.type==='skills').selection.manual_ids,['manual']);view.runs=[{id:'run',state:'paused'}];await view.handle({type:'skills-change',session:'session',revision:1,ids:[]});assert.equal(calls.length,1);assert.equal(posted.at(-1).type,'skills-error');const length=posted.length;view.dispose();await view.readSkills();assert.equal(posted.length,length,'Disposed views cannot emit a skill clear or late receipt');}finally{view.dispose();}
});

test('conversation selection recovers the new provider catalogue after its native selection acknowledgement is retired',async()=>{
 let state={revision:4,active:'first',profiles:[{id:'first',provider:'openai',route_id:'openai.responses',model:'first-current',revision:1},{id:'next',provider:'anthropic',route_id:'anthropic.messages',model:'next-current',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true},{id:'anthropic.messages',provider:'anthropic',wire:'anthropic-messages',discovery:true}]};
 let release;const acknowledgement=new Promise(resolve=>release=resolve),calls=[],posted=[];
 const client={providerProfiles:async()=>state,discoverProfileModels:async(...args)=>{calls.push(['discover',...args]);return {models:[{id:state.active+'-current'},{id:state.active+'-alternate'}]};},selectProviderProfile:async(...args)=>{calls.push(['select',...args]);state={...state,revision:5,active:args[0]};return acknowledgement;},saveProviderProfile:async()=>{throw new Error('No automatic model write permitted');},health:async()=>({agent_execution:true}),models:async()=>({models:[{id:state.active+'-current'}],default_model:state.active+'-current'}),graphs:async()=>({graphs:[]}),sessions:async()=>[{id:'older'}],history:async()=>[{role:'assistant',data:{content:'Retained synthetic history'}}],runs:async()=>[]};
 const view=new BrowserController(client,value=>posted.push(value));
 try{await view.discover();const selection=view.handle({type:'select-provider',id:'next'});for(let n=0;n<50&&!calls.some(c=>c[0]==='select');n++)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.filter(c=>c[0]==='select').length,1);
  const conversation=view.handle({type:'select',id:'older'});release(state);await Promise.all([selection,conversation]);
  assert.deepEqual(calls,[['discover','first','openai.responses',undefined,4],['select','next',4],['discover','next','anthropic.messages',undefined,5]]);
  assert.equal(view.model,'next-current');assert.equal(view.session,'older');assert.equal(posted.findLast(m=>m.type==='history').history[0].data.content,'Retained synthetic history');assert.deepEqual(posted.findLast(m=>m.type==='model-list').models,[{id:'next-current'},{id:'next-alternate'}]);assert.equal(posted.findLast(m=>m.type==='provider-profiles').active,'next');
 }finally{view.dispose();}
});

test('a second conversation/profile observation rejects the retired recovery catalogue and publishes only its current native binding',async()=>{
 const profiles=['first','next','last'].map(id=>({id,provider:'openai',route_id:'openai.responses',model:id+'-current',revision:1}));let state={revision:4,active:'first',profiles,routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true}]};
 let release;const pending=new Promise(resolve=>release=resolve),calls=[],posted=[];
 const client={providerProfiles:async()=>state,discoverProfileModels:async(...args)=>{calls.push(args);return args[0]==='next'?pending:{models:[{id:args[0]+'-current'},{id:args[0]+'-alternate'}]};},health:async()=>({agent_execution:true}),models:async()=>({models:[{id:state.active+'-current'}],default_model:state.active+'-current'}),graphs:async()=>({graphs:[]}),sessions:async()=>[{id:'older'},{id:'latest'}],history:async id=>[{role:'assistant',data:{content:'Synthetic history for '+id}}],runs:async()=>[]};
 const view=new BrowserController(client,value=>posted.push(value));
 try{await view.discover();state={...state,revision:5,active:'next'};const older=view.handle({type:'select',id:'older'});for(let n=0;n<50&&!calls.some(c=>c[0]==='next');n++)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.filter(c=>c[0]==='next').length,1);
  state={...state,revision:6,active:'last'};const latest=view.handle({type:'select',id:'latest'});release({models:[{id:'retired-next-only'}]});await Promise.all([older,latest]);
  assert.deepEqual(calls,[['first','openai.responses',undefined,4],['next','openai.responses',undefined,5],['last','openai.responses',undefined,6]]);assert.equal(view.session,'latest');assert.equal(view.model,'last-current');assert.ok(!posted.some(m=>m.type==='model-list'&&m.models.some(x=>x.id==='retired-next-only')));assert.deepEqual(posted.findLast(m=>m.type==='model-list').models,[{id:'last-current'},{id:'last-alternate'}]);assert.equal(posted.findLast(m=>m.type==='history').history[0].data.content,'Synthetic history for latest');
 }finally{view.dispose();}
});

test('browser imported key-only profiles guide the footer selection without a new-key error or provider calls',async()=>{
 const state={revision:1,active:'',profiles:[{id:'saved-openai',provider:'openai',route_id:'openai.responses',model:'',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true}]},calls=[],posted=[];
 const view=new BrowserController({providerProfiles:async()=>state,discoverProfileModels:async()=>{calls.push('discover');},selectProviderProfile:async()=>{calls.push('select');},saveProviderProfile:async()=>{calls.push('save');},providerConfiguration:async()=>{calls.push('legacy');}},value=>posted.push(value));
 try{await view.discover();assert.deepEqual(calls,[]);assert.equal(view.profileController.state.active,'');assert.ok(!posted.some(value=>value.type==='error'));assert.match(posted.findLast(value=>value.type==='status').text,/Choose a saved provider below/);assert.match(posted.findLast(value=>value.type==='settings-state').text,/saved key will be used/);assert.equal(view.profileController.draft,undefined);}finally{view.dispose();}
});

test('browser saved catalogue remains usable after settings close, new conversation and selection without automatic profile writes',async()=>{
 let state={revision:4,active:'saved',profiles:[{id:'saved',provider:'openai',route_id:'openai.responses',model:'current',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true}]};const writes=[],discoveries=[],posted=[],models=Array.from({length:135},(_,n)=>({id:'discovered-'+n}));
 const client={providerProfiles:async()=>state,discoverProfileModels:async(...args)=>{discoveries.push(args);return {models};},saveProviderProfile:async(...args)=>{writes.push(args);state={...state,revision:state.revision+1,profiles:[{...state.profiles[0],revision:state.profiles[0].revision+1,model:args[2]}]};return state;},health:async()=>({agent_execution:true}),models:async()=>({models:[{id:state.profiles[0].model}],default_model:state.profiles[0].model}),graphs:async()=>({graphs:[]}),createSession:async()=>({id:'new-session'}),sessions:async()=>[{id:'new-session'},{id:'older-session'}],history:async()=>[],runs:async()=>[]};
 const view=new BrowserController(client,value=>posted.push(value));
 try{await view.discover();await view.handle({type:'discardProviderKey'});assert.equal(posted.findLast(m=>m.type==='model-list').models.length,135);await view.handle({type:'new'});await view.handle({type:'select',id:'older-session'});assert.equal(writes.length,0);assert.equal(discoveries.length,1);await view.handle({type:'model',id:'discovered-134'});assert.deepEqual(writes,[['saved','openai.responses','discovered-134',undefined,4,true]]);assert.equal(posted.findLast(m=>m.type==='model-list').models.length,135);
  state={...state,revision:6,profiles:[{...state.profiles[0],revision:3,model:'external'}]};await view.handle({type:'model',id:'discovered-133'});assert.equal(writes.length,1);assert.equal(view.model,'external');assert.equal(view.profileController.savedCatalogue,undefined);assert.match(posted.at(-1).text,/settings changed/);
 }finally{view.dispose();}
});

test('browser footer provider command uses native profile CAS and saved-key discovery, with no automatic model enrollment',async()=>{
 let state={revision:4,active:'first',profiles:[{id:'first',provider:'openai',route_id:'openai.responses',model:'current',revision:1},{id:'claude',provider:'anthropic',route_id:'anthropic.messages',model:'',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true},{id:'anthropic.messages',provider:'anthropic',wire:'anthropic-messages',discovery:true}]};const calls=[],posted=[];
 const client={providerProfiles:async()=>state,selectProviderProfile:async(...args)=>{calls.push(['select',...args]);state={...state,revision:5,active:args[0]};return state;},discoverProfileModels:async(...args)=>{calls.push(['discover',...args]);return {models:[{id:'fixture-claude'},{id:'fixture-claude-next'}]};},saveProviderProfile:async(...args)=>{calls.push(['save',...args]);state={...state,revision:6,profiles:state.profiles.map(profile=>profile.id===args[0]?{...profile,revision:2,model:args[2]}:profile)};return state;},health:async()=>({agent_execution:!!state.profiles.find(value=>value.id===state.active)?.model}),models:async()=>{const model=state.profiles.find(value=>value.id===state.active).model;return {models:model?[{id:model}]:[],default_model:model};},graphs:async()=>({graphs:[]})};
 const view=new BrowserController(client,value=>posted.push(value));try{await view.discover();calls.length=0;await view.handle({type:'select-provider',id:'claude'});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls,[['select','claude',4],['discover','claude','anthropic.messages',undefined,5]]);assert.equal(view.model,undefined);assert.equal(posted.findLast(value=>value.type==='provider-profiles').active,'claude');assert.equal(posted.findLast(value=>value.type==='model-list').models.length,2);await view.handle({type:'discardProviderKey'});await view.handle({type:'model',id:'fixture-claude'});assert.deepEqual(calls[2],['save','claude','anthropic.messages','fixture-claude',undefined,5,true]);assert.equal(view.model,'fixture-claude');assert.equal(state.profiles[0].model,'current');}finally{view.dispose();}
});
test('browser graph resume requires displayed and freshly verified backend eligibility/CAS and never retries conflicts',async()=>{
 const root={run:{id:'graph',session_id:'session',state:'paused',graph_root:true},checkpoint_revision:7,context:{enabled:true,resumable:true,remaining_active_ms:1000}},calls=[],posted=[];
 let fresh=root;const client={graph:async()=>fresh,resumeGraph:async(...args)=>{calls.push(args);return root.run;}};const view=new BrowserController(client,value=>posted.push(value));view.session='session';view.runId='graph';view.graph=root;view.poll=async()=>{};view.watch=()=>{};
 try{await view.handle({type:'graph-resume',root:'graph',revision:7});assert.deepEqual(calls,[['graph',7]]);fresh={...root,checkpoint_revision:8};await view.handle({type:'graph-resume',root:'graph',revision:7});assert.equal(calls.length,1);assert.match(posted.at(-1).text,/changed/);
  client.graph=async()=>{throw Object.assign(new Error('Mixed observation'),{status:409});};await view.handle({type:'graph-resume',root:'graph',revision:7});assert.equal(view.graph,undefined);assert.equal(calls.length,1);assert.ok(posted.some(message=>message.type==='graph-clear'));
 }finally{view.dispose();}
});
test('browser context control uses actual discovery and discards a stale session/model generation before compaction',async()=>{
 const actual={session_id:'session',model_id:'model',enabled:true,automatic:true,head_revision:3,source_watermark:5,manual:null,checkpoint:null},calls=[],posted=[];let pause;
 const client={context:async()=>pause?pause:actual,compactContext:async(...args)=>{calls.push(args);return {id:args[1],state:'pending'};},contextRequest:async(_s,id)=>({id,state:'completed'})};
 const view=new BrowserController(client,value=>posted.push(value));view.health={context_controls:true};view.session='session';view.model='model';
 try{await view.readContext();let resolve;pause=new Promise(yes=>resolve=yes);const action=view.handle({type:'context-compact',session:'session',model:'model',expected_head_revision:3});view.stop();view.session='foreign';resolve(actual);await action;assert.equal(calls.length,0);assert.ok(!posted.some(message=>message.type==='context'&&message.record.session_id==='foreign'));
  view.health={context_controls:false};await view.handle({type:'context-compact',session:'foreign',model:'model',expected_head_revision:3});assert.equal(calls.length,0);
 }finally{view.dispose();}
});
function planController(record,planRead=async()=>record){const posted=[],calls=[];const client={plan:planRead,planInput:async(...args)=>{calls.push(['input',...args]);return {...record.run,state:'running'};},resumePlan:async(...args)=>{calls.push(['resume',...args]);return {...record.run,state:'running'};}};const view=new BrowserController(client,value=>posted.push(value));view.session=record.run.session_id;view.runId=record.run.id;view.health={agent_planning:true};view.planObservation=JSON.parse(JSON.stringify(record));view.poll=async()=>{};view.watch=()=>{};return {view,posted,calls};}
test('browser binds raw human input and explicit final-human resume to actual displayed and freshly observed plan identities',async()=>{
 const record=planFixture(),h=planController(record);try{const raw='{"quantity":1.00000000000000000001,"answer":true}';await h.view.handle(inputMessage(record,raw));assert.deepEqual(h.calls,[['input',record.run.id,record.questions[0].id,raw,2,17]]);assert.ok(h.posted.some(message=>message.type==='plan'));}finally{h.view.dispose();}
 const ready=planFixture({answer:true}),resume=planController(ready);try{await resume.view.handle({type:'plan-resume',root:ready.run.id,plan_id:ready.plan.id,expected_revision:2,expected_state_sequence:18});assert.deepEqual(resume.calls,[['resume',ready.run.id,2,18]]);}finally{resume.view.dispose();}
});
test('browser rejects stale CAS, changed question identity, duplicate keys, foreign roots and observation conflicts before any controller mutation',async()=>{
 for(const change of [record=>record.plan.state_sequence++,record=>record.questions[0].expires_unix_ms++,record=>record.run.session_id='foreign-session']){
  const original=planFixture(),fresh=JSON.parse(JSON.stringify(original));change(fresh);const h=planController(original,async()=>fresh);try{await h.view.handle(inputMessage(original));assert.equal(h.calls.length,0);assert.ok(h.posted.some(message=>message.type==='error'));}finally{h.view.dispose();}
 }
 const original=planFixture(),h=planController(original);try{await h.view.handle(inputMessage(original,'{"x":1,"\\u0078":2}'));assert.equal(h.calls.length,0);assert.ok(h.posted.some(message=>message.type==='error'));await h.view.handle({...inputMessage(original),root:'foreign-root'});assert.equal(h.calls.length,0);}finally{h.view.dispose();}
 const conflict=planController(original,async()=>{throw Object.assign(new Error('Plan reads conflicted'),{status:409});});try{await conflict.view.handle(inputMessage(original));assert.equal(conflict.calls.length,0);assert.equal(conflict.view.planObservation,undefined);assert.ok(conflict.posted.some(message=>message.type==='plan-clear'));}finally{conflict.view.dispose();}
});
test('browser generation change during a fresh plan check discards response and cannot answer the prior selected owner',async()=>{
 const record=planFixture();let resolve,entered;const started=new Promise(yes=>entered=yes),h=planController(record,()=>{entered();return new Promise(yes=>resolve=yes);});try{const action=h.view.handle(inputMessage(record));await started;h.view.stop();h.view.session='another-session';h.view.runId='another-root';resolve(record);await action;assert.equal(h.calls.length,0);assert.ok(!h.posted.some(message=>message.type==='plan'));}finally{h.view.dispose();}
});
test('browser transient plan GET conflicts discard actions and retry only bounded read observation',async()=>{
 const record=planFixture();let reads=0;const h=planController(record,async()=>{reads++;throw Object.assign(new Error('Changing topology'),{status:409});});try{for(let i=0;i<3;i++)await h.view.readPlan(record.run.id,h.view.generation);assert.equal(reads,3);assert.equal(h.calls.length,0);assert.equal(h.view.planObservation,undefined);assert.equal(h.view.pendingPlanObservation,false);assert.match(h.posted.at(-1).text,/Refresh/);}finally{h.view.dispose();}
});
test('owned observation rejects a same-session status for another root and selection resets cursor backlog',async()=>{
 const posted=[];let trees=0;const client={status:async()=>({id:'foreign-root',session_id:'session',state:'completed',parent_id:'',graph_root:false}),treeEvents:async()=>{trees++;return [];}};
 const view=new BrowserController(client,value=>posted.push(value));view.session='session';view.runId='selected-root';view.health={owned_child_observation:true};view.pendingTreeEvents=true;
 try{await view.poll();assert.equal(trees,0);assert.equal(view.runId,'selected-root');assert.ok(posted.some(value=>value.type==='error'&&value.text.includes('identity changed')));assert.ok(!posted.some(value=>value.type==='owned-children'));view.stop();assert.equal(view.pendingTreeEvents,false);}finally{view.dispose();}
});
test('normal Agent shows native-owned investigations and drains terminal child history without a graph selection',async()=>{
 const parent={id:'parent',session_id:'session',state:'completed',parent_id:'',graph_root:false},child={run:{id:'leaf',session_id:'session',parent_id:'parent',state:'failed',graph_root:false},kind:'delegated_leaf',batch_id:'batch',task_id:'inspect',preset_id:'workspace.inspect',preset_revision:1},posted=[];let reads=0;
 const client={status:async()=>parent,treeEvents:async()=>++reads===1?[]:[{seq:1,run_id:'leaf',kind:'run.failed',data:{reason:'synthetic_fixture_failure'}},{seq:2,run_id:'parent',kind:'run.completed',data:{}}],ownedChildren:async()=>[child],ownedChildHistory:async()=>[{role:'assistant',data:{content:'Synthetic failed leaf fixture',usage:{prompt_tokens:4,completion_tokens:2}}}],operations:async()=>[],history:async()=>[{role:'assistant',data:{content:'Synthetic parent continuation after typed leaf failure',usage:{prompt_tokens:7,completion_tokens:3}}}],runs:async()=>[parent]};
 const view=new BrowserController(client,value=>posted.push(value));view.session='session';view.runId='parent';view.health={owned_child_observation:true};try{await view.poll();assert.equal(view.graphId,undefined);assert.equal(view.graph,undefined);assert.equal(posted.findLast(value=>value.type==='owned-children').children[0].run.state,'failed');assert.ok(posted.some(value=>value.type==='owned-event'&&value.child_id==='leaf'));assert.equal(posted.findLast(value=>value.type==='transcript').history[0].data.usage.prompt_tokens,7);assert.equal(view.cursor,2);assert.equal(posted.findLast(value=>value.type==='status').text,'completed');}finally{view.dispose();}
});
test('profile conflicts refresh the displayed account and model without replaying the retained task',async()=>{
 const {ProviderProfileController}=require('../../../extensions/vscode/client.js');let state={revision:4,active:'first',profiles:[{id:'first',route_id:'openai.responses',provider:'openai',model:'fixture-first',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true}]};let admissions=0;const posted=[];
 const client={providerProfiles:async()=>state,run:async()=>{admissions++;state={...state,revision:5,active:'second',profiles:[...state.profiles,{id:'second',route_id:'openai.responses',provider:'openai',model:'fixture-second',revision:1}]};throw Object.assign(new Error('Profile changed'),{status:409});},health:async()=>({agent_execution:true,provider_profile_admission:true}),models:async()=>({models:[{id:'fixture-second'}],default_model:'fixture-second'}),graphs:async()=>({graphs:[]})};
 const view=new BrowserController(client,value=>posted.push(value));view.health={agent_execution:true,provider_profile_admission:true};view.session='session';view.model='fixture-first';view.profileController=new ProviderProfileController(client,value=>posted.push(value));
 try{await view.profileController.refresh();await view.handle({type:'send',prompt:'Retained fixture draft'});assert.equal(admissions,1);assert.equal(view.model,'fixture-second');assert.equal(view.runId,undefined);assert.ok(posted.some(value=>value.type==='provider-profiles'&&value.active==='second'));assert.match(posted.at(-1).text,/draft has been kept/);assert.ok(!posted.some(value=>value.type==='user'));}finally{view.dispose();}
});
test('browser sends its known profile revision and retains the prompt when native admission rejects a stale view',async()=>{
 const posted=[],calls=[];const client={run:async(...args)=>{calls.push(args);throw Object.assign(new Error('Provider profile changed before run admission'),{status:409});}};
 const view=new BrowserController(client,value=>posted.push(value));view.health={agent_execution:true,provider_profile_admission:true};view.session='session';view.model='same-model';view.profileController={admission:async()=>({provider_profile_id:'saved-account',expected_provider_revision:4}),reconcileAdmission:async()=>false,dispose(){},invalidate(){}};
 try{await view.handle({type:'send',prompt:'Keep this task'});assert.deepEqual(calls[0],['session','Keep this task','same-model',{provider_profile_id:'saved-account',expected_provider_revision:4}]);assert.ok(posted.some(value=>value.type==='error'&&value.text.includes('profile changed')));assert.ok(!posted.some(value=>value.type==='user'));assert.equal(view.runId,undefined);}finally{view.dispose();}
});
test('browser Settings preserves the selected profile route through private discovery and footer enrollment',async()=>{
 let state={revision:3,active:'openai',profiles:[{id:'openai',provider:'openai',route_id:'openai.responses',model:'fixture-openai',revision:3}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true},{id:'anthropic.messages',provider:'anthropic',wire:'anthropic-messages',discovery:true}]};const posted=[],calls=[],secret='synthetic-browser-claude-profile-key';
 const client={providerProfiles:async()=>state,discoverProfileModels:async(...args)=>{calls.push(['discover',...args]);return {models:[{id:'fixture-claude'}]};},saveProviderProfile:async(...args)=>{calls.push(['save',...args]);state={...state,revision:4,active:args[0],profiles:[...state.profiles,{id:args[0],provider:'anthropic',route_id:args[1],model:args[2],revision:1}]};return state;},health:async()=>({agent_execution:true}),models:async()=>({models:[{id:state.profiles.at(-1).model}],default_model:state.profiles.at(-1).model}),graphs:async()=>({graphs:[]})};
 const view=new BrowserController(client,value=>posted.push(value));try{const message={type:'saveProviderKey',key:secret,profile:'',route:'anthropic.messages'};await view.handle(message);assert.ok(!Object.hasOwn(message,'key'));assert.equal(calls[0][2],'anthropic.messages');assert.equal(calls.length,1);await view.handle({type:'model',id:'fixture-claude'});assert.equal(calls[1][2],'anthropic.messages');assert.equal(calls[1][4],secret);assert.equal(view.model,'fixture-claude');assert.ok(!JSON.stringify(posted).includes(secret));assert.equal(state.profiles[0].model,'fixture-openai');}finally{view.dispose();}
});
test('rename sends the displayed expected title only for the selected supported conversation and retains conflicts',async()=>{
 const posted=[],calls=[];let conflict=false;
 const client={renameSession:async(...args)=>{calls.push(args);if(conflict)throw Object.assign(new Error('Conflict'),{status:409});},sessions:async()=>[{id:'selected',title:'Renamed fixture'}]};
 const view=new BrowserController(client,message=>posted.push(message));view.health={session_rename:true};view.session='selected';
 await view.handle({type:'rename-session',id:'foreign',title:'New',expected_title:'Old'});assert.equal(calls.length,0);
 await view.handle({type:'rename-session',id:'selected',title:'New',expected_title:'Displayed original'});assert.deepEqual(calls[0],['selected','New','Displayed original']);assert.ok(posted.some(message=>message.type==='sessions'));assert.equal(posted.at(-1).success,true);
 conflict=true;await view.handle({type:'rename-session',id:'selected',title:'Draft',expected_title:'Stale'});assert.equal(posted.at(-1).success,false);assert.match(posted.at(-1).text,/title changed/);
 view.health={};await view.handle({type:'rename-session',id:'selected',title:'New',expected_title:'Old'});assert.equal(calls.length,2);view.dispose();
});
test('Responses saved-key discovery and model selection preserve backend-reported wire',async()=>{
 const posted=[],setup={provider:'openai',wire:'responses',endpoint:'https://api.openai.com/v1/responses',revision:3,configured:true,model:'gpt-5.6-sol'};let discovered=0,configured=0;
 const client={providerConfiguration:async()=>setup,discoverProviderModels:async(key,revision)=>{assert.equal(key,undefined);assert.equal(revision,3);discovered++;return {models:[{id:'gpt-5.6-sol'}]};},configureProvider:async(id,key,revision)=>{assert.equal(id,'gpt-5.6-sol');assert.equal(key,undefined);assert.equal(revision,3);configured++;return {...setup,revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'gpt-5.6-sol',models:[{id:'gpt-5.6-sol'}]})};
 const view=new BrowserController(client,message=>posted.push(message));await view.discover();await view.handle({type:'model',id:'gpt-5.6-sol'});assert.equal(discovered,1);assert.equal(configured,1);assert.equal(view.selection.revision,4);assert.ok(posted.some(message=>message.type==='provider-wire'&&message.wire==='responses'));view.dispose();
});
test('restoring the native view does not wait for provider catalogue discovery',async()=>{
 let release,discovery=0;const pending=new Promise(resolve=>release=resolve),posted=[],client={health:async()=>({agent_execution:true}),models:async()=>({default_model:'fixture-default',models:[{id:'fixture-default'}]}),graphs:async()=>({graphs:[]}),sessions:async()=>[],providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:1,configured:true,model:'fixture-default'}),discoverProviderModels:()=>{discovery++;return pending;}};
 const view=new BrowserController(client,value=>posted.push(value));let deadline;try{const restored=await Promise.race([view.initialize().then(()=>true),new Promise(resolve=>deadline=setTimeout(()=>resolve(false),250))]);assert.equal(restored,true,'Slow provider discovery must not block native session restoration');await new Promise(resolve=>setImmediate(resolve));assert.equal(discovery,1);assert.equal(posted.find(m=>m.type==='capabilities').model,'fixture-default');assert.ok(posted.some(m=>m.type==='status'&&m.text==='Ready'));const count=posted.length;view.dispose();release({models:[{id:'fixture-discovered'}]});await new Promise(resolve=>setImmediate(resolve));assert.equal(posted.length,count,'Late discovery must not publish into a disposed view');}finally{clearTimeout(deadline);view.dispose();release({models:[]});}
});
test('view catches a completion between event and status reads and drains final events',async()=>{let status=0,eventReads=0;const posted=[];const client={status:async()=>({id:'run',session_id:'session',state:++status===1?'running':'completed'}),events:async()=>++eventReads===1?[]:[{seq:1,run_id:'run',kind:'conversation.assistant',data:{content:'Actual fixture result'}}],operations:async()=>[],history:async()=>[{role:'assistant',data:{content:'Actual fixture result',usage:{prompt_tokens:4,completion_tokens:2}}}],runs:async()=>[{id:'run',state:'completed'}]};const view=new BrowserController(client,value=>posted.push(value));view.runId='run';view.session='session';await view.poll();assert.equal(posted.findLast(m=>m.type==='status').text,'completed');assert.ok(posted.some(m=>m.type==='event'&&m.event.seq===1));assert.equal(posted.findLast(m=>m.type==='transcript').preserveLive,false);view.dispose();});
test('an obsolete view response cannot overwrite the next selection',async()=>{let release;const waiting=new Promise(resolve=>release=resolve),posted=[];const client={status:()=>waiting};const view=new BrowserController(client,value=>posted.push(value));view.runId='old';view.session='old-session';const poll=view.poll();view.dispose();release({id:'old',state:'completed'});await poll;assert.deepEqual(posted,[]);});
test('provider key is consumed privately, IDs must come from discovery, disposal clears unsaved state',async()=>{const key='synthetic-browser-fixture-key',posted=[],calls=[];const client={providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:3,configured:false}),discoverProviderModels:async(...args)=>{calls.push(args);return {models:[{id:'actual-fixture-model'}]};},configureProvider:async(...args)=>{calls.push(args);return {revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'actual-fixture-model',models:[{id:'actual-fixture-model'}]}),graphs:async()=>({graphs:[]})};const view=new BrowserController(client,value=>posted.push(value));const message={type:'saveProviderKey',key};await view.handle(message);assert.ok(!('key' in message));assert.ok(!JSON.stringify(posted).includes(key));await view.handle({type:'model',id:'forged'});assert.equal(calls.length,1);await view.handle({type:'model',id:'actual-fixture-model'});assert.deepEqual(calls[1],['actual-fixture-model',key,3]);assert.equal(view.selection.key,undefined);view.dispose();assert.equal(view.selection,undefined);});
test('stale operation bytes cannot produce an approval request',async()=>{let decisions=0;const posted=[],original={id:'op',run_id:'run',workspace_id:'workspace',tool:'replace_file',state:'awaiting_approval',arguments_json:'{"after_content":"reviewed"}',expires_unix_ms:Date.now()+10000};const view=new BrowserController({operation:async()=>({...original,arguments_json:'{"after_content":"changed"}'}),decide:async()=>{decisions++;}},value=>posted.push(value));view.runId='run';view.operations.set(original.id,original);await view.handle({type:'decide',id:'op',decision:'allow'});assert.equal(decisions,0);assert.ok(posted.some(m=>m.type==='error'&&m.text.includes('changed')));view.dispose();});
