const {test}=require('node:test'),assert=require('node:assert/strict');const {BrowserController}=require('../browser.js');
test('profile conflicts refresh the displayed account and model without replaying the retained task',async()=>{
 const {ProviderProfileController}=require('../../../extensions/vscode/client.js');let state={revision:4,active:'first',profiles:[{id:'first',route_id:'openai.responses',provider:'openai',model:'fixture-first',revision:1}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true}]};let admissions=0;const posted=[];
 const client={providerProfiles:async()=>state,run:async()=>{admissions++;state={...state,revision:5,active:'second',profiles:[...state.profiles,{id:'second',route_id:'openai.responses',provider:'openai',model:'fixture-second',revision:1}]};throw Object.assign(new Error('Profile changed'),{status:409});},health:async()=>({agent_execution:true,provider_profile_admission:true}),models:async()=>({models:[{id:'fixture-second'}],default_model:'fixture-second'}),graphs:async()=>({graphs:[]})};
 const view=new BrowserController(client,value=>posted.push(value));view.health={agent_execution:true,provider_profile_admission:true};view.session='session';view.model='fixture-first';view.profileController=new ProviderProfileController(client,value=>posted.push(value));
 try{await view.profileController.refresh();await view.handle({type:'send',prompt:'Retained fixture draft'});assert.equal(admissions,1);assert.equal(view.model,'fixture-second');assert.equal(view.runId,undefined);assert.ok(posted.some(value=>value.type==='provider-profiles'&&value.active==='second'));assert.match(posted.at(-1).text,/draft has been kept/);assert.ok(!posted.some(value=>value.type==='user'));}finally{view.dispose();}
});
test('browser sends its known profile revision and retains the prompt when native admission rejects a stale view',async()=>{
 const posted=[],calls=[];const client={run:async(...args)=>{calls.push(args);throw Object.assign(new Error('Provider profile changed before run admission'),{status:409});}};
 const view=new BrowserController(client,value=>posted.push(value));view.health={agent_execution:true,provider_profile_admission:true};view.session='session';view.model='same-model';view.profileController={admission:async()=>({provider_profile_id:'saved-account',expected_provider_revision:4}),reconcileAdmission:async()=>false,dispose(){},invalidate(){}};
 try{await view.handle({type:'send',prompt:'Keep this task'});assert.deepEqual(calls[0],['session','Keep this task','same-model',{provider_profile_id:'saved-account',expected_provider_revision:4}]);assert.ok(posted.some(value=>value.type==='error'&&value.text.includes('profile changed')));assert.ok(!posted.some(value=>value.type==='user'));assert.equal(view.runId,undefined);}finally{view.dispose();}
});
test('browser Settings preserves the selected profile route through private discovery and footer enrollment',async()=>{
 let state={revision:3,active:'openai',profiles:[{id:'openai',provider:'openai',route_id:'openai.responses',model:'fixture-openai',revision:3}],routes:[{id:'openai.responses',provider:'openai',wire:'responses',discovery:true},{id:'anthropic.messages',provider:'anthropic',wire:'anthropic-messages',discovery:true}]};const posted=[],calls=[],secret='synthetic-browser-claude-profile-key';
 const client={providerProfiles:async()=>state,discoverProfileModels:async(...args)=>{calls.push(['discover',...args]);return {models:[{id:'fixture-claude'}]};},saveProviderProfile:async(...args)=>{calls.push(['save',...args]);state={...state,revision:4,active:args[0],profiles:[...state.profiles,{id:args[0],provider:'anthropic',route_id:args[1],model:args[2],revision:1}]};return state;},health:async()=>({agent_execution:true}),models:async()=>({models:[{id:state.profiles.at(-1).model}],default_model:state.profiles.at(-1).model}),graphs:async()=>({graphs:[]})};
 const view=new BrowserController(client,value=>posted.push(value));try{const message={type:'saveProviderKey',key:secret,profile:'',route:'anthropic.messages'};await view.handle(message);assert.ok(!Object.hasOwn(message,'key'));assert.equal(calls[0][2],'anthropic.messages');assert.equal(calls.length,1);await view.handle({type:'model',id:'fixture-claude'});assert.equal(calls[1][2],'anthropic.messages');assert.equal(calls[1][4],secret);assert.equal(view.model,'fixture-claude');assert.ok(!JSON.stringify(posted).includes(secret));assert.equal(state.profiles[0].model,'fixture-openai');}finally{view.dispose();}
});
test('rename sends the displayed expected title only for the selected supported conversation and retains conflicts',async()=>{
 const posted=[],calls=[];let conflict=false;
 const client={renameSession:async(...args)=>{calls.push(args);if(conflict)throw Object.assign(new Error('Conflict'),{status:409});},sessions:async()=>[{id:'selected',title:'Renamed fixture'}]};
 const view=new BrowserController(client,message=>posted.push(message));view.health={session_rename:true};view.session='selected';
 await view.handle({type:'rename-session',id:'foreign',title:'New',expected_title:'Old'});assert.equal(calls.length,0);
 await view.handle({type:'rename-session',id:'selected',title:'New',expected_title:'Displayed original'});assert.deepEqual(calls[0],['selected','New','Displayed original']);assert.ok(posted.some(message=>message.type==='sessions'));assert.equal(posted.at(-1).success,true);
 conflict=true;await view.handle({type:'rename-session',id:'selected',title:'Draft',expected_title:'Stale'});assert.equal(posted.at(-1).success,false);assert.match(posted.at(-1).text,/title changed/);
 view.health={};await view.handle({type:'rename-session',id:'selected',title:'New',expected_title:'Old'});assert.equal(calls.length,2);view.dispose();
});
test('Responses saved-key discovery and model selection preserve backend-reported wire',async()=>{
 const posted=[],setup={provider:'openai',wire:'responses',endpoint:'https://api.openai.com/v1/responses',revision:3,configured:true,model:'gpt-5.6-sol'};let discovered=0,configured=0;
 const client={providerConfiguration:async()=>setup,discoverProviderModels:async(key,revision)=>{assert.equal(key,undefined);assert.equal(revision,3);discovered++;return {models:[{id:'gpt-5.6-sol'}]};},configureProvider:async(id,key,revision)=>{assert.equal(id,'gpt-5.6-sol');assert.equal(key,undefined);assert.equal(revision,3);configured++;return {...setup,revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'gpt-5.6-sol',models:[{id:'gpt-5.6-sol'}]})};
 const view=new BrowserController(client,message=>posted.push(message));await view.discover();await view.handle({type:'model',id:'gpt-5.6-sol'});assert.equal(discovered,1);assert.equal(configured,1);assert.equal(view.selection.revision,4);assert.ok(posted.some(message=>message.type==='provider-wire'&&message.wire==='responses'));view.dispose();
});
test('restoring the native view does not wait for provider catalogue discovery',async()=>{
 let release,discovery=0;const pending=new Promise(resolve=>release=resolve),posted=[],client={health:async()=>({agent_execution:true}),models:async()=>({default_model:'fixture-default',models:[{id:'fixture-default'}]}),graphs:async()=>({graphs:[]}),sessions:async()=>[],providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:1,configured:true,model:'fixture-default'}),discoverProviderModels:()=>{discovery++;return pending;}};
 const view=new BrowserController(client,value=>posted.push(value));let deadline;try{const restored=await Promise.race([view.initialize().then(()=>true),new Promise(resolve=>deadline=setTimeout(()=>resolve(false),250))]);assert.equal(restored,true,'Slow provider discovery must not block native session restoration');await new Promise(resolve=>setImmediate(resolve));assert.equal(discovery,1);assert.equal(posted.find(m=>m.type==='capabilities').model,'fixture-default');assert.ok(posted.some(m=>m.type==='status'&&m.text==='Ready'));const count=posted.length;view.dispose();release({models:[{id:'fixture-discovered'}]});await new Promise(resolve=>setImmediate(resolve));assert.equal(posted.length,count,'Late discovery must not publish into a disposed view');}finally{clearTimeout(deadline);view.dispose();release({models:[]});}
});
test('view catches a completion between event and status reads and drains final events',async()=>{let status=0,eventReads=0;const posted=[];const client={status:async()=>({id:'run',session_id:'session',state:++status===1?'running':'completed'}),events:async()=>++eventReads===1?[]:[{seq:1,run_id:'run',kind:'conversation.assistant',data:{content:'Actual fixture result'}}],operations:async()=>[],history:async()=>[{role:'assistant',data:{content:'Actual fixture result',usage:{prompt_tokens:4,completion_tokens:2}}}],runs:async()=>[{id:'run',state:'completed'}]};const view=new BrowserController(client,value=>posted.push(value));view.runId='run';view.session='session';await view.poll();assert.equal(posted.findLast(m=>m.type==='status').text,'completed');assert.ok(posted.some(m=>m.type==='event'&&m.event.seq===1));assert.equal(posted.findLast(m=>m.type==='transcript').preserveLive,false);view.dispose();});
test('an obsolete view response cannot overwrite the next selection',async()=>{let release;const waiting=new Promise(resolve=>release=resolve),posted=[];const client={status:()=>waiting};const view=new BrowserController(client,value=>posted.push(value));view.runId='old';view.session='old-session';const poll=view.poll();view.dispose();release({id:'old',state:'completed'});await poll;assert.deepEqual(posted,[]);});
test('provider key is consumed privately, IDs must come from discovery, disposal clears unsaved state',async()=>{const key='synthetic-browser-fixture-key',posted=[],calls=[];const client={providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:3,configured:false}),discoverProviderModels:async(...args)=>{calls.push(args);return {models:[{id:'actual-fixture-model'}]};},configureProvider:async(...args)=>{calls.push(args);return {revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'actual-fixture-model',models:[{id:'actual-fixture-model'}]}),graphs:async()=>({graphs:[]})};const view=new BrowserController(client,value=>posted.push(value));const message={type:'saveProviderKey',key};await view.handle(message);assert.ok(!('key' in message));assert.ok(!JSON.stringify(posted).includes(key));await view.handle({type:'model',id:'forged'});assert.equal(calls.length,1);await view.handle({type:'model',id:'actual-fixture-model'});assert.deepEqual(calls[1],['actual-fixture-model',key,3]);assert.equal(view.selection.key,undefined);view.dispose();assert.equal(view.selection,undefined);});
test('stale operation bytes cannot produce an approval request',async()=>{let decisions=0;const posted=[],original={id:'op',run_id:'run',workspace_id:'workspace',tool:'replace_file',state:'awaiting_approval',arguments_json:'{"after_content":"reviewed"}',expires_unix_ms:Date.now()+10000};const view=new BrowserController({operation:async()=>({...original,arguments_json:'{"after_content":"changed"}'}),decide:async()=>{decisions++;}},value=>posted.push(value));view.runId='run';view.operations.set(original.id,original);await view.handle({type:'decide',id:'op',decision:'allow'});assert.equal(decisions,0);assert.ok(posted.some(m=>m.type==='error'&&m.text.includes('changed')));view.dispose();});
