const {test}=require('node:test'),assert=require('node:assert/strict');const {BrowserController}=require('../browser.js');
test('Responses saved-key discovery and model selection preserve backend-reported wire',async()=>{
 const posted=[],setup={provider:'openai',wire:'responses',endpoint:'https://api.openai.com/v1/responses',revision:3,configured:true,model:'gpt-5.6-sol'};let discovered=0,configured=0;
 const client={providerConfiguration:async()=>setup,discoverProviderModels:async(key,revision)=>{assert.equal(key,undefined);assert.equal(revision,3);discovered++;return {models:[{id:'gpt-5.6-sol'}]};},configureProvider:async(id,key,revision)=>{assert.equal(id,'gpt-5.6-sol');assert.equal(key,undefined);assert.equal(revision,3);configured++;return {...setup,revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'gpt-5.6-sol',models:[{id:'gpt-5.6-sol'}]})};
 const view=new BrowserController(client,message=>posted.push(message));await view.discover();await view.handle({type:'model',id:'gpt-5.6-sol'});assert.equal(discovered,1);assert.equal(configured,1);assert.equal(view.selection.revision,4);assert.ok(posted.some(message=>message.type==='provider-wire'&&message.wire==='responses'));view.dispose();
});
test('restoring the native view does not wait for provider catalogue discovery',async()=>{
 let release,discovery=0;const pending=new Promise(resolve=>release=resolve),posted=[],client={health:async()=>({agent_execution:true}),models:async()=>({default_model:'fixture-default',models:[{id:'fixture-default'}]}),graphs:async()=>({graphs:[]}),sessions:async()=>[],providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:1,configured:true,model:'fixture-default'}),discoverProviderModels:()=>{discovery++;return pending;}};
 const view=new BrowserController(client,value=>posted.push(value));let deadline;try{const restored=await Promise.race([view.initialize().then(()=>true),new Promise(resolve=>deadline=setTimeout(()=>resolve(false),250))]);assert.equal(restored,true,'Slow provider discovery must not block native session restoration');await new Promise(resolve=>setImmediate(resolve));assert.equal(discovery,1);assert.equal(posted.find(m=>m.type==='capabilities').model,'fixture-default');assert.ok(posted.some(m=>m.type==='status'&&m.text==='Ready'));const count=posted.length;view.dispose();release({models:[{id:'fixture-discovered'}]});await new Promise(resolve=>setImmediate(resolve));assert.equal(posted.length,count,'Late discovery must not publish into a disposed view');}finally{clearTimeout(deadline);view.dispose();release({models:[]});}
});
test('view catches a completion between event and status reads and drains final events',async()=>{let status=0,eventReads=0;const posted=[];const client={status:async()=>({id:'run',session_id:'session',state:++status===1?'running':'completed'}),events:async()=>++eventReads===1?[]:[{seq:1,run_id:'run',kind:'conversation.assistant',data:{content:'Actual fixture result'}}],operations:async()=>[],history:async()=>[{role:'assistant',data:{content:'Actual fixture result',usage:{prompt_tokens:4,completion_tokens:2}}}],runs:async()=>[{id:'run',state:'completed'}]};const view=new BrowserController(client,value=>posted.push(value));view.runId='run';view.session='session';await view.poll();assert.equal(posted.findLast(m=>m.type==='status').text,'completed');assert.ok(posted.some(m=>m.type==='event'&&m.event.seq===1));assert.equal(posted.findLast(m=>m.type==='transcript').preserveLive,false);view.dispose();});
test('an obsolete view response cannot overwrite the next selection',async()=>{let release;const waiting=new Promise(resolve=>release=resolve),posted=[];const client={status:()=>waiting};const view=new BrowserController(client,value=>posted.push(value));view.runId='old';view.session='old-session';const poll=view.poll();view.dispose();release({id:'old',state:'completed'});await poll;assert.deepEqual(posted,[]);});
test('provider key is consumed privately, IDs must come from discovery, disposal clears unsaved state',async()=>{const key='synthetic-browser-fixture-key',posted=[],calls=[];const client={providerConfiguration:async()=>({provider:'openai',endpoint:'https://api.openai.com/v1/chat/completions',revision:3,configured:false}),discoverProviderModels:async(...args)=>{calls.push(args);return {models:[{id:'actual-fixture-model'}]};},configureProvider:async(...args)=>{calls.push(args);return {revision:4};},health:async()=>({agent_execution:true}),models:async()=>({default_model:'actual-fixture-model',models:[{id:'actual-fixture-model'}]}),graphs:async()=>({graphs:[]})};const view=new BrowserController(client,value=>posted.push(value));const message={type:'saveProviderKey',key};await view.handle(message);assert.ok(!('key' in message));assert.ok(!JSON.stringify(posted).includes(key));await view.handle({type:'model',id:'forged'});assert.equal(calls.length,1);await view.handle({type:'model',id:'actual-fixture-model'});assert.deepEqual(calls[1],['actual-fixture-model',key,3]);assert.equal(view.selection.key,undefined);view.dispose();assert.equal(view.selection,undefined);});
test('stale operation bytes cannot produce an approval request',async()=>{let decisions=0;const posted=[],original={id:'op',run_id:'run',workspace_id:'workspace',tool:'replace_file',state:'awaiting_approval',arguments_json:'{"after_content":"reviewed"}',expires_unix_ms:Date.now()+10000};const view=new BrowserController({operation:async()=>({...original,arguments_json:'{"after_content":"changed"}'}),decide:async()=>{decisions++;}},value=>posted.push(value));view.runId='run';view.operations.set(original.id,original);await view.handle({type:'decide',id:'op',decision:'allow'});assert.equal(decisions,0);assert.ok(posted.some(m=>m.type==='error'&&m.text.includes('changed')));view.dispose();});
